### ISSUE TITLE
REQ_ADD_PATH request does not send the BGP Update message

### ISSUE THREAD

**Issue by PeiwenChen** [osrg/gobgp#1000]
HI @ishidawataru ,

I am following the https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md to add routes.
And I was monitoring the port 179 with tcpdump, but did not see the "UPDATE" messages sent and from the host, and the remote host did not show the route installed successfully.

I believe my tcpdump cmd is correctly used, because I saw "UPDATE" received from the remote host, but not sent out to announce the route.
And I use `REQ_MONITOR_RIB" to monitor the route, but only see the "UPDATE" received as well. I expect it should show both sent and received message since I config with GLOBAL.

Is there any trick to add routes with `REQ_ADD_PATH`?

And when I was printing the response of the request, i got:
```response is:  &{<nil> uuid:"\3514N\200\345HO\005\270\372\311?\323m\244M" }```

Any comments will be very appreciated.

**Comment by PeiwenChen** [comment]
Close it for my personal mistakes

**Comment by PeiwenChen** [comment]
@ishidawataru  Seems like I need to add a policy to export to announce the route?

**Comment by fujita** [comment]
You don't need to add any policy for this. I updated the example of the code:

https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md

If you still have the issue, please reopen it.
