### ISSUE TITLE
Unknown method  MonitorBestChanged

### ISSUE THREAD

**Issue by PeiwenChen** [osrg/gobgp#1002]
Hi,

I run `sudo -E gobgpd -f gobgpd.conf` to start gobgp, and trying to monitor rib, but have this error:
```
peiwen@lb-perf1.ash:~/go/src/github.com $ gobgp monitor global rib
rpc error: code = 12 desc = unknown method MonitorBestChanged
```

Any comments?

**Comment by ishidawataru** [comment]
please re-compile `gobgp` with the latest source code. 
`MonitorBestChanged` was merged into `MonitorRib` by [this commit](https://github.com/osrg/gobgp/commit/aca6fd6ad4409b4cb63682bff3c79fca8ca2800d).

**Comment by PeiwenChen** [comment]
@ishidawataru 
I run `go get` to get `gobgp` and `gobgpd` and build it everytime I made any changes.
I believe its latest source code.
