### ISSUE TITLE
Send flowspec tcp-flags with bitmask

### ISSUE THREAD

**Issue by shevchenkodenis** [osrg/gobgp#1048]
Feature-request by RFC 5575 

>  Type 9 - TCP flags
> 
> ```
>      Encoding: <type (1 octet), [op, bitmask]+>
> 
>      Bitmask values can be encoded as a 1- or 2-byte bitmask.  When
>      a single byte is specified, it matches byte 13 of the TCP
>      header [RFC0793], which contains bits 8 though 15 of the 4th
>      32-bit word.  When a 2-byte encoding is used, it matches bytes
>      12 and 13 of the TCP header with the data offset field having a
>      "don't care" value.
> 
>      As with port specifiers, this component evaluates to FALSE for
>      packets that are not TCP packets.
> 
>      This type uses the bitmask operand format, which differs from
>      the numeric operator format in the lower nibble.
> 
>                    0   1   2   3   4   5   6   7
>                  +---+---+---+---+---+---+---+---+
>                  | e | a |  len  | 0 | 0 |not| m |
>                  +---+---+---+---+---+---+---+---+
> 
>      e, a, len -  Most significant nibble: (end-of-list bit, AND
>                   bit, and length field), as defined for in the
>                   numeric operator format.
> 
>      not - NOT bit.  If set, logical negation of operation.
> 
>      m -   Match bit.  If set, this is a bitwise match operation
>            defined as "(data & value) == value"; if unset, (data &
>            value) evaluates to TRUE if any of the bits in the value
>            mask are set in the data.
> ```

**Comment by ishidawataru** [comment]
Could you clarify what you need?
Matching with byte 13 of the TCP header is already implemented.
Do you need to match with data offset field of TCP header ?

**Comment by shevchenkodenis** [comment]
Well,  I want to match by statements like this:

- S/SA - that inidicates that packet should have SYN flag, but not ACK

Could I achieve it by existing syntax?

**Comment by ishidawataru** [comment]
No, currently gobgp cli doesn't support that.

To support the feature, we have to reconsider the syntax of flowspec since it is already getting into a mess.
Do you know what is other implementation's syntax like?

Also, how about using `match` flag for your use-case?

You can do something like

`gobgp g ri -a ipv4-flowspec add match tcp-flags match syn then accept`

This matches with a TCP flow who has only SYN flag.

**Comment by ishidawataru** [comment]
> S/SA - that inidicates that packet should have SYN flag, but not ACK

Now this can be achieved by [this enhancement](https://github.com/osrg/gobgp/commit/6de16dc885ebfeffb9ff3470805980f6fac579c5)

Try like

```
$ gobgp g ri -a ipv4-flowspec add match tcp-flags 'S&!A' then discard
```

Please reopen if this doesn't work for you.
