### ISSUE TITLE
Feature Request: Send BMP Stats message

### ISSUE THREAD

**Issue by PeiwenChen** [osrg/gobgp#1061]
Hi, I found currently gobgpd does not send the BMP Stats message.
Is it easy to add it?
@fujita While its not urgent.

**Comment by fujita** [comment]
What statistics types you need?

**Comment by PeiwenChen** [comment]
From the BMP RFC, these are all types of Stats message.
```
10.4.  BMP Statistics Types

   This document defines fourteen statistics types for statistics
   reporting (Section 4.8):

   o  Stat Type = 0: Number of prefixes rejected by inbound policy
   o  Stat Type = 1: Number of (known) duplicate prefix advertisements
   o  Stat Type = 2: Number of (known) duplicate withdraws
   o  Stat Type = 3: Number of updates invalidated due to CLUSTER_LIST
      loop
   o  Stat Type = 4: Number of updates invalidated due to AS_PATH loop
   o  Stat Type = 5: Number of updates invalidated due to ORIGINATOR_ID
   o  Stat Type = 6: Number of updates invalidated due to a loop found
      in AS_CONFED_SEQUENCE or AS_CONFED_SET
   o  Stat Type = 7: Number of routes in Adj-RIBs-In
   o  Stat Type = 8: Number of routes in Loc-RIB
   o  Stat Type = 9: Number of routes in per-AFI/SAFI Adj-RIB-In
   o  Stat Type = 10: Number of routes in per-AFI/SAFI Loc-RIB
   o  Stat Type = 11: Number of updates subjected to treat-as-withdraw
   o  Stat Type = 12: Number of prefixes subjected to treat-as-withdraw
```

Type 7, 8, 11, 12 are the most interested.

**Comment by mstrother** [comment]
Yes. 7, 8, 11, and 12 would be a good start. The RFC doesn't define when statistic messages have to be transmitted. It states they can be event or timer driven. I propose they are off by default and timer driven with the settings specified in the configuration file.

**Comment by iwaseyusuke** [comment]
Hi,
I've just create PR for BMP Statistics Types of 7 and 8 at the start; https://github.com/osrg/gobgp/pull/1332
Could you review my PR?

For 11 and 12, I'm searching how to get counts of withdraws.

**Comment by iwaseyusuke** [comment]
Hi,
I've just create PR for BMP Statistics Types of 11 and 12; https://github.com/osrg/gobgp/pull/1341
Could you review my PR?

BTW, any other interested stat types?

**Comment by fujita** [comment]
Please create a new pr if are there any bmp features to be supported.
