### ISSUE TITLE
Microsoft SONiC use gobgp?

### ISSUE THREAD

**Issue by xiaopeng163** [osrg/gobgp#1069]
I found this from twitter,  https://twitter.com/sonoble/status/710546241495498752
do you guys know more details about this?  any information will be thankful.

**Comment by ishidawataru** [comment]
Hi,
They showed a demo of hitless migration of Quagga to GoBGP at the event.

https://twitter.com/ryusdn/status/708004761199480832

They connected GoBGP and zebra with [this](https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md) feature.

**Comment by xiaopeng163** [comment]
any video recording for this session?

**Comment by ishidawataru** [comment]
Only I found was this..

https://www.youtube.com/watch?v=UPuqCX4PLmw

**Comment by xiaopeng163** [comment]
Thanks
