### ISSUE TITLE
AddPath with new api

### ISSUE THREAD

**Issue by luizbafilho** [osrg/gobgp#1075]
Hi guys,

Thanks for the excellent job doing the `gobgp`, but I need your help. I'm using it as a library and after updating to the latest version a lot of thinks got broken. Right now I'm trying to update to the code to the latest API but without success when trying to add a new path. 

The code I had was:
```go
	route := "192.168.30.10"
	path, _ := cmd.ParsePath(bgp.RF_IPv4_UC, []string{route})
	req := gobgp.NewGrpcRequest(gobgp.REQ_ADD_PATH, "", bgp.RouteFamily(0), &gobgp_api.AddPathRequest{
		Resource: gobgp_api.Resource_GLOBAL,
		Path:     path,
	})
	bs.bgp.GrpcReqCh <- req
	res := <-req.ResponseCh
	if err := res.Err(); err != nil {
		log.Fatal(err)
	}
```

That worked like a charm, but the new version is not, I'm trying to do this:
```go
	attrs := []bgp.PathAttributeInterface{
		bgp.NewPathAttributeOrigin(0),
		bgp.NewPathAttributeNextHop("0.0.0.0"),
		bgp.NewPathAttributeAsPath([]bgp.AsPathParamInterface{bgp.NewAs4PathParam(bgp.BGP_ASPATH_ATTR_TYPE_SEQ, []uint32{100})}),
	}
	if _, err := bs.bgp.AddPath("", []*table.Path{table.NewPath(nil, bgp.NewIPAddrPrefix(32, "192.168.33.10"), false, attrs, time.Now(), false)}); err != nil {
		log.Fatal(err)
	}

```

I'm not sure what should I pass in `bgp.NewAs4PathParam` parameters, I couldn't find any documentation about it. The `100` there is an ASN.

Could you help me on that? What should a do to reproduce the code I was using, but using the new API.

**Comment by ishidawataru** [comment]
You can make it work the same by just removing AS path attribute from attrs like below.

```
   attrs := []bgp.PathAttributeInterface{
        bgp.NewPathAttributeOrigin(0),
        bgp.NewPathAttributeNextHop("0.0.0.0"),
    }
    if _, err := bs.bgp.AddPath("", []*table.Path{table.NewPath(nil, bgp.NewIPAddrPrefix(32, "192.168.33.10"), false, attrs, time.Now(), false)}); err != nil {
        log.Fatal(err)
    }
```

**Comment by luizbafilho** [comment]
It worked. Thank you.
