### ISSUE TITLE
Provide the command to regenerate api/gobgp.pb.go

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#1080]
Hey!

While most users won't care about that, it would be useful to have the command used to generate `api/gobgp.pb.go` somewhere (in `Makefile` or `README.md`). I guess this something like:

``` sh
protoc -Iapi/ --gogo_out=plugins=grpc:api/ api/gobgp.proto
```

However, maybe you are using the fast version?

**Comment by fujita** [comment]
I considered gogo but there were some reported issues about grpc and gogo. I prefer the safer and easier option. Injecting routes from a mrt file might be faster but the official protobuf is better for the the majority of GoBGP use cases, I think.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/BUILD.md
Please feel free to add anything useful for developers.
