### ISSUE TITLE
global rib ip lookup fails

### ISSUE THREAD

**Issue by tarfu** [osrg/gobgp#1081]
Hello,

in the past something like this worked:
`gobgp global rib 8.8.8.8`

this would have returned in the past:
```
    Network             Next Hop             AS_PATH              Age        Attrs
*>  8.8.8.0/24          xxx.xxx.xxx.xxx        xxx zzz vvv     00:14:46   [{Origin: i} {Communities: xxx, ccc, vvv}]
```

Which now returns:
`Network not in table`

If you do `gobgp global rib 8.8.8.0/24`  it will return:
```
    Network             Next Hop             AS_PATH              Age        Attrs
*>  8.8.8.0/24          xxx.xxx.xxx.xxx        xxx zzz vvv     00:14:46   [{Origin: i} {Communities: xxx, ccc, vvv}]
```

Is this new behaviour intended or a bug? 
I think it has something to do with commit [17331d](https://github.com/osrg/gobgp/commit/17331d161fae507424a9760a9dbca41b3669ed36) or later.

If someone points me at it I'm willing to try fix it myself and file a pull request.

Have a nice Day,

Tobias

**Comment by ishidawataru** [comment]
@tarfu Hi, sorry for the regression. It's a bug.

Here is where we have to fix.

https://github.com/osrg/gobgp/blob/master/table/table.go#L368-L383

`f(id, key)` never returns `error`, so we should check whether `key` is host format(8.8.8.8) or not first.
