### ISSUE TITLE
Is there any plan to support evpn type 5?

### ISSUE THREAD

**Issue by ruansteve** [osrg/gobgp#1082]
Type 5 is used to advertise prefix routes in evpn.
   https://tools.ietf.org/html/draft-ietf-bess-evpn-prefix-advertisement-02

Is type 5 on the plan?

**Comment by tmmorin** [comment]
Support for the NLRI encoding was committed some time ago:

https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/bgp/message/update/nlri/evpn/prefix.py

I haven't checked whether the implementation is up to date with the IETF draft, however.

**Comment by ruansteve** [comment]
Thanks. Thomas.
