### ISSUE TITLE
feature: implement add-path bgp capability

### ISSUE THREAD

**Issue by nskalis** [osrg/gobgp#1085]
hi guys,

what do you think about adding `add-path` capability to gobgp for all address families 
_(mostly-wanted: ip-unicast, ip6-nlri-mpls)_ ?

that would allow advertise not-only the best routes towards a peer,
giving the potential of many more uses for gobgp :)

nikos

**Comment by fujita** [comment]
Just out of curiosity, Cisco and Juniper supports add-path with eBGP?

**Comment by nskalis** [comment]
not with ebgp, only ibgp as far as juniper is concerned : http://www.juniper.net/techpubs/en_US/junos15.1/topics/concept/bgp-add-path-introduction.html

**Comment by btarno** [comment]
It's only really needed for iBGP in route-reflector scenarios to prevent the reflector from choosing the best path.  This feature allows the clients to decide on best path.  Makes a lot of sense in an environment with out-of-path dedicated route reflectors.  For what it's worth I am evaluating the use of gobgp as a dedicated route reflector and it's a no-go without this feature.

**Comment by nskalis** [comment]
i noticed some commits about `add-path`, so i think the team is already working on it. they will provide this functionality before the end of the year maybe :)

**Comment by jwhited** [comment]
+1

**Comment by martink2** [comment]
+1

**Comment by marcusgc** [comment]
+1

**Comment by KarlAustin** [comment]
Another +1 on this, we're looking to GoBGP as RR, but need add-path before we can roll out.

**Comment by dmkovalenko** [comment]
is there any progress on this request?

**Comment by fujita** [comment]
the rx support is already in master branch.
I've been working on the tx support. Looks like the very basic features works but needs more testings:
https://github.com/fujita/gobgp/tree/addpath

**Comment by fujita** [comment]
I've just pushed the addpath tx support.

To enable addpath, you need to add the following to the neighbor section configuration:
```
    [neighbors.add-paths.config]
        send-max = 8
        receive = true
```
https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md

Enjoy!
