### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by AjdinGH** [osrg/gobgp#1090]
Hi,

I'm trying to install gobgp but I wait 2 hours and it isn't finish jet.
I'm trying to install it via fastnetmon and when it comes to Build gobgp it waits for hours.
Evertingy works fine but when it comes to install gobgp it freez and wait?

Can you please help me to resolve this issue? Kind regards.

**Comment by fujita** [comment]
Sounds like that it's your env issue.

GoBGP automated build on dockerhub succeeds.
https://hub.docker.com/r/osrg/gobgp/builds/
Also I've just tried to install gobgpd on clean ubuntu environment and worked fine.

You can see what stalls with `go get -v github.com/osrg/gobgp/gobgpd`.
