### ISSUE TITLE
SOS!HELP!Why can't build peers when using gobgpd.conf    - cry -

### ISSUE THREAD

**Issue by Darinyazanr** [osrg/gobgp#1091]
{"Key":"10.10.0.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENSENT","old":"BGP_FSM_ACTIVE","reason":"new-connection","time":"2016-09-06T11:20:44+08:00"}
{"Key":"10.10.0.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_IDLE","old":"BGP_FSM_OPENSENT","reason":"**read-failed**","time":"2016-09-06T11:20:44+08:00"}
{"Key":"10.10.0.255","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENSENT","old":"BGP_FSM_ACTIVE","reason":"new-connection","time":"2016-09-06T11:20:48+08:00"}
{"Key":"10.10.0.255","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_IDLE","old":"BGP_FSM_OPENSENT","reason":# **"read-failed**","time":"2016-09-06T11:20:48+08:00"}
{"Duration":5,"Key":"10.10.0.254","Topic":"Peer","level":"debug","msg":"IdleHoldTimer expired","time":"2016-09-06T11:20:49+08:00"}
{"Key":"10.10.0.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":"idle-hold-timer-expired","time":"2016-09-06T11:20:49+08:00"}
{"Key":"10.10.1.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENSENT","old":"BGP_FSM_ACTIVE","reason":"new-connection","time":"2016-09-06T11:20:50+08:00"}
{"Key":"10.10.1.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENCONFIRM","old":"BGP_FSM_OPENSENT","reason":"open-msg-received","time":"2016-09-06T11:20:50+08:00"}
{"Key":"10.10.1.254","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_IDLE","old":"BGP_FSM_OPENCONFIRM","reason":# "**invalid-msg**","time":"2016-09-06T11:20:50+08:00"}

**Comment by fujita** [comment]
"read-failed" means gobgpd failed to read data from the socket. Likely the peer closed the connection. Needs to investigate with tcpdump and the log on the peer.
