### ISSUE TITLE
Support for BLACKHOLE BGP Community

### ISSUE THREAD

**Issue by tking** [osrg/gobgp#1136]
Hi GoBGP developers,

could you please add support for the BLACKHOLE BGP community ( https://tools.ietf.org/html/draft-ietf-grow-blackholing-03 ) which will soon be published as RFC 7999?

Could you please add the BLACKHOLE BGP community to the list of well-known BGP communities (e.g., CLI and filtering)?

Best regards,
Thomas

**Comment by fujita** [comment]
@s2ugimot add this:
https://github.com/osrg/gobgp/commit/bd42075ef02f1c1c99fb00eedc08a887f71a8303

Of course, CLI and policy work with this.
