### ISSUE TITLE
Duplicate Large Communities handling

### ISSUE THREAD

**Issue by pierky** [osrg/gobgp#1143]
Hello,

I'm running some tests on these Large Communities draft's statements:

> Duplicate Large Communities SHOULD NOT be transmitted. A receiving speaker SHOULD silently remove duplicate Large Communities from a BGP UPDATE message.

As of my findings it seems that GoBGP is not removing duplicate communities from the received BGP UPDATEs and also it sends duplicate values:

https://github.com/pierky/large-bgp-communities-playground/blob/master/tests/03-DUPLICATE_COMMUNITIES.md#gobgp-announcing

**Comment by pierky** [comment]
Hello,

I tested this new commit but I found that GoBGP still sends duplicate values if it is instructed via CLI.

This command `gobgp global rib add -a ipv4 203.0.113.24/32 large-community 65537:1:1,65537:1:1` produces the following:

```
    192.0.2.3.36189 > 192.0.2.103.179: Flags [P.], cksum 0x84dc (incorrect -> 0xcb9d), seq 132:207, ack 132, win 457, options [nop,nop,TS val 697398 ecr 691150], length 75: BGP, length: 75
        Update Message (2), length: 75
          Origin (1), length: 1, Flags [T]: Incomplete
          AS Path (2), length: 6, Flags [T]: 65537
          Next Hop (3), length: 4, Flags [T]: 192.0.2.3
          Unknown Attribute (32), length: 24, Flags [OT]:
            no Attribute 32 decoder
            0x0000:  0001 0001 0000 0001 0000 0001 0001 0001
            0x0010:  0000 0001 0000 0001
          Updated routes:
            203.0.113.24/32
```

(please note two identical values for attribute 32, `0001 0001 0000 0001 0000 0001`)

Now everything looks fine when it receives the duplicate values:

```
root@gobgpreceiver:/go# gobgp neighbor 192.0.2.3 adj-in
    Network             Next Hop             AS_PATH              Age        Attrs
    203.0.113.24/32     192.0.2.3            65537                00:10:18   [{Origin: ?} {LargeCommunity: [ 65537:1:1]}]

**Comment by fujita** [comment]
@pierky This is the expected behavior. GoBPG sends what you want like exabgp. So you can use gobgp for sorta testings.
