### ISSUE TITLE
Peer groups are undocumented

### ISSUE THREAD

**Issue by devicenull** [osrg/gobgp#1149]
Looking through the source, I see that PeerGroups are apparently implemented, but completely undocumented.  

It would be nice to have some examples of these in the documentation somewhere (perhaps in https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md ?)

**Comment by ishidawataru** [comment]
@devicenull Peer groups feature is not fully implemented yet.
(only configuration structures are defined and no logic is implemented)
