### ISSUE TITLE
Memory usage is crazy

### ISSUE THREAD

**Issue by devicenull** [osrg/gobgp#1150]
I have this setup (full IPv4 + IPv6 table from one peer, forwarding that to one downstream peer)

```
# gobgp neighbor
Peer                         AS  Up/Down State       |#Advertised Received Accepted
45.32.x.x               64515 00:04:16 Establ      |     600721       29       29
45.63.y.y                20473 00:04:13 Establ      |         29   600750   600721
45.63.z.z                20473 00:04:17 Establ      |         39        0        0
2001:19f0:x           20473 00:04:13 Establ      |          0    32829    32433
2001:19f0:y           20473 00:04:06 Establ      |          1        0        0
2001:19f0:z           64515 00:04:16 Establ      |      32434        0        0
```

Memory usage there is a little high (at 2.6GB), but still fairly acceptable.

```
# pmap -x 2156 | egrep 'total|Add'
Address           Kbytes     RSS   Dirty Mode   Mapping
total kB         2663548 2275344 2268644
```

Now, I add another two peers that will receive the full table (one IPv4, one IPv6):

```
45.32.a.a              64515 00:04:47 Establ      |     600596       29       29
2001:19f0:a          64515 00:04:44 Establ      |      32428        0        0
```

Memory usage goes up by ~1.1 MB, perfectly reasonable

```
# pmap -x 2156 | egrep 'total|Add'
Address           Kbytes     RSS   Dirty Mode   Mapping
total kB         2664700 2278308 2271540
```

And another two peers:

```
45.32.b.b              64515 00:00:06 Establ      |     600589       35       35
2001:19f0:b          64515 00:00:02 Establ      |      32431        1        1
```

And, memory shoots up by 176MB, which seems very high

```
# pmap -x 2156 | egrep 'total|Add'
Address           Kbytes     RSS   Dirty Mode   Mapping
total kB         2841028 2451980 2445212
```

And another two peers (which currently makes for a total of 8 (4 each IPv4, IPv6) downstream peers, as well as the two (1 each IPv4, IPv6) upstream peers:

```
45.32.c.c              64515 00:00:04 Establ      |     600583        0        0
2001:19f0:c         64515 00:00:10 Establ      |      32432        2        2
```

And things get crazy, with a 568 MB spike in memory

```
# pmap -x 2156 | egrep 'total|Add'
Address           Kbytes     RSS   Dirty Mode   Mapping
total kB         3409184 3016424 3009640
```

And a final two more peers:

```
45.32.d.d              64515 00:01:33 Establ      |     600622       36       36
2001:19f0:d         64515 00:01:36 Establ      |      32430        2        2
```

Which uses an additional 134 MB of memory.

```
# pmap -x 2156 | egrep 'total|Add'
Address           Kbytes     RSS   Dirty Mode   Mapping
total kB         3543712 3068140 3061356
```

So, from #1127 I learned that memory usage isn't a huge priority, but this level of usage seems largely unsustainable.  It seems like I'd need to throw crazy amounts of memory at gobgp to do anything useful with it.

For what it's worth, I've been testing this sending a full IPv4 + IPv6 table to ~60 hosts (so 120 sessions).  gobgp is running out of memory on a machine with 8GB of memory.  With the same configuration, bird  uses 325 MB of memory _total_.

Is gobgp not intended to receive a full table, and redistribute it to other peers?

**Comment by fujita** [comment]
Please try the latest master. The memory usage is supposed to be hugely reduced.
