### ISSUE TITLE
Unable to remove flowspec routes

### ISSUE THREAD

**Issue by rrickardt** [osrg/gobgp#1185]
When I add a route like:

gobgp global rib -a flowvpn4 add rd 11111:2  match destination 11.0.0.0/24 source 30.0.0.0/24 then discard
route is installed correctly. When i try to remove it with:

gobgp global rib -a flowvpn4 del rd 11111:2  match destination 11.0.0.0/24 source 30.0.0.0/24 then discard

i have in gobgpd log:

{"Key":"0.0.43.0/18","Length":1,"Topic":"Table","level":"debug","msg":"Found withdrawals for path(s) that did not get installed","time":"2016-12-02T18:23:29+01:00"}

and route is still there with gobgp global rib -a flowvpn4.

Do you have any hint what am i doing wrong?

Thank you.

**Comment by ishidawataru** [comment]
@rrickardt Thanks for the report. This was a bug. It is now fixed. Could you try the latest code?

**Comment by rrickardt** [comment]
@ishidawataru Thank you for the fix.It is working correctly now.
