### ISSUE TITLE
Peer added from CLI is in ipv4 address family, ignoring -a

### ISSUE THREAD

**Issue by rrickardt** [osrg/gobgp#1196]
To replicate:

gobgp neighbor -a vpnv4 add 4.3.2.1 as 12345  or
gobgp neighbor add 4.3.2.1 as 12345 -a vpnv4

Neighbor capabilities:
    multiprotocol:
        ipv4-unicast:	advertised

It is possible that i am not understanding syntax correctly, if so, please show me the right direction.

Thank you.

**Comment by ishidawataru** [comment]
Hi @rrickardt, `gobgp` command currently doesn't support adding a neighbor with multiprotocol capability other than ipv4 and ipv6.

We shouldn't allow passing `-a` option to `gobgp neighbor add` subcommand, but it is not the case now.

**Comment by rrickardt** [comment]
Thank you for feedback. It works ok from config file.
