### ISSUE TITLE
Import Policy

### ISSUE THREAD

**Issue by fakrul** [osrg/gobgp#1199]
I am trying following configuration; the idea is to tag rpki validation result and change the local preference.

```
[global.config]
as = 65420
router-id = "192.168.168.33"

[[neighbors]]
  [neighbors.config]
    peer-as = 65420
    neighbor-address = "192.168.168.254"
    auth-password = "abcd1234abcd"
  [neighbors.apply-policy-config]
    import-policy-list = ["AS65420-IMPORT-RPKI"]

[[rpki-servers]]
  [rpki-servers.config]
    address = "192.168.168..47"
    port = 323

[[policy-definitions]]
  name = "AS65420-IMPORT-RPKI"
  [[policy-definitions.statements]]
    name = "statement1"
    [policy-definitions.statements.conditions.bgp-conditions]
      rpki-validation-result = "valid"
    [policy-definitions.statements.actions.bgp-actions]
      set-local-pref = 110
```
But when I try to run the command, get the following error:

`{"Error":"2 error(s) decoding:\n\n* 'neighbors[0]' has invalid keys: apply-policy-config\n* 'policy-definitions[0].statements[0].conditions' has invalid keys: actions","Topic":"Config","level":"fatal","msg":"Can't read config file gobgpd.conf","time":"2017-01-03T13:01:50+10:00"}
`

Any clue? Is there any way to get more debug output?

**Comment by s2ugimot** [comment]
@fakrul `[neighbors.apply-policy-config]` is **for route server setup**. You need to use global import policy if you are not running gobgpd as a route server.

See pp.84-86 of [my tutorial slides](http://www.slideshare.net/shusugimoto1986/tutorial-using-gobgp-as-an-ixp-connecting-router).

**Comment by fakrul** [comment]
@s2ugimot Thanks!
