### ISSUE TITLE
support for Administrative Shutdown Communication

### ISSUE THREAD

**Issue by job** [osrg/gobgp#1200]
The draft-ietf-idr-shutdown document specifies a mechanism to transmit a short freeform UTF-8 [RFC3629] message as part of a Cease NOTIFICATION message [RFC4486] to inform the peer why the BGP session is being shutdown. I believe this would be a useful feature for people who use GoBGP in Route Server scenarios.

https://tools.ietf.org/html/draft-ietf-idr-shutdown

**Comment by job** [comment]
For a full overview of all feature considerations that we applied to OpenBGPD - please review the issues list at https://github.com/job/openbgpd/issues?utf8=%E2%9C%93&q=is%3Aissue

**Comment by iwaseyusuke** [comment]
@job 
Hi,

GoBGP have already has the feature to send Cease NOTIFICATION messages with the following command.
(it seems to be deprecated, though...)
```
# with subcode "Administrative Shutdown"
$ gobgp neighbor <NEIGHBOR_IP> shutdown
WARNING: command `shutdown` is deprecated. use `disable` instead
```
You mean the feature to transmit an arbitrary UTF-8 message, right?
If so, I'm going to add "--message" option to specify the transmitted message like:
```
gobgp neighbor -m "some message" <NEIGHBOR_IP> shutdown
```
What do you think?

Thanks

**Comment by job** [comment]
Yes indeed I mean the feature to transmit (or receive) the UTF8 message at shutdown time. A "--message" feature would be most welcome!

**Comment by job** [comment]
@iwaseyusuke will you also add support so a received shutdown communication is printed into the appropriate places (terminal, syslog, etc)?

**Comment by iwaseyusuke** [comment]
@job 
Thank you for your confirmation!

Currently, I have implemented "to send message" only.

I found that GoBGP already can log the received NOTIFICATION message body, but as a binary like `"c2h1dGRvd24gVGh1IEphbiAxOSAwMDoyMzoxMSBVVEMgMjAxNw=="`(base64?).

Though I don't know whether we can "always" decode the NOTIFICATION message body as "a character string", if we can, I will implement it as following.
What do you think about if we should decode as "a character string"?

Command:
```
$ gobgp neighbor -m "shutdown by administrator" 172.17.0.3 shutdown
```
Sent side:
```
{"Key":"172.17.0.3","Topic":"Operation","level":"info","msg":"Neighbor shutdown","time":"2017-01-19T00:51:52Z"}
{"Code":6,"Data":"shutdown by administrator","Key":"172.17.0.3","State":"BGP_FSM_ESTABLISHED","Subcode":2,"Topic":"Peer","level":"warning","msg":"sent notification","time":"2017-01-19T00:51:52Z"}
{"Key":"172.17.0.3","Reason":"notification-sent code 6(cease) subcode 2(administrative shutdown)","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2017-01-19T00:51:52Z"}
```
Received side:
```
{"Code":6,"Data":"shutdown by administrator","Key":"172.17.0.2","Subcode":2,"Topic":"Peer","level":"warning","msg":"received notification","time":"2017-01-19T00:51:52Z"}
{"Key":"172.17.0.2","Reason":"notification-received code 6(cease) subcode 2(administrative shutdown)","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2017-01-19T00:51:52Z"}
```

**Comment by job** [comment]
This looks very good!

You can perhaps take a look at the ExaBGP code to create a similar logic to decide when to decode a `Cease NOTIFICATION` body as a UTF8 character string: https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/bgp/message/notification.py#L108-L145

I'd create a new keyword in the dictionary called "communication", put the decoded character string in that key, and if there is any trailing data put that under the 'data' key. That way if someone sends data _after_ the shutdown communication (you know when the shutdown communication ends because of the embedded length field) this binary data is available in base64.

**Comment by iwaseyusuke** [comment]
@job 
Thank you for your advice!

From ExaBGP source, I understood that decoding as UTF8 characters is required only when Cease NOTIFICATION message with "Administrative Shutdown" subcode.
I need some fixes in my current implementation, then I will update and create Pull Request.

BTW, I wonder if the "length" field should be placed to tell the length of the following "communication" field.
Because we can determine the end of "data" filed of NOTIFICATION message by using the "length" field in BGP header, I guess.

**Comment by job** [comment]
Correct, decoding as UTF8 is _only_ required for (Code 6, Subcode 2). 

The length field inside the shutdown communication exists so that, should the need arise, that part of the protocol can be extended in the future. Hypothetically speaking: if we don't like the shutdown communication in its current form, a new IETF draft could say "set the length field to `0x0`, and whatever comes after the that zeroized lengthfield is something new". So the shutdown communication length field exists to allow future innovation.

The exabgp implementation will show a hexdump of any data that comes after the shutdown communication, this facilitates debugging. I've improved the wording in this section a little bit, perhaps that helps? https://tools.ietf.org/html/draft-ietf-idr-shutdown-03#section-2

**Comment by iwaseyusuke** [comment]
@job 
I did't knows IETF's rule. Thanks!

draft 03 is more clear! It helps me to understand that!

**Comment by fujita** [comment]
Please reopen if the master doesn't work.
