### ISSUE TITLE
GetRib() cause crash

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1227]
{"level":"info","msg":"gobgpd started","time":"2017-01-27T17:33:19Z"}
{"level":"info","msg":"gobgpd started","time":"2017-02-01T15:10:06Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4a53ac]

goroutine 52 [running]:
panic(0xa889c0, 0xc42000c040)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/osrg/gobgp/api.(*Server).GetRib(0xc420193640, 0x7f943f09d028, 0xc42021a360, 0xc42012e0e0, 0x0, 0x6, 0x6)
        /home/kunihiro/src/github.com/osrg/gobgp/api/grpc_server.go:315 +0x16c
github.com/osrg/gobgp/api._GobgpApi_GetRib_Handler(0xb53460, 0xc420193640, 0x7f943f09d028, 0xc42021a360, 0xc42025a240, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kunihiro/src/github.com/osrg/gobgp/api/gobgp.pb.go:4936 +0x280
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200e40c0, 0x1088e80, 0xc42026c0c0, 0xc420066500, 0xc4201d42d0, 0x10751e8, 0x0, 0x0, 0x0)
        /home/kunihiro/src/google.golang.org/grpc/server.go:708 +0xbd8
google.golang.org/grpc.(*Server).handleStream(0xc4200e40c0, 0x1088e80, 0xc42026c0c0, 0xc420066500, 0x0)
        /home/kunihiro/src/google.golang.org/grpc/server.go:892 +0x6a4
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42012c870, 0xc4200e40c0, 0x1088e80, 0xc42026c0c0, 0xc420066500)
        /home/kunihiro/src/google.golang.org/grpc/server.go:468 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/kunihiro/src/google.golang.org/grpc/server.go:469 +0xa3

**Comment by ishidawataru** [comment]
@kishiguro Could you explain more how to reproduce the issue?

**Comment by kishiguro** [comment]
Let me figure out the reproducing procedure.

**Comment by kishiguro** [comment]
Fixed in the release 1.17.  Thanks.
