### ISSUE TITLE
Existing RIB is not sent to zapi when connection is established

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1231]
Even if there is RIB exists before connection with zebra, it is not sent to zapi.  That will cause missing RIB in forwarder...

**Comment by ishidawataru** [comment]
should be fixed by [this](https://github.com/osrg/gobgp/commit/52356c26f821fdebb3fdf943a1b898a2d1b4d0db).
Please try the latest master.

**Comment by kishiguro** [comment]
Thanks let us try it!

**Comment by kishiguro** [comment]
Fixed.  Thanks.
