### ISSUE TITLE
DeletePolicyAssignment out of cap range panic

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1239]
We encounter crash in DeletePolicyAssignment func.

{"Key":"","Topic":"Operation","level":"info","msg":"Neighbor soft reset out","time":"2017-02-16T09:24:08Z"}
panic: runtime error: makeslice: cap out of range
goroutine 21 [running]:
panic(0xac4560, 0xc4201a0770)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/osrg/gobgp/table.(*RoutingPolicy).DeletePolicyAssignment(0xc4201b4100, 0xb9f1da, 0x6, 0x3, 0xc4200
        /home/kunihiro/src/github.com/osrg/gobgp/table/policy.go:3529 +0x5c0
github.com/osrg/gobgp/server.(*BgpServer).DeletePolicyAssignment.func1(0x43f84c, 0xc42003fe68)
        /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:1976 +0xe3
github.com/osrg/gobgp/server.(*BgpServer).handleMGMTOp(0xc42005a400, 0xc420242b20)
        /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:155 +0x36
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc42005a400)
        /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:265 +0x398
created by main.main
        /home/kunihiro/src/github.com/osrg/gobgp/gobgpd/main.go:119 +0x3c7

It seems that: policy.go:3529

		n := make([]*Policy, 0, len(cur)-len(ps))

cause a crash.  There could be a situation that len(ps) > len(cur).  That will give negative value to make slice function.  Make the line to

		n := make([]*Policy, 0, len(cur))

seems fix the issue.

**Comment by fujita** [comment]
Thanks for the report!

The bug should be fixed with the following:

https://github.com/osrg/gobgp/commit/564c45b90b959f6159119fd8f28fa6479f40c717

**Comment by kishiguro** [comment]
The change fixed the issue.  Thanks!
