### ISSUE TITLE
Crash in getDestinationCount() with nil arguments.

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1244]
It seems there could be a situation with nil pointer argument passed to getDestinationCount()...

Feb 17 22:25:08 esehost gobgpd[6858]: {"level":"info","msg":"gobgpd started","time":"2017-02-17T22:25:08Z"}
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c4267]
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: goroutine 21 [running]:
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: panic(0xac7460, 0xc42000c080)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/table.(*TableManager).tables(0x0, 0x0, 0x0, 0x0, 0xc42025a050, 0x30, 0x10d9530)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/table/table_manager.go:303 +0x37
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/table.(*TableManager).getDestinationCount(0x0, 0x0, 0x0, 0x0, 0xc42003f6f0)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/table/table_manager.go:320 +0x49
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/table.(*TableManager).GetBestPathList(0x0, 0xba23fd, 0x6, 0x0, 0x0, 0x0, 0x6, 0x0, 0x0)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/table/table_manager.go:327 +0x67
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/server.(*BgpServer).Watch.func1(0x43f84c, 0xc42003fe68)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:2328 +0x37d
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/server.(*BgpServer).handleMGMTOp(0xc42018e400, 0xc42025cb80)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:155 +0x36
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc42018e400)
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/server/server.go:265 +0x398
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]: created by main.main
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 gobgpd[6858]:         /home/kunihiro/src/github.com/osrg/gobgp/gobgpd/main.go:119 +0x3c7
Feb 17 22:27:54 d7ee2d6d-2e5d-494f-af31-c4ef7a4f8d23 systemd[1]: gobgpd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by fujita** [comment]
getDestinationCount() can handle nil because in tables(), len(nil) returns zero.

crashed at:
https://github.com/osrg/gobgp/blob/master/table/table_manager.go#L303

I think that accessing to uninitialized Tables. I pushed the fix. Can you try the latest?

https://github.com/osrg/gobgp/commit/61890751e12a39dadc0ef072463a71c01704eaf1

**Comment by kishiguro** [comment]
Confirmed the crash is fixed.  Thanks!
