### ISSUE TITLE
Ability to lock TTL for iBGP

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#1268]
Hey!

It's possible to set TTL for eBGP peers. Would it be possible to set it also for iBGP peers? Additionnaly, being able to specify a minimal value would be great (`IP_MINTTL`). This is a security measure to set it to 255 to ensure only directly connected hosts are able to speak with the peer.

**Comment by iwaseyusuke** [comment]
Hi @vincentbernat 

For `IP_MINTTL`, you mean TTL security, right?
I've just create a PR related to this feature.
Could you review my PR?

For 'ebgp-multihop' feature in iBGP, I guess implementation is not so difficult, but this feature should not be necessary in iBGP peering.
This topic seems to be discussed below;
https://supportforums.cisco.com/discussion/10714216/multihop-ibgp

**Comment by vincentbernat** [comment]
I'll test your PR. For `ebgp-multihop`, this is just a matter of being able to set the TTL to a value high enough to pass the TTL security check. On Linux, the default TTL is 64. Maybe setting a minimum TTL also bump the outgoing TTL. I'll check today.

**Comment by fujita** [comment]
@vincentbernat Can you try the latest master?

**Comment by vincentbernat** [comment]
I already tested the PR, so all good :)
