### ISSUE TITLE
Help configuring gobgpd.conf

### ISSUE THREAD

**Issue by plojr** [osrg/gobgp#1269]
Hi, I'm trying to configure gobgpd in order to create a BGP session with a router, and gobgpd's connection with the router cannot be established.
I'm not sure about the parameters' values. Could someone help me?

My /etc/gobgpd.conf is:

[global.config]
  as = 25000
  router-id = "200.xxx"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "201.xxx"
    peer-as = 25000

[[neighbors]]
  [neighbors.config]
    neighbor-address = "202.xxx"
    peer-as = 25000

First doubt: how can I get the AS number for global config? I was looking at the configuration file that I got from the Network Engineering guys, and I found an old configuration with Arbor (Anti-DDoS) and there was this 25000 there. Do I use the same number for neighbor and global.config?

Second one: after filling the values in the configuration file, I ran the command: gobgpd -f /etc/gobgpd.conf & and I got no errors. Does that mean that the connection can already be established?

If everything is alright, the problem can be with the router configuration?

Thanks in advance.

**Comment by plojr** [comment]
I'm running tcpdump in order to see what the routers were responding and the server only gets Fin and Reset TCP packets from the routers.

When I run gobgp neighbor 201.xxx or gobgp neighbor 202.xxx, the server receives only opens and keepalives messages.

Am I missing something?

**Comment by ishidawataru** [comment]
> First doubt: how can I get the AS number for global config?

If you are trying to peer with routers within the public Internet, you must use the AS number which is assigned to your organization.

see here. https://www.ultratools.com/tools/asnInfoResult?domainName=25000

If not, use the number within the range of 64512 - 65534.

see here. https://tools.ietf.org/html/rfc6996

> Second one: after filling the values in the configuration file, I ran the command: gobgpd -f /etc/gobgpd.conf & and I got no errors. Does that mean that the connection can already be established?

You can check that by `gobgp neighbor` command.
If your neighbor's state is `Establ`, it means the connection is established.

**Comment by plojr** [comment]
I got my organization AS number. Do I have to use the same number for neighbor and global.config? If not, what AS number do I have to use?

Thank you for your answer. :+1:

**Comment by ishidawataru** [comment]
Depends on how your neighbor router is configured.
You need to know your neighbor router's AS number and use it in neighbor configuration.

**Comment by plojr** [comment]
My neighbor router's AS number is ok. I know what it is. What I don't know is AS global config.

**Comment by ishidawataru** [comment]
This also depends on how your neighbor router is configured.
You need to set global AS number as same as the value in your neighbor's configuration.

**Comment by plojr** [comment]
I see.
I'll talk to the Network Guys and ask for the router's configuration, but how do I know if gobgp will use the same AS global config or not?

I think there is a piece of information I don't know that's causing my doubt. (But I'll figure it out.)

Thanks one more time.

**Comment by plojr** [comment]
My tcpdump output is something like this:

my_server_where_gobgp_is_installed.some_port -> router.bgp: Flags [S]
router.bgp -> my_server_where_gobgp_is_installed.some_port [F]
my_server_where_gobgp_is_installed.some_port -> router.bgp: Flags [S]
router.bgp -> my_server_where_gobgp_is_installed.some_port [R]
my_server_where_gobgp_is_installed.some_port -> router.bgp: Flags [S]
router.bgp -> my_server_where_gobgp_is_installed.some_port [R]
my_server_where_gobgp_is_installed.some_port -> router.bgp: Flags [S]
router.bgp -> my_server_where_gobgp_is_installed.some_port [F]

I only get RST and FIN packets from the router.

**Comment by plojr** [comment]
I've just read this https://www.juniper.net/techpubs/en_US/junos12.1x46/topics/usage-guidelines/routing-configuring-bgp-groups-and-peers.html (My organization's router's Juniper), and I've just realized that my doubt's answer is: "yes, both AS (for global config and neighbor) must be the same, as my server is inside my organization." Am I right?

**Comment by plojr** [comment]
I found my problem. Network guys made a wrong configuration on router. After checking the configuration out, the problem was solved.
