### ISSUE TITLE
gRPC-Go dropped support of Go 1.5

### ISSUE THREAD

**Issue by iwaseyusuke** [osrg/gobgp#1280]
Because gRPC-Go dropped the support of Go 1.5, Travis-CI have became to raise error.
See https://github.com/grpc/grpc-go/commit/0a20758157ab70dd0712015b88914c0c38666e62, for details.

Error messages on GoBGP's Travis-CI:
```
$ go get -t ./...
# google.golang.org/grpc/transport
../../../google.golang.org/grpc/transport/http2_client.go:130: undefined: dialContext
```

I guess we need to drop the support of Go 1.5 or do some workarounds.

**Comment by fujita** [comment]
Thanks for the report. No reason to stick with go1.5 so let's drop it rather than inventing workarounds.
