### ISSUE TITLE
Feature Request: Support for Local RIB in BGP Monitoring Protocol (BMP)

### ISSUE THREAD

**Issue by mstrother** [osrg/gobgp#1281]
[https://tools.ietf.org/html/draft-evens-grow-bmp-local-rib-00.html](https://tools.ietf.org/html/draft-evens-grow-bmp-local-rib-00.html)

The above draft defines a new peer type, Peer Type = 3: Loc-RIB Instance Peer. The peer type adds access to to the BGP Local-RIB (RFC 4271) after the local BGP speaker's decisions process. 

Currently monitoring the Loc-RIB requires two routers and a BGP session between them.

**Comment by iwaseyusuke** [comment]
Hi @mstrother 

That sounds great feature for me!
Just to confirm... in this case, GoBGP should be an BMP client, but is there any BGP Sever supporting this feature?
I wonder wow we should test the implementation? Do you have any idea or some implementations?

**Comment by mstrother** [comment]
BMP sends all routes in the Adj-RIB-In of every peer but does not provide a Local RIB view of the routes after best path selection. This is overly complex for simple monitoring. It also results in a very large amount of unwanted data. For example, with 5 peers and full routing tables it results in millions messages  upon starting GoBGP. In addition it doesn't allow monitoring of your own announcements (Adj-RIB-Out). The monitoring application has to reproduce the best path selection process.

The new peer type would add a third view to BMP.

Adj-RIB - per peer (pre-policy)
Adj-RIB - per peer (post-policy)
_Local-RIB - (after best path selection)_

A monitoring application may wish to collect all one or more of the views. For example, my default configuration may be Local-RIB but to debug a problem with a peer I may need to see their announcements even if they don't make it past best path selection and into the Local RIB.

This would need to be configurable:

[[bmp-servers]]
  [bmp-servers.config]
    address = "127.0.0.1"
    port=11019
    route-monitoring-policy = [ "pre-policy", "post-policy", "local" ]

**Comment by iwaseyusuke** [comment]
Thank you for your reply!

It makes it clear for me!
I understand (roughly) that this draft adds the type of view in which the peer is interested, and enable to monitor the routes after the best path selection.

Thanks!

**Comment by mstrother** [comment]
Yes. The same information I would see with `gobgp global rib`

**Comment by mstrother** [comment]
There should be a way to monitor pre, post, and local-rib policy. Having more than two route monitoring policies also makes the configuration setting route-monitoring-policy = "local-rib" unclear.

As stated in "bmp-draft-evens-grow-bmp-local-rib" :

For example, in order to validate if multi-path prefixes are installed as expected for all advertising peers, the Adj-RIB-In Post-Policy and Loc-RIB needs to be compared.

Thoughts?

**Comment by fujita** [comment]
Yeah, replacing "both" with "all"?

**Comment by iwaseyusuke** [comment]
I might be wrong but...
You mean the arbitrary combination of these types?
e.g.) "pre-policy"+"local" or "post-policy"+"local"

**Comment by mstrother** [comment]
"all" works well and is simple. "both" should be deprecated. Ideally the value should probably be a string array as @iwaseyusuke mentioned.

**Comment by iwaseyusuke** [comment]
For the simple way, I added a new key "all" into "route-monitoring-policy": https://github.com/osrg/gobgp/pull/1325
@mstrother , could you review it?

**Comment by mstrother** [comment]
@iwaseyusuke #1325 isn't currently building correctly. I haven't had time to look at in detail yet.

I think there are issues with #1297 . When I set `route-monitoring-policy = "local-rib"` The L flag is removed correctly but I still see peer header information in the BMP messages for my peers not for the local-rib.

The peer type should be set to 3 but I see 0. Also the peer-address should be zero filled as it's not applicable and the peer AS should be the BGP instance global or default ASN value.

**Comment by iwaseyusuke** [comment]
Thanks @mstrother 

I've updated my PR https://github.com/osrg/gobgp/pull/1325 to fix the problem you mentioned.
Could you check it?

**Comment by mstrother** [comment]
Thanks @iwaseyusuke . Looks good!

**Comment by iwaseyusuke** [comment]
@mstrother 
Thank you for reviewing my patch and pointing out this issue!

**Comment by fujita** [comment]
Thanks guys! Pushed https://github.com/osrg/gobgp/pull/1325
