### ISSUE TITLE
client connection closed to grpc server FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427} 

### ISSUE THREAD

**Issue by rajnkamr** [osrg/gobgp#1288]
Getting errors while connecting client to grpc server running in gobgp daemon

Local attempting GRPC connect to BGP: state 0
GRPC:ERRO [chttp2_transport.c::1810] close_transport{"created":"@1490884677.946632042","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}

**Comment by fujita** [comment]
https://github.com/grpc/grpc/issues/10378

Solved? Either way, I think that it's not a GoBGP issue.
