### ISSUE TITLE
long lived graceful restart does not work when we have 2 neighbor

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1296]
We configure one RR with two iBGP neighbors.

<pre>
RR <-> iBGP1
   <-> iBGP2
</pre>

With this setup, RR is configured as graceful restart's Restarting Router.  First convergence worked fine but when RR's gobgpd is restarted with -r option, iBGP1 can establish the peering but iBGP2 can't establish the peering.

The iBGP2 which can't establish the connection said: "restart flag is not set".   The behavior is not consistent.  Sometimes, iBGP2 can establish the connection but iBGP1 can't.  Among 20 tries, one time both peering can be established but is is very rare.

When this occurs, iBGP2 can't establish the peering forever.  There is no way to operationally fix the status unless we restart iBGP2's gobgpd.

Right now we simply comment out the code in server/fsm.go

 <pre>
						// RFC 4724 4.1
						// To re-establish the session with its peer, the Restarting Speaker
						// MUST set the "Restart State" bit in the Graceful Restart Capability
						// of the OPEN message.
						// if fsm.pConf.GracefulRestart.State.PeerRestarting && cap.Flags&0x08 == 0 {
						// 	log.WithFields(log.Fields{
						// 		"Topic": "Peer",
						// 		"Key":   fsm.pConf.Config.NeighborAddress,
						// 		"State": fsm.state.String(),
						// 	}).Warn("restart flag is not set")
						// 	// send notification?
						// 	h.conn.Close()
						// 	return bgp.BGP_FSM_IDLE, FSM_INVALID_MSG
						// }
						if fsm.pConf.GracefulRestart.Config.NotificationEnabled && cap.Flags&0x04 > 0 {
							fsm.pConf.GracefulRestart.State.NotificationEnabled = true
						}
</pre>

RR gobgpd.conf
<pre>
[global.config]
  as = 1
  router-id = "192.168.55.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.2"
    peer-as = 1
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.55.1"

  [neighbors.graceful-restart.config]
    enabled = true
    long-lived-enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
    [neighbors.afi-safis.long-lived-graceful-restart.config]
        enabled = true
        restart-time = 172800

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.66.2"
    peer-as = 1
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.55.1"

  [neighbors.graceful-restart.config]
    enabled = true
    long-lived-enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
    [neighbors.afi-safis.long-lived-graceful-restart.config]
        enabled = true
        restart-time = 172800
</pre>

iBGP's gobgpd.conf
<pre>
[global.config]
  as = 1
  router-id = "192.168.55.2"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.1"
    peer-as = 1

[neighbors.graceful-restart.config]
    enabled = true
    long-lived-enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "ipv4-unicast"
    [neighbors.afi-safis.long-lived-graceful-restart.config]
        enabled = true
</pre>

**Comment by ishidawataru** [comment]
Which shutdown the connection? RR or RR-client?

**Comment by kishiguro** [comment]
RR shutdown and restart with -r flag.

**Comment by ishidawataru** [comment]
I meant after the restart with -r flag, who is complaining about the open message and rejecting to establish the session?
Could you paste the log of both side here?

**Comment by fujita** [comment]
@kishiguro This bug should be fixed. Can you try the latest master?
