### ISSUE TITLE
Withdraw grouping chaotic

### ISSUE THREAD

**Issue by nshopik** [osrg/gobgp#1309]
Withdraw update messages aren't grouped even when its possible, some withdraws messages are 1 per packet and others are 2-3 or maximum per packet.

My test was just adding 1000 routes and then purge them all with `gobgp global rib del all -a ipv4` all routes are same except prefix, with prefix length /32

**Comment by pavel-odintsov** [comment]
Yep, agree! Would be nice to have support for batching in such cases to decrease the load on GoBGP itself and remote peers.

**Comment by nshopik** [comment]
Small update, while this says `Withdraw` it actually applies to both Withdraw and Announce messages. I used Withdraw just for simplicity sake of case

**Comment by fujita** [comment]
Sorry about the delay, the current master should handle this nicely.
