### ISSUE TITLE
java client is very big

### ISSUE THREAD

**Issue by rslvn** [osrg/gobgp#1338]
I followed java client generation steps.
Finally, 2 files is generated. But the file size is very big. 

```
> ls -lh
total 2.9M
-rw-r--r-- 1 root root 123K Apr 27 15:40 GobgpApiGrpc.java
-rw-r--r-- 1 root root 2.7M Apr 27 15:40 Gobgp.java

>  wc -l Gobgp.java
83327 Gobgp.java
```

is there any way to generate a smaller file?

**Comment by fujita** [comment]
Better to ask grpc developers, I guess.
