### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by michaelc0n** [osrg/gobgp#1342]
Are there production deployments you could share and/or use cases for GoBGP over typical BGP deployments on the edge or within the data center?   Thx!

**Comment by cstockton** [comment]
@michaelc0n I personally believe one great use case for GoBGP is network defense for any company that has edge routers or uses BGP already in some capacity. Currently I've created a REST API backed by GoBGP for DDoS mitigation by peering with our edge network to advertise black holes with the next goal being automated traffic swings. Being able to utilize existing network infrastructure over extremely expensive black box devices allows any granularity of detection mechanisms and mitigation. For example an application team may maintain a histogram of existing login attempts. Having a REST API allows them to black hole an offending IP to immediately relieve strain from the APP that would have occurred while the more holistic network wide thresholds were met.

_fine print: my own personal opinion and not necessarily the opinion of my employer._

**Comment by fujita** [comment]
INTERNET MULTIFEED uses GoBGP as a route server for their Internet Exchange service.
http://www.jpnap.net/english/press/2016/20160930-e.html

**Comment by michaelc0n** [comment]
Thank you both @fujita and @cstockton !!! Those are both great examples of use cases, appreciate it!

**Comment by fujita** [comment]
You can find another user that uses GoBGP in production at the site:
https://osrg.github.io/gobgp/
