### ISSUE TITLE
Please add support for RFC8050

### ISSUE THREAD

**Issue by tking** [osrg/gobgp#1343]
Dear GoBGP Developers,

please add support for RFC8050 (https://tools.ietf.org/html/rfc8050): Multi-Threaded Routing Toolkit (MRT) Routing Information Export Format with BGP Additional Path Extensions.

Thanks in advance,
Thomas

**Comment by iwaseyusuke** [comment]
Hi @tking 

The support for RFC8050 has been merged with by PR https://github.com/osrg/gobgp/pull/1347
But, please note this PR includes only decoder/encoder of MRT format, and does not include the implementation for advertising routes with Add-Path extensions.

For Add-Path extensions advertisement, it seems to be supported sometime soon as far as I've heard

Thanks,
Iwase

**Comment by fujita** [comment]
@iwaseyusuke now the master includes addpath support. Can you update mrt support?

**Comment by iwaseyusuke** [comment]
@fujita 
Sure, I will create another PR to support it.

**Comment by fujita** [comment]
@iwaseyusuke can we close this?

**Comment by iwaseyusuke** [comment]
@fujita Yes, now GoBGP supports exporting MRT files with Add-Paths extensions.

**Comment by fujita** [comment]
@tking please reopen this if the new feature doesn't work as you expect.
