### ISSUE TITLE
api/grpc_server.go does not include  config knob for enable/disable  "graceful_restart".

### ISSUE THREAD

**Issue by yagosys** [osrg/gobgp#1354]
api/grpc_server.go does not include  config for enable/disable  "graceful_restart".

I can enable graceful_restart through YAML configuration below
[neighbors.graceful-restart.config]
        enabled = true
        notification-enabled = true
        long-lived-enabled = true
        # graceful restart restart time
        restart-time = 120 

but I can not find the equivalent API from api/grpc_server.go .

can we have this API ?

**Comment by fujita** [comment]
Surely,
https://github.com/osrg/gobgp/commit/83684d5e62fb14596aabf03747a8b395543f91bb

Would be great if you could create a pull request to improve this if necessary.
