### ISSUE TITLE
graceful restart api doesn't work

### ISSUE THREAD

**Issue by pslzym** [osrg/gobgp#1356]
Hi, I'm happy to see the graceful restart code update.https://github.com/osrg/gobgp/pull/1355.
I test the code , but it  doesn't work. https://github.com/osrg/gobgp/blob/master/docs/sources/graceful-restart.md
[[neighbors.afi-safis]]
[neighbors.afi-safis.config]
afi-safi-name = "ipv4-unicast"
[neighbors.afi-safis.mp-graceful-restart.config]
enabled = true
graceful restart need to be configured mp-graceful-restart.config and afi-safi-name,but grpc  addnei can not be configured it.

**Comment by iwaseyusuke** [comment]
Hi @pslzym 
Just an idea, how about adding a list of afi-safi values named "families" into "GracefulRestart" message structure?
```
 message GracefulRestart {
   bool enabled = 1;
   uint32 restart_time = 2;
   bool helper_only = 3;
   uint32 deferral_time = 4;
   bool notification_enabled = 5;
   bool longlived_enabled = 6;
+  repeated uint32 families = 7;
 }
```

**Comment by iwaseyusuke** [comment]
Hi,
I re-open a new PR for this issue; https://github.com/osrg/gobgp/pull/1367
And it seems to be merged to upstream.
Could test the latest?

**Comment by fujita** [comment]
@pslzym please reopen this if the current master doesn't work.
