### ISSUE TITLE
BGP4 to flowspec

### ISSUE THREAD

**Issue by malizvrcko** [osrg/gobgp#1375]
Hi,

would it be possible to receive BGP4 route and reformat it to flowspec?
E.G. device in network announces route via bgp4 and gobgp reformats it
by adding drop,rate limit or whatever condition is supported by flowspec,
and announces it to selected flowspec  peers.

**Comment by fujita** [comment]
You can use GoBGP as a golang package to implement such
https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md
