### ISSUE TITLE
Random Crash during normal operations

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1391]
Hi, I have just experienced a random crash without any input from my side.

Any idea what the issue could be:

Jul 27 16:46:49 at-router-03 gobgpd[6945]: panic: interface conversion: net.Conn is nil, not *net.TCPConn
Jul 27 16:46:49 at-router-03 gobgpd[6945]: goroutine 118846 [running]:
Jul 27 16:46:49 at-router-03 gobgpd[6945]: panic(0xda0be0, 0xc820527c80)
Jul 27 16:46:49 at-router-03 gobgpd[6945]: /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
Jul 27 16:46:49 at-router-03 gobgpd[6945]: github.com/osrg/gobgp/server.(*TCPDialer).DialTCP.func1(0x3fe, 0x0, 0x0, 0x0)
Jul 27 16:46:49 at-router-03 gobgpd[6945]: /root/go/src/github.com/osrg/gobgp/server/sockopt_linux.go:216 +0xf7
Jul 27 16:46:49 at-router-03 gobgpd[6945]: github.com/osrg/gobgp/server.(*TCPDialer).DialTCP(0xc820481f30, 0xc8201a0820, 0xa, 0
Jul 27 16:46:49 at-router-03 gobgpd[6945]: /root/go/src/github.com/osrg/gobgp/server/sockopt_linux.go:259 +0x150c
Jul 27 16:46:49 at-router-03 gobgpd[6945]: github.com/osrg/gobgp/server.(*FSM).connectLoop.func1()
Jul 27 16:46:49 at-router-03 gobgpd[6945]: /root/go/src/github.com/osrg/gobgp/server/fsm.go:357 +0x5a4
Jul 27 16:46:49 at-router-03 gobgpd[6945]: created by github.com/osrg/gobgp/server.(*FSM).connectLoop
Jul 27 16:46:49 at-router-03 gobgpd[6945]: /root/go/src/github.com/osrg/gobgp/server/fsm.go:391 +0x581

When quickly looking over socktopt_linux.go I found that part (211 ff):
```
	newTCPConn := func(fd int) (*net.TCPConn, error) {
		fi := os.NewFile(uintptr(fd), "")
		defer fi.Close()

		conn, err := net.FileConn(fi)
		return conn.(*net.TCPConn), err
	}
```

I believe that here a check on err should be added BEFORE casting conn to the TCPConn!

**Comment by fujita** [comment]
Thanks a lot! Fixed.
