### ISSUE TITLE
Extended Communities not serializing into BGP Message

### ISSUE THREAD

**Issue by kpradeepnet** [osrg/gobgp#14]
Hi, hopefully it is ok asking a question here. I am new to github. I was looking at this nice project to do something for a research project but am stuck. My problem is trying to serialize "PathAttributeExtendedCommunities". 

-I am seeing the serialization in the bgp_test.go trying to use the test message as follows:

	&IPv4AddressSpecificExtended{SubType: 3, IPv4: net.ParseIP("192.2.1.2").To4(), LocalAdmin: 3000},
	&OpaqueExtended{Value: []byte{0, 1, 2, 3, 4, 5, 6, 7}},
	&UnknownExtended{Type: 99, Value: []byte{0, 1, 2, 3, 4, 5, 6, 7}},

I end up with an empty array:

	&{{192 BGP_ATTR_TYPE_EXTENDED_COMMUNITIES 0 []} []}
	
The message looks good in the BGPUpdate message

	func (msg *BGPUpdate) Serialize() ([]byte, error) {

Creates:

	&{{%!s(uint8=192) BGP_ATTR_TYPE_EXTENDED_COMMUNITIES %!s(uint16=0) } [%!s(*bgp.OpaqueExtended=&{[0 1 2 3 4 5 6 7]})]}

But when the ExtendedCommunity array gets processed further it seems to be empty.

	pbuf := make([]byte, 2)
	for _, p := range msg.PathAttributes {

The nested Extended Attribute is never triggered:

	func (e *OpaqueExtended) Serialize() ([]byte, error) {

Wireshark ends up with an extended attributes structure but it is empty with a length of 0. Thank you for any assistance you can offer.

**Comment by fujita** [comment]
Thanks for the report! I've just pushed a fix. Can you try the latest code?
