### ISSUE TITLE
gobgpd + Too many open files

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1407]
Hi,

I'm running gobgpd with zebra:

```
global.config:
    as: 64512
    router-id: 10.21.13.42

zebra:
    config:
        enabled: true
        url: unix:/var/run/quagga/zserv.api
        redistribute-route-type-list:
            - static
```

But after a day or so, gobgpd has soo many open sockets, that the file system limit is reached.

Anyone experienced this, or can point to where the issue could be?

Edit:

kube-egress is my custom binary, there are 1024 sockets per thread of the application.

```
kube-egre 26191 30766    root  985u     sock                0,7       0t0   14152287 protocol: TCP
kube-egre 26191 30766    root  986u     sock                0,7       0t0   14152336 protocol: TCP
kube-egre 26191 30766    root  987u     sock                0,7       0t0   14126845 protocol: TCP
kube-egre 26191 30766    root  988u     sock                0,7       0t0   14152478 protocol: TCP
kube-egre 26191 30766    root  989u     sock                0,7       0t0   14152564 protocol: TCP
kube-egre 26191 30766    root  990u     sock                0,7       0t0   14152606 protocol: TCP
kube-egre 26191 30766    root  991u     sock                0,7       0t0   14152667 protocol: TCP
kube-egre 26191 30766    root  992u     sock                0,7       0t0   14196836 protocol: TCP
kube-egre 26191 30766    root  993u     sock                0,7       0t0   14196947 protocol: TCP
kube-egre 26191 30766    root  994u     sock                0,7       0t0   14198141 protocol: TCP
kube-egre 26191 30766    root  995u     sock                0,7       0t0   14197025 protocol: TCP
kube-egre 26191 30766    root  996u     sock                0,7       0t0   14197059 protocol: TCP
kube-egre 26191 30766    root  997u     sock                0,7       0t0   14013882 protocol: TCP
kube-egre 26191 30766    root  998u     sock                0,7       0t0   14197150 protocol: TCP
kube-egre 26191 30766    root  999u     sock                0,7       0t0   14197269 protocol: TCP
kube-egre 26191 30766    root 1000u     sock                0,7       0t0   14197322 protocol: TCP
kube-egre 26191 30766    root 1001u     sock                0,7       0t0   14197351 protocol: TCP
kube-egre 26191 30766    root 1002u     sock                0,7       0t0   14197417 protocol: TCP
kube-egre 26191 30766    root 1003u     sock                0,7       0t0   14231663 protocol: TCP
```

**Comment by Thoro** [comment]
I have created a custom binary that includes gobgd and it seems that this one also has the same socket issue.

Based on that info it has nothing todo with Zebra, and more with gobgpd

**Comment by fujita** [comment]
Thanks for the bug report.
I suspect that this can happen without zebra, right? On your setup, a peer is up and down over and over?
You see any suspicious messages?

**Comment by Thoro** [comment]
Yep happens without zebra.

Peers are going up and down constantly, true. Or they never get connected (Establ state).

No suspicious messages ..

**Comment by fujita** [comment]
I guess that the socketopt refactoring introduced the bug. I'll investigate. Meanwhile, can you try to disable active connection?

**Comment by Thoro** [comment]
Moved all Active connections to Idle (Admin) - current open sockets ~111 after about 40 minutes

will monitor if new ones appear now.

**Comment by Thoro** [comment]
After 2 hours still 111 sockets open - bug must be in the connection code.

**Comment by fujita** [comment]
Thanks for the info. I've just pushed a fix for this bug. Please try the latest master.https://github.com/osrg/gobgp/commit/f615fa49a768bb358e6318e64dc42e9a6af10681

**Comment by Thoro** [comment]
Looks good, no new sockets past 20 min, even with Active, non connecting neighbors!

**Comment by fujita** [comment]
Thanks a lot for the confirmation!
