### ISSUE TITLE
Support FRR Zebra

### ISSUE THREAD

**Issue by bschwerer** [osrg/gobgp#1411]
Request to have gobgp support FRR.

It does appear that FRR has a different header version than Quagga.  FRR supports zebra header format version 1 and has a unique marker and version (4)

https://frrouting.org/user-guide/Zebra-Protocol.html#Zebra-Protocol-Definition

**Comment by iwaseyusuke** [comment]
Thank you for your suggestion!

As you said, FRR uses version=4, marker=254 and the header format is the same with version 3 of Quagga.
But message types are extended (Quagga has 30 types, OTOH, FRR(v2.0) has over 50 types!).

I guess we need to upgrade some existing message implementations to support FRR format and implement minimum required messages as the first step.
The other messages should be implemented later to support additional features, I guess.

**Comment by hitoshi-irino-NTT** [comment]
I sent PR  #1425 "Supporting FRR 3 stable"

**Comment by fujita** [comment]
Please try the latest master.
