### ISSUE TITLE
Radix tree implementation, bytes not strings

### ISSUE THREAD

**Issue by dotwaffle** [osrg/gobgp#1414]
I notice in some parts of the code, you're using go-radix to produce a radix tree, however you're doing this by converting the prefix into a string and then converting it back with net.ParseCIDR when the result is found.

I wondered if you'd considered using critbitgo instead, https://godoc.org/github.com/k-sone/critbitgo allows you to store prefix data in the natural []byte format that is used with the net package. It should produce some nice speedups and reduction in memory -- not just for removing the string dependency, but also because you'll be storing the data in a proper compressed trie.

Not urgent by any means, as I don't actually tend to use the codepaths this would affect, but I figured it would be nice to remove all the string artefacts :)

**Comment by fujimoto-s** [comment]
Thank you for your suggestion!

I think it is worth to tackle. critbitgo will reduce the memory consumption of GoBGP.
However I doubt that critbitgo will speed up GoBGP, because, in the current implementation, radix trees are formed in binary tree.

And another problem is that critbitgo only accepts []byte keys. This causes conflicts.
For example, "192.168.0.0/12" and "192.168.0.0/16" has the same []byte representation, [192 168]. 
So these network addresses cannot coexist in the same tree.
We need some tricks, such as attaching a prefix length to []byte representations. (e.g. [192 168 12] and [192 168 16])

Anyway, I think we need to compare the performance between the current implementation and the implementation with critbitgo.

**Comment by dotwaffle** [comment]
The key creation in critbitgo includes the mask already, see function netIPNetToKey. Therefore your example 192.168.0.0/16 would be [192 168 0 0 255 255 0 0] and 192.168.0.0/12 would be [192 168 0 0 255 240 0 0]. It's all in "net.go" which contains everything to handle v4 and v6 net.IPNet records :)

**Comment by fujimoto-s** [comment]
Thanks! I overlooked it.
I will try to use it.

**Comment by fujimoto-s** [comment]
I've made a critbitgo version GoBGP with a naive implementation, and did a simple performance evaluation.
I found that there is no significant difference in terms of speed, but memory consumption will be decreased by about 8%.

I got a mrt format ribs from [here](http://archive.routeviews.org/bgpdata/2017.08/RIBS/) (it contains the large amount of routes), and I injected it to GoBGP.
And I measured the elapsed time to inject all routes and the memory consumption after injection three times, and I took the average of these.
The elapsed time was took by `time` command, and I extracted `real` and `user` rows form its output.
The memory consumption was took by `ps` command.

The result is:
```
                         current        with critbitgo
Time to Injection(real)  44.97s         42.67s
Time to Injection(user)  21.97s         21.98s
Memory consumption       2458M          2280M
```

There is no difference between `user` times, but memory consumption was decreased by about 8%.
So, We can expect that critbitgo will be good for the memory usage.

**Comment by dotwaffle** [comment]
Injection should be roughly comparable, but lookup should be a lot faster. Either way, hopefully I've been of assistance, thank you very much for looking at my idea!

**Comment by fujita** [comment]
How about this?
https://vincent.bernat.im/en/blog/2017-ipv4-route-lookup-linux

**Comment by fujimoto-s** [comment]
Thanks for the information!
I think LPC-trie will give us more memory and lookup time reduction.

However, there seems to be no libraries which provides LPC-trie structure for golang, unfortunately.
Adding to this, LPC-trie algorithm itself may be under patent protection:
https://patents.google.com/patent/US20050171959A1

I agree that LPC-trie is efficient, but I think there is some problem to use this.

**Comment by fbettag** [comment]
Well there is this library at least https://github.com/yl2chen/cidranger :)

**Comment by fujimoto-s** [comment]
Thanks!
It looks a nice library, however I think we cannot immediately use cidranger.

GoBGP has to list all or some destinations in order to display RIBs or do some operations.
So, the library for storing routing information should have "walk" API, which walks its tree from a specific node and do some operations for each node.

Currently, cidranger provides insert/delete/contains API, but not "walk" API.
So it is hard to use cidranger in GoBGP for now.
(If we use it, we should send some PR for this library.)

But, thanks for your information!

**Comment by fujita** [comment]
@fujimoto-s Can you evaluate the performance of cidranger a bit? I would like to know if it's worth adding necessary features to it or not.

**Comment by fujimoto-s** [comment]
Sure, I'll try to evaluate it.

**Comment by fujimoto-s** [comment]
I made a simple evaluation for go-radix, critbitgo and cidrager in the aspect of time efficiency and memory consumption.
In this evaluation, critbitgo shows good performance among these.



I know it is the best to make a version of GoBGP with critbitgo or with cidranger and evaluate with them, but it will be a hard work.
So, I made a simple program to evaluate their standalone performance.

In this program,
1. Create network addresses of `a.b.c.0/24` format and insert it into each trie. And measure the required time. Repeat this 128^3 times and take an average.
2. randamly create network addresses of `a.b.c.0/24` format and search it from each trie. And measure the required time. Repeat this 10000 times and take an average.

(I uploded these programs to Gist: [go-radix](https://gist.github.com/fujimoto-s/64e45882cc566708bd0afbf67c726333), [critbitgo](https://gist.github.com/fujimoto-s/9ed6ff3d9635818c49d7e852d3dd9e80), [cidranger](https://gist.github.com/fujimoto-s/d988a119c2d38cf56d937b13b3c94e08))

After this, I see the memory consumption of each program by `ps aux`  command. It is a measure of how much memory each trie is consuming.

The following table shows the result.

|           | Insert Avg. (ns) | Search Avg. (ns) | VSZ (KB) | RSS (KB) |
| --------- | ---------------: | ---------------: | -------: | -------: |
| go-radix  |              825 |             1206 |   325848 |   320696 |
| critbitgo |              440 |             1051 |   363300 |   246952 |
| cidranger |            11442 |             3102 |  1771636 |  1581080 |

critbitgo shows a good performance in the both aspects of time efficiency and memory consumption. 
On the other hand, somehow the performance of cidranger is lower.

The resuls may change if they are integrated with GoBGP, but at least I don't think cidranger is a good choice.

**Comment by vincentbernat** [comment]
I didn't read the patent, but implementation of LPC-trie in Linux is a direct translation of [this paper](https://www.nada.kth.se/~snilsson/publications/IP-address-lookup-using-LC-tries/) which predates the patent.

However, I don't think using LPC-trie is a good idea if you want the same structure for IPv4 and IPv6 as the level compression is less likely to work well with IPv6.

**Comment by fujita** [comment]
overdue but I finally added necessary functions like interating routes that have a given prefix to critbitgo.Net:
https://github.com/k-sone/critbitgo/commits/master/net.go?author=fujita

Now all the usage of go-radix in gobgp was replaced with critbitgo.

**Comment by gaissmai** [comment]
please let me reopen this discussion. Have you ever thought about using the newer stdlib net/netip? And maybe, you will check my comparing [benchmarks](https://github.com/gaissmai/iprbench) fo go IP LPM packages.

Shameless plug, I think the bart library would be a perfect fit for GoBGP but a big rewrite to transform net.IP to net/netip

**Comment by fujita** [comment]
Feel free to reopen if you think that this discussion is still valid.
Recently we discussed algorithms for the table again:
https://github.com/osrg/gobgp/pull/2984

@nplanelcisco reimplemented the related code.

btw, replacing the net package with the netip package is on my TODO list before the major 4.0 release.

**Comment by gaissmai** [comment]
I have no permissions to reopen the discussion

**Comment by gaissmai** [comment]
One advantage is that `bart` is still actively maintained (by myself), which is not the case for `critbitgo` or several other IP LPM algorithms. Tailscale has also discontinued development of `art` and now uses my `bart` instead. If a feature is missing for GoBGP, I’d be happy to implement it. But first, take a look at the performance and memory usage and see for yourself.

**Comment by vincentbernat** [comment]
There is also https://github.com/kentik/patricia. That's the one I use in Akvorado. I don't think I knew about `bart` at the time I chose this one. The scaling is pretty good (some users are/were putting 60 million routes), but unfortunately, I didn't find (yet) a way to workaround the long pauses needed for major updates. I may rewrite again as I am introducing an architecture change that would indirectly help.

**Comment by gaissmai** [comment]
I will try to add kentik/patricia to my benchmark suite, I'll keep you informed

**Comment by gaissmai** [comment]
@vincentbernat well, the interface of `kentik/patricia` is, hmm, at the very least something you have to get used to. The benchmarks put `kentik/patricia` somewhere in the middle of the suite.
Although I’m not entirely sure I understood how Delete() works. Maybe you’d like to take a look—I’ve uploaded it to the [devel branch](https://github.com/gaissmai/iprbench/tree/devel), please see the` adapter.go` file in the kentik-patricia directory.

##### longest-prefix-match:
```text
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
                                     │ bart/lpm.bm  │         kentik-patricia/lpm.bm          │
                                     │    sec/op    │    sec/op      vs base                  │
LpmTier1Pfxs/RandomMatchIP4            16.38n ±  5%   181.05n ±  9%  +1004.97% (p=0.000 n=20)
LpmTier1Pfxs/RandomMatchIP6            28.70n ± 30%   259.65n ± 22%   +804.55% (p=0.000 n=20)
LpmTier1Pfxs/RandomMissIP4             18.61n ±  0%   143.75n ±  5%   +672.23% (p=0.000 n=20)
LpmTier1Pfxs/RandomMissIP6             29.07n ± 36%   166.80n ± 13%   +473.79% (p=0.000 n=20)
LpmRandomPfxs/1_000/RandomMatchIP4     16.54n ±  0%    81.81n ±  8%   +394.44% (p=0.000 n=20)
LpmRandomPfxs/1_000/RandomMatchIP6     19.24n ±  0%    99.82n ± 16%   +418.81% (p=0.000 n=20)
LpmRandomPfxs/1_000/RandomMissIP4      16.59n ±  9%    68.03n ±  5%   +310.07% (p=0.000 n=20)
LpmRandomPfxs/1_000/RandomMissIP6      19.23n ±  0%    78.61n ± 11%   +308.81% (p=0.000 n=20)
LpmRandomPfxs/10_000/RandomMatchIP4    18.19n ±  0%   105.90n ±  7%   +482.19% (p=0.000 n=20)
LpmRandomPfxs/10_000/RandomMatchIP6    19.25n ±  0%   124.70n ±  3%   +547.79% (p=0.000 n=20)
LpmRandomPfxs/10_000/RandomMissIP4     18.16n ±  0%    93.60n ±  4%   +415.45% (p=0.000 n=20)
LpmRandomPfxs/10_000/RandomMissIP6     19.27n ± 33%   108.40n ±  4%   +462.68% (p=0.000 n=20)
LpmRandomPfxs/100_000/RandomMatchIP4   14.88n ± 41%   134.00n ±  8%   +800.24% (p=0.000 n=20)
LpmRandomPfxs/100_000/RandomMatchIP6   25.71n ±  0%   153.60n ±  3%   +497.43% (p=0.000 n=20)
LpmRandomPfxs/100_000/RandomMissIP4    18.32n ± 39%   109.45n ±  5%   +497.43% (p=0.000 n=20)
LpmRandomPfxs/100_000/RandomMissIP6    25.71n ±  0%   136.70n ±  6%   +431.70% (p=0.000 n=20)
geomean                                19.83n          120.7n         +508.78%
```

#### size
```text
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
                         │ bart/size.bm │       kentik-patricia/size.bm       │
                         │ bytes/route  │ bytes/route  vs base                │
Tier1PfxSize/1_000           104.1 ± 2%    145.4 ± 1%   +39.67% (p=0.002 n=6)
Tier1PfxSize/10_000          76.06 ± 0%   200.20 ± 0%  +163.21% (p=0.002 n=6)
Tier1PfxSize/100_000         41.17 ± 0%   164.00 ± 0%  +298.35% (p=0.002 n=6)
Tier1PfxSize/200_000         32.85 ± 0%   164.00 ± 0%  +399.24% (p=0.002 n=6)
Tier1PfxSize/500_000         25.19 ± 0%   144.50 ± 0%  +473.64% (p=0.002 n=6)
Tier1PfxSize/1_000_000       21.39 ± 0%   144.50 ± 0%  +575.55% (p=0.002 n=6)
RandomPfx4Size/1_000         74.64 ± 3%   140.70 ± 1%   +88.50% (p=0.002 n=6)
RandomPfx4Size/10_000        48.26 ± 0%   109.60 ± 0%  +127.10% (p=0.002 n=6)
RandomPfx4Size/100_000       59.57 ± 0%   139.80 ± 0%  +134.68% (p=0.002 n=6)
RandomPfx4Size/200_000       52.51 ± 0%   139.80 ± 0%  +166.24% (p=0.002 n=6)
RandomPfx4Size/500_000       37.84 ± 0%   139.70 ± 0%  +269.19% (p=0.002 n=6)
RandomPfx4Size/1_000_000     31.83 ± 0%   139.80 ± 0%  +339.21% (p=0.002 n=6)
RandomPfx6Size/1_000         82.67 ± 2%   157.10 ± 1%   +90.03% (p=0.002 n=6)
RandomPfx6Size/10_000        98.87 ± 0%   201.30 ± 0%  +103.60% (p=0.002 n=6)
RandomPfx6Size/100_000       67.59 ± 0%   160.80 ± 0%  +137.91% (p=0.002 n=6)
RandomPfx6Size/200_000       64.96 ± 0%   160.80 ± 0%  +147.54% (p=0.002 n=6)
RandomPfx6Size/500_000       67.62 ± 0%   156.30 ± 0%  +131.14% (p=0.002 n=6)
RandomPfx6Size/1_000_000     73.74 ± 0%   156.50 ± 0%  +112.23% (p=0.002 n=6)
RandomPfxSize/1_000          98.98 ± 2%   144.50 ± 1%   +45.99% (p=0.002 n=6)
RandomPfxSize/10_000         71.38 ± 0%   140.20 ± 0%   +96.41% (p=0.002 n=6)
RandomPfxSize/100_000        76.54 ± 0%   180.00 ± 0%  +135.17% (p=0.002 n=6)
RandomPfxSize/200_000        65.49 ± 0%   180.00 ± 0%  +174.85% (p=0.002 n=6)
RandomPfxSize/500_000        47.95 ± 0%   144.00 ± 0%  +200.31% (p=0.002 n=6)
RandomPfxSize/1_000_000      39.50 ± 0%   144.00 ± 0%  +264.56% (p=0.002 n=6)
geomean                      56.09         152.8       +172.40%
```

#### insert/delete
```text
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
                         │ bart/update.bm │      kentik-patricia/update.bm       │
                         │   sec/route    │  sec/route    vs base                │
InsertRandomPfxs/1_000       30.43n ±  3%   190.60n ± 1%  +526.36% (p=0.002 n=6)
InsertRandomPfxs/10_000      36.54n ±  3%   286.70n ± 0%  +684.62% (p=0.002 n=6)
InsertRandomPfxs/100_000     76.37n ± 10%   559.15n ± 0%  +632.16% (p=0.002 n=6)
InsertRandomPfxs/200_000     115.7n ±  1%    704.1n ± 1%  +508.56% (p=0.002 n=6)
DeleteRandomPfxs/1_000       16.75n ±  0%    13.03n ± 0%   -22.23% (p=0.002 n=6)
DeleteRandomPfxs/10_000      16.80n ±  0%    15.05n ± 0%   -10.44% (p=0.002 n=6)
DeleteRandomPfxs/100_000     17.07n ±  1%    16.33n ± 0%    -4.36% (p=0.002 n=6)
DeleteRandomPfxs/200_000     17.62n ±  0%    19.04n ± 1%    +8.03% (p=0.002 n=6)
geomean                      30.91n          77.58n       +151.00%
```

**Comment by nplanelcisco** [comment]
@fujimoto-s I'm currently working on the `netip` my devel branch is here https://github.com/nplanelcisco/gobgp/tree/nplanel/netip

**Comment by gaissmai** [comment]
> I didn't find (yet) a way to workaround the long pauses needed for major updates

@vincentbernat `bart` has (still experimental) lock-free updates. I'd be happy if I could win you as a tester.

**Comment by vincentbernat** [comment]
> > I didn't find (yet) a way to workaround the long pauses needed for major updates
> 
> [@vincentbernat](https://github.com/vincentbernat) `bart` has (still experimental) lock-free updates. I'd be happy if I could win you as a tester.

I'll do that. But dunno when. ;-)

**Comment by gaissmai** [comment]
> #### insert/delete
> 
> ```
> goos: linux
> goarch: amd64
> cpu: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
>                          │ bart/update.bm │      kentik-patricia/update.bm       │
>                          │   sec/route    │  sec/route    vs base                │
> InsertRandomPfxs/1_000       30.43n ±  3%   190.60n ± 1%  +526.36% (p=0.002 n=6)
> InsertRandomPfxs/10_000      36.54n ±  3%   286.70n ± 0%  +684.62% (p=0.002 n=6)
> InsertRandomPfxs/100_000     76.37n ± 10%   559.15n ± 0%  +632.16% (p=0.002 n=6)
> InsertRandomPfxs/200_000     115.7n ±  1%    704.1n ± 1%  +508.56% (p=0.002 n=6)
> DeleteRandomPfxs/1_000       16.75n ±  0%    13.03n ± 0%   -22.23% (p=0.002 n=6)
> DeleteRandomPfxs/10_000      16.80n ±  0%    15.05n ± 0%   -10.44% (p=0.002 n=6)
> DeleteRandomPfxs/100_000     17.07n ±  1%    16.33n ± 0%    -4.36% (p=0.002 n=6)
> DeleteRandomPfxs/200_000     17.62n ±  0%    19.04n ± 1%    +8.03% (p=0.002 n=6)
> geomean                      30.91n          77.58n       +151.00%
> ```

The benchmark for insert/delete had a general design flaw; please see the [correct values](https://github.com/gaissmai/iprbench#update-insertdelete)
