### ISSUE TITLE
Travis CI crashes because golang/dep drops Go 1.7 supports

### ISSUE THREAD

**Issue by fujimoto-s** [osrg/gobgp#1422]
Today, golang/dep drops Go 1.7 supports in [this commit](https://github.com/golang/dep/commit/5b1fe9e6d89372487d0aac78d9c5362a517857e7).

Currently, we use Go 1.7 in Travis CI (https://github.com/osrg/dockerfiles/blob/master/quagga/Dockerfile#L5), so CI crashes.
We should use Go 1.8 or upper.

**Comment by fujita** [comment]
Thanks for the report. I fixed the issue.
