### ISSUE TITLE
ReplaceStatement does not work as expected

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1426]
When seeing the ReplaceStatement function I would expect that the whole statement is swapped in an atomic operation.

What's happening is, that a poor copy of the passed statement is created:

```
        cs := make([]Condition, len(lhs.Conditions))
	copy(cs, lhs.Conditions)
	ra := lhs.RouteAction
	as := make([]Action, len(lhs.ModActions))
	copy(as, lhs.ModActions)
```

All commands of the original statement are copied, what if there's less Conditions / Actions in the replaced Statement, or what if there are more??

```
                 case REPLACE:
			if a == nil {
				return fmt.Errorf("action %d is not set", x.Type())
			}
			as[i] = x
```
And then the Conditions / Actions are replaced based on a index operation?

Is this expected behaviour??

**Comment by fujita** [comment]
Removed ReplaceStatement() API. not intuitive. https://github.com/osrg/gobgp/commit/008c961ecd943739c5db63fcd931904804a45aa5
