### ISSUE TITLE
GetPolicyAssignment should have a GetPolicyAssignments equivalent

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1427]
Currently it's only possible to retrieve a single PolicyAssignment, but for management it would make sense to also provide a GetPolicyAssignments method to retrieve all set PolicyAssignments

**Comment by fujimoto-s** [comment]
What "all set" means?
Getting all the PolicyAssignments for all neighbors, or for a specific neighbor?

Which do you think is useful?

**Comment by Thoro** [comment]
All assigned policies, I now understand that it's useless in a non-route-server operation (wasn't clear about that before)

But for configuration update of deleted policies for specific neighbors, it would be useful to get ALL policy assignments (neighbors + global)

**Comment by fujimoto-s** [comment]
Related to what you said, GoBGP doesn't allow to configure/show policies for non-route-server-client.
So it should be better to get policy assignments for "global" and all route-server-clients.

**Comment by fujita** [comment]
To be consistent with the other APIs, this should be handled with GetPolicyAssignment?

**Comment by fujimoto-s** [comment]
It's true, but we have the problem to do this.

Other APIs will return all results when it receives an empty string.
However, currently when GetPolicyAssignment API receives an empty string, it will return the policy assigned to GLOBAL, not all.

I think we have some options to get all policy assignments via GetPolicyAssignment API.
* Modify to return all when the API receives "all" (not very consistent with other APIs)
* Modify to return all when the API receives an empty string, and return the policy for GLOBAL when it receives "global" (breaks backward compatibility)

Which is good, or do you have any other idea?

**Comment by fujita** [comment]
I prefer another option, just let it alone for now. I plan to change the policy model for route servers.

**Comment by fujimoto-s** [comment]
I understood that we don't merge this PR for now.
