### ISSUE TITLE
GetPolicy returns ALL policies, should provide a filter like other Get methods

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1431]
The GetPolicy method currently returns all policies within the system, other Get functions filter the results based on the passed name.

"" -> all
name -> just the policy

The GetPolicy API should behave the same as others.

**Comment by fujimoto-s** [comment]
I made a PR for this issue, thanks!

However, as described in the PR, changing GetPolicy API will break backward compatibility, so we need to be cautious as to whether to merge this PR.

And, there is other APIs which has similar interface to GetPolicy API's one, like GetStatement API, which receives no argument and returns all statements.
It is better to unify input and output interfaces for all APIs we have.

**Comment by fujita** [comment]
Now both GetPolicy() and GetStatement() support filtering:
https://github.com/osrg/gobgp/commit/f0b724878360618dd0a950364709b048486771b6
