### ISSUE TITLE
Cannot stop GoBGPd via "kill -SIGTERM" when no neighbor configured

### ISSUE THREAD

**Issue by iwaseyusuke** [osrg/gobgp#1449]
Related to the issue https://github.com/osrg/gobgp/issues/711, I found a weird behavior of GoBGPd when stopping the daemon using "kill -SIGTERM" command.

---
When any neighbor on gobgpd.toml, I could stop GoBGPd successfully;
A neighbor "10.0.0.2" is configured.
```
$ cat gobgpd.toml 
[global.config]
  as = 65001
  router-id = "10.0.0.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.2"
    peer-as = 65002
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
```
Start GoBGPd.
```
$ gobgpd -f gobgpd.toml
{"level":"info","msg":"gobgpd started","time":"2017-09-27T10:12:04+09:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2017-09-27T10:12:04+09:00"}
{"level":"info","msg":"Peer 10.0.0.2 is added","time":"2017-09-27T10:12:04+09:00"}
{"Topic":"Peer","level":"info","msg":"Add a peer configuration for:10.0.0.2","time":"2017-09-27T10:12:04+09:00"}
...(snip)...
```
Send SIGTERM to GoBGPd.
```
$ pkill -SIGTERM gobgpd
```
Stopped GoBGPd successfully.
```
$ gobgpd -f gobgpd.toml
...(snip)...
{"Key":"10.0.0.2","State":"BGP_FSM_ACTIVE","Topic":"Peer","level":"info","msg":"Administrative shutdown","time":"2017-09-27T10:12:05+09:00"}
```
---
On the other hand, when no neighbor configured, GoBGPd kept alive;
Neighbor "10.0.0.2" is commented out.
```
$ cat gobgpd.toml 
[global.config]
  as = 65001
  router-id = "10.0.0.1"

#[[neighbors]]
#  [neighbors.config]
#    neighbor-address = "10.0.0.2"
#    peer-as = 65002
#  [[neighbors.afi-safis]]
#    [neighbors.afi-safis.config]
#      afi-safi-name = "ipv4-unicast"
#  [[neighbors.afi-safis]]
#    [neighbors.afi-safis.config]
#      afi-safi-name = "ipv6-unicast"
```
```
$ gobgpd -f gobgpd.toml
{"level":"info","msg":"gobgpd started","time":"2017-09-27T10:20:42+09:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2017-09-27T10:20:42+09:00"}
```
Even if I send SIGTERM to GoBGPd, GoBGPd kept alive.
```
$ pkill -SIGTERM gobgpd
```
```
$ gobgpd -f gobgpd.toml
{"level":"info","msg":"gobgpd started","time":"2017-09-27T10:20:42+09:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2017-09-27T10:20:42+09:00"}
(no output)
```
---
I guess GoBGP triggers exiting on fsm side.

https://github.com/osrg/gobgp/blob/ce258f05d2fd9c3f66b831cae1e40bc9958cef1f/server/server.go#L1132-L1142

Is any mechanism to monitor whether all fsm is stopped or not from BgpServer side required?

**Comment by fujita** [comment]
Thanks for the bug report.
The main goroutine waits for all peers' goroutines to stop and then dies.

https://github.com/osrg/gobgp/blob/master/server/server.go#L952

A quick fix would be something like this

https://github.com/fujita/gobgp/tree/fix-no-peer-shutdown

Hacky but gobgp will stop soon anyway so I guess that we don't care much about how to stop.

**Comment by iwaseyusuke** [comment]
@fujita 
Thank you for letting me know.
Currently, it looks good enough for me, but when I needed to implement cleaning up something (e.g., create pidfile, then remove it when stopping), I couldn't catch up exit of GoBGP with "defer" statement in gobgpd's main().

Anyway, `fix-no-peer-shutdown@ branch fixes this problem.
