### ISSUE TITLE
grpc received message size

### ISSUE THREAD

**Issue by dyk9** [osrg/gobgp#1456]
Hi
Is it possible to setup via configuration grpc message size?

grpc.max_send_message_length
grpc.max_receive_message_length

to avoid such error messages:
% gobgp global rib
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (39530967 vs. 4194304)

**Comment by fujita** [comment]
Please try the latest version. This bug was fixed by:
https://github.com/osrg/gobgp/commit/9b278ba79ba2d12598405d1109b0b90b42e68357
