### ISSUE TITLE
Better API for addPath

### ISSUE THREAD

**Issue by nemith** [osrg/gobgp#1457]
I was able to use GoBGPDas a tutorial for a NANOG hackathon, however there were a couple shortfalls when using a gobgpd as a base for automation.  The largest issue was how difficult it was to add new routes using the GRPC API.  (minus the lack of package level documentation).

https://github.com/nemith/nanog71/blob/master/pkg/bgpctrl/main.go

This was difficult when using Go, but near impossible when using other client languages.

I would imagine this would take a lot more modeling of routes and attributes required inside protobuf.  Any may help here? https://developers.google.com/protocol-buffers/docs/proto3#any

**Comment by fujita** [comment]
Agreed that we really need to improve the usability of AddPath API (and its document).
I don't see how proto.Any would help. Even with it, we still need to define a structure for an attribute? Can you elaborate on the idea?
Btw, thanks a lot for using GoBGP for the tutorial! The slides look great.

**Comment by nemith** [comment]
I was thinking that you can define many different attribute structures (one for each supported attribute) and allow proto.Any to a repeated list of them.

I may give this a shot.

**Comment by dylandreimerink** [comment]
A few days ago I stared on a project that aims to make a PHP wrapper for the gRPC client. So far I have only been able to decode flowspec routes. But my intentions are to cover the full API including inserting routes and using the monitor function ect. I also provides links to the RFC's I have used so far. I hope you find something you can use. https://github.com/dylandreimerink/gobgp-php

**Comment by fujita** [comment]
@nemith 
something like this?
https://github.com/fujita/gobgp/blob/grpc/api/gobgp.proto#L1139-L1173

Then you can put any attribute like:
https://github.com/fujita/gobgp/blob/grpc/api/gobgp.proto#L1139-L1173

**Comment by nemith** [comment]
Yes.  That is exactly what i was thinking!

**Comment by iwaseyusuke** [comment]
Hi, I make a draft proposal of `.protobuf`: [`api/bgp/attribute.proto`](https://github.com/iwaseyusuke/gobgp/blob/f3f26b9e512e78c4e04f15ea146322b8ddac8df8/api/bgp/attribute.proto)

For the usage of this protobuf, please refer to this UT file: [`api/bgp/attribute_test.go`](https://github.com/iwaseyusuke/gobgp/blob/f3f26b9e512e78c4e04f15ea146322b8ddac8df8/api/bgp/attribute_test.go)

With this protobuf, `ModPath` API (not implemented yet) would be like:

```go
nextHopAttribute, _ := ptypes.MarshalAny(&NextHopAttribute{
	NextHop: "10.0.0.1",
})

asPathAttribute, _ := ptypes.MarshalAny(&AsPathAttribute{
	Segments: []*AsSegment{
		{
			Type:    1, // SET
			Numbers: []uint32{100, 200},
		},
		{
			Type:    2, // SEQ
			Numbers: []uint32{300, 400},
		},
	},
})

nlri, err := ptypes.MarshalAny(&IPAddressPrefix{
	PrefixLen: 24,
	Prefix:    "192.168.101.0",
})

c.ModPath(ctx,
	&ModPathRequest{
		Path: &PathInfo{
			Family: Family_IPv4,
			Nlri:  nlri,
			PathAttributes:  []*any.Any{nextHopAttribute, asPathAttribute},
		},
	},
)
```

Any comments and feedback are highly welcomed! For example, "XxxAttribute has inconvenient API" or so.

**Comment by iwaseyusuke** [comment]
@dbarrosop Hi, I'm trying to implement `AddPath` API using this `protobuf` structure. I will share it to you when I have implemented some mock-up.

**Comment by iwaseyusuke** [comment]
I've made patches for using this `protobuf` structure in `AddPath` API: https://github.com/iwaseyusuke/gobgp/compare/master...api-Define_protobuf_of_PathAttribute

With these patches, we can construct `message Path` structure using path attribute structures defined in this `protobuf` file.
https://github.com/iwaseyusuke/gobgp/blob/1505e877c7c193f14d584161fd7ac021f11b4b8f/api/gobgp.proto#L554-L572

**Comment by iwaseyusuke** [comment]
FYI, I wrote an example of Python script for calling AddPath and GetPath API using this protobuf structure.
https://gist.github.com/iwaseyusuke/df1e0300221b0c6aa1a98fc346621fdc

**Comment by dbarrosop** [comment]
Great,  I will try to find some time to test this during weekend.

**Comment by iwaseyusuke** [comment]
I've just posted a PR for this issue.
Please note I kept the existing `bytes nlri = 1` and `repeated bytes pattrs = 2` in `message Path` structure in order to keep the backward compatibility and the performance of `mrt inject` command. So the new `any.Any` type fields are introduced as `google.protobuf.Any any_nlri = 20` and `repeated google.protobuf.Any any_pattrs = 21`.

**Comment by fujita** [comment]
I've closed this; the gRPC API to add a route was fixed and the python and C++ examples were updated.
https://github.com/osrg/gobgp/blob/master/docs/sources/grpc-client.md
Thanks a lot everyone!
