### ISSUE TITLE
Possible bug in policy.go:inUse

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1467]
Hi,

If a RouteType/RpkiValidationCondition/AsPathLengthCondition Condition is used within a statement and a set is deleted, it leads to a null pointer reference at:

https://github.com/osrg/gobgp/blob/7dcbffefc037d18d649ce30fd1201d5071761d52/table/policy.go#L3047

I believe it should be fixed by writing:

```
if c.Set() != nil && c.Set().Name() == name {
```

**Comment by fujita** [comment]
Fixed, thanks!
