### ISSUE TITLE
MRT output doesn't work correctly when multiple configs are specified

### ISSUE THREAD

**Issue by a16** [osrg/gobgp#1469]
I'm using multiple `mrt-dump` in the config like below. It has been working correctly as of 9c03026.

```
[[mrt-dump]]
  [mrt-dump.config]
    dump-type = "updates"
    file-name = "/var/dump/updates/2006/01/02.1504.dump"
    rotation-interval = 60

[[mrt-dump]]
  [mrt-dump.config]
    dump-type = "table"
    file-name = "/var/dump/table/2006/01/2006-01-02-15-04.mrt"
    rotation-interval = 3600
```

After that, the latter one(`table`) looks fine, but the former one(`updates`) is never rotated and its content is not `updates` but `table`.

**Comment by fujita** [comment]
Thanks for the report. Can you try the latest master?

**Comment by fujita** [comment]
Please reopen if you still hit the problem.
