### ISSUE TITLE
gobgp bgp communities format problem in json output 

### ISSUE THREAD

**Issue by dyk9** [osrg/gobgp#1471]
plain text output (correct):
*> 100.43.64.0/19       194.226.71.57        13238 13238 13238 13238 13238 00:11:15   [{Origin: i} {Med: 25} {Communities: 13238:1010, 13238:3004, 13238:3214}]

json output (incorrect):
{"100.43.64.0/19":[{"nlri":{"prefix":"100.43.64.0/19"},"attrs":[{"type":1,"value":0},{"type":2,"as_paths":[{"segment_type":2,"num":5,"asns":[13238,13238,13238,13238,13238]}]},{"type":3,"nexthop":"194.226.71.57"},{"type":4,"metric":25},{"type":8,"communities":[867566578,867568572,867568782]}]

**Comment by iwaseyusuke** [comment]
Hi @dyk9 

I guess it is just a difference of the representation and both shows the correct value.

For example, `867566578` is in the decimal representation of 32 bits field, and `13238:1010` is in the colon separated decimal values of higher 16 bits and lower 16 bits.
https://github.com/osrg/gobgp/blob/7dcbffefc037d18d649ce30fd1201d5071761d52/packet/bgp/bgp.go#L5381-L5392
Snip in Python:
```
$ python
>>> "%d:%d" % ((0xffff0000 & 867566578) >> 16, 0xffff & 867566578)
'13238:1010'
```

You mean you want to get BGP Communities in `%d:%s` string representation in json?

**Comment by dyk9** [comment]
Yes, that would be better. thanks.

**Comment by iwaseyusuke** [comment]
Hmmm... I don't know whether which representation is better for other users...
It seems that BGP Communities attribute is usually configured in "%d:%d" representation though...

**Comment by fujita** [comment]
The json is for computer (code) not human. The plan number representation is more handy for code.
