### ISSUE TITLE
Export ipv6 prefix over ipv4 session

### ISSUE THREAD

**Issue by f0o** [osrg/gobgp#1498]
Hi,

I couldn't find anywhere in the docs how to advertise ipv6 prefixes over an ipv4 session.

Any pointers? :)

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md

something like that
```
[global.config]
as = 65001
router-id = "192.168.0.1"

[[neighbors]]
[neighbors.config]
neighbor-address = "172.16.149.1"
peer-as = 65002
[[neighbors.afi-safis]]
[neighbors.afi-safis.config]
afi-safi-name = "ipv6-unicast"

**Comment by f0o** [comment]
```
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "ipv6-unicast"
```
Doesn't seem to work, it's always either v4 or v6 and never both...
Any pointers?

Also documentation is really sparse about this, the example config is meaningless without documentation..
