### ISSUE TITLE
bmp  data seems to be summarized every 30 second

### ISSUE THREAD

**Issue by bf228** [osrg/gobgp#1500]
I've got gobgp writing BMP information to openBMP (and from there to kafka).  It looks like there's some level of batching happening in terms of how BMP works in goBGP-- meaning the timestamps i see on the BMP data from goBGP is grouped with the same timestamp every 30 seconds.   So I might have 100s of BMP updates (unicast_prefix) that all have the same BMP timestamp and then 30 seconds later i'll see the next set of updates in BMP (all with the same timestamp but 30 seconds later).  The updates aren't arriving to goBGP evey 30 seconds, they are trickling in all the time.

Is there a way to get more accurate timestamping from goBGP when using BMP?  ideally i'd like to get a timestamp on each BGP update and have that timestamp reflected in the timestamp data goBGP sends in BMP for that update.

Possible?  If so how?

**Comment by fujimoto-s** [comment]
GoBGP cannot buffer UPDATE messages for BMP.
It should send a BMP message at the moment it receives an UPDATE message.

Please use Wireshark or other packet captures to check whether GoBGP is really sending BMP messages with summarizing.
I think you should check the configurations of OpenBMP and Kafka.

**Comment by fujita** [comment]
As @fujimoto-s said, no batching BMP messages in GoBGP. I've just tried and as you can see below, BMP server got two messages in two seconds. They have different time stamps.

`2017-12-06 13:49:06.1447015 +0900 JST m=+167.728593595{"Header":{"Version":3,"Length":95,"Type":0},"PeerHeader":{"PeerType":0,"Flags":0,"PeerDistinguisher":0,"PeerAddress":"172.17.0.3","PeerAS":65003,"PeerBGPID":"172.17.0.3","Timestamp":1512535746},"Body":{"BGPUpdate":{"Header":{"Marker":null,"Len":47,"Type":2},"Body":{"WithdrawnRoutesLen":0,"WithdrawnRoutes":[],"TotalPathAttributeLen":20,"PathAttributes":[{"type":1,"value":2},{"type":2,"as_paths":[{"segment_type":2,"num":1,"asns":[65003]}]},{"type":3,"nexthop":"172.17.0.3"}],"NLRI":[{"prefix":"10.1.0.0/24"}]}},"BGPUpdatePayload":null}}

2017-12-06 13:49:08.960653051 +0900 JST m=+170.544545162{"Header":{"Version":3,"Length":95,"Type":0},"PeerHeader":{"PeerType":0,"Flags":0,"PeerDistinguisher":0,"PeerAddress":"172.17.0.3","PeerAS":65003,"PeerBGPID":"172.17.0.3","Timestamp":1512535748},"Body":{"BGPUpdate":{"Header":{"Marker":null,"Len":47,"Type":2},"Body":{"WithdrawnRoutesLen":0,"WithdrawnRoutes":[],"TotalPathAttributeLen":20,"PathAttributes":[{"type":1,"value":2},{"type":2,"as_paths":[{"segment_type":2,"num":1,"asns":[65003]}]},{"type":3,"nexthop":"172.17.0.3"}],"NLRI":[{"prefix":"10.0.0.0/24"}]}},"BGPUpdatePayload":null}}`
