### ISSUE TITLE
Compilation breaks on x86

### ISSUE THREAD

**Issue by shadrick** [osrg/gobgp#1509]
Commit 68d2478e2ea1d8607f85e6ab3d4a792e054ce6c2 introduced a change, in packet/bgp/bgp.go:3370 that overflows an int on 32bit architectures.
Compiler line:
`src/github.com/osrg/gobgp/packet/bgp/bgp.go:3370:18: constant 1099511627775 overflows int`

**Comment by iwaseyusuke** [comment]
Hi @shadrick 

The following fixes this issue?
```diff
diff --git a/packet/bgp/bgp.go b/packet/bgp/bgp.go
index 86b4cfd..56e15a3 100644
--- a/packet/bgp/bgp.go
+++ b/packet/bgp/bgp.go
@@ -3367,7 +3367,7 @@ func flowSpecSnapParser(rf RouteFamily, typ BGPFlowSpecType, args []string) (Flo
        args = normalizeFlowSpecOpValues(args)
 
        f := func(i int) error {
-               if 0 <= i && i <= 0xffffffffff { // 5 bytes
+               if 0 <= i && uint64(i) <= 0xffffffffff { // 5 bytes
                        return nil
                }
                return fmt.Errorf("%s range exceeded", typ.String())
```

**Comment by fujita** [comment]
@iwaseyusuke 
Needs to fix the following and the argument type of validateFunc()?
https://github.com/osrg/gobgp/blob/master/packet/bgp/bgp.go#L3034

**Comment by iwaseyusuke** [comment]
You mean `validateFunc()` should accept the value as `int64` for the case the value of `strconv.Atoi()` exceeds the range of `int`, right?
I guess `strconv.Atoi()` should raise error "value out of range" if the given value exceeds the range of `int` (`0x7fffffff` on the x86?), then the exceeded value should not be passed to `validateFunc()`.

But it is better to change `validationFunc func(int)` to `validationFunc func(int64)`, if the value can be larger than the max of `int32`.
If the above patch fixes this issue, I will update them.

**Comment by fujita** [comment]
> But it is better to change validationFunc func(int) to validationFunc func(int64), if the value can be larger than the max of int32.

The value can't be larger than int32? Why 0xffffffffff is used here?

**Comment by iwaseyusuke** [comment]
It means the the value can't be larger than `int32` "as far as on x86 env", but CAN be larger then `int32` if on 64-bit env.
Because `int` type on x86 is 32 bits (4 bytes) field, so ONLY if on x86 env, the return value of `strconv.Atoi()` is up to the max of 32 bits int.
(Just my assumption though...)

On the other hand, SNAP(Sub-Network Access Protocol) field is defined as "5 bytes" field, and if on 64-bit env, the return value of `strconv.Atoi()` can be the max of 64 bits int, then we need to validate if the value is smaller than or equal with `0xffffffffff` (the max of unsigned 5 bytes) here.

**Comment by fujita** [comment]
> On the other hand, SNAP(Sub-Network Access Protocol) field is defined as "5 bytes" field

I meant that GoBGP needs to handle 5-bytes SNAP field properly on ANY architectures. So we can't use int32 here.

**Comment by iwaseyusuke** [comment]
I agree, we cannot use `int32` here, so I propose to use `int64` instead of `int`.
e.g., `validationFunc func(int64)`

**Comment by shadrick** [comment]
The patch fixes the particular error the compiler gives, but if you need to check 5 bytes, architecture independently, i think the clean approach would be to expect explicit int64 in the function signature.

**Comment by iwaseyusuke** [comment]
Thanks @shadrick 
As you said, it is better to use [strconv.ParseInt()](https://golang.org/pkg/strconv/#ParseInt) here and accept the value as `int64` in `validationFunc()`.

**Comment by iwaseyusuke** [comment]
I just noticed that even if we expand the value to `int64`, `NewFlowSpecComponentItem` supposes `int` type value and it causes the rounding off on x86 env?

https://github.com/osrg/gobgp/blob/9225bec8e032aebfbf52b6435bc0b7bb9b7a93ff/packet/bgp/bgp.go#L3041

**Comment by fujita** [comment]
> I just noticed that even if we expand the value to int64, NewFlowSpecComponentItem supposes int type value and it causes the rounding off on x86 env?

Looks like so.
https://github.com/osrg/gobgp/pull/1514

**Comment by iwaseyusuke** [comment]
Sorry, I've just made the same fix for this issue...
https://github.com/osrg/gobgp/compare/master...iwaseyusuke:packet-bgp-Use_fixed_len_types_in_FlowSpec_components

On my patch, I fixed to use `unit8` in `FlowSpecComponentItem.Op` too.

**Comment by fujita** [comment]
No problem. making op uint8 makes sense too. Create a pr for your branch. I'll close mine.

**Comment by fujita** [comment]
In addition, can you add some tests to catch this kinda bug on travis-ci?

**Comment by iwaseyusuke** [comment]
Thanks, I've create new PR with my patch; https://github.com/osrg/gobgp/pull/1515

**Comment by iwaseyusuke** [comment]
> In addition, can you add some tests to catch this kinda bug on travis-ci?

Sure, but even if with `GOARCH=386` env value, Travis-CI did not raise error for this issue as you tested on this PR (https://github.com/osrg/gobgp/pull/1511/commits/d9ffc119b2615df16fcb3389746c74d46151f143), didn't it?
Hmmm...

**Comment by fujita** [comment]
Yeah, that fails locally but not travis-ci. Needs to investigate.

**Comment by iwaseyusuke** [comment]
Hmmm... Okay, I will investigate why.
