### ISSUE TITLE
Does not populate BMP 2-byte-AS flag

### ISSUE THREAD

**Issue by james-jra** [osrg/gobgp#1527]
I'm using YaBMP as a BMP collector, and it's failing to parse the AS path for some Route Monitoring messages.

The reason for is that gobgp does not populate the "A flag" in the per-peer BMP header https://tools.ietf.org/html/rfc7854#section-4.2.
The BMP header is created in func bmpPeerRouteMirroring in server/bmp.go, and always has flag A = 0
This therefore causes the BMP collector to fail to parse the BGP Update passed in the Route Monitoring message when the Update uses 2-byte AS numbers.

**Comment by fujita** [comment]
Thanks for the report. The following works for you?
https://github.com/osrg/gobgp/pull/1528

**Comment by james-jra** [comment]
Looks good to me
Thanks

**Comment by fujita** [comment]
Thanks, pushed.
