### ISSUE TITLE
Mind to shed some light on this channel buffer size?

### ISSUE THREAD

**Issue by imcom** [osrg/gobgp#1544]
In server.go, I noticed this setup
Line: 2662-2666
```
		w = &Watcher{
			s:      s,
			realCh: make(chan WatchEvent, 8),
			ch:     channels.NewInfiniteChannel(),
		}
```

I am just wondering is there any special consideration behind this buffer size 8 of the "realCh"?

**Comment by fujita** [comment]
Just random, IIRC.
