### ISSUE TITLE
Does not build due to breaking API change in github.com/satori/go.uuid

### ISSUE THREAD

**Issue by 0joshuaolson1** [osrg/gobgp#1568]
While building a dependent project:
```
../go/src/github.com/osrg/gobgp/table/path.go:392:37: multiple-value uuid.NewV4() in single-value context
```
How to fix: https://github.com/sassoftware/relic/pull/3/commits/1d39a0d8183511da703260003453042c7a38add6

Where to fix: https://github.com/osrg/gobgp/blob/be7e6206bc3706214a0aab762ca1af4a782ad27c/table/path.go#L392

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/issues/1547

That's why GoBGP uses the dependency management tool.

**Comment by 0joshuaolson1** [comment]
I don't understand. That issue was closed withing a commit. An upstream project depending on this still sees the problem.

**Comment by fujita** [comment]
You work on a project that uses GoBGP as a library, right? And the project doesn't use a library dependency management tool?

**Comment by 0joshuaolson1** [comment]
It's not my project. I'm letting https://github.com/tenta-browser/tenta-dns know as we speak.

**Comment by fujita** [comment]
I think that the project needs to use a dependency management tool. But as people report this again and again, so I'll update GoBGP with the latest go.uuid. Just a minute.

**Comment by 0joshuaolson1** [comment]
@fujita Thank you! I understand where you're coming from. BTW, the library/issue is:

https://github.com/tenta-browser/tenta-dns/issues/14

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/pull/1569

I'll push the above once the CI finishes successfully.

**Comment by fujita** [comment]
Done
