### ISSUE TITLE
`gobgp global` CLI unusable if gobgpd is launched without [global] config

### ISSUE THREAD

**Issue by nodakai** [osrg/gobgp#1592]
```
$ ls
bin	pkg	src
$ bin/gobgpd &
[1] 8344
$ {"level":"info","msg":"gobgpd started","time":"2018-02-15T19:24:24+08:00"}
$ bin/gobgp global
AS:        0
Router-ID:
$ bin/gobgp global del all
rpc error: code = Unknown desc = bgp server hasn't started yet
$ bin/gobgp global as 60000 router-id 1.2.3.4
rpc error: code = Unknown desc = listen tcp4 0.0.0.0:179: bind: permission denied
```

Reproducible both on macOS High Sierra 10.13 and Amazon Linux 2 x86-64.

This seems to be the culprit
https://github.com/osrg/gobgp/blob/master/server/server.go#L148

I was going to write a shell script to configure gobgpd after it was launched by systemctl (only with a config on GNU Zebra integration) because I'm maintaining many AWS regions and I wanted to let my script assign AS and router-ID to gobgpd's.

**Comment by fujita** [comment]
You need privilege such as root to run gobpgd for listening on 179. As your error message says:

> rpc error: code = Unknown desc = listen tcp4 0.0.0.0:179: bind: permission denied

**Comment by nodakai** [comment]
I’m running it under root (systemd) on AWS. If you cannot reproduce this issue in your environment I’ll post further details.

**Comment by fujita** [comment]
`gobgp global as 60000 router-id 1.2.3.4` makes gobgpd to start listening on 179 and failed due to the permission. So somehow gobgpd can't get the proper privilege on your environment.
Try to see if the following works:
`gobgp global as 60000 router-id 1.2.3.4 listen-port 3333`
With this, gobgpd listens on 3333 instead of 179 so no privilege is necessary.

**Comment by nodakai** [comment]
It turned out my Zebra integration config, *without* BGP config in `[global]`, was the culprit.

```
$ cat gobgpd.conf
[zebra]
  [zebra.config]
    enabled = false
    url = "unix:/var/run/quagga/zserv.api"
$ sudo /usr/local/sbin/gobgpd -f gobgpd.conf &
[1] 4563
[ec2-user@ip-172-24-0-222 tmp]$ {"level":"info","msg":"gobgpd started","time":"2018-02-15T15:17:17Z"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2018-02-15T15:17:17Z"}
$ gobgp global
AS:        0
Router-ID:
Listening Port: 179, Addresses: 0.0.0.0, ::   // ★★★★★
$ gobgp global as 60000 router-id 10.1.1.1
rpc error: code = Unknown desc = listen tcp4 0.0.0.0:179: bind: address already in use
$ gobgp global del all
rpc error: code = Unknown desc = bgp server hasn't started yet
$ sudo lsof -p `pgrep gobgpd`
COMMAND  PID USER   FD      TYPE DEVICE SIZE/OFF    NODE NAME
gobgpd  4564 root  cwd       DIR  202,1     4096 8409152 /tmp
gobgpd  4564 root  rtd       DIR  202,1      257      64 /
gobgpd  4564 root  txt       REG  202,1 12774792 4590701 /usr/local/sbin/gobgpd
gobgpd  4564 root  mem       REG  202,1    56784 4248823 /usr/lib64/libnss_files-2.25.so
gobgpd  4564 root  mem       REG  202,1  2163016 4248809 /usr/lib64/libc-2.25.so
gobgpd  4564 root  mem       REG  202,1   153960 4248825 /usr/lib64/libpthread-2.25.so
gobgpd  4564 root  mem       REG  202,1   187552 4248802 /usr/lib64/ld-2.25.so
gobgpd  4564 root    0u      CHR  136,0      0t0       3 /dev/pts/0
gobgpd  4564 root    1u      CHR  136,0      0t0       3 /dev/pts/0
gobgpd  4564 root    2u      CHR  136,0      0t0       3 /dev/pts/0
gobgpd  4564 root    3u     IPv4 144199      0t0     TCP localhost:6060 (LISTEN)
gobgpd  4564 root    4u  a_inode   0,11        0    6287 [eventpoll]
gobgpd  4564 root    5u     IPv4 144201      0t0     TCP *:bgp (LISTEN)
gobgpd  4564 root    6u     IPv6 144202      0t0     TCP *:bgp (LISTEN)
gobgpd  4564 root    7u     IPv6 144203      0t0     TCP *:50051 (LISTEN)
```

The daemon got stuck in a strange state where BGP socket was apparently listening for incoming connections as usual but no AS/router ID config was present.

**Comment by nodakai** [comment]
Actually the config file can be an empty file for this issue to reproduce
