### ISSUE TITLE
Table.destinations: concurrent map iteration and map write

### ISSUE THREAD

**Issue by thz** [osrg/gobgp#1602]
revision: d779a597c

We have a relative simple setup with one neighbor and zebra (frr) for fib manipulation. We are receiving and pushing about 9k routes. In about 50% of the cases we get the panic below a few seconds after startup.

It seems `Table.destinations` (`map[string]*Destination`) has no protection against such concurrent access. Am I missing anything on higher levels in the calling chain?
What would be the approach for fixing this? Adding `sync.RWLock` to `Table` or using the relatively new `sync.Map`?

```
fatal error: concurrent map iteration and map write

goroutine 16 [running]:
runtime.throw(0xcd8760, 0x26)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4200389e0 sp=0xc4200389c0 pc=0x42d7d5
runtime.mapiternext(0xc420038af8)
	/usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc420038a78 sp=0xc4200389e0 pc=0x40b831
github.com/osrg/gobgp/table.(*Table).GetKnownPathList(0xc42020b070, 0xcbe9ed, 0x6, 0xc42007f4a8, 0x1, 0x25)
	/go/src/github.com/osrg/gobgp/table/table.go:355 +0x144 fp=0xc420038b68 sp=0xc420038a78 pc=0x9fe634
github.com/osrg/gobgp/table.(*TableManager).GetPathListWithNexthop(0xc4201918f0, 0xcbe9ed, 0x6, 0xc420038cd8, 0x2, 0x2, 0xc4201a17a3, 0x4, 0xf, 0xc420038fbe, ...)
	/go/src/github.com/osrg/gobgp/table/table_manager.go:346 +0x16c fp=0xc420038c30 sp=0xc420038b68 pc=0xa0461c
github.com/osrg/gobgp/server.createPathListFromNexthopUpdateMessage(0xc420351480, 0xc4201918f0, 0xc420058e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/osrg/gobgp/server/zclient.go:398 +0xe7 fp=0xc420038d60 sp=0xc420038c30 pc=0xa77f07
github.com/osrg/gobgp/server.(*zebraClient).loop(0xc42013d660)
	/go/src/github.com/osrg/gobgp/server/zclient.go:470 +0x311 fp=0xc420038fd8 sp=0xc420038d60 pc=0xa78801
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420038fe0 sp=0xc420038fd8 pc=0x45e721
created by github.com/osrg/gobgp/server.newZebraClient
	/go/src/github.com/osrg/gobgp/server/zclient.go:564 +0x41a
```

**Comment by iwaseyusuke** [comment]
@thz Thanks for your reporting!
As you said, it seems to have data race. `zebraClient` should call the APIs of BgpServer politely (should not access RIB directly). Does this patch fix this issue?
https://github.com/osrg/gobgp/compare/master...iwaseyusuke:zclient-Avoid_directly_access_to_RIB

**Comment by thz** [comment]
@iwaseyusuke I can no longer reproduce the problem with that patch applied. Thanks!

**Comment by iwaseyusuke** [comment]
@thz Thank you for your confirmation! I will create a new PR.
