### ISSUE TITLE
Full JSON RIB metadata

### ISSUE THREAD

**Issue by mmellin** [osrg/gobgp#1613]
Hi all,
Where can I find an example of the complete JSON RIB dump structure (metadata) from the gobgp client?  

` $ gobgp global -j rib > routes.json`

I'm creating a python parser and would like help identifying all supported keys and value types.
Thank you.

**Comment by fujimoto-s** [comment]
There is no document about the JSON RIB dump structure.
But you can see it in source code:
https://github.com/osrg/gobgp/blob/master/table/path.go#L1084-L1097

The part `json:"xxxx"` corresponds to the JSON key.

The structures of NLRI and PathAttribute differs for each type.
You may also check packet/bgp.go to learn the structure for all NLRI and PathAttribute types.

**Comment by mmellin** [comment]
Thank you fujimoto-s-san
