### ISSUE TITLE
bug: repetitive GetRib() requests can taint existing Global RIB entry

### ISSUE THREAD

**Issue by tamihiro** [osrg/gobgp#1614]
- After gobgp daemon keeps responding to the gRPC GetRib() requests for the same ipv4-unicast network for an unspecified times, its rib entry would be overwritten with an incorrect NLRI.

- Please see https://github.com/tamihiro/taintgobgprib for a specific example and reproducing procedure.

**Comment by fujita** [comment]
Thanks a lot for the report and code to trigger the bug! Really helpful. As discussed on the slack channel, I think that the following commit fixes this:
https://github.com/osrg/gobgp/commit/cda7c44afe723be74e39266823b54ba28d0ec019

**Comment by tamihiro** [comment]
Thank you fujita-san, I have been running my code for hours now but not a single incorrect NLRI shows up yet. I deem your commit a definite fix.

**Comment by fujita** [comment]
Thanks a lot for the confirmation!
