### ISSUE TITLE
Adding same prefixes with different next-hop

### ISSUE THREAD

**Issue by muffadal-presswala** [osrg/gobgp#1615]
It looks like when I try to add two different BGP paths with the same prefix but different next-hops, goBGP installs only the latest one in the global rib

Config
```
blah@blah:~/gobgp$ gobgp global rib add -a ipv4 0.0.0.0/0 med 100 nexthop 4.4.4.4
blah@blah:~/gobgp$ gobgp global rib add -a ipv4 0.0.0.0/0 med 200 nexthop 5.5.5.5
```

Output
```
blah@blah:~/gobgp$ gobgp global rib
   Network              Next Hop             AS_PATH              Age        Attrs
*> 0.0.0.0/0            5.5.5.5                                   00:14:22   [{Origin: ?} {Med: 200}]
```

The plan is to advertise multiple paths to neighbors with the add-path feature enabled.

Additional information:
By default in Cisco IOS, if I try and add two static routes with the same destination and different next-hops, it will import only one path in BGP RIB but will have both the parts in the RIB. To import multiple paths for the same destination in BGP RIB, an additional knob needs to be enabled in BGP, for e.g. 
```
bgp sourced-paths per-net static all
```

Another possibility is to use BGP path-identifier to differentiate between multiple paths.

```
blah@blah:~/gobgp$ gobgp global rib add -a ipv4 0.0.0.0/0 med 100 nexthop 4.4.4.4 path-information 1
blah@blah:~/gobgp$ gobgp global rib add -a ipv4 0.0.0.0/0 med 200 nexthop 5.5.5.5 path-information 2
```

Thanks

**Comment by fujimoto-s** [comment]
As you said, GoBGP can advertise same prefixes combining add-path & path-identifier features.
What you want is a feature that advertises same prefixes without specifying path-identifiers?

**Comment by fujita** [comment]
Please use add-path.

**Comment by GeorgeGuo2018** [comment]
i used add-path，but still meet the same problem.Does anybody know why？the details list below.

root@i-x6f8bhbl:/home/ubuntu# cat gobgp.conf 
[global.config]
  as = 65003
  router-id = "192.168.0.11"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.0.10"
    peer-as = 65002
  [neighbors.add-paths.config]
    send-max = 8
ubuntu@i-blzdyyt5:~/gobgp$ ./gobgp global rib add -a ipv4 10.96.236.139/32 nexthop 192.168.0.3
ubuntu@i-blzdyyt5:~/gobgp$ ./gobgp global rib add -a ipv4 10.96.236.139/32 nexthop 192.168.0.14
root@i-x6f8bhbl:/home/ubuntu# ./gobgp global rib -a ipv4
   Network              Next Hop             AS_PATH              Age        Attrs
*> 10.96.236.139/32     192.168.0.14                              00:01:18   [{Origin: ?}]

**Comment by GeorgeGuo2018** [comment]
Settled the matter by adding a identifier para. 
eg:#gobgp global rib add -a ipv4 10.96.236.13/32 nexthop 192.168.0.14 identifier 10 
     #gobgp global rib add -a ipv4 10.96.236.13/32 nexthop 192.168.0.15 identifier 11

**Comment by GeorgeGuo2018** [comment]
Settled the matter by adding a identifier para when using gobgp command besides add path configuration.

eg:#gobgp global rib add -a ipv4 10.96.236.13/32 nexthop 192.168.0.14 identifier 10
     #gobgp global rib add -a ipv4 10.96.236.13/32 nexthop 192.168.0.15 identifier 11
