### ISSUE TITLE
invalid nexthop address

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#1621]
Hello!

I reproduced this error only with old GoBGP 1.4.

I have two IPv6 peers (both on GoBGP) but I have only "ipv4-unicast" enabled for both of them.

When I create announce for first instance:
```
gobgp global rib add -a ipv4 127.0.0.1/32 nexthop 127.0.0.1
```

And second instance crashes with error:
```
Mar 22 21:48:53 scw-08beb1 bgpd[10410]: {"Key":"2001:bc8:4700:2200::1:120d","Topic":"Peer","error":"invalid nexthop address","level":"warning","msg":"malformed BGP update message","time":"2018-03-22T21:48:53Z"}
```

Do you have any ideas why it happens? I think it should be legit to announce IPv4 over IPv6 session.

Thank you!

**Comment by pavel-odintsov** [comment]
Hello!

I managed to reproduce this issue with gobgp 1.29 :) 

I used this configuration for both peers:
```
[global.config]
  as = 65001
  router-id = "xx0d"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "xxx19"
    peer-as = 65001
    [neighbors.ebgp-multihop.config]
      enabled = true

    [[neighbors.afi-safis]]
      [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"

[global.apply-policy.config]
    import-policy-list = ["policy1"]
    default-import-policy = "accept-route"
      
[[defined-sets.neighbor-sets]]
  neighbor-set-name = "all_neighbors"
  neighbor-info-list = [ "xxx19" ]
 
[[policy-definitions]]
  name = "policy1"
  [[policy-definitions.statements]]
    name = "statement1"
    [policy-definitions.statements.conditions.match-neighbor-set]
      neighbor-set = "all_neighbors"
    [policy-definitions.statements.actions]
      route-disposition = "reject-route"
```

And then injected this announce to first one:
```
./gobgp global rib add -a ipv4 127.0.0.2/24 nexthop 127.0.0.1
```

And on received side I got following error message:
```
{"Key":"xxxd","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","error":"invalid nexthop address","level":"warning","msg":"the received Update message was treated as withdraw","time":"2018-03-25T16:17:06Z"}
```

Then, I changed announce to this one (removed nexthop):
```
./gobgp global rib add -a ipv4 127.0.0.2/24
```

And announce was accepted on receiving side.

But it does not look legit:
```
./gobgp nei 2001:bc8:4700:2200::1:120d adj-in -a ipv4
   ID  Network              Next Hop                   AS_PATH              Age        Attrs
   0   127.0.0.0/24         xx:xx:xx:xx::1:120d                      00:00:44   [{Origin: ?} {LocalPref: 100}]
```

It's kind of strange behaviour because gobgp set netxhop to IPv6 address! Looks like GoBGP implements https://tools.ietf.org/html/rfc5549 instead of standard IPv4 announce over IPv6 session with IPv4 nexthop.

Can you check it, please?

**Comment by fujimoto-s** [comment]
First, GoBGP rejects UPDATE messages whose NEXT_HOP is loopback:
https://github.com/osrg/gobgp/blob/1b84b8145418398e7e68b81cdce506dcf81eec14/packet/bgp/validate.go#L167-L168
So it is expected behavior that the route `127.0.0.2/24 nexthop 127.0.0.1` was rejected on receiving side.

And I think setting IPv6 address to NEXT_HOP is also expected. In your case, GoBGP knows only IPv6 address, so it is natural behavior to set IPv6 address.
What address do you think should be set to NEXT_HOP?

**Comment by pavel-odintsov** [comment]
Wow! I never heard about special rules for 127.0.0.1 :) Thank you so much! :) But I still have some suggestion to clarify this case in the error message.

**Comment by pavel-odintsov** [comment]
Btw, 1.4 also works fine in this case.
