### ISSUE TITLE
Community treated as uint16 and not uint32

### ISSUE THREAD

**Issue by frozon** [osrg/gobgp#1635]
I just came accross an issue regarding to communities.
If you add a community such as 2000000000:03 it will be converted to 65535:03.
RFC1997 says that community should be treated as 32bit values.

**Comment by fujita** [comment]
You are trying to add a route with a community via CLI?
If you put a colon with two values, each value are treated as a 16-bits value, in total, 32-bits values.
If you put a single value without a colon, it's treated as a 32-bits value.
