### ISSUE TITLE
update directly or update after withdraw？

### ISSUE THREAD

**Issue by xiaopeng163** [osrg/gobgp#1639]
+--------+
        |        |   1.1.1.1/32 nexthop 11.11.11.11
        |   R1   +---------------+
        |  as100 |               |
        +--------+         +-----+----+                      +----------+
                           |          |                      |          |
                           |          |  1.1.1.1/32          |   R4     |
                           |   gobgp  +---------+-----------+|          |
                           |  as 100  |   nexthop gobgp      | AS 200   |
                           +----------+   ebgp neighbor addr +----------+
        +--------+               +        for example
        |        |               |
        |        |   1.1.1.1/32  |
        |   R2   +---------------+
        |  as100 | nexthop 22.22.22.22
        +--------+

Hi team

I have a question about the reaction of gobgp, for this topology, R1, R2, R4is routers, R3 is gobgp.

 R1,R2 and R3 is AS 100, R4 is AS 200

R1, R2, both advertise the same prefix with same attributes(besides nexthop, nexthop are diffrerent) to R3,  and R3(gobgp) will select the best path of them, then advertise to R4.

at this time, if the best path of prefix 1.1.1.1/32 on R3 is come from R1, and we shutdown R1,  what will happend to R3 and R4.

1. R3 delete 1.1.1.1/32 which received from R1 in local RIB, keep 1.1.1.1/32 from R2, do nothing with R4
2. R3 delete 1.1.1.1/32 which received from R1, send update to R4
3. R3 delete 1.1.1.1/32 which received from R1, send withdraw to R4, and then send update to R4.

**Comment by fujita** [comment]
No.2, I think.

**Comment by fujita** [comment]
Please reopen or create a new one if you hit an expected behavior on this.

**Comment by xiaopeng163** [comment]
thanks
