### ISSUE TITLE
Issues between GoBGP and Cisco

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#1652]
Hello!

We noticed some really strange issues between few boxes with GoBGP (pretty old version 1.29) and few Cisco routers.

Once per few days Cisco lost BGP connection with following error messages:
```
ASR1002:       Apr 25 00:28:13.085: %BGP-3-NOTIFICATION: received from neighbor xx 4/0 (hold time expired) 0 bytes
ASR1002:       Apr 25 00:28:13.085: %BGP_SESSION-5-ADJCHANGE: neighbor xx IPv4 Unicast topology base removed from session  Peer closed the session
ASR1002:       Apr 25 00:28:13.085: %BGP-5-NBR_RESET: Neighbor xx reset (Peer closed the session)
ASR1002:       Apr 25 00:28:13.087: %BGP-5-ADJCHANGE: neighbor xx Down Peer closed the session
ASR1002:       Apr 25 00:28:36.342: %BGP-5-ADJCHANGE: neighbor xx Up
ASR1002:       Apr 25 00:28:36.342: %BGP-5-NBR_RESET: Neighbor xx active reset (BGP Notification sent)
```
We checked GoBGP logs and found nothing. We're trying to collect pcap of all BGP messages. 

Do you have any ideas? Maybe you got similar issues previously?

Thank you!

**Comment by greenpau** [comment]
@pavel-odintsov , what is the `hold timer` on Cisco for `gobgp` neighbor? 

```
RP/0/0/CPU0:router# show bgp nei 3.3.3.2
BGP neighbor is 3.3.3.2
 Remote AS 500, local AS 65000, external link
 Remote router ID 16.0.0.1
  BGP state = Established, up for 00:05:01 
  BFD enabled (session up): mininterval: 311 multiplier: 7
  Last read 00:00:56, hold time is 180, keepalive interval is 60 seconds
```

It will be nice to see the output of `show bgp nei`.

**Comment by greenpau** [comment]
@pavel-odintsov , I would also try to get the [TimerState](https://github.com/osrg/gobgp/blob/master/api/gobgp.proto#L757-L765) via API for that neighbor. More specifically, `hold_time` and `negotiated_hold_time` values.

**Comment by pavel-odintsov** [comment]
Will try, thank you! But it's slightly complicated because we do not have API integration for these options ;( Would be nice to have them in gobgp's output for debugging purposes.

**Comment by greenpau** [comment]
> Would be nice to have them in gobgp's output for debugging purposes.

@pavel-odintsov, do you run the release from here or do you compile on your on (and perhaps add some code)? In theory, I can give you a simple patch to get that.

**Comment by pavel-odintsov** [comment]
We have our own branch. Would be nice to get patch! Thank you! ;)

**Comment by greenpau** [comment]
> We have our own branch. Would be nice to get patch! Thank you! ;)

@pavel-odintsov , while a get you the patch, please take a look at https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md . Do you have a similar section in your configuration, i.e. `hold-time`?

```
[[neighbors]]
    [neighbors.config]

... intentionally ommitted ...

    [neighbors.timers.config]
        connect-retry = 5
        hold-time = 9
        keepalive-interval = 3
```

**Comment by pavel-odintsov** [comment]
Thank for response!

No, we do not have any configuration about hold time.

**Comment by greenpau** [comment]
@pavel-odintsov , I think your best bet is using GRPC interface.

You could make calls at your own pace and see how things change to a single or multiple BGP peers at a time. Apparently the code is already here. One of the things it outputs is `peer.timers.state.negotiated_hold_time` 😄 

https://github.com/osrg/gobgp/blob/master/tools/grpc/python/get_neighbor.py#L15-L22

When peering with Cisco NX-OS, by default, I get:

```
  Hold time is 90, keepalive interval is 30 seconds
  Configured hold time is 90, keepalive interval is 30 seconds
```

Also, @dbarrosop created this [repo](https://github.com/dbarrosop/gobgp-grpc-demo) that shows how to use the gRPC interface.

As a side thing ... `Down Peer closed the session` ... my wild bet is that it might be related to you IGP 😄 

Also, don't forget the "debug" 😉 

<img width="508" alt="screen shot 2018-05-05 at 1 18 06 am" src="https://user-images.githubusercontent.com/3826416/39659941-3b681db2-5002-11e8-96e5-10f4ebe5eee9.png">

**Comment by pavel-odintsov** [comment]
Wow! show debug bgp should help a lot! Thank you for providing these details! We will try it!

**Comment by pavel-odintsov** [comment]
It does not happen anymore and I think it was caused by some issues outside of GoBGP.
