### ISSUE TITLE
GoBGP can't connect to FRR API

### ISSUE THREAD

**Issue by horseinthesky** [osrg/gobgp#1659]
Hello, i'm trying to connect GoBGP with FRR 3.0.3 but this doesn't work.

This is GoBGO conf:
```
global:
    config:
        as: 65003
        router-id: 10.20.0.3

zebra:
  config:
    enabled: true
    url: "unix:/var/run/frr/zserv.api"
    redistribute-route-type-list: ["connect"]
    version: 4

neighbors:
    - config:
        neighbor-address: 192.168.0.150
        peer-as: 65002
      afi-safis:
        - config:
            afi-safi-name: ipv4-labelled-unicast
```

This is what i see when trying to start it:
```
horseinthesky@ubuntu:~$ sudo systemctl status gobgp 
● gobgp.service - 'GoBGP daemon'
   Loaded: loaded (/etc/systemd/system/gobgp.service; enabled; vendor preset: enabled)
   Active: activating (start-post) (Result: exit-code) since Tue 2018-05-01 21:11:53 MSK; 308ms ago
  Process: 32567 ExecStart=/usr/local/sbin/gobgpd -t yaml -f /etc/gobgp/gobgpd.conf (code=exited, status=1/FAILURE)
 Main PID: 32567 (code=exited, status=1/FAILURE);         : 32568 (gobgp)
    Tasks: 10
   Memory: 4.3M
      CPU: 19ms
   CGroup: /system.slice/gobgp.service
           └─control
             └─32568 /usr/local/sbin/gobgp global rib add -a ipv4-labeled 10.20.0.3/32 3

May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"error","msg":"failed to read header: read unix @-\u003e/var/run/frr/zserv.api: 
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 4. going to retry 
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"error","msg":"failed to read header: read unix @-\u003e/var/run/frr/zserv.api: 
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 2. going to retry 
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"error","msg":"failed to decode header: Unsupported ZAPI version: 5","time":"201
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 3. going to retry 
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"error","msg":"failed to decode header: Unsupported ZAPI version: 5","time":"201
May 01 21:11:53 ubuntu gobgpd[32567]: {"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 4. going to retry 
May 01 21:11:53 ubuntu gobgpd[32567]: {"level":"fatal","msg":"failed to set zebra config: failed to decode header: Unsupported ZAPI version: 5"
May 01 21:11:53 ubuntu systemd[1]: gobgp.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by iwaseyusuke** [comment]
@horseinthesky Hi, thanks for your reporting.

First, please make sure your FRR version is surely "3.0.3".
GoBGP supposes the Zebra protocol version "4" to communicate with FRR/Zebra, but the log messages  you attached show your FRR/Zebra sent messages with version "5". I assumes your FRR/Zebra should be version "master", "4" or later.
For example, FRR version "3.0.3" uses Zebra protocol version 4:
https://github.com/FRRouting/frr/blob/frr-3.0.3/lib/zclient.h#L203
On the other hand, "4.0" uses protocol version "5":
https://github.com/FRRouting/frr/blob/frr-4.0/lib/zclient.h#L230

**Comment by horseinthesky** [comment]
@iwaseyusuke 
Hi. thank you for helping.

I', using FRR 3.0.3 with Zebra 4.0.1
`/usr/lib/frr/zebra  --version | grep version
zebra version 4.1-dev-MyOwnFRRVersion-g62196e6`

And as i posted above i explicitly set `version 4` as it was said here [https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md](url)

I can't understand why but it tries all version from 2 to 5 with message `cannot connect to Zebra with message version #. going to retry another version....`

**Comment by iwaseyusuke** [comment]
@horseinthesky Thanks for your confirmation.

> I'm, using FRR 3.0.3 with Zebra 4.0.1

You mean you are using different versions of FRR's routing daemons together in your environment?
Zebra is the core daemon of FRR (see ["System Architecture"](https://frrouting.org/user-guide/overview.html#system-architecture) on FRR doc) and each version of FRR's routing daemons should be the same, I guess. Zebra and other routing daemons (e.g., bgpd, ripd or ospfd) will communicate via Zebra protocol, and I think mixture of different version should cause some problems.

Then, you said "FRR version is 3.0.3, but Zebra version is 4.1-dev" and this means you are using version "4.1-dev". Please confirm the installed version again and try to re-install FRR with version 3.0.3.

> I can't understand why but it tries all version from 2 to 5 with message cannot connect to Zebra with message version #. going to retry another version....

You mean the log messages like `"cannot connect to Zebra with message version 3. going to retry..."`, right?
GoBGP will retry all supported version (2, 3 and 4) if could not connect to Zebra with the configured version. (version "5" is not supported. Zebra sent messages with version 5.)
https://github.com/osrg/gobgp/blob/97eea7aac6b897f266f79efd2d0bb1aa9b1cf678/server/zclient.go#L542-L551

**Comment by horseinthesky** [comment]
@iwaseyusuke 
Thank you very much for your help.
Was my mistake: i did `git clone` master branch with 4.0.1 version insted of `git clone --branch stable/3.0`.

GoBGP succefully connects with Zebra and install routes to fib
```
horseinthesky@ubuntu:~$ ip r
default via 192.168.0.1 dev vrr-ext onlink 
10.20.0.1 via 192.168.0.150 dev vrr-ext  proto zebra  metric 20 
10.20.0.2 via 192.168.0.150 dev vrr-ext  proto zebra  metric 20 
192.168.0.0/24 dev vrr-ext  proto kernel  scope link  src 192.168.0.95 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 linkdown 
```

May i ask one more question: is it possible to use Zebra with GoBGP to install lebeled-routes in fib?
Here i have `adj-in` but received routes are not injected to fib:
```
horseinthesky@ubuntu:~$ gobgp nei 192.168.0.150 -a ipv4-mpls adj-in
   ID  Network              Labels     Next Hop             AS_PATH              Age        Attrs
   0   10.20.0.1/32         [16]       192.168.0.150        65002 65001          00:03:23   [{Origin: i}]
   0   10.20.0.2/32         [3]        192.168.0.150        65002                00:03:23   [{Origin: i} {Med: 0}]
   0   10.20.0.3/32         [17]       192.168.0.150        65002 65003          00:03:22   [{Origin: ?}]
horseinthesky@ubuntu:~$ ip r
default via 192.168.0.1 dev vrr-ext onlink 
192.168.0.0/24 dev vrr-ext  proto kernel  scope link  src 192.168.0.95 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 linkdown 
```

**Comment by iwaseyusuke** [comment]
@horseinthesky Very sorry for the delay.
According to the discussions on other issues (like https://github.com/osrg/gobgp/issues/1609), FRRouting version 3.x does not support to install labeled routes to FIB. The version 4.x seems to have some improvements, but GoBGP does not support that version...

**Comment by horseinthesky** [comment]
Ok. Thank you very much.
