### ISSUE TITLE
Go Get Fails With: "package github.com/osrg/gobgp: no Go files in /go/src/github.com/osrg/gobgp"

### ISSUE THREAD

**Issue by mathershifter** [osrg/gobgp#1691]
I'm trying to follow "To start developing GoBGP" instructions using the official golang docker container and can't get past the second step.  I'm not sure what additional details I should provide. Note: I'm having the same problem getting this setup w/o docker involved

### Dockerfile

```
FROM golang:1.9-alpine3.7
WORKDIR $GOPATH
RUN \
  apk update && \
  apk add git && \
  go get -u github.com/golang/dep/cmd/dep && \
  go get github.com/osrg/gobgp
```

### STDOUT

```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM golang:1.9-alpine3.7
 ---> 4f3f33e05454
Step 2/3 : WORKDIR $GOPATH
 ---> Using cache
 ---> e724c92d7377
Step 3/3 : RUN   apk update &&   apk add git &&   go get -u github.com/golang/dep/cmd/dep &&   go get github.com/osrg/gobgp
 ---> Running in b32f13af1d80
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.0-170-g9a8ee8c004 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-171-g5500dd12a4 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 9049 distinct packages available
(1/5) Installing libssh2 (1.8.0-r2)
(2/5) Installing libcurl (7.60.0-r0)
(3/5) Installing expat (2.2.5-r0)
(4/5) Installing pcre2 (10.30-r0)
(5/5) Installing git (2.15.0-r1)
Executing busybox-1.27.2-r7.trigger
OK: 19 MiB in 17 packages
package github.com/osrg/gobgp: no Go files in /go/src/github.com/osrg/gobgp
The command '/bin/sh -c apk update &&   apk add git &&   go get -u github.com/golang/dep/cmd/dep &&   go get github.com/osrg/gobgp' returned a non-zero code: 1
```

**Comment by iwaseyusuke** [comment]
@mathershifter Hi,

Because there is no Go file containing `main()` at the top directory of GoBGP (`"github.com/osrg/gobgp"`), `"go get"` output that warning. Please run `"go get"` for each GoBGP's binaries as the following.

```bash
go get github.com/osrg/gobgp/gobgp
go get github.com/osrg/gobgp/gobgpd
```

**Comment by mathershifter** [comment]
I see, works now.  Is the README incorrect or was I missing something?

Thanks for the response!

**Comment by iwaseyusuke** [comment]
Hmmm... ["To start developing GoBGP"](https://github.com/osrg/gobgp#to-start-developing-gobgp) seems to describe how to set up environment to build or developing GoBGP on your machine, but not enough to describe how to directly build GoBGP with `"go get"` command on your CI or Docker. For such purpose, ["binary release"](https://github.com/osrg/gobgp/releases/latest) seems to be recommended.

**Comment by fujita** [comment]
`go get github.com/osrg/gobgp` get the source code necessary for developing even though it returns an error because it fails to build binaries. You can simply ignore the error.

**Comment by yogesnsamy** [comment]
> `go get github.com/osrg/gobgp` get the source code necessary for developing even though it returns an error because it fails to build binaries. You can simply ignore the error.

Thanks for sharing this. I had a relook at the folder after reading your comment and realized that it stills fetches the repo.
