### ISSUE TITLE
user-unfriendly gobgp errors

### ISSUE THREAD

**Issue by greenpau** [osrg/gobgp#1701]
When running `gobgp` cli against a router that is down, a user may encounter "context deadline exceeded" error:

```bash
# gobgp neighbor
context deadline exceeded
```

It is not entirely intuitive to understand whether there are no neighbors or whether the router is down.

Thus, it makes sense to intercept the errors and, if necessary, provide user-friendly error message.

**Comment by fujita** [comment]
Surely, pull requests for such improvement are very welcomed.
