### ISSUE TITLE
Route-reflector: Why cluster-id need to be a valid IPv4 address

### ISSUE THREAD

**Issue by murali-reddy** [osrg/gobgp#1719]
Whey for using Route-reflector, cluster-id need to be a valid IPv4 address?

https://github.com/osrg/gobgp/blob/master/config/default.go#L245

It could be just valid integer as well?

**Comment by iwaseyusuke** [comment]
@murali-reddy Hi, an integer value might be enough when configuring `cluster-id` on files, but RFC4456 says;

```text
7.  Redundant RRs

   Usually, a cluster of clients will have a single RR.  In that case,
   the cluster will be identified by the BGP Identifier of the RR.
   However, this represents a single point of failure so to make it
   possible to have multiple RRs in the same cluster, all RRs in the
   same cluster can be configured with a 4-byte CLUSTER_ID so that an RR
   can discard routes from other RRs in the same cluster.
```

I think this implies the BGP Identifier (represented as IPv4 address) can be the default value of `cluster-id` and the representation of `cluster-id` should be the same with the BGP Identifier.

**Comment by iwaseyusuke** [comment]
I checked the Cisco router's `bgp cluster-id` command, Cisco can accept `cluster-id` as an integer. i will create a patch to accept `cluster-id` as an 32-bit integer value.

**Comment by murali-reddy** [comment]
thanks @iwaseyusuke

**Comment by fujita** [comment]
@murali-reddy please try the latest master.

**Comment by murali-reddy** [comment]
@iwaseyusuke @fujita thanks for a such a quick turnaround. Will try the latest master.
