### ISSUE TITLE
question: grpc.ClientConn

### ISSUE THREAD

**Issue by greenpau** [osrg/gobgp#1736]
Attempting to call GoBGP API in the following way:

```go
import (
    gobgpapi "github.com/osrg/gobgp/api"
    "golang.org/x/net/context"
)

func ... {

    client, err := gobgpapi.NewGobgpApiClient(
```

The `NewGobgpApiClient` takes in `*grpc.ClientConn`.

When I create `*grpc.ClientConn` by importing `"google.golang.org/grpc"` and using it, I get the following error:

```bash
plugins/gobgp/client.go:71:38: cannot use conn (type
  *"github.com/greenpau/kashar/vendor/google.golang.org/grpc".ClientConn) as type
  *"github.com/osrg/gobgp/vendor/google.golang.org/grpc".ClientConn in argument to gobgpapi.NewGobgpApiClient
```

The `gobgpApiClient` struct has `cc` (which is private).

```
type gobgpApiClient struct {
    cc *grpc.ClientConn
}
```

Any ideas how to solve this?

**Comment by greenpau** [comment]
One way is making a few modifications to `api/gobgp.pb.go`:

```go
import (
    "net"
    "time"
)

func (c *gobgpApiClient) UpdateConnection(host string, port string) error {
    if c.cc == nil {
        serverAddr := net.JoinHostPort(host, port)
        var opts []grpc.DialOption
        opts = append(opts, grpc.WithInsecure())
        opts = append(opts, grpc.WithBlock())
        opts = append(opts, grpc.WithTimeout(time.Second*2))
        conn, err := grpc.Dial(serverAddr, opts...)
        if err != nil {
            return err
        }
        c.cc = conn
    }
    return nil
}

type GobgpApiClient interface {
    UpdateConnection(host string, port string) error
    StartServer(ctx context.Context, in *StartServerRequest, opts ...grpc.CallOption) (*StartServerResponse, error)
```

Then, the API can be invoked:

```go
    client := gobgpapi.NewGobgpApiClient(nil)
    err := client.UpdateConnection("127.0.0.1", "50051")
    if err != nil {
        return fmt.Errorf("gobgp: failed to connect: %s", err)
    }
```

Perhaps, there is some other way ...

**Comment by iwaseyusuke** [comment]
IIRC, I saw the same messages. Please try `dep ensure` as ["To start developing GoBGP"](https://github.com/osrg/gobgp#to-start-developing-gobgp).
I guess there are some conflicts of package's version.

**Comment by greenpau** [comment]
> I guess there are some conflicts of package's version.

@iwaseyusuke , I did `dep ensure`. The issue is that the package I am calling gobgpapi from uses `grpc` too. Hence the conflict.

**Comment by iwaseyusuke** [comment]
@greenpau Well, you mean you are using the different version of `grpc` package on a single application? If so, I don't know the practice to solve it...
If your application does not share the dependencies (`vendor` directory) with GoBGP, I think we can integrate them through gRPC communication.

**Comment by greenpau** [comment]
> you mean you are using the different version of grpc package on a single 

@iwaseyusuke , yes. mypackage does `import "google.golang.org/grpc"`, and gobgpapi does `import "google.golang.org/grpc"`.

**Comment by greenpau** [comment]
The best I was able to think of is adding a new function via separate file`github.com/osrg/gobgp/api/gobgp.pb.extended.go`. This way, it does not conflict with autogenerated `gobgp.pb.go` code:

```go
package gobgpapi

import (
	grpc "google.golang.org/grpc"
	"time"
)

func NewGobgpApiExtendedClient(s string, t int) (GobgpApiClient, error) {
	if t == 0 {
		t = 2
	}
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithInsecure())
	opts = append(opts, grpc.WithBlock())
	opts = append(opts, grpc.WithTimeout(time.Duration(t)*time.Second))
	conn, err := grpc.Dial(s, opts...)
	if err != nil {
		return nil, err
	}
	c := &gobgpApiClient{conn}
	return c, nil
}
```

**Comment by fujita** [comment]
I think that you can't use multiple versions of a library in one golang application (at least for now).
