### ISSUE TITLE
enhacement: NewEVPNIPPrefixRoute ipPrefixLength calculcation

### ISSUE THREAD

**Issue by greenpau** [osrg/gobgp#1738]
Based on my observation, the [`NewEVPNMacIPAdvertisementRoute()`](https://github.com/osrg/gobgp/blob/master/packet/bgp/bgp.go#L2456-L2478) function is implemented slightly better than [`NewEVPNIPPrefixRoute()`](https://github.com/osrg/gobgp/blob/master/packet/bgp/bgp.go#L2807-L2823), because the latter requires providing `ipPrefixLength uint8`, while the former does the calculation based on the supplied IP address.

Proposed enhancement:
* extra checks
* prefix length calculation

```go
func NewEVPNIPPrefixRoute(rd RouteDistinguisherInterface, esi EthernetSegmentIdentifier, etag uint32, ipPrefix string, gateway string, label uint32) *EVPNNLRI {
    var ipLen uint8
    ip := net.ParseIP(ipPrefix)
    if ip == nil {
        return nil
    }
    gw := net.ParseIP(gateway)
    if gw == nil {
        return nil
    }
    ipv4 := ip.To4()
    if ipv4 != nil {
        ip = ipv4
        ipLen = 32
    } else {
        ipLen = 128
    }
    gwv4 := gw.To4()
    if gwv4 == nil && ipv4 != nil {
        return nil
    }
    if gwv4 != nil && ipv4 == nil {
        return nil
    }
    if gwv4  != nil {
        gw = gwv4
    }
    return NewEVPNNLRI(EVPN_IP_PREFIX, &EVPNIPPrefixRoute{
        RD:             rd,
        ESI:            esi,
        ETag:           etag,
        IPPrefixLength: ipLen,
        IPPrefix:       ip,
        GWIPAddress:    gw,
        Label:          label,
    })
}
```

**Comment by iwaseyusuke** [comment]
@greenpau Hi,

I quite agree with you about the enhancement of validations, but for `IPPrefixLength uint8`, I think it should not be static (32 or 128) value.

The [draft-ietf-bess-evpn-prefix-advertisement](https://tools.ietf.org/html/draft-ietf-bess-evpn-prefix-advertisement-11#section-3.1) says;
```text
   o The IP Prefix Length can be set to a value between 0 and 32 (bits)
     for IPv4 and between 0 and 128 for IPv6, and specifies the number
     of bits in the Prefix. The value MUST NOT be greater than 128.
```
then, `IPPrefixLength uint8` should represent the "prefix length" (not the "IP address length").

On the other hand, the "IP address length" should be derived from `Length uint8` field of `EVPNNLRI`.
```text
   o The Length field of the BGP EVPN NLRI for an EVPN IP Prefix route
     MUST be either 34 (if IPv4 addresses are carried) or 58 (if IPv6
     addresses are carried). The IP Prefix and Gateway IP Address MUST
     be from the same IP address family.
```

**Comment by greenpau** [comment]
@iwaseyusuke , 👍
