### ISSUE TITLE
UUID was removed from path information.

### ISSUE THREAD

**Issue by cstockton** [osrg/gobgp#1740]
It seems that in dd85cab1ecd3c21a5e2502858790befc6b7f0074 the Uuid was removed from paths. I used this for path deletion in https://godoc.org/github.com/osrg/gobgp/api#DeletePathRequest - I understand that you don't consider "table" to be a public API, however you also no longer set it in the GRPC server https://github.com/osrg/gobgp/commit/dd85cab1ecd3c21a5e2502858790befc6b7f0074#diff-82d5460342cad13f5c00901cf5ce93aeL395 and I can't see any way to access it anymore. I think in the future it may be better to remove associated method when you deprecate them, since I see no way of obtaining a UUID anymore the [DeletePathByUUID](https://github.com/osrg/gobgp/blob/master/client/client.go#L467) will no longer function. The way I deleted paths was simple:

```Go
	get, err := cli.GetPath(ctx, pfx)
	if err != nil {
		t.Fatalf("exp nil err from AddPath; got %v", err)
	}
	delReq := gobgpapi.DeletePathRequest{
		Resource: gobgpapi.Resource_GLOBAL,
		Uuid:     get.Uuid,
	}

	err = cli.DeletePath(ctx, &delReq)
	if err != nil {
		t.Fatalf("exp nil err from DeletePath; got %v", err)
	}
```

The Uuid to delReq is the zero value UUID, which is valid but obviously does not exist. DeletePath returns no errors to indicate the request fails, so it was unclear why deletes stopped working. So this means that GRPC `api` package is not stable as well which is unfortunate but I respect your design decision and appreciate the work you do on the project. Do you provide any guarantees for the GRPC api at least, do you have some fields I can trust will be there in future versions?

I have decided after the prior issue with prefix changes that I will no longer use any packages other than `api` but there are some challenges with that. The biggest one is that to even import it requires something like [40-50 packages after dependencies](https://godoc.org/github.com/osrg/gobgp/api?imports)? This is because things are actually backwards- your `api` package imports every other package, instead of every other package important `api`. Would you be willing to accept some pull requests to reverse this? For example- instead of calling `api.Path.ToNativePath()` you would call `table.PathFromAPI(*api.Path)`. 

If that doesn't interest you no worries, I can copy your proto file and generate my own structures and client if needed and you can close this issue. Thanks for your work on GoBGP.

**Comment by cstockton** [comment]
Yea thanks- I think the main take away from my report at this point is it might be good to at least make calls to the [DeletePathByUUID](https://godoc.org/github.com/osrg/gobgp/client#Client.DeletePathByUUID) function return something like `ErrUnsupported` - if deleting the function entirely for a compile error isn't an option. It was difficult to track down this issue since there was no failures reported.

**Comment by fujita** [comment]
Surely, I'll take care of that soon.  Sorry about the trouble.

I mentioned earlier, I'll change the gRPC APIs with the major version updated. I intend to change AddPath() gRPC API to only one path; 1) returning an UUID only when adding one Path is confusing. 2) handling the situation what adding some of paths are successful and the rest failed are tricky.

Thought?

**Comment by cstockton** [comment]
No worries at all.

I think you are talking about the [gobgp.Client](https://godoc.org/github.com/osrg/gobgp/client) right? I don't use that because it doesn't accept context and it's important my requests don't block when canceled, so instead I call [api.GobgpApiClient](https://godoc.org/github.com/osrg/gobgp/api#GobgpApiClient) directly which already takes 1 path (which I think is a good design). If you do decide to reduce AddPath in the client to 1 argument it might be good to update DeletePath as well for symmetry.

Sort of related question (path deletes), I've been doing some testing today and I can not find a way to delete paths from the global rib anymore after trying every method I've known that has worked in the past. I have a feeling it has something to do with [this change](https://github.com/osrg/gobgp/commit/ee91af5b638755a19c6954579b77a28916fb9bff#diff-fd1900a487e4818b9cea9e62a9fa5075R450) because that is the error I'm getting in GoBGP logs now as seen below:
```console
{"Key":"10.0.0.1/32","Path":{"nlri":{"prefix":"10.0.0.1/32"},"attrs":[{"type":1,"value":0},{"type":8,"communities":[105546]},{"type":3,"nexthop":"192.168.0.1"}],"age":1529280748,"withdrawal":true,"validation":"none"},"Topic":"Table","level":"warning","msg":"No matching path for withdraw found, may be path was not installed into table","time":"2018-06-18T00:12:28Z"}
```

Given a simple global rib of below: 
```Go
*> 10.0.0.1/32          192.168.0.1                               00:44:05   [{Origin: i} {Communities: 1:40010}]
*> 10.0.1.0/24          208.109.114.202                           00:44:05   [{Origin: i} {Communities: 1:40012}]
```

I've tried variations of DeletePathRequest:
```Go
// I deleted code in two ways, one ways using the UUID for known-paths that could have
// potential conflicts. The second way way was using the `InjectMrt.Send()`. I've tried all
// of these using DeletePath and the Send() method for InjectMrt - both seem to yield the
// same result.

p :=  // GetPath successfully with LOOKUP_EXACT from the global rib
req := gobgpapi.DeletePathRequest{
	Resource: gobgpapi.Resource_GLOBAL,
	Path:     gobgpapi.ToPathApi(p.Clone(true), nil), // I've tried to clone it
}
_, err := c.cli.DeletePath(ctx, &req)

p :=  // GetPath successfully with LOOKUP_EXACT from the global rib
req := gobgpapi.DeletePathRequest{
	Resource: gobgpapi.Resource_GLOBAL,
	 // I've just sent it as is since the GoBGP grpc_server.go sets IsWithdraw = true
	Path:     gobgpapi.ToPathApi(p, nil),
}
_, err := c.cli.DeletePath(ctx, &req) 

// Construct the path using the EXACT function as I do for the successful call to addPath
p := c.newPath(...) // this works for AddPathRequest
p.IsWithdraw = true // tried with and without this
req := gobgpapi.DeletePathRequest{
	Resource: gobgpapi.Resource_GLOBAL,
	Path:     gobgpapi.ToPathApi(p, nil),
}
_, err := c.cli.DeletePath(ctx, &req)
```

In all cases I get no errors, but the paths are not withdrawn. At first I thought it has to do with the fact when I create paths I do not send PeerInfo, but the fact that I received the path from the GoBGP server and still can not delete makes me think I'm doing something else wrong. 

What is the correct way to delete those paths in v1.32? Thanks a lot for any hints- I'll close this out after.

**Comment by cstockton** [comment]
After I posted that I dug a little deeper in a stand-alone test, ultimately I discovered the reason why deletes are not working from existing paths has something to do with the source information being out of sync. The full [tests are here](https://gist.github.com/cstockton/db3cc222471e4e9858d3b60290e3b7f8). When I send something as minimal as an NLRI, Family and local identifier it will succeed. But if _ANY_ source information is present it will fail, even if the source information came directly from GetPath. It appears that GetPath returns Source information that is out of sync with what the GoBGP server may store.

The main example that I think helped me was the fact the [ClearAsn](https://gist.github.com/cstockton/db3cc222471e4e9858d3b60290e3b7f8#file-deletetest_test-go-L375) worked, meaning setting the SourceAsn to the zero value causes the test to pass. So what appears to be happening is if the autonomous system is omitted in the original path the GoBGP server AS is injected. However the path can not be withdrawn with the GoBGP server AS set- it must be the exact AS as it was when created which is the zero value.

I propose that under all circumstances a valid path returned by `GetPath` should be removable as an argument in `DeletePath`, i.e. this never fails when `GetPath` succeeds: `DeletePath(GetPath())`. I personally believe GoBGP should return the original SourceAsn of 0, but would be okay with `DeletePath` having a special case instead.

Thanks for the help, you can close this out at your leisure since I have a path forward.

**Comment by cstockton** [comment]
@fujita So today after trying to implement my findings from yesterday I've discovered that they only worked for my simpler use cases of adding paths with "nil" source information (creating blackholes). My other use case is advertising longer prefixes to redirect traffic, part of this process involves looking up the existing path and creating a new advertisement. When creating the new path I set the source to be the `best.GetSource()` which ultimately is all zero values except the AS, ID, Address. The problem comes in that those values do not come back to me in the API as [shown here](https://gist.github.com/cstockton/2378c9835127552718e95f15c5e058d4).

Currently I have no work around for this since I can't go through the best path-selection process when it's time to withdraw, since it may be hours or weeks later a new best-path may emerge due to various reasons (maybe the original peer is offline) so I can't guarantee I can select the same router. Deleting by UUID was a nice way to remove ANY prefix from the globlal rib, since you could do a `LookupExact` with `GetPath` and then `DeleteByUUID` on the paths UUID. Right now I'm struggling to find a way delete something returned by `GetPath` (it seems the official client can't do this either). Any suggestions?

**Comment by fujita** [comment]
I fixed `DeletePathByUUID()`. 
https://gist.github.com/fujita/3219d786e49e1d146a437f47c6bcbbd1 works with the current master.

I guess that 'source' issue has been since I added AddPath() API; only works with 'nil' source. Can you create an issue about how should work? I'll work on it with the api/ rewriting.

**Comment by cstockton** [comment]
Thanks very much for the fix to DeletePathByUUID!
