### ISSUE TITLE
Improve Add, Get, Del Path symmetry for global rib source handling

### ISSUE THREAD

**Issue by cstockton** [osrg/gobgp#1752]
As discussed in #1740 currently when creating a path using `AddPath` for the global rib the source information is either lost or mutated before reaching the final storage location that `GetPath` will use. This means a call to `DeletePath` using the *result* of a `GetPath` request will fail, while calling `DeletePath` with the *request* of an `AddPath` succeeds, in short:

 - `DeletePath(AddPath(pathWithPeerInfo))` // success
 - `DeletePath(GetPath(pathWithPeerInfo))` // failure
 - `DeletePath(AddPath(pathWithoutPeerInfo))` // failure
 - `DeletePath(GetPath(pathWithoutPeerInfo))` // failure

I propose all 4 cases return success- since it's not always possible to construct the same exact path if it's built using dynamic information from the routing tables. I've written a [test](https://gist.github.com/cstockton/19f95f36f5d98570e61f06692eea865a) that should start passing once this is fixed.

**Comment by fujita** [comment]
Sorry for taking too long. I've just fixed this issue and added an unittest:
https://github.com/osrg/gobgp/blob/master/pkg/server/server_test.go#L1056-L1172
Please let me know if it works for you.

**Comment by cstockton** [comment]
Thanks a lot @fujita, appreciate it!
