### ISSUE TITLE
Malformed 0 length NLRI Prefixes

### ISSUE THREAD

**Issue by marcin-ptaszynski** [osrg/gobgp#1782]
Example Scenario: https://github.com/osrg/gobgp/blob/v1.33/test/scenario_test/route_reflector_test.py#L130

![screen shot 2018-07-13 at 11 15 40](https://user-images.githubusercontent.com/129948/42707188-3bbc676a-868e-11e8-98cf-c078ed10e3ba.png)

Atatching pcap file [malformed_nlri_length.pcapng.zip](https://github.com/osrg/gobgp/files/2193739/malformed_nlri_length.pcapng.zip)

It seems issue isn't critical and gobgp derives proper length from parent field anyway, but It's problematic when debugging, as messages don't display properly.

**Comment by fujita** [comment]
wireshark doesn't parse the addpath id field wrongly? It supports vpnv4 prefix with addpath?

**Comment by marcin-ptaszynski** [comment]
Sorry about that, I didn't check how add-path affects NLRI format. it seems Wireshark doesn't support it. Closing.
