### ISSUE TITLE
graceful restart: rtc paths are not send after deferral time expired

### ISSUE THREAD

**Issue by qsqx** [osrg/gobgp#1788]
The problem was appeared after commit https://github.com/osrg/gobgp/commit/db6683bfbfee3a6e04e78d6af40bbdb9f4fcd317 

RTC paths should still be send after deferral time expired in a graceful restarting process ?

**Comment by qsqx** [comment]
It's a better choice. Thanks a lot.

**Comment by fujita** [comment]
thanks!
