### ISSUE TITLE
Exposing the go client for gobgp

### ISSUE THREAD

**Issue by mageshgv** [osrg/gobgp#1797]
Hi,

The client package that we had until the latest release was much helpful for external applications to integrate with gobgp. 
https://github.com/osrg/gobgp/blob/v1.33/client/client.go

This has been made a private one now : https://github.com/osrg/gobgp/commit/c4775c42510d1f1ddd55036dc19e982712fa6a0b

In the current master, the assumption is that the client is only the embedded native cli. But for external integrations, executing the cli binary several times - one per config change is not the way to go and reimplementing the client means that the consumer applications will have to duplicate this file within the external application: https://github.com/osrg/gobgp/blob/c4775c42510d1f1ddd55036dc19e982712fa6a0b/internal/pkg/client/client.go

Can we instead treat the client package as an SDK and expose this back as a public package so that native go applications do not have to reimplement the client.

**Comment by fujita** [comment]
Yeah, that's the plan. However, I think that client.go needs to be fixed to make it the SDK:

- Adding context argument to every public APIs.
- removing the usage of github.com/osrg/gobgp/internal/pkg/config
- removing the usage of github.com/osrg/gobgp/pkg/packet/bgp
- anything else?

It might be better to start from scratch, I'm not sure though. It would be great if you could work on the SDK.

**Comment by mageshgv** [comment]
@fujita Thanks for the update. We would definitely have to do this from our end, let me see how our internal schedule is for the upgrade beyond v1.33 and the priorities.
