### ISSUE TITLE
GoBGP  in route mode, but operating like a route server with single RIB

### ISSUE THREAD

**Issue by ailtonsr** [osrg/gobgp#1798]
To do this you need the following 3 things:

- next-hop unchanged
- med unchanged
- aspath unchanged

These options are already implemented in other brands of routers and can help a lot in some cases.

In our case, is to use GoBGP in route mode, but operating like a route server with single RIB.

Thank You

Ailton

**Comment by fujita** [comment]
what's the use case for this?
