### ISSUE TITLE
4 Byte ASNs

### ISSUE THREAD

**Issue by ecbaldwin** [osrg/gobgp#1799]
Our datacenter network runs ebgp where every router and host has a [4 byte ASN][1]. gobgp doesn't understand it.

```
{"Data":"as number mismatch expected 4206900001, received 23456","Key":"10.112.97.1","Topic":"Peer","level":"warning","msg":"sent notification","time":"2018-08-07T14:53:47Z"}
```

23456 is a reserved 2 byte ASN that says to find the real 4 byte ASN in another field.

[1]: https://www.ietf.org/rfc/rfc4893.txt

**Comment by fujita** [comment]
odd, GoBGP should support it. I've just tried and two gobgp peers (one has 4 byte ASN) successfully established as below.

![2018-08-10 20 51 37](https://user-images.githubusercontent.com/726426/43956448-39fc0c2a-9cdf-11e8-969f-24236d7ff916.png)

Your both peers are GoBGP? If not, the peer sends a proper Open message? As below, the Open message must include the 65 capability with a 4 byte ASN.

![2018-08-10 20 53 52](https://user-images.githubusercontent.com/726426/43956514-82d58958-9cdf-11e8-9c9d-829704591c47.png)

**Comment by ecbaldwin** [comment]
The other end is a Juniper EX9204. I think I see what happened. The Juniper rejected my connection because it was coming from the wrong source address (my fault). The EX's response was an OPEN Message along with a NOTIFICATION Message. This returned open message did not include the "4-octet AS number capability" in it. That's what gobgp was complaining about. I did not see past this red herring.

Below is the response from the EX. After I fixed my source address to match what the EX was expecting, things went better.

```
Border Gateway Protocol - OPEN Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 37
    Type: OPEN Message (1)
    Version: 4
    My AS: 23456 (AS_TRANS)
    Hold Time: 90
    BGP Identifier: 10.112.97.1
    Optional Parameters Length: 8
    Optional Parameters
        Optional Parameter: Capability
            Parameter Type: Capability (2)
            Parameter Length: 2
            Capability: Route refresh capability (Cisco)
                Type: Route refresh capability (Cisco) (128)
                Length: 0
        Optional Parameter: Capability
            Parameter Type: Capability (2)
            Parameter Length: 2
            Capability: Route refresh capability
                Type: Route refresh capability (2)
                Length: 0
Border Gateway Protocol - NOTIFICATION Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 21
    Type: NOTIFICATION Message (3)
    Major error Code: Cease (6)
    Minor error Code (Cease): Connection Rejected (5)
```
