### ISSUE TITLE
API returns incorrect info for BGP peers

### ISSUE THREAD

**Issue by greenpau** [osrg/gobgp#1825]
When querying Peer state via GoBGP API, the router responds the Admin and Session states  a bgp peer's are `0`. However, the connection is Established.

- PeerState.AdminState
- PeerState.SessionState

Code: https://github.com/greenpau/gobgp_exporter/blob/master/gobgp_exporter.go#L441-L457

Further, although `AuthPassword` is set, the API returns an empty string.

- PeerState.AuthPassword
- PeerState.PeerType

Code: https://github.com/greenpau/gobgp_exporter/blob/master/gobgp_exporter.go#L523-L542

**Comment by fujita** [comment]
AdminState is not related with the session state. SessionState should work because gobgp command uses it and shows the proper session states.

AuthPassword is not state (dynamically changed on the server side). You can get it from PeerConf. Same of PeerType.

**Comment by greenpau** [comment]
> AdminState is not related with the session state. 

@fujita , what is it related to? Isn't it similar to tracking `shutdown`/`no shutdown` on a peer?

> AuthPassword is not state (dynamically changed on the server side). You can get it from PeerConf. Same of PeerType.

@fujita , I am referring to https://github.com/osrg/gobgp/blob/master/api/gobgp.pb.go#L3312, which is the part of `PeerState` struct. Should `AuthPassword` be copied from `PeerConf` to `PeerState`?

**Comment by fujita** [comment]
An admin can enable/disable a peer, which is AdminState:
https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#22-operations-for-neighbor---shutdownresetsoftresetenabledisable--

I'm not sure the same information should be duplicated.

**Comment by greenpau** [comment]
> An admin can enable/disable a peer, which is AdminState:

@fujita , 👍
