### ISSUE TITLE
No route updates sent to BMP server

### ISSUE THREAD

**Issue by agember** [osrg/gobgp#1831]
Starting with commit 840807a, gobgpd no longer sends route monitoring messages to the configured BMP server. The configured BMP route-monitoring-policy is `local-rib`.

**Comment by fujita** [comment]
I can't reproduce this. Can you post your config file?

**Comment by agember** [comment]
[Koper.gobgp.txt](https://github.com/osrg/gobgp/files/2407794/Koper.gobgp.txt) is the configuration for one of the devices. All other devices in the network have the same BMP configuration.

**Comment by fujita** [comment]
Please let me know if 2.X versions don't work.
