### ISSUE TITLE
gobgpd crashes while learning evpn routes

### ISSUE THREAD

**Issue by mantri425** [osrg/gobgp#1843]
Hi,
i have a gobgpd running on a vm and it has session with a router where it sends "evpn" routes as an update. sometimes the deamon crashes and doesn't respond with gobgp commands.

Is there a log file that i can see and find the issue? is there a limitation on gobgp for evpn routes?

[root@goBGP gobgp_master]# ls -l
total 40268
-rwxrwxrwx. 1 root root     7637 Oct  2 13:49 config.conf
-rwxrwxrwx. 1 root root 19447080 Aug 27 10:19 gobgp
-rwxrwxrwx. 1 root root 21775456 Aug 27 10:19 gobgpd
[root@goBGP gobgp_master]#

**Comment by fujita** [comment]
Can you send a pcap file including a packet that crashes gobgpd?

**Comment by mantri425** [comment]
Hi Fujita,

192.168.103.3 is the gobgpd speaker, captured the packet in the order where the neighbor is added, started advertising evpn routes to gobgpd speaker and stopped when gobgp crashes . please check

**Comment by mantri425** [comment]
[evpn.zip](https://github.com/osrg/gobgp/files/2506543/evpn.zip)

**Comment by fujita** [comment]
I thought that 'crash' is panic but it's a deadlock in your case. The packet in the capture file can be parsed. Some bugs leading to deadlock were fixed so can you try the latest?

**Comment by mantri425** [comment]
Thank you, will try the latest.

**Comment by fujita** [comment]
Please reopen if the latest master doesn't work.
