### ISSUE TITLE
bad wiretype

### ISSUE THREAD

**Issue by damanloox** [osrg/gobgp#1852]
I'm using version 1.33 binary (gobgpd) and trying to test grpc from my "client" (golang). Here's what I'm trying to do:
```
  // request bgp route injection
  nlri, _ := ptypes.MarshalAny(&bgpapi.IPAddressPrefix{
    Prefix:    "1.1.1.1",
    PrefixLen: 32,
  })

  a1, _ := ptypes.MarshalAny(&bgpapi.OriginAttribute{
    Origin: 0,
  })
  a2, _ := ptypes.MarshalAny(&bgpapi.NextHopAttribute{
    NextHop: "9.9.9.9",
  })
  attrs := []*any.Any{a1, a2}

  pathReq := &bgpapi.AddPathRequest{
    Path: &bgpapi.Path{
      Family:    &bgpapi.Family{Afi: bgpapi.Family_AFI_IP, Safi: bgpapi.Family_SAFI_UNICAST},
      AnyNlri:   nlri,
      AnyPattrs: attrs,
    }}
_, err := s.bgpClient.AddPath(context.Background(), pathReq)

```

Unfortunately I'm getting the following error:

> grpc: error unmarshalling request: proto: bad wiretype for field gobgpapi.Path.Family: got wiretype 2, want 0

Any idea what I'm doing wrong...?

**Comment by fujita** [comment]
The gRPC APIs have been changed after 1.33.
Please refer to the gRPC APIs of v1.33 like
https://github.com/osrg/gobgp/blob/8e6bd4c7145de5a68c40246418500bf05af9ce39/docs/sources/lib.md

**Comment by pavel-odintsov** [comment]
Yep, I hit same issue. @fujita any plans about release? Looks like 1.34 will be quite big one! :)

**Comment by damanloox** [comment]
OK, thanks.
