### ISSUE TITLE
Backward incompatible changes in API

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#1855]
Hello!

I resumed my migration from 2 year old version of GoBGP to 1.33. 

Unfortunately, I noticed number of backward incompatible changes.

For example in https://github.com/osrg/gobgp/commit/97ad6b32ee61fd439c2edefbc371f748cdf82046 you changed field type:
<img width="366" alt="screenshot 2018-10-28 at 22 20 18" src="https://user-images.githubusercontent.com/2744166/47622737-712c1f00-db00-11e8-9205-7ca125cb2686.png">

From Protobuf's perspective you can deprecate old field and add new one with new sequence number instead of changing field type.

Also, you changed sequence of fields in https://github.com/osrg/gobgp/commit/810ba2f791bb9d50b3e9a2777444211ea2e6351a 

It also breaks backward compatibility with existing clients. 

Can I consider current gRPC API format (1.33) as stable and use it?

Thank you!

**Comment by fujita** [comment]
Sorry about the trouble.
https://github.com/osrg/gobgp/issues/1763
Seems impossible to clean up the APIs in the backward compatible way so no compatibility after 1.33. The next release will be 2.0.0. It's so overdue, sometime in December.

If you will use version 2.X, all the binary format in AddPath API was removed. 
https://github.com/osrg/gobgp/blob/master/api/attribute.proto
Path attributes are defined in protobuf. So you can easily use the API with any language. You don't need a hack with C like
https://github.com/osrg/gobgp/tree/master/cmd/gobgp/lib

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for information!

Let me show you how I create announces for BGP Unicast now (1.33 compatible):
```
gobgpapi::Path* current_path = new gobgpapi::Path;
if (is_withdrawal) {
    current_path->set_is_withdraw(true);
}

current_path->set_family(ipv4_unicast_route_family);
current_path->set_nlri(binary_nlri.get_pointer(), binary_nlri.get_used_size());

for (auto bgp_attribute : bgp_attributes) {
    current_path->add_pattrs(bgp_attribute.get_pointer(), bgp_attribute.get_used_size());
}

gobgpapi::AddPathRequest request;
request.set_resource(gobgpapi::Resource::GLOBAL);
request.set_allocated_path(current_path);

gobgpapi::AddPathResponse response;

auto status = stub_->AddPath(&context, request, &response);
```

Are you going to deprecate way to manually inject separate attributes as blobs? 

Thank you!

**Comment by fujita** [comment]
I plan to keep the feature to add a path with a binary attribute but I want to remove the following hack for C:
https://github.com/osrg/gobgp/tree/master/cmd/gobgp/lib

**Comment by pavel-odintsov** [comment]
Oh, sure! You can kill it with fire! We migrated away from it ages ago :) It was very complicated to maintain and very error prone.

**Comment by fujita** [comment]
Great, let's remove it.
https://github.com/osrg/gobgp/pull/1864

**Comment by pavel-odintsov** [comment]
Fine by me ;)
