### ISSUE TITLE
injecting multiple paths

### ISSUE THREAD

**Issue by damanloox** [osrg/gobgp#1879]
Is there any way of injecting/adding multiple paths...? I can't make it work (regardless of global.use-multiple-paths.config setting):
gobgp global rib -a ipv4 add 1.1.1.1/32 nexthop 9.9.9.8
gobgp global rib -a ipv4 add 1.1.1.1/32 nexthop 9.9.9.9

gobgp global rib
   Network              Next Hop             AS_PATH              Age        Attrs
*> 1.1.1.1/32           9.9.9.9                                   00:00:05   [{Origin: ?}]

**Comment by fujita** [comment]
Needs to use addpath feature
https://github.com/osrg/gobgp/blob/master/docs/sources/add-paths.md

The multiple path feature is unrelated
https://github.com/osrg/gobgp/blob/master/docs/sources/add-paths.md
