### ISSUE TITLE
ValidateAttribute() assumes only IPv4 for PathAttributeNextHop. Needs correct IPv6 Handling.

### ISSUE THREAD

**Issue by Arvinderpal** [osrg/gobgp#1893]
The following code applies the isClassDorE(p.Value) check to IPv6 next-hop values, and incorrectly throws the error  "invalid nexthop address" for valid IPv6 address. 

https://github.com/osrg/gobgp/blob/fa387c90650613bceaca6c6c90c8744405988f8c/pkg/packet/bgp/validate.go#L167

Quick fix is to modify isClassDorE() as so:  
`		isClassDorE := func(ip net.IP) bool {
			if ip.To4() == nil {
				return false
			}
			res := ip[0] & 0xe0
			return res == 0xe0
		}`

**Comment by fujita** [comment]
Can you send a pull request of the quick fix?

**Comment by Arvinderpal** [comment]
I would love to however my company policy currently prohibits me from doing so. I hope to have permissions within a couple of weeks and can do  so  then. Thank you.

**Comment by fujita** [comment]
Understood, then I'll do this time. Hopefully, you can next time.
