### ISSUE TITLE
IPv6 equivalent of NewPathAttributeNextHop needed. 

### ISSUE THREAD

**Issue by Arvinderpal** [osrg/gobgp#1894]
The func NewPathAttributeNextHop() assumes IPv4 next-hop addresses:
https://github.com/osrg/gobgp/blob/fa387c90650613bceaca6c6c90c8744405988f8c/pkg/packet/bgp/bgp.go#L5657

An equivalent func for IPv6 is desirable. Sticking to the convention used, it should be called: 
NewIPv6PathAttributeNextHop()

**Comment by fujita** [comment]
fixed
