### ISSUE TITLE
Slack Link Gives 404 Error

### ISSUE THREAD

**Issue by aaglenn** [osrg/gobgp#1906]
404 Not Found: Requested route ('slackin-gobgp.mybluemix.net') does not exist.

README.md should be updated to reflect new url https://gobgp.slack.com/

**Comment by fujita** [comment]
we use slackin-gobgp.mybluemix.net for slackin
https://github.com/rauchg/slackin

Seems that bluemix.net is unstable nowadays so let's try now.sh instead.
https://github.com/osrg/gobgp/commit/9d9061497330afc1f0cbc612cd52a7358a8c76ac
