### ISSUE TITLE
Minor "getting started" issue

### ISSUE THREAD

**Issue by davmaz** [osrg/gobgp#1911]
After
$ go get -u github.com/golang/dep/cmd/dep
$ go get github.com/osrg/gobgp
$ cd $GOPATH/src/github.com/osrg/gobgp && dep ensure

in order for the next step to proceed, the user needs to 
**go install**

This with gobgpd in the PATH the next step in the getting started will run.

**Comment by fujita** [comment]
I moved the above description to the development guide:
https://github.com/osrg/gobgp/blob/master/BUILD.md

For developers, I guess that the next step isn't necessary.
