### ISSUE TITLE
GoBGP can't connect to FRR API (version 6.0)

### ISSUE THREAD

**Issue by joeyqiao12138** [osrg/gobgp#1912]
Hello,

I'm using the GoBGP and FRR to set up MPLS-VPN in Centos 7, with the last step, I found PE received routes from CE and import to vpnv4, it was assigned label 0. Then I found a solution was connect to FRR API, but there was an error happened. The FRR's version I installed is 6.0 and zebra is the same version, and the error displayed below, please help!

{"level":"info","msg":"gobgpd started","time":"2018-12-05T22:45:08+08:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2018-12-05T22:45:08+08:00"}
{"Error":"read unix @-\u003e/var/run/frr/zserv.api: read: connection reset by peer","Topic":"Zebra","level":"error","msg":"failed to read header","time":"2018-12-05T22:45:08+08:00"}
{"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 4. going to retry another version...","time":"2018-12-05T22:45:08+08:00"}
{"Error":"read unix @-\u003e/var/run/frr/zserv.api: read: connection reset by peer","Topic":"Zebra","level":"error","msg":"failed to read header","time":"2018-12-05T22:45:08+08:00"}
{"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 2. going to retry another version...","time":"2018-12-05T22:45:08+08:00"}
{"Error":"read unix @-\u003e/var/run/frr/zserv.api: read: connection reset by peer","Topic":"Zebra","level":"error","msg":"failed to read header","time":"2018-12-05T22:45:08+08:00"}
{"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 3. going to retry another version...","time":"2018-12-05T22:45:08+08:00"}
{"Error":"read unix @-\u003e/var/run/frr/zserv.api: read: connection reset by peer","Topic":"Zebra","level":"error","msg":"failed to read header","time":"2018-12-05T22:45:08+08:00"}
{"Topic":"Zebra","level":"warning","msg":"cannot connect to Zebra with message version 4. going to retry another version...","time":"2018-12-05T22:45:08+08:00"}
{"level":"fatal","msg":"failed to set zebra config: read unix @-\u003e/var/run/frr/zserv.api: read: connection reset by peer","time":"2018-12-05T22:45:08+08:00"}

**Comment by joeyqiao12138** [comment]
Add gobgp-config:

[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/frr/zserv.api"
    version = 5
    mpls-label-range-size = 100

**Comment by irino** [comment]
I am a maintainer of Zebra API for GoBGP. GoBGP mainline does not have the configuration "mpls-label-range-size" in zebra.config. I have implemented ZAPI6 on GoBGP, however I haven't implemented MPLS related API on ZAPI6 for GoBGP currently.

**Comment by irino** [comment]
You should use "version = 6" on the latest source code. FRR version 6 uses ZAPI6. 
Or, You should use "version = 4" on the latest release which does not include my source code for ZAPI5 and 6. FRR version 3 and 4 uses ZAPI4.

**Comment by joeyqiao12138** [comment]
Hello,

I installed FRR 3.0.3 instead of FRR 6.0, and GoBGP connected to FRR API successfully, but the vpnv4 routes added to default ipv4 forwarding table, why not vrf forwarding table? I think this is an error. How can I solve it?

**Comment by irino** [comment]
I committed changes PR1992 (https://github.com/osrg/gobgp/pull/1992) which includes configuration "mpls-label-range-size = 100" and it prevent to install vpnv4 route to default table. Please use combination of master branch of gobgp and frr6.0.x.

**Comment by fujita** [comment]
@joeyqiao12138 if you still hit the problem, please create a new issue.
