### ISSUE TITLE
multiple nlri in a single mp_reach_nlri are not supported

### ISSUE THREAD

**Issue by rahil2508** [osrg/gobgp#1936]
I'm using GoBGP v2.0.0 to connect with Juniper MX device to run EVPN with VXLAN. I get the underlay BGP neighborship established for inet-unicast address family, I get the overlay neighborship established for evpn address family. Output of gobgp neighbor indicates routed received AND accepted by GoBGP -

$ gobgp neighbor
Peer           AS  Up/Down State       |#Received  Accepted
172.16.1.1  10000 00:09:24 Establ      |       12        12
192.168.1.1 10000 00:10:11 Establ      |        2         2

[192.168.1.1 is underlay, 172.16.1.1 is overlay]

But when I check gobgp global rib -a evpn, I get this error -

$ gobgp global rib -a evpn
multiple nlri in a single mp_reach_nlri are not supported

I took some captures and saw that the JunOS sends multiple UPDATE messages with multiple NLRI inside one packet -

![image](https://user-images.githubusercontent.com/23511616/51000051-2a3bac00-14e9-11e9-8bdc-2fe233e23aa9.png)

Is this a bug in GoBGP or can I change something on the JunOS side to get around this?

**Comment by fujita** [comment]
Please reopen if 2.X versions don't work.
