### ISSUE TITLE
gobgpd 2.0 add vrf with frr-6.0.2 panic

### ISSUE THREAD

**Issue by DKCopy** [osrg/gobgp#1941]
**### gobgpd.conf**
[global.config]
  as = 243
  router-id = "55.55.55.55"
 
[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/zserv.api"
    version = 6
 
[[neighbors]]
  [neighbors.config]
    neighbor-address = "20.243.243.243"
    peer-as = 243
  [neighbors.transport.config]
    local-address = "55.55.55.55"
    [[neighbors.afi-safis]]
        [neighbors.afi-safis.config]
        afi-safi-name = "ipv4-unicast"
    [[neighbors.afi-safis]]
        [neighbors.afi-safis.config]
        afi-safi-name = "l3vpn-ipv4-unicast"
[[vrfs]]
  [vrfs.config]
    name = "blue"
    id = 28
    rd = "111:1"
    both-rt-list = ["111:11"]

**### linux kernel 4.14.6 and vrf config**
ip -d l show blue 
28: blue: <NOARP,MASTER,UP,LOWER_UP> mtu 65536 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 4e:7f:7a:71:11:10 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    vrf table 210 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 

**### gobgpd -l debug -p run log**

INFO[0000] gobgpd started                               
INFO[0000] Finished reading the config file              Topic=Config
DEBU[0000] send command to zebra                         Body="route_type: FRR_ZAPI6_ROUTE_BGP, instance :0" Header="{10 254 6 0 FRR_ZAPI6_HELLO}" Topic=Zebra
DEBU[0000] send command to zebra                         Body="<nil>" Header="{10 254 6 0 FRR_ZAPI6_ROUTER_ID_ADD}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{66 254 6 0 FRR_ZAPI6_VRF_ADD} data: [254 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 68 101 102 97 117 108 116 45 73 80 45 82 111 117 116 105 110 103 45 84 97 98 108 101 0 0 0 0 0 0 0 0 0 0 0 0]}" Topic=Zebra
INFO[0000] success to connect to Zebra with message version 6.  Topic=Zebra
DEBU[0000] send command to zebra                         Body="<nil>" Header="{10 254 6 0 FRR_ZAPI6_INTERFACE_ADD}" Topic=Zebra
DEBU[0000] add vrf                                       ExportRt="[111:11]" ImportRt="[111:11]" Key=blue Rd="111:1" Topic=Vrf
DEBU[0000] create Destination                            Nlri="243:111:11" Topic=Table
DEBU[0000] computeKnownBestPath knownPathList: 1         Topic=Table
INFO[0000] Peer 20.243.243.243 is added                 
INFO[0000] Add a peer configuration for:20.243.243.243   Topic=Peer
DEBU[0000] read message from zebra                       Message="&{{66 254 6 28 FRR_ZAPI6_VRF_ADD} data: [210 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 98 108 117 101 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{15 254 6 0 FRR_ZAPI6_CAPABILITIES} data: [1 0 0 0 16]}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{16 254 6 0 FRR_ZAPI6_ROUTER_ID_UPDATE} id: 192.168.2.55/32}" Topic=Zebra
DEBU[0000] IdleHoldTimer expired                         Duration=0 Key=20.243.243.243 Topic=Peer
DEBU[0000] state changed                                 Key=20.243.243.243 Topic=Peer new=BGP_FSM_ACTIVE old=BGP_FSM_IDLE reason=idle-hold-timer-expired
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: Loopback1, idx: 29, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: fa:01:70:fe:e2:b1}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{25 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 29, flags: UNNUMBERED, addr: 55.55.55.55/32}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 29, flags: , addr: fe80::f801:70ff:fefe:e2b1/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: bond0, idx: 13, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | MASTER | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 20000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:55:11:74}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{25 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 13, flags: , addr: 10.0.66.68/24}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 13, flags: , addr: fe80::290:bff:fe55:1174/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: br0, idx: 21, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:53:ce:08}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{25 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 21, flags: , addr: 192.168.2.55/24}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 21, flags: , addr: fe80::290:bff:fe53:ce08/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: dummy0, idx: 4, status: ACTIVE, flags: BROADCAST | NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 2e:54:9a:93:9e:87}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: erspan0, idx: 16, status: ACTIVE|LINKDETECTION, flags: BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1450, mtu6: 1450, bandwidth: 0, linktype: LINK_TYPE_ETHER}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth0, idx: 2, status: ACTIVE, flags: UP | BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 4294967295, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:53:ce:08}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth1, idx: 3, status: ACTIVE, flags: UP | BROADCAST | RUNNING | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 100, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:53:ce:09}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 3, flags: , addr: fe80::290:bff:fe53:ce09/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth2, idx: 25, status: ACTIVE, flags: UP | BROADCAST | RUNNING | SLAVE | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 10000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:55:11:74}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth3, idx: 6, status: ACTIVE, flags: UP | BROADCAST | RUNNING | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 10000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:55:11:75}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 6, flags: , addr: fe80::290:bff:fe55:1175/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth4, idx: 27, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | SLAVE | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 10000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:55:11:74}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth5, idx: 8, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 10000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:55:11:77}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 0 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 8, flags: , addr: fe80::290:bff:fe55:1177/64}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth6, idx: 26, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 4294967295, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:67:85:21}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth8, idx: 11, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 4294967295, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:67:85:23}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: eth9, idx: 12, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 4294967295, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:67:85:24}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: gre0, idx: 14, status: ACTIVE|LINKDETECTION, flags: NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1476, mtu6: 1476, bandwidth: 0, linktype: LINK_TYPE_IPGRE}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: gretap0, idx: 15, status: ACTIVE|LINKDETECTION, flags: BROADCAST | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1462, mtu6: 1462, bandwidth: 0, linktype: LINK_TYPE_ETHER}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: ip6gre0, idx: 18, status: ACTIVE|LINKDETECTION, flags: NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1448, mtu6: 1448, bandwidth: 0, linktype: LINK_TYPE_UNKNOWN}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: ip6tnl0, idx: 17, status: ACTIVE|LINKDETECTION, flags: NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1452, mtu6: 1452, bandwidth: 0, linktype: LINK_TYPE_IPIP6}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: lo, idx: 1, status: ACTIVE, flags: UP | LOOPBACK | RUNNING, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 65536, mtu6: 65536, bandwidth: 0, linktype: LINK_TYPE_LOOPBACK}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{74 254 6 0 FRR_ZAPI6_INTERFACE_ADD} name: sit0, idx: 19, status: ACTIVE|LINKDETECTION, flags: NOARP, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 1480, mtu6: 1480, bandwidth: 0, linktype: LINK_TYPE_SIT}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 28 FRR_ZAPI6_INTERFACE_ADD} name: blue, idx: 28, status: ACTIVE|LINKDETECTION|VRF_LOOPBACK, flags: UP | RUNNING | NOARP | MASTER, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 0, mtu: 65536, mtu6: 65536, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 4e:7f:7a:71:11:10}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{80 254 6 28 FRR_ZAPI6_INTERFACE_ADD} name: eth7, idx: 10, status: ACTIVE|LINKDETECTION, flags: UP | BROADCAST | RUNNING | MULTICAST, ptm_enable: PTM_ENABLE_OFF, ptm_status: PTM_STATUS_UNKNOWN, metric: 0, speed: 10000, mtu: 1500, mtu6: 1500, bandwidth: 0, linktype: LINK_TYPE_ETHER, mac: 00:90:0b:67:85:22}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{25 254 6 28 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 10, flags: , addr: 20.244.48.2/24}" Topic=Zebra
DEBU[0000] read message from zebra                       Message="&{{49 254 6 28 FRR_ZAPI6_INTERFACE_ADDRESS_ADD} idx: 10, flags: , addr: fe80::290:bff:fe67:8522/64}" Topic=Zebra
DEBU[0014] Accepted a new passive connection from:20.243.243.243  Topic=Peer
DEBU[0014] stop connect loop                             Key=20.243.243.243 Topic=Peer
DEBU[0014] state changed                                 Key=20.243.243.243 Topic=Peer new=BGP_FSM_OPENSENT old=BGP_FSM_ACTIVE reason=new-connection
DEBU[0014] state changed                                 Key=20.243.243.243 Topic=Peer new=BGP_FSM_OPENCONFIRM old=BGP_FSM_OPENSENT reason=open-msg-received
INFO[0014] Peer Up                                       Key=20.243.243.243 State=BGP_FSM_OPENCONFIRM Topic=Peer
DEBU[0014] state changed                                 Key=20.243.243.243 Topic=Peer new=BGP_FSM_ESTABLISHED old=BGP_FSM_OPENCONFIRM reason=open-msg-negotiated
DEBU[0014] received update                               Key=20.243.243.243 Topic=Peer attributes="[]" nlri="[]" withdrawals="[]"
DEBU[0014] EOR received                                  AddressFamily=ipv4-unicast Key=20.243.243.243 Topic=Peer
DEBU[0014] received update                               Key=20.243.243.243 Topic=Peer attributes="[{Origin: ?}  {Med: 0} {LocalPref: 100} {Extcomms: [111:11]} {MpReach(l3vpn-ipv4-unicast): {Nexthop: 20.243.243.243, NLRIs: [111:1:20.0.40.0/24]}}]" nlri="[]" withdrawals="[]"
DEBU[0014] create Destination                            Nlri="111:1:20.0.40.0/24" Topic=Table
DEBU[0014] computeKnownBestPath knownPathList: 1         Topic=Table
DEBU[0014] From same AS, ignore.                         Data="{ 111:1:20.0.40.0/24 | src: { 20.243.243.243 | as: 243, id: 30.0.101.1 }, nh: 20.243.243.243 }" Key=20.243.243.243 Topic=Peer
DEBU[0014] send command to zebra                         Body="nexthop:{connected: 0, family: 2, prefix: 20.243.243.243}" Header="{10 254 6 0 FRR_ZAPI6_NEXTHOP_REGISTER}" Topic=Zebra
DEBU[0014] send command to zebra                         Body="type: FRR_ZAPI6_ROUTE_BGP, instance: 0, flags: FLAG_INTERNAL|FLAG_IBGP, message: 9, safi: SAFI_UNICAST, prefix: 20.0.40.0/24, src_prefix: <nil>/0, nexthops[0]: type: NEXTHOP_TYPE(0), gate: 20.243.243.243, ifindex: 0, distance: 0, metric: 0, mtu: 0, tag: 0" Header="{10 254 6 0 FRR_ZAPI6_ROUTE_ADD}" Topic=Zebra
DEBU[0014] send command to zebra                         Body="nexthop:{connected: 0, family: 2, prefix: 20.243.243.243}" Header="{10 254 6 0 FRR_ZAPI6_NEXTHOP_REGISTER}" Topic=Zebra
DEBU[0014] send command to zebra                         Body="type: FRR_ZAPI6_ROUTE_BGP, instance: 0, flags: FLAG_INTERNAL|FLAG_IBGP, message: 9, safi: SAFI_UNICAST, prefix: 20.0.40.0/24, src_prefix: <nil>/0, nexthops[0]: type: NEXTHOP_TYPE(0), gate: 20.243.243.243, ifindex: 0, distance: 0, metric: 0, mtu: 0, tag: 0" Header="{10 254 6 28 FRR_ZAPI6_ROUTE_ADD}" Topic=Zebra
DEBU[0014] send command to zebra                         Body="nexthop:{connected: 0, family: 2, prefix: 20.243.243.243}" Header="{10 254 6 28 FRR_ZAPI6_NEXTHOP_REGISTER}" Topic=Zebra
DEBU[0014] received update                               Key=20.243.243.243 Topic=Peer attributes="[{MpUnreach(l3vpn-ipv4-unicast): End-of-Rib}]" nlri="[]" withdrawals="[]"
DEBU[0014] EOR received                                  AddressFamily=l3vpn-ipv4-unicast Key=20.243.243.243 Topic=Peer
DEBU[0014] read message from zebra                       Message="&{{26 254 6 0 FRR_ZAPI6_NEXTHOP_UPDATE} family: 2, prefix: 20.243.243.243, distance: 0, metric: 0}" Topic=Zebra
panic: runtime error: index out of range

goroutine 22 [running]:
github.com/osrg/gobgp/internal/pkg/zebra.decodeNexthopsFromBytes(0xc0001a49e8, 0xc00025f40f, 0xf, 0xf, 0xc000250602, 0x4, 0x1b, 0x40d2c8)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:2239 +0xa49
github.com/osrg/gobgp/internal/pkg/zebra.(*NexthopUpdateBody).DecodeFromBytes(0xc0001a4990, 0xc00025f400, 0x1e, 0x1e, 0xc30c06, 0x7ffff4550201, 0xc0002615a0)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:2593 +0x299
github.com/osrg/gobgp/internal/pkg/zebra.(*Message).parseFrrZapi6Message(0xc0002615a0, 0xc00025f400, 0x1e, 0x1e, 0x1e, 0x1e)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:2769 +0xb2
github.com/osrg/gobgp/internal/pkg/zebra.ParseMessage(0xc000263420, 0xc00025f400, 0x1e, 0x1e, 0x1e, 0x1e, 0x0)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:2779 +0x90
github.com/osrg/gobgp/internal/pkg/zebra.NewClient.func2(0xc0001f8fc0, 0xc0000cbfb8, 0x0)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:1061 +0x64f
github.com/osrg/gobgp/internal/pkg/zebra.NewClient.func3(0xc0001f8fc0, 0xc00022cf90)
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:1095 +0x51
created by github.com/osrg/gobgp/internal/pkg/zebra.NewClient
        /home/fujita/go/src/github.com/osrg/gobgp/internal/pkg/zebra/zapi.go:1092 +0x24e

**Comment by irino** [comment]
@DKCopy @fujita I'm sorry for that you got error from my source code.
The panic happens on 
https://github.com/osrg/gobgp/blob/1e133bd50141bb294dd63cd0f9f70f69c2b60422/internal/pkg/zebra/zapi.go#L2239
My source code access slices which hasn't make capacity by "make". I forgot it.
Following code is temporary fix code. But, I haven't tested because I don't have MPLS test environment now.
https://github.com/osrg/gobgp/compare/master...irino:zapi6
If @DKCopy test my fix code in your environment and it run without panic, I will send PR.

Anyway, my source code was not tested with MPLS functionality when I sent PR about zapi5 and 6.

**Comment by fujita** [comment]
@DKCopy please reopen if the latest master doesn't work.

**Comment by DKCopy** [comment]
> @DKCopy please reopen if the latest master doesn't work.

sorry to later, I had test it and it works ok
