### ISSUE TITLE
Issues with import-policy-list

### ISSUE THREAD

**Issue by damirsamardzic** [osrg/gobgp#1943]
Hi, I'm facing an issue that global import-policy-list is not applied. Now I tried to run the [gobgp-tutorial](https://github.com/shusugmt/gobgp-tutorial) setup and see the same issue there as well. For example, community tags are not applied, local routes provided by zebra are still visible (not filtered by zebra-import-my-prefixes) etc.

Tested with release v2.0.0 binaries as well as manual build from master.

If someone has a hint or could re-run the tutorial environment and verify g2 router's gobgp.conf, I would appreciate that.

**Comment by fujita** [comment]
You tries to set up route server clients? If so, no global policy are applied to route server clients.

**Comment by fujita** [comment]
If you set up non route server clients, you might hit the following bug:
https://github.com/osrg/gobgp/issues/1949

If so, please try the latest master.

**Comment by damirsamardzic** [comment]
That bug looks related to my issue (next-hop didn't work for me as well). I have just tested the master and the issue is solved. Thanks a lot! 

I will close this issue, feel free to mark it as duplicate if needed.
