### ISSUE TITLE
Why is apiutil internal?

### ISSUE THREAD

**Issue by rcgoodfellow** [osrg/gobgp#1956]
I need to make a fairly basic API call to `AddPath`. This involves creating a `Path` object in the format the gRPC API expects. To do this, I took a look at the [gobgp client code](https://github.com/osrg/gobgp/blob/master/cmd/gobgp/global.go#L1279) which uses `apiutil.NewPath` to perform marshaling of the NLRI and attributes. This would seem to be critical to using the API but is disallowed from code that is not in the gobgp source tree, why? Did i miss some other higher level code path for using this part of the API?

**Comment by fujita** [comment]
That's the workaround to handle the new APIs with the old code. It should be updated but overdue. You can find an example with the new APIs:
https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md

**Comment by rcgoodfellow** [comment]
Hi @fujita, the new APIs referenced seem to be about talking to a process-embedded GoBGP server. My question is about talking to a GoBGP instance through the gRPC API from a separate process which may be on a different machine all together.

**Comment by fujita** [comment]
Same. Both APIs (the gRPC and native library) use the structures generated by protobuf. You don't need to use apiutil.NewPath. You can simply build the structures generated by protobuf.

**Comment by leoluk** [comment]
`MarshalFlowSpecRules` for instance, would be very useful to have. What's the reason for internal-ness? No API stability guarantees?

**Comment by fujita** [comment]
The structures generated by protobuf and the APIs with them are written in stone. They should be used. Converting stuff in pkg/bgp to them is work around for a mistake in the past.

**Comment by netixx** [comment]
I am using the API to _read_ routes from gobgp, and I am having difficulties parsing the return values, mostly form the attributes.

I need to have a nested type switch to extract the values, which is often copy/paste for apiutil (e.g. `unmarshalExComm`).

With some refactoring, it could be a good golang library to help with the API.

**Comment by alistairking** [comment]
I'm having the same problem as @netixx -- parsing the API Path structure into some other format has required me to copy/paste hundreds of lines of code from apiutil.
If there's interest, I'd be happy to help with the effort needed to get this code publicly exposed.

**Comment by fujita** [comment]
Why not using the API Path structures directly instead of converting them into some?

**Comment by alistairking** [comment]
Maybe it's easier to reason in terms of the gobgp CLI since this should have a similar use case -- parsing API Path structures into a human readable format -- and it's where I started from as a reference for the parsing I wanted to do.

If I look at where it handles outputting paths received from MonitorTable, it seems to use the internal apiutil code that I'm referring to: https://github.com/osrg/gobgp/blob/8d0a8b0ffa696a3838740fec7accc54ccfb452ab/cmd/gobgp/monitor.go#L32

**Comment by fujita** [comment]
The API become public.
