### ISSUE TITLE
I want to apply the mrt-dump setting by reloading instead of restarting

### ISSUE THREAD

**Issue by lch7829** [osrg/gobgp#1957]
If neighbors.config, after editing gobgp.conf,can be applied with "systemctl reload gobgpd".
But mrt-dump.config can not be applied with "systemctl reload gobgpd".
I can't use "systemctl restart gobgpd".

How do I apply mrt-dump.confg without affecting gobgpd.services?

**Comment by fujita** [comment]
Needs to update the code to handle the diff of mrt config. But how should gobgpd handle a file written by the previous configuration? Just stop writing? Wait for the next interval to write then stop? I'm not sure that  it's a good idea to support the feature.

**Comment by lch7829** [comment]
Thank you for your reply.
Me,too. I'm out of ideas.
I want to try another method, please tell me.

I want to ask the command corresponding to the setting below
I can not write the continuation of this command.

~$gobgp mrt dump rib global  ??? ??? ???
------------------------------
[[mrt-dump]]
  [mrt-dump.config]
    dump-type = "table"
    file-name = "/tmp/table.dump"
    dump-interval = 60
------------------------------

gobgpd version is 1.33

**Comment by lch7829** [comment]
I did not understand even referring to this site.
And I think there is no option like [format] or [outdir].

https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md
https://github.com/osrg/gobgp/blob/master/docs/sources/mrt.md

**Comment by fujita** [comment]
Oops, the description is obsolete. You can write the code to support such feature with the APIs.

**Comment by lch7829** [comment]
Thank you.
