### ISSUE TITLE
UseMultiplePaths and MonitorTable unable to receive all paths

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1958]
Hi,

currently MonitorTable callback from server.go accepts only a single Path which makes handling multiple paths impossible.

I would propose to change the API so that a list of paths is sent instead. 

i.e. change from func (path *api.Path) to func (path []*api.Path)

I will submit a PR for the changes in server.go, I don't like to touch the API (protobuf files).

**Comment by fujita** [comment]
The proposal looks fine but MonitorTable API is public so we cannot change it without the major version update. I prefer that callers work around.

**Comment by Thoro** [comment]
Does the major version increase affect only the GRPC interface, or also the programming interface?

Then I guess for version 3 this could be a possible upgrade.

**Comment by fujita** [comment]
Both. The version 2 was released last month. I don't think that it's a good idea to release v3.

**Comment by Thoro** [comment]
it definitely is not a good idea ;)

I will keep my fork active, since I need to use the functionality. And you could tag it / mark it for whenever a bigger API change is necessary.

**Comment by fujita** [comment]
surely, I've added v3 label.

**Comment by cnjinshuai** [comment]
Thanks, I also encountered the same problem. MonitorTable callback accepts only a path, I can't identify if it is one of ecmp paths.

**Comment by fujita** [comment]
fixed
