### ISSUE TITLE
GoBGP CLI - Policy Prefix is not rendered correctly

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1960]
I have defined a prefix set for a policy, but ./gobgp policy prefix only shows an empty result.

The issue might be that the DefinedSet has two properties List and Prefixes.
For the prefix set only the Prefixes are used. (grpc_server.go:892)
But the cli utility only uses the list property. (cmd/gobgp/policy.go:181)

Version v2.1.0

**Comment by fujita** [comment]
Thanks a lot! This is a 2.X regression. I've pushed your fix with change the output same to 1.X versions.
