### ISSUE TITLE
Panic if you call gobgp neigh adj-in

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1965]
Version 2.1.5 - looks like it's unexpected input

gobgp neigh adj-in
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b9f1b]

goroutine 1 [running]:
main.showNeighbor(0xc000093f50, 0x1, 0x1, 0xc000034078, 0xc42600)
	/data/go/src/github.com/osrg/gobgp/cmd/gobgp/neighbor.go:237 +0x15b
main.newNeighborCmd.func7(0xc00021fb00, 0xc000093f50, 0x1, 0x1)
	/data/go/src/github.com/osrg/gobgp/cmd/gobgp/neighbor.go:1475 +0x17b
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).execute(0xc00021fb00, 0xc000093f00, 0x1, 0x1, 0xc00021fb00, 0xc000093f00)
	/data/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:653 +0x2af
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f58c0, 0xc000226d80, 0xc000226fc0, 0xc000227680)
	/data/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:728 +0x2cc
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000f58c0, 0x4072b0, 0xc0000c0058)
	/data/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/data/go/src/github.com/osrg/gobgp/cmd/gobgp/main.go:33 +0x63

**Comment by Thoro** [comment]
I also noticed when I checked 1.33, that the gobgp neigh command returned all neighbors, now it does not anymore. (did not fix this in my PR)

**Comment by fujita** [comment]
fixed
