### ISSUE TITLE
EOF when calling gobgp global policy (import|export)

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1966]
Hi,

not sure what's going on here:

gobgp global policy
EOF

gobgp global policy export
EOF

gobgp global policy import
EOF

Can you reproduce this?

**Comment by Thoro** [comment]
I figured out that this happens if there's no global Policy, an error message akin to  "The are no policy assignments" would be better

**Comment by fujita** [comment]
Thanks for the report! I guess that this is another 2.0 regression in the CLI (looks like other two issues too). I'll take care of them.

**Comment by fujita** [comment]
fixed.
