### ISSUE TITLE
v2 gobgp neigh takes a long time

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1975]
Next regression I believe, v1.33 does not request the advertised count for global lookup v2.0 requests the advertised count, but never uses it!

https://github.com/osrg/gobgp/blob/e87bfcba68f4b5a6673162a3f9b6219f45ada38a/cmd/gobgp/neighbor.go#L62

getNeighbors is never used anywhere else than showNeighbors, and showNeighbors doesn't use advertised

**Comment by fujita** [comment]
Thanks a lot for the report! I fixed getNeighbors() and update the code using ListPeer()  to use it.
