### ISSUE TITLE
Unable to download pkg/server

### ISSUE THREAD

**Issue by gedOHub** [osrg/gobgp#1978]
Hello,

I'm trying to integrate GoBGP to my project by example https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md.

When I try to download github.com/osrg/gobgp/pkg/server with `go get` I'm getting an error:
```
github.com/osrg/gobgp/pkg/server
# github.com/osrg/gobgp/pkg/server
src\github.com\osrg\gobgp\pkg\server\sockopt.go:31:9: undefined: setListenTcpTTLSockopt
src\github.com\osrg\gobgp\pkg\server\util.go:87:12: undefined: syscall.SetsockoptString
src\github.com\osrg\gobgp\pkg\server\util.go:99:37: cannot use int(s) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt
```

User command:
```
go get -v github.com/osrg/gobgp/pkg/server
```

Golang version:
```
go version go1.11.4 windows/amd64
```

Running on Windows 10

**Comment by fujita** [comment]
Windows is not supported. If you add a pull request to support Windows, I'm happy to push it.

**Comment by gedOHub** [comment]
@fujita Do you have any recommendations for setting up developing environment for GoBGP?

**Comment by fujita** [comment]
Linux
