### ISSUE TITLE
IPv6 subnet nexthop over API

### ISSUE THREAD

**Issue by gedOHub** [osrg/gobgp#1981]
Hi,

I was able to add ipv4 routes to GoBGP via API using NextHopAttribute.
Once I try to use the same method for IPv6 I get an error:

```
invalid nexthop address: 2001:db8:0:f101::5
```

Which API call I should use to set next hop for the ipv6 subnet?

My used code to add nexthop for IPv4 subnet:
```
...
hop, _ := ptypes.MarshalAny(&api.NextHopAttribute{
   //NextHop: network.GetNextHop(myid, addRoute.Nexthop),
   NextHop: addRoute.Address,
})
// Adding next hop inforamtion to atrributes
attrs = append(attrs, hop)
...
// Adding route to GoBGP
_, err = bgp.AddPath(
   context.Background(),
      &api.AddPathRequest{
         Path: &api.Path{
            Family: &family,
            Nlri:   route,
            Pattrs: attrs,
        },
    },
)
...
```

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/internal/pkg/apiutil/attribute_test.go#L241

**Comment by gedOHub** [comment]
@fujita Thank you. 
Do you have an example of how to add community attribute to the route?

**Comment by fujita** [comment]
I guess that you can find a hint in the above file.

**Comment by gedOHub** [comment]
@fujita Please help.
I have made **api.MpReachNLRIAttribute** structure, but I can't locate any server method for obtaining it.
Could you direct my how to adding IPv6 route?

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md

**Comment by gedOHub** [comment]
Thank you @fujita ! 

I already owe you a beer!
Contact me and we will figure it out :)

I have another communities question. When using communities (according your example) I get communities like: 
```
[{Origin: i} {Communities: 0:100, 0:200}]
```
I want to get communities like. 666- shoule be my ASN number:
```
[{Origin: i} {Communities: 666:100, 666:200}]
```
I have tried using extended communites, result is:
```
[{Origin: i} {Extcomms: [0.666:100], [0.666:200]}]
```
Is it possible to achieve this?

**Comment by gedOHub** [comment]
I just figured out. 
I needed to use `TwoOctetAsSpecificExtended`

**Comment by gedOHub** [comment]
@fujita 
Could you update example https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md how to use communities?

This example shows how to get **0:$COMMUNITIE** community. I have tried to use `TwoOctetAsSpecificExtended` to get **$ASN:$COMMUNITIE**. If connecting GoBGP to GoBGP everything looks great. Once Conencted to Juniper MX router getting error like; 
`unknown iana 0`

Once I add the route with communities from gobgp client everything looks great.
I was unable to trace back how client adds route with communities, so I could add it by my self.

Could you add snipped how to add a route with communities like **$ASN:$COMMUNITIE**?
