### ISSUE TITLE
AddPath()'ed path doesn't get source_asn from global config

### ISSUE THREAD

**Issue by tamihiro** [osrg/gobgp#1984]
In previous versions, AddPath() used to set source_asn to each path in the arg list from global config. But it doesn't do so any more, possibly since commit 5d008d7. Now every API request needs to set source_asn in the Path message inside AddPathRequest. To me it seems a little odd, and it's tempting to give the following change, which causes server_test.go to fail.
```
--- a/internal/pkg/table/path.go
+++ b/internal/pkg/table/path.go
@@ -386,6 +386,10 @@ func (path *Path) GetRouteFamily() bgp.RouteFamily {
        return bgp.AfiSafiToRouteFamily(path.OriginInfo().nlri.AFI(), path.OriginInfo().nlri.SAFI())
 }
 
+func (path *Path) SetSource(source *PeerInfo) {
+       path.OriginInfo().source = source
+}
+
 func (path *Path) GetSource() *PeerInfo {
        return path.OriginInfo().source
 }
--- a/pkg/server/server.go
+++ b/pkg/server/server.go
@@ -1862,6 +1862,12 @@ func (s *BgpServer) AddPath(ctx context.Context, r *api.AddPathRequest) (*api.Ad
                if err != nil {
                        return err
                }
+               if path.GetSource().AS == 0 {
+                       path.SetSource(&table.PeerInfo{
+                               AS:      s.bgpConfig.Global.Config.As,
+                               LocalID: net.ParseIP(s.bgpConfig.Global.Config.RouterId).To4(),
+                       })
+               }
                err = s.addPathList(r.VrfId, []*table.Path{path})
                if err != nil {
                        return err
```
I can't suggest anything at the moment because I don't know what led you to decide the above mentioned commit to be made. But again it seems a little odd, and I'm curious how other users see this.

**Comment by tamihiro** [comment]
Thanks for directing me to these previous issues.
> API request doesn't need to set source_asn in the Path, right?

Honestly I'm not sure.. To me being a conventional network operator, it makes sense when a BGP router originates a path, be it via CLI or API, the source ASN of the path is that router's ASN. Although I know GoBGP is not anywhere near a conventional bgp daemon, but still... wrt @cstockton's comment [here](https://github.com/osrg/gobgp/issues/1740#issuecomment-398508233):
> I propose that under all circumstances a valid path returned by `GetPath` should be removable as an argument in `DeletePath`, i.e. this never fails when `GetPath` succeeds: `DeletePath(GetPath())`.

I'm not sure about that either. :confused: 
As a coder I think any path my app (client of GoBGP) has successfully made the server originate with `AddPath` should be removable by `DeletePath`, and it's my app's job to keep track of all the paths it has requested.
> if a user doesn't specify the source information, returning zero is reasonable, I thought.

If you and other users see it reasonable, I have absolutely no objection. After all, my app only needs to include source_asn value in Path message.

**Comment by fujita** [comment]
I'm not sure everyone think that this is reasonable. I guess that there isn't the correct answer for everyone. I can say, if an application cares about source_asn, it needs to set explicitly.

**Comment by tamihiro** [comment]
Fair enough.
Is there any API call for an app to get the server's asn in global config which it can then set explicitly in `AddPath`?

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L2472
`GetBgp`?

**Comment by tamihiro** [comment]
Oh there it is. Thank you!
