### ISSUE TITLE
Regression v1.33 to v2.1.0 - Soft Reset Out does not send path withdrawls

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1986]
Previously a softresetout sent a withdraw for all filtered paths and send okay paths.

In v.2.1.0 the code to send the filtered paths is missing:

https://github.com/osrg/gobgp/blob/259d9b5264fa22165fdc66843cb00927c6c6fdf2/pkg/server/server.go#L2200
vs.
https://github.com/osrg/gobgp/blob/8e6bd4c7145de5a68c40246418500bf05af9ce39/server/server.go#L1853

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/pull/1910
Discussed here.

**Comment by Thoro** [comment]
Okay, then move discussion there.
