### ISSUE TITLE
ListPath ignores UseMultiPath option

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1988]
Hi,

just noticed that ListPath selects the bestPath via it's own logic (first available path) - not sure if the list is sorted, so if it is, that's okay

But, it fully ignores the UseMultiPaths configuration option, therefore ListPath always returns only 1 best Path

Possible Solution:

use the destinations functions to get the best path(s) GetBestPath, GetMultiBestPath

**Comment by fujita** [comment]
>just noticed that ListPath selects the bestPath via it's own logic (first available path) - not sure if the list is sorted, so if it is, that's okay

Always sorted. The first one is always the best.

**Comment by fujita** [comment]
fixed by the following the commit
https://github.com/osrg/gobgp/commit/49448ac67d61bf769e0b443a4dccd9972ebae117
