### ISSUE TITLE
clarify the behavior of route-server-client

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [osrg/gobgp#1990]
gobgp does not advertise routes added with `gobgp global rib add` to peers with `route-server-client` set

What is the intended behavior when `route-server-client` is set?
- do not include route server's ASN in as_path
- only propagate routes received from `route-server-client`?
- routes received from `route-server-client` not installed in local rib (`gobgp global rib` empty)

**Comment by fujita** [comment]
All the above are true. The behavior is supposed to be same as the router-server behavior of other BGP implementations like bird. You can find the details at:
https://www.rfc-editor.org/rfc/rfc7947.txt
