### ISSUE TITLE
Error occurs when install gobgp using “go get”

### ISSUE THREAD

**Issue by NetprogDong** [osrg/gobgp#1994]
Hi：
   I got an error when I'm trying to install gobgp on the 'go get' way.
   My OS is CentOS7, the kernel version is 3.10.0-957.el7.x86_64.
   My GOPATH is :
echo $GOPATH
/root/go
   My PATH is :
echo $PATH
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin:/usr/local/go/bin
   My golang  was installed in /usr/local/go.
   And I got the error:
go get github.com/osrg/gobgp/gobgpd
package github.com/osrg/gobgp/gobgpd: cannot find package "github.com/osrg/gobgp/gobgpd" in any of:
	/usr/local/go/src/github.com/osrg/gobgp/gobgpd (from $GOROOT)
	/root/go/src/github.com/osrg/gobgp/gobgpd (from $GOPATH)
go get github.com/osrg/gobgp/gobgp
package github.com/osrg/gobgp/gobgp: cannot find package "github.com/osrg/gobgp/gobgp" in any of:
	/usr/local/go/src/github.com/osrg/gobgp/gobgp (from $GOROOT)
	/root/go/src/github.com/osrg/gobgp/gobgp (from $GOPATH)
     Please don't hesitate to contact me if any information need to offer.

**Comment by fujita** [comment]
> go get github.com/osrg/gobgp/gobgpd

Hmm, which document you find the above command?

btw, what version of go?

**Comment by NetprogDong** [comment]
Hi,
the link of the document is blow：
http://networkstatic.net/gobgp-control-plane-evolving-software-networking/
And my go version is 1.12

**Comment by fujita** [comment]
Please use the binaries as the official README describes:
https://github.com/osrg/gobgp/releases/tag/v2.2.0

if you really need to compile the source for some reasons:
```
# go get github.com/osrg/gobgp/cmd/gobgp
# go get github.com/osrg/gobgp/cmd/gobgpd
```

**Comment by NetprogDong** [comment]
I install gobgp using the binary way, and it works well now, thanks.
