### ISSUE TITLE
i am using v2.2.0 tar.gz and get invalid request when making global rib summary call 

### ISSUE THREAD

**Issue by devendra-nvidia** [osrg/gobgp#1996]
$ ./gobgp global rib add 10.10.10.10/24 -a ipv4
$ ./gobgp global rib summary
rpc error: code = Unknown desc = invalid request
$ ./gobgp global rib del 10.10.10.10/24 -a ipv4

**Comment by fujita** [comment]
thanks for the report. I've just pushed a fix. Please try the latest master.
