### ISSUE TITLE
Need an option route-monitoring-enabled

### ISSUE THREAD

**Issue by KumaMonX** [osrg/gobgp#2000]
I don't want to monitor bgp route，could developers add an option "route-monitoring-enabled" just like "route-mirroring-enabled"?

It means I'd just need  Type PeerUp and Type PeedDown Notification，not Type Route Monitoring

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#52-monitor-neighbor-status
