### ISSUE TITLE
Is there a config option to specify BMP sysName and sysDescr?

### ISSUE THREAD

**Issue by KumaMonX** [osrg/gobgp#2003]
Is there a config option to specify BMP sysName and sysDescr?

According to documents（RFC 7854），BMP Initiation Message must contain sysDescr and sysName Information TLVs， but current release BMP feature didn't send this two mandatory TLVs.

Any plan to fix it?

**Comment by fujita** [comment]
No. You can see the current bmp configuration options:
https://github.com/osrg/gobgp/blob/master/tools/pyang_plugins/gobgp.yang#L560

there are many issues with higher priorities for me right now so a pull request for that is very welcome.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/commit/80ff3a325cbced352489fa4ea4b570e5f08062ef
now supported.
