### ISSUE TITLE
Add rib route in config file

### ISSUE THREAD

**Issue by Ezeon** [osrg/gobgp#2004]
Can a rib route be added via the configuration file? I couldn't find any information about this in the documentation or in the issue tracker.

I can add the route via cli with the following command, but I would like to do the same in the configuration file so the route is announce automatically when gobgp is started.
> gobgp global rib add 10.5.5.5/32 nexthop 10.4.4.4

**Comment by fujita** [comment]
No. The feature is not supported by intention.

**Comment by jdbarnes-isi** [comment]
Hello, I also want this feature. Is there a link to blog post or discussion about why this is intentionally not supported?  How about the proper way to automate this within the intended design? There is no documentation about that that I have found. Maybe I am looking in the wrong place.
