### ISSUE TITLE
Code generated error

### ISSUE THREAD

**Issue by JieJhih** [osrg/gobgp#2022]
I'm using ```protoc -I api/ --go_out=./api attribute.proto``` command to generate attribute.pb.go , then I got the errors.
<img width="2249"  src="https://user-images.githubusercontent.com/25479061/55003077-a175dc00-5012-11e9-8eb6-e17daee2176e.png">

**Comment by fujita** [comment]
Try the generator https://github.com/osrg/gobgp/blob/master/BUILD.md#changing-the-grpc-api
