### ISSUE TITLE
bgp connection can't recover after network partition until gr/llgr expire

### ISSUE THREAD

**Issue by qsqx** [osrg/gobgp#2026]
After network partition take place between bgp peers, both peers detect tcp session failure (before hold time expired), and consider the other peer is restarting. And when the network recover, both peers will send open message to each other with restarting flag unset, but will reject to establish by procedure
```
// RFC 4724 4.1
// To re-establish the session with its peer, the Restarting Speaker
// MUST set the "Restart State" bit in the Graceful Restart Capability
// of the OPEN message.
if fsm.pConf.GracefulRestart.State.PeerRestarting && cap.Flags&0x08 == 0 {
    log.WithFields(log.Fields{
        "Topic": "Peer",
        "Key":   fsm.pConf.State.NeighborAddress,
        "State": fsm.state.String(),
    }).Warn("restart flag is not set")
    // send notification?
    h.conn.Close()
    fsm.lock.Unlock()
    return bgp.BGP_FSM_IDLE, newfsmStateReason(fsmInvalidMsg, nil, nil)
}
```
Restarting flag is a constraint to restarting speaker in order to avoid waiting eor between restarting peers, and in this case when no body is restarting, we can advertising routing information regardless of whether eor is received, and drop stale routes after eor received. 
And in this function, just skip the judgement seems meet the expectation.

https://github.com/osrg/gobgp/pull/2024

**Comment by fujita** [comment]
the fix was pushed.
