### ISSUE TITLE
Feature Request: don't suppress initial non-established peer state in MonitorPeer

### ISSUE THREAD

**Issue by jwhited** [osrg/gobgp#2047]
MonitorPeerRequest w/current=true does not return the current state unless it is established. https://github.com/osrg/gobgp/blob/ccdc2e6277020e571da7792c1d9e76cf13e82f44/pkg/server/server.go#L4013-L4023

**Comment by fujita** [comment]
You meant that you want to know the states of all the peers even if a peer is not in the established state, right?

**Comment by jwhitedte** [comment]
@fujita, yes

**Comment by jwhited** [comment]
@fujita, yes

**Comment by ecbaldwin** [comment]
I just hit upon this and was about to file the same ticket. In my application, I have written a monitor which will call ListPeer, iterate on the results, and call MonitorPeer on each one.

Since it does not get the initial state, I use the result from ListPeer as the initial state of the peer. However, there is a race condition using this method. If ListPeer returns the peer in established state and then the state switches away from established before the call to MonitorPeer, then we will miss the state change and assume that the peer is still in an established state until the next update.

I looked into the code a little bit. I will try to find the time to fix this bug.

**Comment by fujita** [comment]
https://github.com/fujita/gobgp/tree/monitor-event

The API sends the state of all the peers (with any states) and then any state changes.

Better to sends kinda marker between the initial states and state changes, to represent the end of the state of all the peers?

**Comment by Mikeburke14** [comment]
As discussed in Slack:

Currently, when calling AddPath with FlowSpec the MonitorTable does not return the NextHopAttribute which was passed to it. 

It would be great if MonitorTable could include the data that was passed to it via addPath.

**Comment by imcom** [comment]
> MonitorPeerRequest w/current=true does not return the current state unless it is established.
> 
> https://github.com/osrg/gobgp/blob/ccdc2e6277020e571da7792c1d9e76cf13e82f44/pkg/server/server.go#L4013-L4023

If the peer is not established yet, what state changes would you like to know about it ? Are you going to take actions on state like "idle", "active" etc.. ? Once the peer is established , MonitorPeer will let you know that a peer is up, wouldn't it ?

**Comment by jwhited** [comment]
> > MonitorPeerRequest w/current=true does not return the current state unless it is established.
> > https://github.com/osrg/gobgp/blob/ccdc2e6277020e571da7792c1d9e76cf13e82f44/pkg/server/server.go#L4013-L4023
> 
> If the peer is not established yet, what state changes would you like to know about it ? Are you going to take actions on state like "idle", "active" etc.. ? Once the peer is established , MonitorPeer will let you know that a peer is up, wouldn't it ?

see https://github.com/osrg/gobgp/issues/2047#issuecomment-516209397

also loosely related to https://github.com/osrg/gobgp/issues/2046

**Comment by imcom** [comment]
> > > MonitorPeerRequest w/current=true does not return the current state unless it is established.
> > > https://github.com/osrg/gobgp/blob/ccdc2e6277020e571da7792c1d9e76cf13e82f44/pkg/server/server.go#L4013-L4023
> > 
> > 
> > If the peer is not established yet, what state changes would you like to know about it? Are you going to take actions on a state like "idle", "active" etc.. ? Once the peer is established, MonitorPeer will let you know that a peer is up, wouldn't it?
> 
> see [#2047 (comment)](https://github.com/osrg/gobgp/issues/2047#issuecomment-516209397)
> 
> also loosely related to #2046

Yea, sorry that missed it earlier, so I guess you are actually looking for a transactional API endpoint where you have the Get and Watch (Monitor) as a transaction within GoBGPd. 

> > Better to sends kinda marker between the initial states and state changes, to represent the end of the state of all the peers?

So perhaps on the first call to MonitorPeer, one gets a message confirms the watch registration and all states of existing peers. Then the following messages would be UPDATE with the change of state of any peer.

Something like ListPeer(withWatch=True)
