### ISSUE TITLE
GoBGP not advertising route with different nexthop with different community string

### ISSUE THREAD

**Issue by Shaffath** [osrg/gobgp#2055]
For our Application, we have to have two routes in the Router. 
Its a scenario of Uplink and downlink scenario. Based on the direction packets land on different vrf. based on the vrf, the nexthop is decided.

so for a given srcip, there can be two next hops. using identifier tag in gobgp i can able to add two routes.

1.2.3.4  nexthop 10.1.10 community "100:100" identifier 1
1.2.3.4  nexthop 100.1.1.100 community "200:200" identifier 2

now based on the community, it is decided to pick which VRF. but GoBGP is not advertising the second route, until the first one is deleted.

This is not the case with Juniper router with RM functionality, where based on the vlanid i was able to add the same ip with different nexthop on different vrf of the Router. 

Can someone help me on this.

This is the output of global rib
# gobgp global rib
   Network              Next Hop             AS_PATH              Age        Attrs
*> 4.0.0.1/32           169.254.1.1                               00:12:09   [{Origin: i} {Communities: 3344:4433}]
*  4.0.0.1/32           10.88.179.203                             00:12:09   [{Origin: i} {Communities: 33:44}]
*> 5.1.0.1/32           10.88.179.203                             03:38:50   [{Origin: i} {Communities: 1111:2222}]

This is what i see on the juniper router
root@vMX> show route hidden extensive 4.0.0.1/32 

inet.0: 4 destinations, 6 routes (2 active, 0 holddown, 4 hidden)
4.0.0.1/32 (2 entries, 0 announced)
         BGP    Preference: 170/-101
                Next hop type: Unusable
                Address: 0x92ce764
                Next-hop reference count: 7
                State: <Hidden Int Ext>
                Local AS: 65001 Peer AS: 65001
                Age: 56 
                Validation State: unverified 
                Task: BGP_65001.10.88.185.150+58065
                AS path: I
                Communities: 3344:4433
                Accepted
                Localpref: 100
                Router ID: 10.88.185.150
                Indirect next hops: 1
                        Protocol next hop: 169.254.1.1
                        Indirect next hop: 0x0 - INH Session ID: 0x0
         BGP    Preference: 170/-101
                Next hop type: Unusable
                Address: 0x92ce764
                Next-hop reference count: 7
                State: <Hidden Int Ext>
                Local AS: 65001 Peer AS: 65001
                Age: 56 
                Validation State: unverified 
                Task: BGP_65001.10.88.185.4+60545
                AS path: I
                Communities: 3344:4433
                Accepted
                Localpref: 100
                Router ID: 10.88.185.4
                Indirect next hops: 1
                        Protocol next hop: 169.254.1.1
                        Indirect next hop: 0x0 - INH Session ID: 0x0

But when i use the Juniper Route manager functionality here is what i achieved and would expect the same to achieve in Gobgp

ocp-dev-2024.inet.0: 1 destinations, 1 routes (0 active, 0 holddown, 1 hidden)
                                        
4.0.0.1/32 (1 entry, 0 announced)
         Static Preference: 3
                Next hop type: Unusable
                Address: 0x92ce764
                Next-hop reference count: 7
                State: <Hidden Int NSR-incapable>
                Age: 56 
                Validation State: unverified 
                Task: RPD Unix Domain Server./var/run/rpd_serv.local
                AS path: I
                Indirect next hops: 1
                        Protocol next hop: 10.88.179.203
                        Indirect next hop: 0x0 - INH Session ID: 0x0

ocp-dev-p-dev-2025.inet.0: 1 destinations, 1 routes (0 active, 0 holddown, 1 hidden)

4.0.0.1/32 (1 entry, 0 announced)
         Static Preference: 3
                Next hop type: Unusable
                Address: 0x92ce764
                Next-hop reference count: 7
                State: <Hidden Int NSR-incapable>
                Age: 56 
                Validation State: unverified 
                Task: RPD Unix Domain Server./var/run/rpd_serv.local
                AS path: I
                Indirect next hops: 1
                        Protocol next hop: 169.254.1.1
                        Indirect next hop: 0x0 - INH Session ID: 0x0

**Comment by fujita** [comment]
I'm not sure what you try to do. add-path?

**Comment by Shaffath** [comment]
yes, i was using add path.
