### ISSUE TITLE
gRPC "as" field of Global message conflicts with Python Token

### ISSUE THREAD

**Issue by OriolOMM** [osrg/gobgp#2071]
Hi,

I'm trying to call StartBgp from python:

 stub.StartBgp(gobgp_pb2.StartBgpRequest(gobgp_pb2.Global(
            as= settings.autonomous_system,
            router_id=settings.router_id
        )
    ))

The problem is that "as" is a reserved token in Python.

How I can solve this?

Thanks

**Comment by iwaseyusuke** [comment]
Hi @OriolOMM 
How about using `**kwargs` style argument to call `StartBgp`?
For example,

```python
kwargs = {
    ‘as’: 100,
    ‘router_id’: '1.1.1.1’,
}

stub.StartBgp(gobgp_pb2.StartBgpRequest(gobgp_pb2.Global(
    **kwargs,
)))
```

**Comment by OriolOMM** [comment]
Solved, thanks!
