### ISSUE TITLE
Question: Is there a reason why ipv4-flowspec is not supported for VRF enslaved neighbor

### ISSUE THREAD

**Issue by lechnertech** [osrg/gobgp#2073]
I am using the gobgp as a route injector and have each one of my peers in their own VRF.  This works great for announcing ipv4-unicast and ipv6-unicast routes for Source/Dest RTBH.  I want to expand the functionality to support ipv4-flowspec and ipv6-flowspec but receive the error ipv4-flowspec is not supported for VRF enslaved neighbor.  Is there a reason why this is not supported?

Thanks in advance.

**Comment by fujita** [comment]
I guess that nobody is interested in such feature. If you are, please send a pull request.

**Comment by lechnertech** [comment]
I am testing changes and will submit a pull request soon.  Thanks
