### ISSUE TITLE
gobgp version: incorrect version

### ISSUE THREAD

**Issue by mcorbin** [osrg/gobgp#2088]
I downloaded gobgp 2.3.0, but gobgp --version returns `master`:

```
./gobgp --version
gobgp version master
```

I was expecting `gobgp version 2.3.0`.

**Comment by fujita** [comment]
will be fixed by
https://github.com/osrg/gobgp/pull/2094

**Comment by fujita** [comment]
fixed

**Comment by mcorbin** [comment]
thanks you.
