### ISSUE TITLE
goBGP CLI response very slow in large configurations

### ISSUE THREAD

**Issue by bakulkhanna** [osrg/gobgp#2096]
Hello,

I am running a config with two hosts as follows:
gobgp-host <->juniper-router  (18 bgp-sessions established)

The goBGP-host receives routes over gRPC from a goBGP client device. At the moment there are 3 million routes in gobgp-host global rib.

At the gobgp-host I do a “gobgp neighbor”. It takes ~ 5 min for the response. Also, the bgp-session setup rate is very slow and there are several gobgp-session timeouts due to hold timer expired. I expect this long CLI response time to be an issue during debug sessions. I also expect the goBGP sessions timeouts to be an issue.

During this time only one of the 12 CPU-cores on the goBGP host is at 100% - other 11 CPU-cores are at 0%. If I disable all the bgp-peers or if I remove the 3 million routes the “gobgp neighbor”, response is instantaneous. 

Is there any way to configure goBGP to use more CPU-cores  under these conditions OR is there any other suggestion for the slow CLI response time and the bgp-sessions instability?

Thanks.

**Comment by fujita** [comment]
>At the gobgp-host I do a “gobgp neighbor”. It takes ~ 5 min for the response.

The command calculates the numbers of advertised routes for every neighbors. So if there are lots of routes, it takes long time. If you specify a peer, it should not take time.

> Is there any way to configure goBGP to use more CPU-cores under these conditions

https://github.com/osrg/gobgp/blob/master/cmd/gobgpd/main.go#L116
The `cpu` option might work for you.

**Comment by bakulkhanna** [comment]
Thank you. Very helpful.

**Comment by bakulkhanna** [comment]
Hello, I used your suggestion of specifying "number of CPUs" in the command line. For the most part I see CPU load nicely distributed among all CPUs. 

However, when I do a "gobgp neighbor", I see only one of the many available CPUs being used at 100%. With a small number of bgp peers, and with 2 million routes, this command takes of the order of 6 minutes to finish execution.  

Is it possible to have the software that implements "gobgp neighbors" to take advantage of the many CPUs specified in the command line.

**Comment by fujita** [comment]
>Is it possible to have the software that implements "gobgp neighbors" to take advantage of the many CPUs specified in the command line.
That's the direction that I like but it's not easy because the way to handle mutual exclusion has to be changed.

**Comment by fujita** [comment]
Few OSS BGP implementations fully use CPUs.
https://elegantnetwork.github.io/posts/bird-on-bird-bgp-perf-episode4/

I would recommend RustyBGP if you want performance on multiple cores.
