### ISSUE TITLE
How can we get UUID when select list of flowspecs

### ISSUE THREAD

**Issue by triadium** [osrg/gobgp#2102]
In version 1.3.1 command
`gobgp -p 50071 global rib -a ipv4-flowspec -j`
output
`{"[destination: 1.1.1.1/32]":[{"nlri":{"value":[{"type":1,"value":{"prefix":"1.1.1.1/32"}}]},"attrs":[{"type":1,"value":2},{"type":14,"nexthop":"0.0.0.0","afi":1,"safi":133,"value":[{"value":[{"type":1,"value":{"prefix":"1.1.1.1/32"}}]}]}],"age":1560524628,"validation":"none","uuid":"6168a06c-d696-4df4-8c51-c24632a783b6"}]}` with UUID
After  we updated version to 2.5 there is no UUID field in the output.
How can we get it now?

**Comment by fujita** [comment]
When you install a path, you can get the uuid of the path in the response.
