### ISSUE TITLE
Two problems I encountered while using the vrf feature

### ISSUE THREAD

**Issue by shengslin** [osrg/gobgp#2104]
Two problems I encountered while using the vrf feature.

The configuration is consistent with what I described in the following question：
https://github.com/osrg/gobgp/issues/2092

1. A BGP neighbor cannot be created from the vrf. The establishment of the neighbor needs to be initiated by the peer.
2. It is not possible to establish a neighbor with the same ip address in a different vrf.
    If BGP-related services are provided for different users on one host and vrf is used for route isolation, the IP address used to establish BGP neighbors is likely to be the same, if it is configured by the user. Since GoBGP already supports the vrf feature, this should be supported. 
I tested it with FRR and it works very well.

some log info:
```

{"Key":"1.1.1.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":{"Type":7,"BGPNotification":null,"Data":null},"time":"2019-06-02T12:26:08Z"}
{"Key":"1.1.1.1","Topic":"Peer","level":"debug","msg":"try to connect","time":"2019-06-02T12:26:27Z"}
{"Key":"1.1.1.1","Topic":"Peer","level":"debug","msg":"failed to connect: dial tcp 0.0.0.0:0-\u003e1.1.1.1:179: connect: no route to host","time":"2019-06-02T12:26:27Z"}
```

**Comment by fujita** [comment]
If you create a new issue, close the existing one.
