### ISSUE TITLE
Announce prefix whose as-path contains Peer-As

### ISSUE THREAD

**Issue by amalakhov** [osrg/gobgp#2126]
How can I enable option like juniper ‘advertise-peer-as’? I trying to announce prefix whose as-path contains peer-as and gobgp doesn't announce it. 

PeerConf:
```
peer = &api.Peer{
		Conf: &api.PeerConf{
			NeighborAddress:	n.NeighborAddress,
			PeerAs:         	65000,
			LocalAs:		65000,
		},
}

```

AddPath:
```
nlri, _ := ptypes.MarshalAny(&api.IPAddressPrefix{
	Prefix:    "212.93.181.0",
	PrefixLen: "24",
})

originAttribute, _ := ptypes.MarshalAny(&api.OriginAttribute{
	Origin: 0,
})

nextHopAttribute, _ := ptypes.MarshalAny(&api.NextHopAttribute{
	NextHop: msg.NextHop,
})

asPathAttribute, _ := ptypes.MarshalAny(&api.AsPathAttribute{
	Segments: []*api.AsSegment{
		{
			Type:    2,
			Numbers: []uint32{6762, 39919, 65000, 35753, 65000},
		},
	},
})

_, err := mh.server.AddPath(context.Background(), &api.AddPathRequest{
		Path: &api.Path{
			Family: &api.Family{Afi: api.Family_AFI_IP, Safi: api.Family_SAFI_UNICAST},
			Nlri:   nlri,
			Pattrs: attrs,
		},
})
```

**Comment by fujita** [comment]
Adding a path with the AS number or using an export policy to append the AS number.

**Comment by amalakhov** [comment]
> Adding a path with the AS number or using an export policy to append the AS number.

May you show me the example please? I have to announce prefix with AsPath:
`6762 39919 65000 35753 65000`

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md

The above example gives:

```
root@14acf8c7468a:/go/src/github.com/osrg/gobgp# ./cmd/gobgp/gobgp g r
   Network              Next Hop             AS_PATH                      Age        Attrs
*> 10.0.0.0/24          10.0.0.1             6762 39919 65000 35753 65000 00:00:03   [{Origin: i} {LocalPref: 100}]
```

**Comment by amalakhov** [comment]
> https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md
> 
> The above example gives:
> 
> ```
> root@14acf8c7468a:/go/src/github.com/osrg/gobgp# ./cmd/gobgp/gobgp g r
>    Network              Next Hop             AS_PATH                      Age        Attrs
> *> 10.0.0.0/24          10.0.0.1             6762 39919 65000 35753 65000 00:00:03   [{Origin: i} {LocalPref: 100}]
> ```

Did you test this example with PeerAs = 65000 ?

**Comment by fujita** [comment]
not 65000 but two peers has the same AS number so iBGP like your configuration. In the case of iBGP, the AS path attribute isn't changed when advertising; you need to add a path with the AS path attribute that you exactly want to advertise.

**Comment by fujita** [comment]
can we close?

**Comment by amalakhov** [comment]
> can we close?

Yes, I'll close.

P.s. 
I couldn't announce as-path with peer-as, but It isn't important for now.
