### ISSUE TITLE
A question about the "vrf" and "bind-interface" configurations

### ISSUE THREAD

**Issue by shengslin** [osrg/gobgp#2127]
> This is an example.
> [[neighbors]]
> [neighbors.config]
> neighbor-address = "10.0.1.2"
> peer-as = 65002
> vrf = "blue"
> [neighbors.transport.config]
> local-address = "10.0.1.1"
> bind-interface = "vpee-bluee"

Vrf and bind-interface in the configuration file I think should be the same concept, frr can also find its corresponding interface according to vrf, without the need to separate configuration, is my understanding of these two configurations biased?

**Comment by irino** [comment]
I introduced bind-interface in recent commit for setsockopt with syscall.SO_BINDTODEVICE.
syscall.SO_BINDTODEVICE is used for specifying interface name of a socket created with parameters in neighbors.transport.config. Major use cases of this setsockopt is VRF, however it is not only for. If this config is not compained to any standards (e.g., openconfig), it should be changed to comlain to the standard. However if standards have not defined any similar parameters for specifying interface, I think there is no reason to change.

**Comment by irino** [comment]
Can this issue be closed?
