### ISSUE TITLE
Add BGP Confederation Documentation to GoBGP

### ISSUE THREAD

**Issue by kkirsche** [osrg/gobgp#2146]
Good afternoon,

I would like to open a discussion regarding adding / implementing support for BGP confederation within GoBGP. Based on the following ticket, https://github.com/osrg/gobgp/issues/1428, GoBGP does not currently support confederation. I would like to ask if:

1. This is something that was incorrectly stated (GoBGP does actually support confederation) and a pull request is required to add the supporting documentation so that others may identify how to use this feature / functionality.
2. This is something which is on the roadmap but not yet in a pull request, and does not require discussion / assistance
3. BGP Confederation is not on the roadmap and discussion about it hasn't been completed. At which point I'd ask is the project open to assistance in and/or supporting implementation of BGP confederation.  I'd be willing to try to assist with this, but would need support from the GoBGP team in terms of ensuring that this meets the project's requirements to ensure its maintained moving forward once accepted and implemented. 

## What is BGP Confederation?
In network routing, BGP confederation is a method to use Border Gateway Protocol (BGP) to subdivide a single autonomous system (AS) into multiple internal sub-AS's, yet still advertise as a single AS to external peers. The intent is to reduce iBGP mesh size. This is commonly performed within large Internet Service Providers (ISPs) in part to segment operations by team, region, or other factors.

## Why might a large provider need or want BGP confederation?
A confederated AS is composed of multiple ASs. Each confederated AS alone has iBGP fully meshed and has connections to other ASs inside the confederation. Even though these ASs have eBGP peers to ASs within the confederation, the ASs exchange routing as if they used iBGP. In this way, the confederation preserves next hop, metric, and local preference information. To the outside world, the confederation appears to be a single AS. With this solution, iBGP transit AS problems can be resolved as iBGP requires a full mesh between all BGP routers: large number of TCP sessions and unnecessary duplication of routing traffic. It may also be used to segment a network's responsibility by internal team, region, or other distinct properties.

**Comment by fujita** [comment]
As far as I know, nobody is working on that feature. Please send pull requests. Happy to merge them. Don't forget to include tests, which could prevent someone to break in the future.

**Comment by iwaseyusuke** [comment]
Excuse me for jumping in.

As mentioned in the above, the confederation feature is not easy to find on the docs, but GoBGP does support this feature. Sorry for this feature is not documented though, the following `scenario_test` should be helpful for you.

https://github.com/osrg/gobgp/blob/master/test/scenario_test/bgp_confederation_test.py

**Comment by fujita** [comment]
Oops, I completely forgot that. Thanks!

**Comment by fujita** [comment]
Improving the documents is always welcome, thanks!
