### ISSUE TITLE
Softreset clears llgr community in routes

### ISSUE THREAD

**Issue by mageshgv** [osrg/gobgp#2171]
Softreset clears llgr community because in markLLGR we are not updating the community in adjrib in, but only using it for updating the rib and sending updates to neighbors. On Softreset, we recompute the rib from adj-in where we do not have the LLGR community
https://github.com/osrg/gobgp/blob/master/pkg/server/peer.go#L335

**Comment by fujita** [comment]
Thanks a lot for the bug report and fix!
