### ISSUE TITLE
Question on GR/LLGR

### ISSUE THREAD

**Issue by mageshgv** [osrg/gobgp#2174]
In the current implementation in gobgp, GR/LLGR state transition only happens if TCP session fails (literally remote peer restarting would be the only scenario that would see a tcp layer failure due to tcp reset. We are not setting any timeouts on recv/send, so we will not be hitting any timeout errors on tcp unless hold timer is extremely high). When gobgp runs into hold timer expiry, it clears all the routes from the peer ignoring GR and LLGR.
https://github.com/osrg/gobgp/blob/master/pkg/server/fsm.go#L1807
https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L1309

While the graceful restart/llgr RFCs do not explicitly mention hold timer expiry, for practical purposes llgr is more useful for the scenarios where the bgp peer is not reachable(not necessarily process/os restart) and we want to work in pure headless mode.

Is the current implementation of ignoring GR on hold timer expiry in gobgp by design or is this a bug ? 

For reference, BIRD transitions to graceful restart state on hold timer expiry, thereby preserving the routes. (Not sure about Cisco/Juniper, but will try to verify this on Cisco if possible).

**Comment by fujita** [comment]
the behavior is by design but applying llgr to hold timer expiry would make sense to me. Can you try Cisco?

**Comment by mageshgv** [comment]
@fujita thanks for your reply. Unfortunately the routers in our lab are running a older software version that does not support llgr. 

Meanwhile, for the headless mode, may be we can add a configuration based approach to transition to llgr on hold timer expiry thereby keeping the current behavior unchanged ?

**Comment by fujita** [comment]
I really want to avoid GoBGP specific configuration like such. Once adding workaround, we have to keep it for long time. It's not good.

This behavior is unclear in RFCs. GoBGP is expected to work in a way that RFC authors expect. The easiest way to do it is checking out how Cisco (or Juniper) works, I guess.

**Comment by mageshgv** [comment]
@fujita I am still trying to get a working Juniper/Cisco with the software version that supports llgr. However, I found a knowledge base article from Juniper which confirms the implementation details:
https://kb.juniper.net/InfoCenter/index?page=content&id=KB31390
As per this, Juniper implementation is unconditional and the routes are retained for hold timer expiry as well.

**Comment by fujita** [comment]
Thanks for the pointer. I'm waiting for a pull request. ;)

**Comment by mageshgv** [comment]
Thanks. I will prepare a PR for this.
