### ISSUE TITLE
Memory consumed by gobgpd increases over time

### ISSUE THREAD

**Issue by bakulkhanna** [osrg/gobgp#2187]
Hello,

I have been running gobgp (ver 2.1.0) on two 16GB Linux VMs for the past month. Each gobgp instance has around 200K routes.

At the time the gobgp  VM is started, the "top" command indcates gobgpd using 4 % MEM
After a month, the "top" command indicates gobgpd using 80 % MEM

Is there a known memory leak for gobgpd? In the "top" command below the %MEM is different between the two gobgp-VMs. In the "cat /proc/meminfo" command below the AnonPages and AnonHugePages are different between the two gobgp-VMs.

Following are some statistics taken from:
1. gobgp-VM-01 that has recently been started
2. gobgp-VM-02 that has been running for 1 month. 

-----------------------------------------------------------------------------------------
Gobgp-VM-01 (just started)

>top - 21:27:26 up 185 days,  3:55,  1 user,  load average: 0.03, 0.17, 0.22
Tasks: 180 total,   1 running,  98 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.2 us,  0.4 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.1 st
KiB Mem : 16423896 total, 15305236 free,   776880 used,   341780 buff/cache
KiB Swap:   207236 total,   169680 free,    37556 used. 15330580 avail Mem
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
8013 root      20   0 3557052 502844  13328 S  16.6  **3.1**  74:03.19 gobgpd
  366 root      19  -1  212904  33520  26656 S   0.0  0.2  10:19.11 systemd-journal

>root@gc-rm-den-01-alpha:/home/bkhanna# cat /proc/meminfo
MemTotal:       16423896 kB
MemFree:        15298028 kB
MemAvailable:   15323372 kB
Buffers:               0 kB
Cached:           125076 kB
SwapCached:         1816 kB
Active:           663584 kB
Inactive:          66136 kB
Active(anon):     600324 kB
Inactive(anon):     4620 kB
Active(file):      63260 kB
Inactive(file):    61516 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        207236 kB
SwapFree:         169680 kB
Dirty:                 0 kB
Writeback:             0 kB
**AnonPages:        528116 kB**
Mapped:            59788 kB
Shmem:               300 kB
Slab:             263704 kB
SReclaimable:     216704 kB
SUnreclaim:        47000 kB
KernelStack:        3824 kB
PageTables:         7612 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8419184 kB
Committed_AS:    1229820 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
**AnonHugePages:     51200 kB**

-----------------------------------------------------------------------------------------
Gobgp-VM-02 (Has been running for a month)

>top - 21:28:05 up 185 days,  3:55,  1 user,  load average: 0.38, 0.87, 0.86
Tasks: 180 total,   1 running,  98 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.7 us,  0.5 sy,  0.0 ni, 97.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.1 st
KiB Mem : 16423896 total,  2903308 free, 13378768 used,   141820 buff/cache
KiB Swap:   207236 total,     2584 free,   204652 used.  2804808 avail Mem
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23141 root      20   0 18.797g 0.012t   5144 S  30.1 **80.2**  14357:13 gobgpd
329 root      19  -1  188280  33404  26860 S   0.0  0.2   9:35.49 systemd-journal 

>root@gc-rm-den-02-alpha:/home/bkhanna#  cat /proc/meminfo
MemTotal:       16423896 kB
MemFree:         2903884 kB
MemAvailable:    2805380 kB
Buffers:               0 kB
Cached:           113380 kB
SwapCached:         2968 kB
Active:         12083272 kB
Inactive:        1279860 kB
Active(anon):   12011716 kB
Inactive(anon):  1238312 kB
Active(file):      71556 kB
Inactive(file):    41548 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        207236 kB
SwapFree:           2584 kB
Dirty:                 0 kB
Writeback:             0 kB
**AnonPages:      13198668 kB**
Mapped:            50608 kB
Shmem:               276 kB
Slab:              64020 kB
SReclaimable:      28436 kB
SUnreclaim:        35584 kB
KernelStack:        3824 kB
PageTables:        39060 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8419184 kB
Committed_AS:   17312128 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
**AnonHugePages:   4737024 kB**
-----------------------------------------------------------------------------------------

Any suggestions?

Thanks,

-Bakul Khanna

**Comment by fujita** [comment]
If you add/delete paths locally, then you would hit the following memory leak:
https://github.com/osrg/gobgp/commit/da536952b3d12104bdcf9c0385970100b2aefe3e

Otherwise, as far as I know, there is no known memory leak bug.

**Comment by bakulkhanna** [comment]
Thanks for your response. In our environment we add/delete paths from a remote client via gRPC. Would that count as add/delete paths locally?

**Comment by fujita** [comment]
Yes, try the latest release.

**Comment by fujita** [comment]
Please reopen with pprof result if you hit the bug with the latest release.
