### ISSUE TITLE
eBGP doesn't withdraw routes to other eBGP peers when peer goes down

### ISSUE THREAD

**Issue by ABrilliantBeast** [osrg/gobgp#2208]
I'm running 1.32, but the code looks very similar between the latest.

I have a configuration of A-B-C.

B propagates A's routes to see correctly, but if I break the link between A and B and wait for the session to go to IDLE, B does not send an update to C withdrawing A's routes.

If I look at the adj-out rib from A to C, those routes are not present.  I do not see the withdraw if I capture the traffic between A and C.  If I do a soft reset on B, the withdraw goes out and A's routes are withdraw from C.

It looks like propagateUpdateToNeighbors, server/server.go is doing something wrong and I haven't quite debugged it yet.

**Comment by fujita** [comment]
I've tried with the latest master but can't reproduce.

**Comment by ABrilliantBeast** [comment]
OK.  I will give that a try in the next couple of days.
