### ISSUE TITLE
Python gRPC error on calling ListPeer

### ISSUE THREAD

**Issue by AcidicNut** [osrg/gobgp#2210]
I tried to call ListPeer, but I get this error: 

`<_Rendezvous object of in-flight RPC>`

Here is the code:

    peer = stub.ListPeer(gobgp_pb2.ListPeerRequest(
        address='172.16.127.42',
        enableAdvertised=True
    ))
    print(peer)

Also I found a year old tutorial where they used GetNeighbor, but I can't seem to find this function. Is it deprecated?

**Comment by fujita** [comment]
ListPeer API is a streaming API. I added an example:
https://github.com/osrg/gobgp/blob/master/tools/grpc/python/list_peer.py

GetNeighbor API is not supported in GoBGP v2.

**Comment by AcidicNut** [comment]
Thanks I didn't notice that. in this code:
    peers = stub.ListPeer(
        gobgp_pb2.ListPeerRequest(
        ),
        _TIMEOUT_SECONDS,
    )

What does _TIMEOUT_SECONDS do?

**Comment by fujita** [comment]
The timeout of the request.

**Comment by AcidicNut** [comment]
I've just tried it. So after the timeout it raises an exception, and I guess it's intended.
Raised exception:
```
Unhandled exception in thread started by <function my_MonitorTable at 0x7f8cbf5fb1e0>
Traceback (most recent call last):
  File "get_neighbor.py", line 28, in my_MonitorTable
    for table in tables:
  File "/home/lb/work/sdn/practice/py3/venv/lib/python3.7/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/home/lb/work/sdn/practice/py3/venv/lib/python3.7/site-packages/grpc/_channel.py", line 357, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1573519207.180507000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```
But what if I want to use a streaming API indefinitely, for example for monitoring?
