### ISSUE TITLE
Peer cannot be established in IPv6 passive mode

### ISSUE THREAD

**Issue by M-anazawa** [osrg/gobgp#2219]
Peer cannot be established in IPv6 passive mode.
IPv4 can establish a peer in passive mode.
AS33333 side is not in passive mode

route-server peer configuration
************************************************
[[neighbors]]
  [neighbors.config]
    neighbor-address = "2001:DE8:8::2:3815:254"
    peer-as = 33333
  [neighbors.transport.config]
    passive-mode = true
  [neighbors.route-server.config]
    route-server-client = true
************************************************

/var/log/messages
************************************************
Dec 20 15:11:37 rs-GoBGP bgpd[6058]: time="2019-12-20T15:11:37+09:00" level=info msg="Reload the config file" Topic=Config
Dec 20 15:11:37 rs-GoBGP bgpd[6058]: time="2019-12-20T15:11:37+09:00" level=info msg="Peer 2001:DE8:8::2:3815:254 is added"
Dec 20 15:11:37 rs-GoBGP bgpd[6058]: time="2019-12-20T15:11:37+09:00" level=info msg="Add a peer configuration for:2001:DE8:8::2:3815:254" Topic=Peer
Dec 20 15:12:00 rs-GoBGP bgpd[6058]: time="2019-12-20T15:12:00+09:00" level=info msg="Can't find configuration for a new passive connection from:2001:de8:8::2:3815:254" Topic=Peer
************************************************

**Comment by fujita** [comment]
duplicated with
https://github.com/osrg/gobgp/issues/2220
