### ISSUE TITLE
GoBGP of route-server and GoBGP of client side cannot establish peer in IPv6

### ISSUE THREAD

**Issue by M-anazawa** [osrg/gobgp#2220]
GoBGP of route-server and GoBGP of client side cannot establish peer in IPv6.
IPv4 can establish a peer.
GoBGP route-server and bird, OpenBGPD, Juniper vMX can establish peers with IPv6.

route-server configuration
*********************************************
[[neighbors]]
  [neighbors.config]
    neighbor-address = "2001:DE8:8::2:3815:204"
    peer-as = 204
    auth-password = "204"
  [neighbors.route-server.config]
    route-server-client = true
  [neighbors.timers.config]
    hold-time = 180
    keepalive-interval = 60
*********************************************

client configuration
*********************************************
[[neighbors]]
  [neighbors.config]
    neighbor-address = "2001:DE8:8::2:3815:7"
    peer-as = 23815
    auth-password = "204"
  [neighbors.timers.config]
    hold-time = 180
    keepalive-interval = 60
*********************************************

/var/log/messages
*********************************************
Dec 20 15:34:30 rs-GoBGP bgpd[6058]: time="2019-12-20T15:34:30+09:00" level=info msg="Can't find configuration for a new passive connection from:2001:de8:8::2:3815:204" Topic=Peer
*********************************************

**Comment by fujita** [comment]
Try Lowercase for `neighbor-address`
`neighbor-address = "2001:de8:8::2:3815:204"`
