### ISSUE TITLE
With MD5 authentication, only about 900 peers can be established.

### ISSUE THREAD

**Issue by M-anazawa** [osrg/gobgp#2221]
With MD5 authentication, only about 900 peers can be established.
Without MD5 authentication, more than 1000 peers can be established.

route-server configuration
*********************************************
[[neighbors]]
  [neighbors.config]
    neighbor-address = "210.171.225.146"
    peer-as = 146
    auth-password = "146"
  [neighbors.route-server.config]
    route-server-client = true
  [neighbors.timers.config]
    hold-time = 180
    keepalive-interval = 60
*********************************************

/var/log/messages
*********************************************
Dec 23 13:09:44 rs-GoBGP bgpd[18700]: time="2019-12-23T13:09:44+09:00" level=info msg="Peer 210.171.225.146 is added"
Dec 23 13:09:44 rs-GoBGP bgpd[18700]: time="2019-12-23T13:09:44+09:00" level=warning msg="failed to set md5: cannot allocate memory" Key=210.171.225.146 Topic=Peer
Dec 23 13:09:44 rs-GoBGP bgpd[18700]: time="2019-12-23T13:09:44+09:00" level=info msg="Add a peer configuration for:210.171.225.146" Topic=Peer
*********************************************

**Comment by fujita** [comment]
The error came from your OS. GoBGP has no limit. If you use Linux, the following might be useful:
https://bird.network.cz/pipermail/bird-users/2015-August/009882.html
