### ISSUE TITLE
About SNMP monitoring

### ISSUE THREAD

**Issue by M-anazawa** [osrg/gobgp#2225]
Hello,

Is it possible to monitor the status of GoBGP peers with SNMP?

Best regards,

Anazawa Masatsune

**Comment by fujita** [comment]
No supported. You need to implement something accessing to gobgpd via the APIs and talking SNMP.

**Comment by M-anazawa** [comment]
Any plans to support it in the future?

**Comment by fujita** [comment]
Not on my list. I'm interested in prometheus or such rather than snmp.
