### ISSUE TITLE
Does have document about GoBGP send EVPN message to other process ?

### ISSUE THREAD

**Issue by kungyuncheng** [osrg/gobgp#2226]
Hello, I'm new to study GoBGP, and want GoBGP send evpn message to my software.
Dose have any way to connet GoBGP and other process ?

such as -
1. socket port
2. BMP
3. gRPC
...

Thanks.

**Comment by xiaopeng163** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/evpn.md

**Comment by kungyuncheng** [comment]
Thanks for your reply! 

my test is not send evpn message between GoBGP, 
the test process and GoBGP are at same VM, like below -
+--------------------------------------------------------+
|                                                                                    |
|    +------------------+            +------------------+     |
|     |    My process      |             |       GoBGP          |      |
|    +------------------+            +------------------+     |
|                        VM : 192.168.40.10                             |
+--------------------------------------------------------+

and while add a route through CLI such like - ./gobgp global rib add 10.10.10.10/32,
can notify to "My process"

**Comment by xiaopeng163** [comment]
GoBGP is a "BGP/BMP router" somehow.  you need establish a BGP/BMP connection between goBGP and "your software" before you can send BGP/BMP message.

**Comment by kungyuncheng** [comment]
yes, you are right,
I found config BMP on GoBGP by https://github.com/osrg/gobgp/blob/master/docs/sources/bmp.md 
but less the receive-side example such like use java/C, I will continue search it.

if have any suggestion please mail to me : oldman0528@gmail.com
thanks!
