### ISSUE TITLE
Supporting Unix sockets for gRPC api?

### ISSUE THREAD

**Issue by ABrilliantBeast** [osrg/gobgp#2230]
Have you thought about allowing Unix sockets for the gRPC api?  We use are playing with running in multiple docker containers and it would make managing the multiple containers easier, at least for us.  It's doesn't look terribly hard so if you want to discuss the correct way to design, I could probably do the work.

**Comment by fujita** [comment]
I've not tried but looks like grpc supports unix domain socket?
https://github.com/grpc/grpc/blob/master/doc/naming.md

If so, simply making `--api-hosts` option parse unix domain socket is enough?
https://github.com/osrg/gobgp/blob/b615942abb0445849e81cbbb2fcdbf98a0bfbdf0/cmd/gobgpd/main.go#L56

**Comment by ABrilliantBeast** [comment]
I don't think the golang net.Dial supports the URI format directly, I couldn't get it to work.  You have to call out the protocol separately.

https://golang.org/pkg/net/#Dial

net.Dial("unix", "/var/run/gobgp.sock")

**Comment by fujita** [comment]
grpc.DialContext() doesn't support unix domain socket?

**Comment by ABrilliantBeast** [comment]
Oh, Yes, that does.  I think it may have been Listen that was the issue.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/b615942abb0445849e81cbbb2fcdbf98a0bfbdf0/pkg/server/grpc_server.go#L68
Parsing the host and specify "unix" If necessary?

**Comment by ABrilliantBeast** [comment]
I think that would work

**Comment by fujita** [comment]
I'm waiting for a pull request :)

**Comment by ABrilliantBeast** [comment]
OK.  I just need to figure out how that way to do this that makes Corporate happy.
