### ISSUE TITLE
get table info from vrf

### ISSUE THREAD

**Issue by pvorontsovd** [osrg/gobgp#2235]
is it possible get routes count from vrf?

from cli i can do `gobgp global rib summary` of similar grpc method `GetTable`
but this works only on global table
i want get similar from vrf

**Comment by pvorontsovd** [comment]
i try do this https://github.com/pvorontsovd/gobgp/commit/30fb2e019c3287ec9a6c13b5f885b007dab76a80

**Comment by fujita** [comment]
can you create a pull request? thanks!
