### ISSUE TITLE
Announce prefix to specific neighbor(peer) rather than global?

### ISSUE THREAD

**Issue by shane-zhang** [osrg/gobgp#2243]
I am conducting some routing related experiment with GoBGP, it's pretty handy at first.
But I am just wondering, is that possible to announce a prefix with different community numbers to the different neighbor? e.g. can I use GoBGP to announce prefix neighbor-wise?
Thanks!

**Comment by fujita** [comment]
Yes. In the export policy, the neighbor condition matches neighbors that gobgp advertise to.

**Comment by shane-zhang** [comment]
Got it, thanks! I implement a peer wise announcement mechanism with GoBGP neighbor set and self-defined community set policies.
