### ISSUE TITLE
How to enable display #Advertised in the neighbor list

### ISSUE THREAD

**Issue by shane-zhang** [osrg/gobgp#2244]
In the document: https://github.com/osrg/gobgp/blob/72bbb9678381686acf14b0177dbf442a6761f41b/docs/sources/cli-operations.md
We can see, there is a column named #Advertised. However, I used the latest binary distribution in Ubuntu, this column does not appear.
I compared the two configures, I can not see the difference.
Is this a feature need specific router support?

**Comment by fujita** [comment]
thanks. the output is outdated. I'll update
https://github.com/osrg/gobgp/pull/2245

Counting the advertised number is costly so the current version don't. If you know the number, specify one neighbor.
https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#21-show-neighbor-status
