### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by xiaopeng163** [osrg/gobgp#2246]
Created a Dockerfile to build gobgp with multi-stage, then generate a small docker image.

If this is useful, I can create a PR to add it in one doc file with simple description, or any other suggestion?

```
# build stage
FROM golang:alpine AS build-env

ENV GOBGP_VERSION v2.14.0

RUN apk add --no-cache gcc linux-headers musl-dev git 

RUN git clone https://github.com/osrg/gobgp && cd gobgp && git checkout tags/${GOBGP_VERSION} -b ${GOBGP_VERSION} && go mod download && go install ./cmd/gobgpd ./cmd/gobgp

# final stage
FROM alpine

LABEL maintainer="Peng Xiao <xiaoquwl@gmail.com>"

COPY --from=build-env /go/bin/* /usr/bin/

CMD []
```

**Comment by fujita** [comment]
I have the similar one.
https://github.com/fujita/dockerfiles/blob/master/gobgp/Dockerfile

Everyone has own requirement and it's very easy to create one. Not sure if it's useful to have such.

**Comment by xiaopeng163** [comment]
oh, 👍 nice, I will use yours then lol
