### ISSUE TITLE
Does hava java example code for communicate through grpc ?

### ISSUE THREAD

**Issue by kungyuncheng** [osrg/gobgp#2255]
Hi all, 
I generated a Gobgp java class through gobgp.proto, and want used it to add/delete evpn route,
but only can find Go/python/C++ add ipv4 route example code,
does hava java example code ? thanks.

**Comment by kungyuncheng** [comment]
I follow the [c++ example code](ur:https://github.com/osrg/gobgp/blob/48fa25d06c96262779253b0b051e8d1a34604764/tools/grpc/cpp/add_path.ccl)

**Comment by kungyuncheng** [comment]
Finally I know how to add a ipv4/evpn route type 2 path by using java,

[gobgp_add_path_java_example.txt](https://github.com/osrg/gobgp/files/4400375/gobgp_add_path_java_example.txt)

[gobgp_add_path_evpn_type2_java_example.txt](https://github.com/osrg/gobgp/files/4400376/gobgp_add_path_evpn_type2_java_example.txt)

and find a lost description of attribute.proto,

message ExtendedCommunitiesAttribute {
    // Each Community must be one of:
    // - TwoOctetAsSpecificExtended
    // - IPv4AddressSpecificExtended
    // - FourOctetAsSpecificExtended
    // - OpaqueExtended
    // - ESILabelExtended
    // - MacMobilityExtended
    // - RouterMacExtended
    // - TrafficRateExtended
    // - TrafficActionExtended
    // - RedirectTwoOctetAsSpecificExtended
    // - RedirectIPv4AddressSpecificExtended
    // - RedirectFourOctetAsSpecificExtended
    // - TrafficRemarkExtended
    // - UnknownExtended
    **// - EncapExtended**        <====   need add this 
    repeated google.protobuf.Any communities = 1;
}

**Comment by fujita** [comment]
I don't know how you read the above. It means that you need to encode the following EncapExtended struct into protobuf.Any
https://github.com/osrg/gobgp/blob/master/api/attribute.proto#L94-L96

**Comment by kungyuncheng** [comment]
I used the command :
./gobgp global rib -a evpn add macadv aa:bb:cc:dd:ee:ff 20.20.20.20 etag 0 label 30 rd 65000:1 encap vxlan

and observed the packet content notice that EncapExtended seems like encode to ExtendedCommunitiesAttribute,
![image](https://user-images.githubusercontent.com/49181658/77887987-1de27100-729e-11ea-94b5-a2057e3dff8f.png)

so I check the description of ExtendedCommunitiesAttribute and expect  EncapExtended will at the one of Community list, but it's not.

by my test if EncapExtended add on pattrs directly, 
**message Path {
  ...
  google.protobuf.Any nlri = 1;
  // Each attribute must be one of *Attribute defined in
  // "api/attribute.proto".
  repeated google.protobuf.Any pattrs = 2;**   

the Gobgp can not analysis it, unless encode to ExtendedCommunitiesAttribute.
