### ISSUE TITLE
How to config BGP-LS in current gobgp version  ? who know  ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2256]
I want to config bgp-ls in gobgpd.conf,but didn't find any configuration example :
https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md

current gobgp release version doesn't support bgp-ls configuration   ? who can give me introduction  ?

**Comment by zhanggongc** [comment]
func checkAddressFamily(def *api.Family) (*api.Family, error) {
	var f *api.Family
	var e error
	switch subOpts.AddressFamily {
	case "ipv4", "v4", "4":
		f = ipv4UC
	case "ipv6", "v6", "6":
		f = ipv6UC
	case "ipv4-l3vpn", "vpnv4", "vpn-ipv4":
		f = ipv4VPN
	case "ipv6-l3vpn", "vpnv6", "vpn-ipv6":
		f = ipv6VPN
	case "ipv4-labeled", "ipv4-labelled", "ipv4-mpls":
		f = ipv4MPLS
	case "ipv6-labeled", "ipv6-labelled", "ipv6-mpls":
		f = ipv6MPLS
	case "evpn":
		f = evpn
	case "encap", "ipv4-encap":
		f = ipv4Encap
	case "ipv6-encap":
		f = ipv6Encap
	case "rtc":
		f = rtc
	case "ipv4-flowspec", "ipv4-flow", "flow4":
		f = ipv4Flowspec
	case "ipv6-flowspec", "ipv6-flow", "flow6":
		f = ipv6Flowspec
	case "ipv4-l3vpn-flowspec", "ipv4vpn-flowspec", "flowvpn4":
		f = ipv4VPNflowspec
	case "ipv6-l3vpn-flowspec", "ipv6vpn-flowspec", "flowvpn6":
		f = ipv6VPNflowspec
	case "l2vpn-flowspec":
		f = l2VPNflowspec
	case "opaque":
		f = opaque
	case "ls", "linkstate", "bgpls":         
                //this case is supported,but when this fuction is called ,input para is all ipv4UC  ??
		f = ls
	case "":
		f = def
	default:
		e = fmt.Errorf("unsupported address family: %s", subOpts.AddressFamily)
	}
	return f, e
}

and i can't find any detail introduction about bgp-ls in cli-command-syntax.md 
so bgp-ls is not supported  ??
 If we want to make use of bgp ls function ,we must develop it further  ?

**Comment by fujita** [comment]
CLI doesn't support bgp-ls. I haven't tried but gobgpd should receive and advertise bgp-ls, bgp-ls routes can be added via the api.

**Comment by fujita** [comment]
duplicated with https://github.com/osrg/gobgp/issues/2263
