### ISSUE TITLE
two BGP sessions with same remote host

### ISSUE THREAD

**Issue by bringingkatigbak** [osrg/gobgp#2262]
```
+--------------+         +--------------+
|              |         |              |
|              |         |              |
|      AS 16506|         |      AS 16512|
|      10.0.0.6|         |     10.0.0.12|
+--------------+         +--------------+
```
Both Configs of 10.0.0.6 and 10.0.0.66: https://gist.github.com/bringingkatigbak/b60c78d98e5acf9436f65c8298586221
Config of 10.0.0.12: https://gist.github.com/bringingkatigbak/7ed44a398b68579bc62394a69fe0e51d

Initially I have 1 gobgpd running on the left and right hosts. Then I start up a second gobgpd on the left host on different `port` and `--api-hosts` ports using a somewhat arbitrary IP address that none of the left host's interfaces actually have.

What happens is the right host keeps logging:
```{"Key":"10.0.0.6","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2020-04-11T11:20:41Z"}``` But I see that the original session with 10.0.0.6 is fine and in `Establ` state while session with 10.0.0.66 stays `Active`.

I know this is kind of weird setup but my question is if gobgp should be able to handle this setup? Can gobgp have two separate BGP sessions on two different sockets on the same remote host? is there any way to make this work?

**Comment by fujita** [comment]
No

**Comment by hongliangl** [comment]
I got the same log in a similar case:

- Create 3 gobgp servers.
  - Create gobgp server1 with asn 61179, listen port 1179, router-id 192.168.1.1.
  - Create gobgp server2 with asn 62179, listen port 2179, router-id 192.168.1.2.
  - Create gobgp server3 with asn 63179, listen port 3179, router-id 192.168.1.3.
- Start these 3 gobgp servers without specifying binding address.
- Add peer with address 127.0.0.1, port 1179, asn 61179 to server2.
- Add peer with address 127.0.0.1, port 2179, asn 62179 to server1.
- Add peer with address ::1, port 1179, asn 62179 to server3.
- Add peer with address ::1, port 3179, asn 63179 to server1.

I know this is not a normal case and is only used in my test code. Most times, it works well, but it fails occasionally. Could you help with that? Thanks a lot! @fujita
