### ISSUE TITLE
policy invalid

### ISSUE THREAD

**Issue by daysomeon** [osrg/gobgp#2264]
I running two gobgpd on 192.168.3.113 and 192.168.3.125
gobgpd version : 2.15.0
113 config file:
![image](https://user-images.githubusercontent.com/39798518/79974671-53a8fd00-84cc-11ea-897c-db6bdeb4a821.png)

125 config file:
![image](https://user-images.githubusercontent.com/39798518/79974724-6ae7ea80-84cc-11ea-8584-afcce6055dda.png)

when i am on 192.168.3.113 declare 1.1.1.1/32 network ， and contain 65525:18000 community，192.168.3.125 still receive
![image](https://user-images.githubusercontent.com/39798518/79974973-c619dd00-84cc-11ea-979e-89c05139768f.png)
![image](https://user-images.githubusercontent.com/39798518/79975010-dd58ca80-84cc-11ea-9637-4ea2f31c32f9.png)
![image](https://user-images.githubusercontent.com/39798518/79975040-e9dd2300-84cc-11ea-9b30-83e5bd973ae9.png)

1、why still receive rib？
2、why neighbor display one rib，but gobgp global rib is null , and mrb table dump file also zero

**Comment by fujita** [comment]
1. receive and doesn't insert it into the rib.
2. you use route-server mode. routes are not inserted into the global rib. mrt dump doesn't work with route-server mode.

**Comment by daysomeon** [comment]
thanks, now my gobgpd have  two  peer neighbors，i want receive them all rib and mrt dump it， and configure them with different policy attr，
example: accept export contain 1:1 communtiy router  to A neighbor, reject other router export
accept export contain 2:2 communtiy router  to B neighbor, reject other router export,  it's  real?

**Comment by daysomeon** [comment]
> 1. receive and doesn't insert it into the rib.
> 2. you use route-server mode. routes are not inserted into the global rib. mrt dump doesn't work with route-server mode.
thanks, now my gobgpd have two peer neighbors，i want receive them all rib and mrt dump it， and configure them with different policy attr，
example: accept export contain 1:1 communtiy router to A neighbor, reject other router export
accept export contain 2:2 communtiy router to B neighbor, reject other router export, it's real?

**Comment by fujita** [comment]
Add neighbor condition.
