### ISSUE TITLE
bgpattrtype_string.go out of date

### ISSUE THREAD

**Issue by dnikulin** [osrg/gobgp#2265]
`BGPAttrType` itself has had several commits since the file was auto-generated, but none of those commits re-generated the corresponding stringer code. This means several types do not have corresponding names, even though they appear in public BGP sessions.

**Comment by fujita** [comment]
I'm not sure what you mean. BGPAttrType is defined in bgp.go, which isn't auto-generated.

**Comment by dnikulin** [comment]
That's right, but `bgpattrtype_string.go` (in the issue title) is out of date with respect to bgp.go
None of the last several changes to `BGPAttrType` have included corresponding changes to `bgpattrtype_string.go` (generated by stringer)

**Comment by fujita** [comment]
Ah, understood. Can you create a pull request for updating?

**Comment by dnikulin** [comment]
I am very happy to do that, but even though it's trivial, it will require undertaking a legal process with my employer. I'll try to get that started and get back to you.
