### ISSUE TITLE
How to view global rib with regexp？

### ISSUE THREAD

**Issue by wangln** [osrg/gobgp#2270]
about 800k routing entries have been received. When I "gobgp global rib", my vm CPU is very high, and take about 3mins before output.
How to view global rib with regexp？

**Comment by fujita** [comment]
no such feature. longest/shortest/exact matches are supported.

https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#12-operations-for-global-rib---adddelshow--
