### ISSUE TITLE
【global rib issue】a rib can be advertised to neighbor only if policy must be configged  ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2271]
![image](https://user-images.githubusercontent.com/58503468/80465943-6a3cd180-896e-11ea-8283-047a8137cb8d.png)

if i don't config this policy,global rib can not be advertised to neighbor.
is that correct  ?reasonable  ?

**Comment by fujita** [comment]
you need to configure the export policies of the global rib
https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md#policy-model
