### ISSUE TITLE
 local network missing after restart

### ISSUE THREAD

**Issue by daysomeon** [osrg/gobgp#2272]
![image](https://user-images.githubusercontent.com/39798518/80556322-ca328700-8a05-11ea-945f-60bb97f35fd3.png)
when I restart gobgpd
![image](https://user-images.githubusercontent.com/39798518/80556365-ec2c0980-8a05-11ea-8425-84012aacc8a9.png)
how to still have local add network after gobgpd restart ?

**Comment by fujita** [comment]
run a scrip to add routes after restart.
