### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/osrg/gobgp/v2

### ISSUE THREAD

**Issue by KateGo520** [osrg/gobgp#2274]
## Background
The `github.com/osrg/gobgp` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v2`. And it’s module path is `"github.com/osrg/gobgp"`, instead of `"github.com/osrg/gobgp/v2"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version > v2.0.0 of the `osrg/gobgp`:
```
$ go get github.com/osrg/gobgp@v2.16.0
go: finding github.com/osrg/gobgp v2.16.0
go: finding github.com/osrg/gobgp v2.16.0
go get github.com/osrg/gobgp@v2.16.0: github.com/osrg/gobgp@v2.16.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
run `go get github.com/osrg/gobgp`, the version will stuck in v2.0.0:
```
$go get github.com/osrg/gobgp
go: downloading github.com/osrg/gobgp v2.0.0+incompatible
go: github.com/osrg/gobgp upgrade => v2.0.0+incompatible
```
SO anyone using Go modules will not be able to easily use any newer version of `osrg/gobgp`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/osrg/gobgp/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

**[*]** You can see who will be affected here: [3 module-unaware users, i.e., Rezopole/goasmap, thomasf/internet, alkasir/alkasir]
https://github.com/search?q=osrg%2Fgobgp+filename%3AGodeps.json+filename%3Avendor.conf+filename%3Avendor.json+filename%3Aglide.toml+filename%3AGodep.toml&type=Code

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v2 `subdirectory` (github.com/osrg/gobgp/v2) and place a new go.mod file in that subdirectory. The `module path` must end with `/v2`. Copy or move the code into the v2 subdirectory. Update `import statements` within the module to also use `/v2` (import "github.com/osrg/gobgp/v2/…"). Tag the release with `v2.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/osrg/gobgp@version-tag`, module users need to use this following way to get the `osrg/gobgp`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/osrg/gobgp@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `osrg/gobgp`.

**[*]** You can see who will be affected here: [31 module users, e.g., projectcalico/calicoctl, sbezverk/jalapeno-gateway, duanjiong/test-framework]
https://github.com/search?q=osrg%2Fgobgp+filename%3Ago.mod&type=Code

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by KateGo520** [comment]
@fujita  @serejkus

**Comment by fujita** [comment]
I can't break the existing software using gobgp.

> Kill the go.mod files.

This is a breaking change too, I think. I can't compile the following any more with this change:
https://github.com/fujita/misc

> Major version bump / repository change

This was the plan with some API changes (you can find some in the issues). It's overdue.

Having something like the following in go.mod works?

`github.com/osrg/gobgp v2.16.0+incompatible`

**Comment by VladoLavor** [comment]
@fujita

dependency marked as `+incompatible` means it uses major semver version >1 and it is not yet a go module, so nothing later than github.com/osrg/gobgp@v2.0.0 does not work this way

**Comment by fujita** [comment]
With that line, the specific version is fetched?

```
$ grep gobgp go.mod 
	github.com/osrg/gobgp v2.16.0+incompatible
```

after building the binary, I got the following
```
$ grep const pkg/mod/github.com/osrg/gobgp@v2.16.0+incompatible/internal/pkg/version/version.go 
const MAJOR uint = 2
const MINOR uint = 16
const PATCH uint = 0
```

**Comment by KateGo520** [comment]
```
$ grep go.mod 
	github.com/osrg/gobgp v2.16.0+incompatible
verifying github.com/osrg/gobgp@v2.16.0+incompatible/go.mod: github.com/osrg/gobgp@v2.16.0+incompatible/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/osrg/gobgp@v2.16.0+incompatible: 404 Not Found
```

**Comment by fujita** [comment]
`GOPRIVATE` doesn't work?

**Comment by KateGo520** [comment]
```
>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Cass\AppData\Local\go-build
set GOENV=C:\Users\Cass\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\software\workspace\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\software\work-software\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\software\work-software\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\work\研究生\实验室\Go\编程\workspace\gomodproject4\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Cass\AppData\Local\Temp\go-build092228838=/tmp/go-build -gno-record-gcc-switches
```

**Comment by duanjiong** [comment]
We could use  commit id  in go.mod.
github.com/osrg/gobgp v0.0.0-20200501041838-df76b278eee6

**Comment by fujita** [comment]
fixed with the major version bumped up to 3.
