### ISSUE TITLE
【mrt-dump】How to read the details of **.dump files when using mrt-dump ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2275]
![image](https://user-images.githubusercontent.com/58503468/80959969-7925f700-8e3a-11ea-909a-a7dda412c87c.png)

how to look into the dump file and read the details of gobgp updates or tables ?

**Comment by zhanggongc** [comment]
is there any tools for reading dump file specially  ?  need emergency help !!

**Comment by fujita** [comment]
https://blog.apnic.net/2018/11/29/new-mrt-bgp-reader-six-times-faster-than-its-predecessors/

**Comment by zhanggongc** [comment]
@fujita  sir, how to make use of bgpscanner after installing it  in one docker ?
![image](https://user-images.githubusercontent.com/58503468/81133435-3b34ea00-8f84-11ea-925f-f8e3878aa68a.png)
