### ISSUE TITLE
log level command is ready ?when can it be used for gobgp   ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2282]
![image](https://user-images.githubusercontent.com/58503468/81466043-fe295b80-9200-11ea-8d77-7e14c76259f5.png)

**Comment by serejkus** [comment]
here's a link to PR: https://github.com/osrg/gobgp/pull/2111
one more PR that may be interesting in this context too: https://github.com/osrg/gobgp/pull/1756

**Comment by fach** [comment]
There hasn't been any movement on #2111 so I took it over in #2329.

**Comment by fujita** [comment]
pushed https://github.com/osrg/gobgp/pull/2329
