### ISSUE TITLE
who know this warning report after killing gobgpd pid   ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2284]
root@53e02300d0f6:/sonic# 
root@53e02300d0f6:/sonic# ps aux |grep gobgp
root       843  0.0  0.0 921964 13372 pts/2    Sl   03:18   0:00 ./gobgpd -f gobgpd.conf
root       854  0.0  0.0  11112   960 pts/2    S+   03:19   0:00 grep gobgp
root@53e02300d0f6:/sonic# **kill 843**
root@53e02300d0f6:/sonic# setTCPMD5SigSockopt:return setsockOptString
setsockOptString:return opterr
**{"Key":"10.17.200.220","Topic":"Peer","level":"warning","msg":"failed to unset md5: no such file or directory","time":"2020-05-13T03:19:32Z"}**

what 's the meaning of this warning  ?

**Comment by vasya4k** [comment]
When you configure BGP to use MD5 security the actual MD5 string is going to be encoded  into TCP options header and not inside BGP messages themselves.  So when you kill gobgp there seems to be a race condition where the socket is closed before this gets executed.

/gobgp/pkg/server/server.go
`	for _, l := range s.listListeners(addr) {
		if err := setTCPMD5SigSockopt(l, addr, ""); err != nil {
			log.WithFields(log.Fields{
				"Topic": "Peer",
				"Key":   addr,
			}).Warnf("failed to unset md5: %s", err)
		}
	}`

It appears that setTCPMD5SigSockopt is trying to unset the MD5 for a given TCP socket which does not longer exist. In linux everything is a file so a socket is a file too hence the message "no such file or directory".  I am not sure if it is worth trying to fix this as if you sent kill -9 to a process there might always exist a potential race condition.

**Comment by fujita** [comment]
I don't think that it's worth fixing this. You can safely ignore this warning.
