### ISSUE TITLE
[problem]report "context deadline exceeded" when showing gobgp neighbors 

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2285]
I want to see the details of update packets ,so i open the log of debug level :
![image](https://user-images.githubusercontent.com/58503468/81900845-33162380-95f0-11ea-800f-6eb1e85183f6.png)

but when input ./gobgp neighbor command ,it reports "context deadline exceeded" and gobgpd process exit directly..
what is it's meaning  ? what is wrong  ?
![image](https://user-images.githubusercontent.com/58503468/81901215-ba639700-95f0-11ea-8493-ad6e5463c0ba.png)

**Comment by smarkm** [comment]
Hi @zhanggongc, you can use `ss -tap |grep 50051` to check the API server already started or not, the `gobgp` command talk with `gobgpd` via api server

**Comment by zhanggongc** [comment]
@smarkm , OK,I try it. thanks a lot
I should not modify the Debug level into Fatal log level, that result in gobgpd cann't continue to run next stage.
use info level will be ok.
