### ISSUE TITLE
AddPath request to BGP daemon failed with code: 2 message failed to unmarshal nlri: message is nil

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#2287]
Hello!

Thank you for such great progress with GoBGP development!

I'm using our own C++ based BGP library to craft attributes and NLRIs and it works fine with GoBGP 2.16.0 for IPv4.

We use following logic:
```
    auto ipv6_unicast_route_family = new gobgpapi::Family;

    ipv6_unicast_route_family->set_afi(gobgpapi::Family::AFI_IP6);
    ipv6_unicast_route_family->set_safi(gobgpapi::Family::SAFI_UNICAST);

    gobgpapi::Path* current_path = new gobgpapi::Path;
    current_path->set_allocated_family(ipv6_unicast_route_family);

    current_path->set_nlri_binary(binary_nlri.get_pointer(), binary_nlri.get_used_size());
    logger << log4cpp::Priority::DEBUG << "Binary NLRI size: " << binary_nlri.get_used_size();

    for (auto bgp_attribute : bgp_attributes) {
        current_path->add_pattrs_binary(bgp_attribute.get_pointer(), bgp_attribute.get_used_size());
        logger << log4cpp::Priority::DEBUG << "Populate BGP attribute with size: " << bgp_attribute.get_used_size();
    }    

    gobgpapi::AddPathRequest request;
    
    request.set_table_type(gobgpapi::TableType::GLOBAL);
    request.set_allocated_path(current_path);

    grpc::ClientContext context;
    gobgpapi::AddPathResponse response;

    auto status = stub_->AddPath(&context, request, &response);
```

But it does not work well with IPv6 Unicast announces.

Internally, for IPv6 announces we inject 3 attributes:
```
Populate BGP attribute with size: 41
Populate BGP attribute with size: 4
Populate BGP attribute with size: 7
```

But we do not use NLRI and it has zero size because it's not required for IPv6 announces but GoBGP requires it explicitly:
```
AddPath request to BGP daemon failed with code: 2 message failed to unmarshal nlri: message is nil
```

Also, we have exactly same issue with IPv4 Flow Spec announces, they do not use NLRI too and all information is carried in attributes:
```
2020-05-21 17:59:25,086 [DEBUG] Binary NLRI size: 0
2020-05-21 17:59:25,086 [DEBUG] Populate BGP attribute with size: 4
2020-05-21 17:59:25,086 [DEBUG] Populate BGP attribute with size: 50
2020-05-21 17:59:25,086 [DEBUG] Populate BGP attribute with size: 11
```

And error is exactly same:
```
AddPath request to BGP daemon failed with code: 2 message failed to unmarshal nlri: message is nil
```

Is it possible to omit requirement to have NLRI for such cases?

**Comment by fujita** [comment]
Like you do with ipv4, setting ipv6 binary nlri to `nlri_binry` doesn't work? Note that you don't need mp_reach attribute in that approach.

**Comment by pavel-odintsov** [comment]
Thank you for reply and recommendations! We're addressed this issue by setting nlri_binary to mp_reach attribute. In our configuration we've using same mp_reach attribyte for nlri_binary and for attributes_binary.

Would you consider making NLRI optional? So many modern BGP protocol families do not use it and it's not very obvious to use fake NLRI.

Thank you!
