### ISSUE TITLE
Inconsistent regex result for parseCommunityRegexp

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#2289]
Hi,

I have just noticed that parseCommunityRegexp returns inconsistent results if the community itself is parseable.

````
parseCommunityRegexp("6830:24370$")  => ^6830:247380$$
parseCommunityRegexp("^6830:24370$")  => ^^6830:247380$$
````

I believe the correct result should be:

```
parseCommunityRegexp("6830:24370$")  => 6830:24738$
parseCommunityRegexp("^6830:24370$")  => ^6830:247380$
```

This is caused by the matching regex repexpCommunity (regexp.MustCompile(`(\d+.)*\d+:\d+`)) which only matches on the numbers, but then the full arg is used:

```
        if repexpCommunity.MatchString(arg) {
		return regexp.Compile(fmt.Sprintf("^%s$", arg))
	}
```

I propose to either change the regex to:

```
regexp.MustCompile(`^(\d+.)*\d+:\d+$`)
```

or

```
regexp.MustCompile(`((\d+.)*\d+:\d+)`)
```

and use the substring match regex function.

**Comment by fujita** [comment]
Thanks a lot for the report. Can you send a pull request to fix this?

**Comment by Thoro** [comment]
Sorry it took that long ;)

Here is the PR #2320 

I also removed the parsing code from cmd/gobgp/policy.go and replaced it with the equivalent from pkg/internal/table, on the one hand it make sense to now have duplicate regex, but on the otherhand it uses the internal parsing, please decide if you want it that way or not!
