### ISSUE TITLE
this function return nil ,correct or make mistake ?

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2293]
type LsAddrPrefix struct {
	PrefixDefault
	Type   LsNLRIType
	Length uint16
	NLRI   LsNLRIInterface
}

func (l *LsAddrPrefix) MarshalJSON() ([]byte, error) {
	return nil, nil
}
>>>>why this function returns nil  ? should it be unusefull  ?

**Comment by fujita** [comment]
I guess that it's not implemented yet. Please send a pull request if you need.
