### ISSUE TITLE
MessageMTU error when redistribute static, ask for help

### ISSUE THREAD

**Issue by zhanggongc** [osrg/gobgp#2299]
config redistribute static route in gobgpd.conf 
![image](https://user-images.githubusercontent.com/58503468/85260340-1a294980-b49d-11ea-80e0-0c7bcbeedcbf.png)
and config FRR with static route item ,show ip route result is below:
![image](https://user-images.githubusercontent.com/58503468/85260561-7724ff80-b49d-11ea-91f3-41629eef4940.png)

but when gobgpd started up ,it reports MTU error:
![image](https://user-images.githubusercontent.com/58503468/85260733-ba7f6e00-b49d-11ea-9a10-3147f2925f6c.png)

I have not find the origin reason of this error. anyone know this problem  ?

**Comment by zhanggongc** [comment]
{"Data":"AwAAAAAASBcBAhgUAAAAAQAAAAACAAoAAAEBAAAAAAAAAAA=","Error":"MessageMTU message length invalid pos:24 rest:24","Header":{"Len":45,"Marker":254,"Version":6,"VrfID":0,"Command":33},"Topic":"Zebra","level":"warning","msg":"failed to decode body","time":"2020-06-22T07:15:15Z"}

**Comment by irino** [comment]
What version of frr do you use?

**Comment by zhanggongc** [comment]
@irino   FRR version is 7.2.1

**Comment by irino** [comment]
You need software-name option to use frr7.2.
Please see https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md.
And I pushed modified code yesterday. Perhaps the modified code may solve your problem. Please retry with newest code.

**Comment by zhanggongc** [comment]
@irino    thanks a lot.. I will try to test it again.
