### ISSUE TITLE
Penetration/Fuzz Testing?

### ISSUE THREAD

**Issue by lamannaj-amzn** [osrg/gobgp#2304]
Has any penetration or fuzz testing been done on GoBGP? I haven't seen any CVEs filed against it, so I'm curious if this has ever been done.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/pkg/packet/bgp/bgp_test.go#L1181

IIRC, I did something for the parser, but I didn't push the test code because it makes the CI really longer. I can't recall the details.
