### ISSUE TITLE
Speed of importing from GRT MRT file. 

### ISSUE THREAD

**Issue by buraglio** [osrg/gobgp#2307]
I don't know if this is an issue, user error, or just expected behavior. I have been working with goBGP for a while for some other things and wanted to use it to simulate a GRT in a lab environment. I have that working and am using the PAlo Alto MRT dump from RIPE. This is working, but my question is about performance and time. How long should it take to import a GRT into a goBGP instance? My system has 8 cores and 32G of RAM and has been happily importing the MRT file and re-announcing for almost 48 hours now, and is at around 500k ipv4 routes, and pretty much the entire v6 table. Am I missing any easy things that would cause the process to take this long? My command was pretty simple and based off of the current docs.

**Comment by fujita** [comment]
Just tried on my env (ec2 m5a.8xlarge: 32 vcpu 128 G),
```
$ time gobgp mrt inject global ~/rib.20190830.0800 

real	0m54.714s
user	1m15.184s
sys	0m29.717s
$ gobgp g r s
Table afi:AFI_IP safi:SAFI_UNICAST 
Destination: 771684, Path: 1528472
$ gobgp g r s -a ipv6
Table afi:AFI_IP6 safi:SAFI_UNICAST 
Destination: 78050, Path: 97319
```

**Comment by buraglio** [comment]
Huh. So it's likely a local problem

**Comment by fujita** [comment]
I didn't configure any peers. If you configure peers, then gobgpd receives routes from mrt, calculates the best paths, advertises them again and again. So it takes longer than the above.

**Comment by buraglio** [comment]
Ah, ok. that's my issue. I have two peers configured. Makes total sense now that I see it typed out here, because, duh, it's a BGP daemon.  =P Apologies for the noise.
