### ISSUE TITLE
gobgp does not support bgp flowspec redirect ip

### ISSUE THREAD

**Issue by xterms-art** [osrg/gobgp#2310]
gobgp does not support bgp flowspec redirect ip
https://tools.ietf.org/html/draft-ietf-idr-flowspec-redirect-ip-02

**Comment by vasya4k** [comment]
The RFC you listed is a draft which expired. This provides some details on IPv4 redirect https://tools.ietf.org/html/rfc7674  
For IPv6 there is another draft https://tools.ietf.org/html/draft-ietf-idr-flow-spec-v6-10 still it says  Redirect IPv6 (rt-redirect-ipv6) Type/Sub-Type 0x80/TBD . So I kind of fail to understand how one can implement the draft you posted the link to. However I can see Nokia are saying they have implemented the draft somehow.

**Comment by easternboyz** [comment]
is there a roadmap to support flowspec redirect ip?

**Comment by channelsss** [comment]
I'm interested in this feature.
WANguard is starting to develop GoBGP support.
It looks excellent to replace ExaBGP.

**Comment by fujita** [comment]
> I'm interested in this feature. WANguard is starting to develop GoBGP support. It looks excellent to replace ExaBGP.

Please send a pull request.

**Comment by channelsss** [comment]
i'm not a dev.
How can open a pull request ?
