### ISSUE TITLE
failure to withdraw w/parallel eBGP sessions

### ISSUE THREAD

**Issue by jwhited** [osrg/gobgp#2311]
Consider the following topology:

![bgp-lab-2](https://user-images.githubusercontent.com/10344482/89675581-05631280-d89f-11ea-97d0-9bd7e85de789.png)

When a route is injected at R3 and then subsequently removed, R1 and R2 fail to send withdraws over one of their two parallel eBGP sessions. This leads to a "stuck" route.

**Comment by Thoro** [comment]
I think I also ran into this with multiple route servers and multiple networks, i.e.

Router Servers: A, B, C 

and Clients 1 - 30, each client had two connections (eth0, ib0) to A,B,C - sometimes a route got stuck and I couldn't figure out why.

I have now separated the route servers into Ae Be Ce and Ai Bi Ci, this works.

(just fyi that other people also have that issue)

**Comment by fujita** [comment]
Very sorry for the delay. I've just merged the pull request. Thanks a lot!
