### ISSUE TITLE
why the bgp routes can not enter the rib of the linux kernel routing table ?

### ISSUE THREAD

**Issue by EW-ZQ** [osrg/gobgp#2313]
I have two VM (CentOS7) running the gobgp, and one of the gobgp advertise two route entries to another gobgp, which can be found at the log posted here, but why the "ip route" did not show the "10.10.10.0/24" with next hop 192.168.202.138 ? how to have the routes from gobgp to the linux kernel routing table ?

---------------------------------gobgp neighbor / global rib ------------------------------------
<pre>[root@localhost admin]# gobgp neighbor
Peer               AS  Up/Down State       |#Received  Accepted
192.168.202.138 65001 01:02:58 Establ      |        2         2
[root@localhost admin]# gobgp neighbor 192.168.202.138 adj-in
   ID  Network              Next Hop             AS_PATH              Age        Attrs
   0   10.10.10.0/24        192.168.202.138      65001                01:00:11   [{Origin: ?}]
   0   192.168.122.0/24     192.168.202.138      65001                01:02:16   [{Origin: ?}]
[root@localhost admin]# gobgp neighbor 192.168.202.138 adj-in 
   ID  Network              Next Hop             AS_PATH              Age        Attrs
   0   10.10.10.0/24        192.168.202.138      65001                01:00:24   [{Origin: ?}]
   0   192.168.122.0/24     192.168.202.138      65001                01:02:29   [{Origin: ?}]
[root@localhost admin]# ^C
</pre>
<pre>[root@localhost admin]# gobgp global rib
   Network              Next Hop             AS_PATH              Age        Attrs
*&gt; 10.10.10.0/24        192.168.202.138      65001                01:12:07   [{Origin: ?}]
*&gt; 192.168.122.0/24     192.168.202.138      65001                01:14:12   [{Origin: ?}]
[root@localhost admin]# 
</pre>

-------------------- ip route at VM --------------------------------------------------------
<pre>[root@localhost admin]# ip route
default via 192.168.202.2 dev eno16777736 proto dhcp metric 102 
192.168.17.0/24 dev ens37 proto kernel scope link src 192.168.17.150 metric 101 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 
192.168.202.0/24 dev eno16777736 proto kernel scope link src 192.168.202.137 metric 102 
[root@localhost admin]# 
</pre>

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md

**Comment by ldelossa** [comment]
@fujita am I mistaken, or does this only import kernel routes into gobpg? How do you export GoBPG learned routes to the kernel's routing table?
