### ISSUE TITLE
Mismatch between API and config default policy type enums

### ISSUE THREAD

**Issue by alistairking** [osrg/gobgp#2321]
Hey, first of all, thanks for the great project!

I'm pretty new to this code base, so my apologies if I'm missing something, but I've come across what appears to be a mismatch between the enum values for Default Policy Types in the gRPC API and the internal config.

If I have some code like
```golang
s.StartBgp(ctx, &api.StartBgpRequest{
    Global: &api.Global{
        ...
        ApplyPolicy: &api.ApplyPolicy{
		ImportPolicy: &api.PolicyAssignment{
			DefaultAction: api.RouteAction_REJECT,
		},
		ExportPolicy: &api.PolicyAssignment{
			DefaultAction: api.RouteAction_REJECT,
		},
	},
    },
})
```

From what I can tell, the `api.RouteAction_REJECT` value is 2: 
https://github.com/osrg/gobgp/blob/4e4113124f8d4a43b638d63d10af8698b4370d93/api/gobgp.pb.go#L170

But walking through the functions called by `StartBgp`:
`StartBgp` → `newGlobalFromAPIStruct` → `readApplyPolicyFromAPIStruct` → `config.IntToDefaultPolicyTypeMap`
I end up at https://github.com/osrg/gobgp/blob/50df0390faedad489614c94bd00b1749d57dbbab/internal/pkg/config/bgp_configs.go#L708 which only has the values 0 (accept) and 1 (reject).

If I pass in an explicit `1` to the API then this seems to get correctly recognized as "reject".

**Comment by fujita** [comment]
Thanks for the report. We should do something like
https://github.com/osrg/gobgp/compare/master...fujita:fix-policy-conversion

**Comment by alistairking** [comment]
Yeah, that would do the trick. Thanks!

**Comment by fujita** [comment]
Fixed.
