### ISSUE TITLE
How to set IPv6 multipath path identifier via gRPC ?

### ISSUE THREAD

**Issue by mimuret** [osrg/gobgp#2333]
I tried to add IPv6 multi-path routes via gRPC.
https://github.com/mimuret/gobgp-ipv6-multipath/blob/master/test.go

But, BGP Server had only one path.

Maybe, It looks like you are overriding nlri when using MP-BGP.
https://github.com/osrg/gobgp/blob/7ce0dddd4f49307540b13024168310c237d28c2f/pkg/server/grpc_server.go#L292-L314

**Comment by fujita** [comment]
IIRC, you are right. via AddPath API, gobgpd doesn't accept multi paths with the same nlri.

**Comment by mimuret** [comment]
Thanks, I understand.
