### ISSUE TITLE
Getting paths

### ISSUE THREAD

**Issue by blakexdd** [osrg/gobgp#2350]
Can i get the same info from api as if using `gobgp -p 50071 global rib -a ipv4-flowspec` command?
The only thing i found is ListPath method, but it doesn't look like correct command

**Comment by fujita** [comment]
ListPath API provides the information that you want to get.

**Comment by blakexdd** [comment]
Thank you. Can i find any examples how to do so?

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/cmd/gobgp/neighbor.go#L863

gobgp command is implemented on the top of the APIs.

**Comment by blakexdd** [comment]
Got it. Thank you again :)
