### ISSUE TITLE
Issue with GoBGP+Zebra integration in frr 7.5-0~deb10

### ISSUE THREAD

**Issue by venkat-xaptum** [osrg/gobgp#2351]
I am facing an issue with GoBGP + Zebra integration after upgrading to `frr 7.5-0~deb10`. This worked fine with `frr 7.3.1-1+frr1~deb10u1`. 

**To Reproduce**
1. Install `frr 7.5-0~deb10`
2. Install GoBGP v 2.21.0 (available from https://github.com/osrg/gobgp/releases/tag/v2.21.0)
3. Create a GoBGP config file `/etc/gobgp/gobgp.conf`
```
[global.config]
        as = 65536
        router-id = "fc00:1::1000"

[zebra]
    [zebra.config]
        enabled = true
        url = "unix:/var/run/frr/zserv.api"
        version = 6
```
4. Start `frr`
```bash
$ systemctl start frr
```
5. Start `gobgpd`
```bash
$ gobgpd -f /etc/gobgp/gobgp.conf`
```
`gobgpd` hangs, and `frr` throws lots of error messages in `/var/log/frr/frr.log`

From the updates by FRR team in https://github.com/FRRouting/frr/issues/7567, this is potentially an issue with GoBGP.

**Comment by irino** [comment]
My PR #2359 was merged to master branch. Please use master branch.
