### ISSUE TITLE
Filtered routes showed as accepted

### ISSUE THREAD

**Issue by bugtoo** [osrg/gobgp#2371]
Hello,
I have a test setup with 4 neighbors:

```
[root@net-rr3 /]# gobgp nei 
Peer             AS  Up/Down State       |#Received  Accepted
10.25.25.54 65530 01:28:29 Establ      |       25        25
10.25.25.53 65530 00:59:55 Establ      |       24        24
10.25.22.1  65530 01:28:22 Establ      |       29        29
192.168.2.1 65530 01:28:54 Establ      |       25        25
```

Neighbor 10.25.22.1 is sending 29 ipv4 prefixes that are all correctly filtered by the global policy.
This works fine from the BGP point of view but both the CLI and the API are reporting all prefixes being accepted, making it impossible to monitor it correctly, while the filtered list via API works fine (tested with alice-lg).

Any suggestions?
(running on version 2.23)

**Comment by fujita** [comment]
To get the number of accepted, you apply policies. With lots of peers and policies, it takes long to execute `gobgp neighbor` command. To avoid that, the above accepted numbers represent dropped routes due to as-loop, etc.

**Comment by bugtoo** [comment]
Thanks for the explanation @fujita. Is there a way to get the number of accepted routes and number of announced routes from/to a certain neighbor after the filters have been applied, via API and/or CLI?

**Comment by fujita** [comment]
Getting all the routes in the global rib gives the number of accepted routes. Getting the adj-rib for a certain neighbor gives the number of announced routes. It might be useful to add an option to ListPath API to get the routes from a certain neighbor in the global rib.
