### ISSUE TITLE
set-community BGP action

### ISSUE THREAD

**Issue by eimann** [osrg/gobgp#2384]
Hi,

defining this in a BGP input policy doesn't do anything:

[policy-definitions.statements.actions.bgp-actions.set-community]
  options = "remove"

I would expect it to remove all community, but nothing happens. How would one clean up all received BGP communities?

**Comment by fujita** [comment]
You need to specify what communities should be removed together.
```
[policy-definitions.statements.actions.bgp-actions.set-community.set-community-method]
    communities-list = ["[0-9]+:[0-9]+"]
```

**Comment by eimann** [comment]
Thank you.
