### ISSUE TITLE
QUESTION: what is the difference between `adj-in` and `local` in cli

### ISSUE THREAD

**Issue by nskalis** [osrg/gobgp#2388]
Hi,

would you be so kind to explain the difference between `adj-in` and `local`

- `gobgp neighbor 10.31.4.1 adj-in` and
- `gobgp neighbor 10.31.4.1 local` 

?

**Comment by fujita** [comment]
`local` is for route server setup
https://github.com/osrg/gobgp/blob/master/docs/sources/route-server.md
