### ISSUE TITLE
bmp.go -- stats report message BMPStatsTLV32 ParseValue sames wrong

### ISSUE THREAD

**Issue by xskingdom** [osrg/gobgp#2389]
func (s *BMPStatsTLV32) ParseValue(data []byte) error {
	if s.Length != 4 {
		return fmt.Errorf("invalid length: %d bytes (%d bytes expected)", s.Length, 4)
	}
	s.Value = binary.BigEndian.Uint32(data[:8])
	return nil
}

There should be "s.Value = binary.BigEndian.Uint32(data[:4])" ?

**Comment by fujita** [comment]
Yeah, looks like so. Can you send a pull request for this?

**Comment by xskingdom** [comment]
OK, Pull Request #2393
