### ISSUE TITLE
PANIC on receipt of RFC 9003 (shutdown message)

### ISSUE THREAD

**Issue by agalloGWU** [osrg/gobgp#2391]
Sending a shutdown message ([RFC9003](https://tools.ietf.org/html/rfc9003)) to GoBGP v2.24.0 causes a panic:

```
panic: runtime error: slice bounds out of range [:19] with capacity 17

goroutine 78 [running]:
github.com/osrg/gobgp/pkg/server.decodeAdministrativeCommunication(...)
        /home/runner/work/gobgp/gobgp/pkg/server/util.go:65
github.com/osrg/gobgp/pkg/server.(*fsmHandler).recvMessageWithError(0xc00018c9a0, 0x0, 0x0, 0x0)
        /home/runner/work/gobgp/gobgp/pkg/server/fsm.go:1082 +0x27bf
github.com/osrg/gobgp/pkg/server.(*fsmHandler).recvMessageloop(0xc00018c9a0, 0xdeb700, 0xc00021e940, 0xc0001af2b0, 0x0, 0x0)
        /home/runner/work/gobgp/gobgp/pkg/server/fsm.go:1721 +0x62
created by github.com/osrg/gobgp/pkg/server.(*fsmHandler).established
        /home/runner/work/gobgp/gobgp/pkg/server/fsm.go:1743 +0x1c2
```

Source of the message: Junos OS  20.1R2.7

GoBGP configuration used:
```
[global.config]
as = 64512
router-id = "172.16.12.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.55.1"
    peer-as = 4901
```

Junos config
```
group GoBGP {
    type external;
    peer-as 64512;
    shutdown {
        notify-message "please dont crash";
    }
    neighbor 172.17.55.22;
}
```

details of packet sent
```
Border Gateway Protocol - NOTIFICATION Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 38
    Type: NOTIFICATION Message (3)
    Major error Code: Cease (6)
    Minor error Code (Cease): Administratively Shutdown (2)
    Data: 706c6561736520646f6e74206372617368
```

I tried with different messages content / different message lengths.  Panic is reproducible.

**Comment by fujita** [comment]
Thanks for the report. I've just pushed the fix. Can you try the latest master?
https://github.com/osrg/gobgp/commit/65d094d7f25e7304832b104f429449cbcd22770d

**Comment by agalloGWU** [comment]
gobgpd no longer panics.  However, it looks like the first character of the message is being clipped:
message sent:
```
    shutdown {
        notify-message "fujita fixed this problem.  no more panic on BGP shutdown notification";
```

gobgpd message on the console:
```
{"Code":6,"Communicated-Reason":"ujita fixed this problem.  no more panic on BGP shutdown notification","Data":"","Key":"172.17.55.1","Subcode":2,"Topic":"Peer","level":"warning","msg":"received notification","time":"2021-02-24T11:09:16-05:00"}
```

Sorry- I don't know enough go to fix that.  I did try a few things in util.go, but same behavior- first character is dropped.

Thanks for the quick response!

**Comment by fujita** [comment]
![スクリーンショット 2021-03-02 14 15 46](https://user-images.githubusercontent.com/726426/109601592-7e3efa00-7b62-11eb-9adc-e2c8f95ce0f6.png)
I tried frr with GoBGP. GoBGP properly showed the notification message that frr sent. If you send a pcap file, I could figure out.

**Comment by agalloGWU** [comment]
Thanks for taking a look at this.

Message sent from Junos 20.1R2.7:
```
group GoBGP {
    type external;
    peer-as 64512;
    shutdown {
        notify-message "this is an RFC9003 message";
    }
    neighbor 172.17.55.22;
}
```

Message received:
```
{"Code":6,"Communicated-Reason":"his is an RFC9003 message","Data":"","Key":"172.17.55.1","Subcode":2,"Topic":"Peer","level":"warning","msg":"received notification","time":"2021-03-02T09:07:07-05:00"}
{"Key":"172.17.55.1","Reason":"notification-received code 6(cease) subcode 2(administrative shutdown)","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2021-03-02T09:07:07-05:00"}
```

Full pcap attached.

BGP NOTIFICATION message:
```
Border Gateway Protocol - NOTIFICATION Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 47
    Type: NOTIFICATION Message (3)
    Major error Code: Cease (6)
    Minor error Code (Cease): Administratively Shutdown (2)
    Data: 7468697320697320616e2052464339303033206d657373616765
```

Decode in Wireshark as
```
0000   74 68 69 73 20 69 73 20 61 6e 20 52 46 43 39 30   this is an RFC90
0010   30 33 20 6d 65 73 73 61 67 65                     03 message
```

[AdminMSG1.pcap.gz](https://github.com/osrg/gobgp/files/6069309/AdminMSG1.pcap.gz)


Thank you.

**Comment by fujita** [comment]
Seems that Junos doesn't implement RFC9003 properly, as you can see, Wireshark prints the data as hex. Wireshark can decode the data as text if the notification message format is proper (Junos doesn't set shutdown communication length field).

![スクリーンショット 2021-03-03 8 43 07](https://user-images.githubusercontent.com/726426/109730505-ee9a5980-7bfc-11eb-919f-a53f88a69c39.png)
