### ISSUE TITLE
Load injected routes after daemon restart

### ISSUE THREAD

**Issue by mkhachfeh** [osrg/gobgp#2411]
Hello,

Kindly I built GoBGPd on Ubuntu system, and depends on design some routes are injected there manually like:

`gobgp global rib add -a ipv4 10.10.10.0/24 nexthop 2.2.2.2`

And working fine, till the point I restart the daemon, which will affect into losing these manually injected routes.

Is there any built-in option within GoBGP to load/inject these routes automatically for example from a file/DB once it is restarted?
Or I need to develop that from scratch?

Thanks,
Mou

**Comment by fujita** [comment]
No such option.
