### ISSUE TITLE
Is there any document for beginners to learn how to compile GoBGP? and the architecture and design details of GoBGP?

### ISSUE THREAD

**Issue by MaoJianwei** [osrg/gobgp#2417]
Hi, friends,

I'm a newcomer, but I don't find a document in https://osrg.github.io/gobgp/ and https://github.com/osrg/gobgp/tree/master/docs/sources,
about how to compile GoBGP, and about the architecture and design details of GoBGP.

Is there any meterials about that?

Thanks!
Mao

**Comment by fujita** [comment]
GoBGP doesn't nothing special so you can compile in the same way that you can compile Go code. If you need the exact command lines, for example, you can use Dockerfile for GoBGP https://github.com/osrg/dockerfiles/blob/master/gobgp/Dockerfile

Unfortunately, There is no architecture or design docs.

**Comment by MaoJianwei** [comment]
Thanks @fujita :)
