### ISSUE TITLE
Have you guys discussed about exploring https://tools.ietf.org/html/draft-ietf-idr-performance-routing-00?

### ISSUE THREAD

**Issue by c4milo** [osrg/gobgp#244]
https://tools.ietf.org/html/draft-ietf-idr-performance-routing-00

**Comment by ishidawataru** [comment]
I didn't know this I-D but interesting! Do you have any use case to use this?

**Comment by c4milo** [comment]
The best CDNs I've seen use Anycast and BGP to pick the closest edge server to the user. So, factoring latency in addition to number of hops is pretty convenient. I know Akamai does it using their own internal magic for instance. But, it is cool that it is getting standardized at the IETF.

**Comment by c4milo** [comment]
In the introduction of the draft they also explain it the reasoning behind it.

**Comment by ishidawataru** [comment]
I see. Do you know any CDNs that would be interested in this feature?
We would work together.

**Comment by c4milo** [comment]
Unfortunately not. The ones I know have enough engineering ability to craft the algorithm by themselves.

**Comment by fujita** [comment]
Seems that the draft didn't make it. Closed.
