### ISSUE TITLE
ListVrf grpc call seems to be returning all VRFs

### ISSUE THREAD

**Issue by edoboker** [osrg/gobgp#2445]
Hi,

I've been exploring GoBGP's gRPC API using Golang, and seemed to have stumbled upon a weird issue - when initiating a call, the server randomly returns a VRF regardless of the name specified in the ListVrfRequest object.

**Environment:**

- Gobgpd and gobgp are running on Ubuntu18.04 (which is running as WSL)
- Golang 1.16 on windows

**Steps to reproduce:**

1. Run gobgpd and create a few VRFs using the CLI
2. Initiate a ListVrf call with a specific VRF name in the request
3. Repeat step 2 multiple times and compare the results

**Expected results:**

- The same VRF object is always returned as the result of the API call

**Observed results:** 

- All of the VRFs are returned in some arbitrary/random order

My code:
`
	package main

	import (
		"fmt"
		"log"

		"golang.org/x/net/context"
		"google.golang.org/grpc"

		gobgpapi "github.com/osrg/gobgp/api"
	)

	func main() {

		conn, err := grpc.Dial("localhost:50051", grpc.WithInsecure())
		if err != nil {
			log.Fatalf("grpc.Dial err: %v", err)
		}

		client := gobgpapi.NewGobgpApiClient(conn)

		req := gobgpapi.ListVrfRequest{
			Name: "test1",
		}

		if c, err := client.ListVrf(context.Background(), &req); err != nil {
			log.Fatal(err)
		} else {
			t, _ := c.Recv()
			fmt.Println(t.Vrf)
		}
	}
`

**Comment by fujita** [comment]
Fixed. Please try the master. The order isn't guaranteed though.
