### ISSUE TITLE
Exact syntax of golang ListPath with VPNv4

### ISSUE THREAD

**Issue by edoboker** [osrg/gobgp#2460]
Hi,

I'm not exactly sure what is the correct usage of the function since there's no relevant documentation. What I've done is first configure a route using the CLI:

``` 
Predator:~$ gobgp global rib add -a vpnv4 10.4.3.0/24 label 450 rd 100:100
Predator:~$ gobgp global rib -a vpnv4
   Network              Labels     Next Hop             AS_PATH              Age        Attrs
*> 100:100:10.4.3.0/24  [450]      0.0.0.0                                   00:00:29   [{Origin: ?}]
``` 
Then in go I run the following code:
```
conn, err := grpc.Dial("localhost:50051", grpc.WithInsecure())
	if err != nil {
		log.Fatalf("grpc.Dial err: %v", err)
	}
client := gobgpapi.NewGobgpApiClient(conn)var tableLookupPrefixes []*gobgpapi.TableLookupPrefix

tableLookupPrefixes = append(tableLookupPrefixes, &gobgpapi.TableLookupPrefix{
Prefix:       "101:100:10.4.3.0/24",
//LookupOption: gobgpapi.TableLookupOption_LOOKUP_EXACT,
})
listPathReq = gobgpapi.ListPathRequest{
TableType: gobgpapi.TableType_GLOBAL,
Family: &gobgpapi.Family{
	Afi:  gobgpapi.Family_AFI_IP,
	Safi: gobgpapi.Family_SAFI_MPLS_VPN,
},
Prefixes: tableLookupPrefixes,
}

if c, err := client.ListPath(context.Background(), &listPathReq); err != nil {
log.Fatal(err)
} else {
t, _ := c.Recv()
fmt.Println(t)
}
```
Which returns a <nil> value. Is there something wrong with the request? I've tried a "10.4.3.0/24" prefix to no avail...

**Comment by fujita** [comment]
vpnv4 doesn't support prefix filtering in ListPath API. Use empty prefixes in ListPathRequest.

**Comment by fujita** [comment]
`t, _ := c.Recv()`
You get an error here.

**Comment by edoboker** [comment]
Is there any intention to add support to this? Or at least document which APIs allow which actions? It could save a ton of work...

**Comment by fujita** [comment]
Pull requests are very welcome.

**Comment by edoboker** [comment]
Not sure if this is worth opening a new issue, similar to another issue I've opened in the past (#2445) - the ListPath action returns all vpnv4 routes in some random order instead of returning all paths in a list or channel of some sort. Is this by design, @fujita ?

**Comment by fujita** [comment]
Yes, by design.

**Comment by fujita** [comment]
LIstPath API returns all routes in a random order. Filtering are supported with IP v4/v6. Nobody hasn't asked for the feature with other families. If you want, please send a pull request.
