### ISSUE TITLE
SIGSEGV when trying to send empty protobuf for add request

### ISSUE THREAD

**Issue by vhsmacabre** [osrg/gobgp#2463]
**GoBGP version**
v2.30.0

**Issue description**
`gobgpd` falling with panic when I'm trying to make gRPC add request with empty protobuf

**How to reproduce**
1. Download [python script](https://github.com/osrg/gobgp/files/7091308/add_empty_proto.zip)
2. `python3 add_empty_proto.py`

Result: `panic: runtime error: invalid memory address or nil pointer dereference`

<details>
 <summary>Stacktrace</summary>
<pre>
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa52017]

goroutine 22 [running]:
github.com/osrg/gobgp/pkg/server.newNeighborFromAPIStruct(0x0, 0xb0e000, 0xc0000bca20, 0xc000188030)
	/home/runner/work/gobgp/gobgp/pkg/server/grpc_server.go:643 +0x57
github.com/osrg/gobgp/pkg/server.(*BgpServer).AddPeer.func1(0x49e229, 0xaf4880)
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:2937 +0x36
github.com/osrg/gobgp/pkg/server.(*BgpServer).handleMGMTOp(0xc0000d4d80, 0xc00020efe0)
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:240 +0x47
github.com/osrg/gobgp/pkg/server.(*BgpServer).Serve(0xc0000d4d80)
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:422 +0x735
created by main.main
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/main.go:153 +0x38f
</pre>
</details>

**Comment by ton31337** [comment]
This is already fixed in master, can be closed.
