### ISSUE TITLE
bgp bandwidth community -- EC_SUBTYPE_LINK_BANDWIDTH

### ISSUE THREAD

**Issue by gpl** [osrg/gobgp#2466]
Hello,

I'm trying to use EC_SUBTYPE_LINK_BANDWIDTH ( https://datatracker.ietf.org/doc/html/draft-ietf-idr-link-bandwidth-06) with gobgp, but it looks like the only extended communities supported are RT, SoO, and encap.

Could this be added?  Thank you!

**Comment by ton31337** [comment]
I can work on this.

**Comment by fujita** [comment]
surely, go ahead.

**Comment by fujita** [comment]
@gpl is this what you wanted?

**Comment by gpl** [comment]
Hello,

We'll test this patch out next week and see if it works, thank you!

**Comment by gpl** [comment]
Hello,

Apologies for the late reply.  It looks like that patch is working, thank you!

**Comment by fujita** [comment]
please create a new issue if the current code doesn't work as expected.

**Comment by gpl** [comment]
apologies, we have had time to look at this and have been busy testing it.  however there is a typo in the name of 
LinkBandiwdthExtended

should be
LinkBandwidthExtended

I will make a new PR shortly to correct this, if that works

**Comment by fujita** [comment]
thanks!
