### ISSUE TITLE
How to prevent zebra from feeding FIB to the kernel?

### ISSUE THREAD

**Issue by difficultwork** [osrg/gobgp#2509]
I do not need forwarding function, so I do not want affect the kernel FIB.
how could I do? is there any configuration option or command?

thanks

**Comment by fujita** [comment]
If you don't add zebra config to GoBGP's config file, GoBGP doesn't use zebra.

**Comment by difficultwork** [comment]
> If you don't add zebra config to GoBGP's config file, GoBGP doesn't use zebra.

thanks, fujita.

sometimes zebra is needed. I will ask somebody in frr project~
