### ISSUE TITLE
HELP: anyone start gobgp and zebra in different network namespace?

### ISSUE THREAD

**Issue by difficultwork** [osrg/gobgp#2517]
I hope that deploying gobgp and zebra in different containers. (firstly I used quagga, but quagga did not support tcp socket, so I switched frr)

when I started zebra with opt '-z 0.0.0.0:2600' in alpine container, it failed with this information:
```
ZEBRA: [EC 100663299] Can't bind zserv socket on 0.0.0.0:2600: Permission denied
```
my linux kernel version is 2.34.0.
alpine linux version is 3.14.
frr version is 7.5.1.

I set cap for zebra, but has the same problem.
```
/ # getcap /usr/lib/frr/zebra
/usr/lib/frr/zebra cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_admin=eip
```

are there any details I missed?

@fujita please please help me. thanks

**Comment by imcom** [comment]
It does not seem to be a gobgp issue ... rather it is your container configuration issue with zebra, perhaps some privileges required or some SEC CAPs ? Do you have issue with zebra just set privileged: true ?

**Comment by difficultwork** [comment]
@imcom thank you for your reply.
it is definitely not gobgp issue.
and I set ```--privileged=true``` when I start container of zebra(frr).

**Comment by imcom** [comment]
Could you switch to some other base OS for the FRR container? It might be easier to use a debian/ubuntu release for the base OS, slim version can also offer the size advantage

**Comment by difficultwork** [comment]
@imcom thanks, imcom. i will try other OS.
BTW: can you add me as a wechat friend? or is there wechat group of gobgp? my id is: yemo31995556.

**Comment by imcom** [comment]
> @imcom thanks, imcom. i will try other OS. BTW: can you add me as a wechat friend? or is there wechat group of gobgp? my id is: yemo31995556.

There is no WeChat group for GoBGP at least none that I know about, do you use slack? The maintainers and me are all in the slack channel, which is preferred gobgp.slack.com

**Comment by difficultwork** [comment]
> > @imcom thanks, imcom. i will try other OS. BTW: can you add me as a wechat friend? or is there wechat group of gobgp? my id is: yemo31995556.
> 
> There is no WeChat group for GoBGP at least none that I know about, do you use slack? The maintainers and me are all in the slack channel, which is preferred gobgp.slack.com

can you invite me，please? yemo@foxmail.com

**Comment by imcom** [comment]
I could not find where to invite, just register a Slack account, the workspace of GoBGP is open to public I assume

**Comment by imcom** [comment]
you can find the link in project README, but here it goes https://join.slack.com/t/gobgp/shared_invite/zt-g9il5j8i-3gZwnXArK0O9Mnn4Yu~IrQ

**Comment by difficultwork** [comment]
> you can find the link in project README, but here it goes https://join.slack.com/t/gobgp/shared_invite/zt-g9il5j8i-3gZwnXArK0O9Mnn4Yu~IrQ

ok, i'm in. thank you very much~
