### ISSUE TITLE
Uppercase ipv6 don't match with peer

### ISSUE THREAD

**Issue by MrFreezeex** [osrg/gobgp#2530]
If I put my ipv6 address with uppercase characters in the config, the peer is successfully added but the config can't match it.
```
Feb 04 16:57:27 redacted.cern.ch gobgpd[273049]: {"Key":"<redacted>::100:2DE","Topic":"config","level":"info","msg":"Add Peer","time":"2022-02-04T16:57:27+01:00"}
Feb 04 16:59:27 redacted.cern.ch gobgpd[273049]: {"Key":"<redacted>::100:2de","Topic":"Peer","level":"info","msg":"Can't find configuration for a new passive connection","time":"2022-02-04T16:59:27+01:00"}
```

Obviously this isn't very severe, a simple workaround is to put everything in lowercase!

I didn't tested but probably if you don't use the "::" notation in the config the behavior would be similar.

**Comment by fujita** [comment]
"::" should work.

RFC says:
>The characters "a", "b", "c", "d", "e", and "f" in an IPv6 address MUST be represented in lowercase

https://datatracker.ietf.org/doc/html/rfc5952#section-4.3

**Comment by MrFreezeex** [comment]
Oh you are right, I am using puppet and it prints ipv6 in uppercase by default unfortunately... Will try to report somewhere that they should use lowercase by default instead :)
