### ISSUE TITLE
GoBGP 3.0.0 can't work with FRR 8.2.2

### ISSUE THREAD

**Issue by SLoeuillet** [osrg/gobgp#2538]
Hello,

Had GoBGP 3.0.0 working with FRR 8.1.0
FRR 8.2.2 was just released, I tested both together :

Mar 22 09:52:59 router00-network-htz systemd[1]: Started gobgp.service.
Mar 22 09:52:59 router00-network-htz gobgpd[61182]: {"level":"info","msg":"gobgpd started","time":"2022-03-22T09:52:59+01:00"}
Mar 22 09:52:59 router00-network-htz gobgpd[61182]: {"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2022-03-22T09:52:59+01:00"}
Mar 22 09:52:59 router00-network-htz zebra[54372]: [V98V0-MTWPF] client 33 says hello and bids fair to announce only bgp routes vrf=0
Mar 22 09:52:59 router00-network-htz gobgpd[61182]: {"Topic":"Zebra","Version":6,"level":"info","msg":"success to connect to Zebra","time":"2022-03-22T09:52:59+01:00"}
Mar 22 09:52:59 router00-network-htz gobgpd[61182]: {"Data":"/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlZmF1bHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","Error":"unknown route type: 254 in version: 6 ()","Header":{"Len":86,"Marker":254,"Version":6,"VrfID":0,"Command":33},"Topic":"Zebra","level":"warning","msg":"failed to decode body","time":"2022-03-22T09:52:59+01:00"}

Went back to frr 8.1.0 then restarted GoBGP, zebra & GoBGP can communicate again together

**Comment by SLoeuillet** [comment]
https://frrouting.org/release/8.2.2/

**Comment by irino** [comment]
I sent PR #2548. This PR is merged.

**Comment by fujita** [comment]
@irino Thanks a lot!
