### ISSUE TITLE
AddPath API Call returns OK response if uuid.NewRandom fails

### ISSUE THREAD

**Issue by dawn-minion** [osrg/gobgp#2560]
In this block of code here: https://github.com/osrg/gobgp/blob/2117125f0dc41671fdfc069b953059f568010ea5/pkg/server/server.go#L2141-L2145 
the code checks if an error was returned by `uuid.NewRandom` before assigning it to `s.uuidMap`, but it does not return the error to the caller if it fails. This then leads to an OK response being sent back to the caller, with a `Uuid` set to empty. 

It seems like the final `return nil` line there should actually be `return err` to indicate to the caller there was an error.

**Comment by fujita** [comment]
Thanks, fixed:
https://github.com/osrg/gobgp/commit/42a5f1d771d574c0759701444246e8e1b9585efc
