### ISSUE TITLE
Support for VPLS route family

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#2590]
Hey!

Currently, route family VPLS (AFI L2VPN/SAFI VPLS) is not supported. A BGP session with the family enabled will trigger an error during parsing due to the inability to instantiate a prefix.

I can try to implement it as it seems simple enough (it is not parametrized). Is there a recent commit adding a route family that I could use?

**Comment by fujita** [comment]
SAFI_MUP?
https://github.com/osrg/gobgp/commit/3e31939c008d0ad411466d478e2d0139f6ff10f7
