### ISSUE TITLE
Q&A - Advice on Best Way to Add Statement to an Existing Policy

### ISSUE THREAD

**Issue by aauren** [osrg/gobgp#2636]
When using gobgp as a library, I'm not sure if I understand the intended way to add a statement to an existing policy.

I can see that there is an `AddStatement()` method, but that doesn't seem to have a way to specify the policy that it is supposed to be added to. On the policy API I don't see just an `UpdatePolicy()` function that would allow me to add the statement to an existing policy object and then update it with GoBGP. Instead there is a `SetPolicies()` API function, but that seems to throw away all of the existing policies and rebuild them from scratch with what you call `SetPolicies()` with. When I played with this, it seemed as though it also removed all of the DefinedSets that I had created prior to calling `SetPolicies()`.

Could you please advise on the intended way to use the API to inject a statement into an existing policy?

Also, if I were to do something like `DeletePolicy` and `AddPolicy` I would assume that there would be a brief period of time when advertised routes could be affected between the delete and add operation, is this a correct assumption?

**Comment by aauren** [comment]
@fujita - any thoughts on this? I'm trying to figure out the best way to adjust this code here: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/bgp_policies.go#L467-L622

Because when defined sets are empty it causes the conditional to always be true, I prefer to add and withdraw statements from a given policy. Currently, the code only checks if the policy exists and is assigned. However, I'm a bit at a loss on how to add statements to an existing policy without having to re-create all policies. Using GoBGP as a library seems complex in this manner (although I could also be missing something obvious).

The easiest thing to do using what I know works with the GoBGP library would be to delete the policy and re-add it, but I'm afraid that this may have negative consequences on my advertisements in the few ms between the delete and the add operation.

It would really be helpful if there was some more documentation with the library functions or some more examples on how they are intended to be used.

**Comment by fujita** [comment]
You could modify the existing policy but in a very limited way.
```
	s.AddStatement(context.Background(), &api.AddStatementRequest{
		Statement: &api.Statement{
			Name: "st0",
			Actions: &api.Actions{
				Med: &api.MedAction{
					Value: 1,
				},
			},
		},
	})

	s.AddStatement(context.Background(), &api.AddStatementRequest{
		Statement: &api.Statement{
			Name: "st1",
			Actions: &api.Actions{
				RouteAction: api.RouteAction_ACCEPT,
			},
		},
	})

	if err := s.AddPolicy(context.Background(), &api.AddPolicyRequest{
		Policy: &api.Policy{
			Name: "p0",
			Statements: []*api.Statement{&api.Statement{
				Name: "st0",
			}},
		},
		ReferExistingStatements: true,
	}); err != nil {
		log.Fatal(err)
	}

	if err := s.ListPolicy(context.Background(), &api.ListPolicyRequest{}, func(p *api.Policy) { log.Info(p) }); err != nil {
		log.Fatal(err)
	}

	if err := s.AddPolicy(context.Background(), &api.AddPolicyRequest{
		Policy: &api.Policy{
			Name: "p0",
			Statements: []*api.Statement{&api.Statement{
				Name: "st1",
			}},
		},
		ReferExistingStatements: true,
	}); err != nil {
		log.Fatal(err)
	}

	if err := s.ListPolicy(context.Background(), &api.ListPolicyRequest{}, func(p *api.Policy) { log.Info(p) }); err != nil {
		log.Fatal(err)
	}
```

GoBGP handles policies as immutable. You add a new policy and delete the old one.

**Comment by aauren** [comment]
Thanks for the response @fujita! I really appreciate you taking the time to clear this up for me!

It's also good to know that in general GoBGP considers policies as immutable.

From what I can see, from your example and from working your example into kube-router, even though policies are immutable, you can call AddPolicy multiple times on a given policy and statements will update. So when you say that they are immutable, do you mean just the attributes on the policy and not the statements themselves?

Also, I still did have the question, if, in the future, I want to delete and then add a statement, is there a way to do this that won't affect advertised routes in the moments between the delete and the add? Would you recommend adding the policy with a new name, associating it, and then deleting the old policy in that order?

**Comment by fujita** [comment]
> So when you say that they are immutable, do you mean just the attributes on the policy and not the statements themselves?

The original design was handling everything (policy, statement, etc) immutably. Then we allowed them to be modified in a limited way (I can't recall why). Even if you could modify, I think that it would work better with handling them immutably.

> Also, I still did have the question, if, in the future, I want to delete and then add a statement, is there a way to do this that won't affect advertised routes in the moments between the delete and the add?

The policy is applied to routes only when routes are received and advertised. The routes in the table are not affected by adding or deleting policies.

> Would you recommend adding the policy with a new name, associating it, and then deleting the old policy in that order?

Surely.

**Comment by aauren** [comment]
Thank you very much!
