### ISSUE TITLE
MRT decoding fails due to unsupported MP_REACH_NLRI format

### ISSUE THREAD

**Issue by hfreeb** [osrg/gobgp#2649]
When trying to parse some public MRT dumps, e.g. https://data.ris.ripe.net/rrc01/2023.04/bview.20230417.0000.gz, some RIB entries fail to parse with the following error `error: unknown route family. AFI: 8224, SAFI: 1`.

Specifically, this failure happens in the [MP_REACH_NLRI](https://github.com/osrg/gobgp/blob/master/pkg/packet/bgp/bgp.go#L10940) decoding. I believe this is because gobgp doesn't support the abbreviated form of this attribute described in https://www.rfc-editor.org/rfc/rfc6396.html:
> There is one exception to the encoding of BGP attributes for the BGP
   MP_REACH_NLRI attribute (BGP Type Code 14) [[RFC4760](https://www.rfc-editor.org/rfc/rfc4760)].  Since the AFI,
   SAFI, and NLRI information is already encoded in the RIB Entry Header
   or RIB_GENERIC Entry Header, only the Next Hop Address Length and
   Next Hop Address fields are included.  The Reserved field is omitted.
   The attribute length is also adjusted to reflect only the length of
   the Next Hop Address Length and Next Hop Address fields.

These MRT dumps are correctly decoded by bgpdump, which does support this abbreviated form (https://github.com/RIPE-NCC/bgpdump/blob/master/bgpdump_lib.c#L1499).

**Comment by hfreeb** [comment]
I've implemented a fix for this and plan to open the PR on Tuesday.

**Comment by fujita** [comment]
Fixed, thanks!
