### ISSUE TITLE
tcp-mss is defined but doesn't seem to be effect

### ISSUE THREAD

**Issue by jtollet** [osrg/gobgp#2666]
Hello,
in file https://github.com/osrg/gobgp/blob/master/internal/pkg/config/bgp_configs.go I can see a mention of TCP MSS setting:
// original -> bgp:tcp-mss
// Sets the max segment size for BGP TCP sessions.
TcpMss uint16 `mapstructure:"tcp-mss" json:"tcp-mss,omitempty"`

However, looking at the code, it seems it doesn't have an impact. Are you planning to support this parameter ?

**Comment by fujita** [comment]
Please send a pull request for it.

**Comment by fujita** [comment]
thanks!
