### ISSUE TITLE
gobgpd grpc stops listening on v6, gobgp commands fail

### ISSUE THREAD

**Issue by pmeyerson** [osrg/gobgp#2668]
We recently added a v6 address to v4 eth interface.
Now we notice that the gobgp command fails, and it seems gobgpd is only listening on v6, even though listen-address-list specifies v4.  Is there some other configuration option I need to use in this scenario?

NOTE: seems to only listen for 50051 on tcp6
```
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      540020/gobgpd       
tcp        0      0 127.0.0.1:179           0.0.0.0:*               LISTEN      540020/gobgpd       
tcp6       0      0 :::50051                :::*                    LISTEN      540020/gobgpd   
```

**gobgpd version 3.13.0**

```
[global.config]
  as = 65000
  router-id = "XXXX"
  local-address-list = ["127.0.0.1"]
...

```
gobgpd starts fine and peer is added successfully, but `gobgp` command seems unavailable.

```
#> gobgpd -f gobgpd_testlab.conf -l DEBUG
{"level":"info","msg":"gobgpd started","time":"2023-06-15T12:00:11Z"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2023-06-15T12:00:11Z"}
{"Key":"XXX","Topic":"config","level":"info","msg":"Add Peer","time":"2023-06-15T12:00:11Z"}
{"Key":"XXX,"Topic":"Peer","level":"info","msg":"Add a peer configuration","time":"2023-06-15T12:00:11Z"}
{"Key":"XXX","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Peer Up",
   "time":"2023-06-15T12:00:29Z"}
```

> /opt/gobgp/gobgp global
context deadline exceeded

**Comment by fujita** [comment]
`local-address-list` is for bgp port.
> tcp6       0      0 :::50051                :::*                    LISTEN      540020/gobgpd 

this is for gRPC port.

**Comment by pmeyerson** [comment]
Ah, right thank you.
Just realized , I think the real issue was enabling TLS on gobgpd start.  Will try to reproduce in clean environment and open new issue if additional support needed.  thank you!
