### ISSUE TITLE
C++ API Issue

### ISSUE THREAD

**Issue by RubberCthulhu** [osrg/gobgp#2675]
Hello,
It isn't an issue report actually, just some questions, but it looks like slack conf isn't active so I'm asking here. Sorry for that)

I have several questions about c++ API.
1. Message AddPathRequest
Is it possible to send multiple prefixes in nlri attribute? BGP Update message may contain more than one prefix, but it looks like that AddPathRequest can take a single one only.

2. There is a messge AddPathStreamRequest, however it isn't clear enough how to use it. As far as I understand I can add multiple path with method add_paths() like
auto request = AddPathStreamRequest{};
auto path1 = request.add_paths();
// serialize path1
auto path2 = request.add_paths();
// serialize path2
Is it correct way to do it?

And sending api for AddPathStreamRequest looks different to AddPathRequest. I couldn't find any examples for AddPathStream, but it seems the sinding should be something like
auto writer = stub->AddPathStream(&context, &response);
writer->Write(request);
auto status = writer->Finish();

Is it correct way to do it?

3. DeletePathRequest.
Like with AddPathRequest, is it allowed to delete path for single prefix only? Is there any way to delete path for multiple prefixes with a single request?

**Comment by fujita** [comment]
1. No
2. Check out MRT inject code https://github.com/osrg/gobgp/blob/master/cmd/gobgp/mrt.go
I would recommend you to try to understand APIs in Go firstly.
3. single prefix
