### ISSUE TITLE
Add path for a specific neighbor or a set of neighbors

### ISSUE THREAD

**Issue by RubberCthulhu** [osrg/gobgp#2678]
Hello,

Is there any way to add path for a given neighbor or set of neighbors using CLI or API?

I added several neighbors to my gobgp config file and I need to be able to create/delete routes for a given set of them. 

I tried to solve it myself, however I'm new with gobgp and wasn't able to find a solution. Looks like that CLI doesn't provide such an option. AddPathRequest API call has neighbor-ip attribute, but if it is set it looks like that the path is still added globally.

Any advise how I can do it?
I've had a look at policies and it seems they can be used to do my task but looks a bit complicated.

**Comment by fujita** [comment]
You can use export policies.

**Comment by RubberCthulhu** [comment]
Thanks
