### ISSUE TITLE
panic loading mrt with locally injected routes on cmd/gobgp/mrt.go:148

### ISSUE THREAD

**Issue by pmeyerson** [osrg/gobgp#2692]
Hi,

I have r1 (local) and r2 (10.1.255.62), both with mrt table dump configured.

`gobgp global rib add 1.1.1.1/32`
[wait for MRT dump]
`gobgp global rib del 1.1.1.1/32`
`gobgp mrt inject dumpfile.dump`

Should this scenario work with MRT?

panic: runtime error: index out of range [2] with length 2

goroutine 18 [running]:
main.injectMrt.func1()
	/go/pkg/mod/github.com/osrg/gobgp/v3@v3.17.0/cmd/gobgp/mrt.go:148 +0xbbd
created by main.injectMrt
	/go/pkg/mod/github.com/osrg/gobgp/v3@v3.17.0/cmd/gobgp/mrt.go:50 +0x198

I also tried specifying origin igp, and aspath, that didn't seem to help.

Adding a bit more debug output to mrtInject I see:

loadCmdRun backup/table-2023_0829_1458.dump
Found MRT Header: &{Timestamp:1693321146 Type:13 SubType:1 Len:34}
Found MRT Body &{Header:{Timestamp:1693321146 Type:13 SubType:1 Len:34} Body:PEER_INDEX_TABLE: CollectorBgpId [0.0.0.0] ViewName [] Peers [[PEER ENTRY: ID [0.0.0.0] Addr [0.0.0.0] AS [0] PEER ENTRY: ID [10.1.255.62] Addr [10.1.255.62] AS [65000]]]}
Found MRT Header: &{Timestamp:1693321146 Type:13 SubType:8 Len:43}
Found MRT Body &{Header:{Timestamp:1693321146 Type:13 SubType:8 Len:43} Body:RIB: Seq [0] Prefix [1.1.1.0/30] Entries [[RIB_ENTRY: PeerIndex [2] OriginatedTime [1693321081] PathIdentifier[0] PathAttributes [[{Origin: i} 666 {Nexthop: 0.0.0.0}]]]]}
 
 
 Thank you

**Comment by pmeyerson** [comment]
Alternatively if I add `aspath 666` the command succeeds, but I don't see anything in global rib.

**Comment by fujita** [comment]
I don't think that this scenario works.

**Comment by pmeyerson** [comment]
In what scenario would this work? 
If the prefixes were added on R1 and the tablev2 dump /inject command run on R2?
Trying to understand.
