### ISSUE TITLE
How to build goBGP? From the BUILD.MD I still can not know how to build the whole project.

### ISSUE THREAD

**Issue by wangchong2023** [osrg/gobgp#2695]
In [build](https://github.com/osrg/gobgp/blob/master/BUILD.md) and [layout](https://github.com/golang-standards/project-layout) these two documents these explain the build method, but there is no the steps for building the whole project(gobgp and gobgpd).And after building where I can get the binary files.

**Comment by fujita** [comment]
No gobgp specific stuff. Check out other projects that have multiple binaries.

```
$ go build ./cmd/gobgp
$ go build ./cmd/gobgpd
```
