### ISSUE TITLE
Policy change only triggers inbound soft reset

### ISSUE THREAD

**Issue by wenovus** [osrg/gobgp#2697]
Currently on policy change only the IN direction is reset. However, this
means that if export policies were modified, then it is not immediately
applied:

https://github.com/osrg/gobgp/blob/5f01c74a5b067aa05f6aa05610f2cc3bfebc4ab3/pkg/config/config.go#L405-L410

What's the reason why only the IN direction is reset? Should the code above rather say `Direction: api.ResetPeerRequest_BOTH`?

**Comment by fujita** [comment]
IIRC, same as a major router vendor bgp.

**Comment by wenovus** [comment]
Thanks, I see that Cisco only talks about automatic inbound reset in their documentation https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-3se/3850/irg-xe-3se-3850-book/irg-soft-reset.pdf
