### ISSUE TITLE
Does GoBGP support saving the configuration to a file while delivering the configuration through the grpc API?

### ISSUE THREAD

**Issue by wangchong2023** [osrg/gobgp#2700]
Our business needs to send the configuration to gobgp through grpc. Can gobgp itself save the configuration to a file while sending the configuration to grpc? If the configuration is delivered through grpc and the gobgp process is restarted, can the configuration previously delivered through grpc only be re-delivered by the user?

**Comment by fujita** [comment]
No. Users store configuration information in their way (db, file, etc) and then configure gobgpd via the API.

**Comment by wangchong2023** [comment]
> No. Users store configuration information in their way (db, file, etc) and then configure gobgpd via the API.

Got it.Thanks very much.
