### ISSUE TITLE
Request for Review on Exporting BGP Configuration Package

### ISSUE THREAD

**Issue by wenovus** [osrg/gobgp#2710]
Hi, I'm looking to resolve issue https://github.com/osrg/gobgp/issues/2593, and below are two candidate PRs which I'm looking for a review:

* https://github.com/osrg/gobgp/pull/2688 (preferred)
* https://github.com/osrg/gobgp/pull/2696 (alternative)

Please let me know if you have questions or comments on this issue, thanks.

**Comment by fujita** [comment]
I prefer the first option.
