### ISSUE TITLE
after installing grpcio and grpc-tools, attribute_pb2.py and other files aren't available 

### ISSUE THREAD

**Issue by ju619** [osrg/gobgp#2719]
i am following the example for gobgp via python using grpc and i am unable to see or get the attributes.py file mentioned https://github.com/osrg/gobgp/blob/master/tools/grpc/python/add_path.py. i have searched if any had posted the contents of the file so i could just copy them into my dir but no luck. i have tried using python and python3 with no luck. from the guides i've seen on the web it looks like i am missing a few files.

```
[j069194 ~]$ python -m grpc_tools.protoc -I./ --python_out=. --grpc_python_out=. *.proto
[069194 ~]$ ls *.py
gobgp_pb2_grpc.py  gobgp_pb2.py  

[069194 ~]$ python3 -m grpc_tools.protoc -I./ --python_out=. --grpc_python_out=. *.proto
[069194 ~]$ ls *.py
gobgp_pb2_grpc.py  gobgp_pb2.py  

```

what i should be expecting 

`attribute_pb2.py  attribute_pb2_grpc.py  capability_pb2.py  capability_pb2_grpc.py  gobgp_pb2.py  gobgp_pb2_grpc.py
`

**Comment by ju619** [comment]
never mind i found it https://github.com/osrg/gobgp/tree/master/api

**Comment by ju619** [comment]
i was able to wget attribute.proto how do i extract/covert this into a py file where it can be imported ?

**Comment by mbanatt** [comment]
unsubscribe
