### ISSUE TITLE
[oss-fuzz] upstream support request

### ISSUE THREAD

**Issue by 0x34d** [osrg/gobgp#2721]
@fujita, do you support the integration of [gobgp](https://github.com/osrg/gobgp) with [oss-fuzz](https://github.com/google/oss-fuzz/pull/11028) to help find bugs and crashes like [this one](https://github.com/osrg/gobgp/issues/2708) through automated fuzzing? We would need to add the email addresses of the maintainers who will receive potential bug reports to a public list in the oss-fuzz repository.

**Comment by fujita** [comment]
You can add my address.

**Comment by 0x34d** [comment]
> You can add my address.

I'm sorry, I don't have your email address, can you provide me your email address?

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/commit/ed5732bb6ede6624e7e29e91257352c2ca149b6f
