### ISSUE TITLE
Quick EVPN question

### ISSUE THREAD

**Issue by m1waterman88** [osrg/gobgp#2748]
I'm reviewing my company's BGP stack due to faults in our current one. I noticed that EVPN support is listed as "very experimental," but I wanted to check if the documentation is simply out of date since that was added in an April 2015 commit. We really need solid EVPN support.

Source: https://github.com/osrg/gobgp/blob/master/docs/sources/evpn.md

Thanks!

**Comment by fujita** [comment]
Likely all the features aren't implemented.

**Comment by m1waterman88** [comment]
It sounds like this won't work for us at this time. Thanks.
