### ISSUE TITLE
Breaking change in WatchEvent API introduced in v3.24.0

### ISSUE THREAD

**Issue by rastislavs** [osrg/gobgp#2777]
The `v3.24.0` introduced a breaking change in WatchEvent API by the commit https://github.com/osrg/gobgp/commit/aff055b44d0f036da26f5d82275d15e3cb23fee0

As of this commit, `Path` in generated events no longer has `Nlri` and `Pattrs` attributes set (they are always `nil`), and instead `NlriBinary` and `PattrsBinary` attributes are set.

Not sure what was the motivation behind [this change](https://github.com/osrg/gobgp/commit/aff055b44d0f036da26f5d82275d15e3cb23fee0#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L4146-L4170), but as it changes the behavior of the API, it is breaking for the API consumers.

**Comment by fujita** [comment]
Thanks for the report! Sounds like needs to be reverted.

**Comment by fujita** [comment]
The intention is adding EOR support to the EventAPI.

**Comment by rastislavs** [comment]
> The intention is adding EOR support to the EventAPI.

Ah, I meant specifically, switching the `onlyBinary` argument of `toPathApi` calls in `WatchEvent` from `false` to `true`.

**Comment by fujita** [comment]
Oops, understood.

**Comment by bayrinat** [comment]
Hello, my bad. This change wasn't suppose to be there. 

@fujita Thanks for the quick revert, I'll do the proper change soon.

**Comment by fujita** [comment]
I prefer clean revert:
https://github.com/osrg/gobgp/pull/2779

**Comment by fujita** [comment]
I reverted two commits. The API should work as before.

**Comment by rastislavs** [comment]
Yes, I just tested that on top of the commit https://github.com/osrg/gobgp/commit/9d05544d1e8d069beb5bfe97f222711231da38f5 everything works as expected. Thank you.

**Comment by bayrinat** [comment]
The second attempt without breaking changes - https://github.com/osrg/gobgp/pull/2780
