### ISSUE TITLE
Bad BGP initial state for neighbour 

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#300]
Hello, folks!

I have started with gobgpd and created following configuration on single server (178...):
```bash
[Global]
  [Global.GlobalConfig]
    As = 65001
    RouterId = "178.xxxx"

[Neighbors]
  [[Neighbors.NeighborList]]
    [Neighbors.NeighborList.NeighborConfig]
      NeighborAddress = "213.xxxx"
      PeerAs = 65002
```

But on the server 213 I haven't started any BGP daemon yet.

But gobgp tool shows it as "active":
```bash
gobgp neighbor
Peer               AS Up/Down State       |#Advertised Received Accepted
213.133.111.200 65002   never Active      |          0        0        0
```

```bash
telnet 213.133.111.200 179
Trying 213.133.111.200...
telnet: connect to address 213.133.111.200: Connection refused
```

What's wrong here? From my point of view we should show it as "down" instead "active".

**Comment by ishidawataru** [comment]
Hello @pavel-odintsov !

The State shows BGP state machine's state. (See https://en.wikipedia.org/wiki/Border_Gateway_Protocol.)
And 'Active' means its "Actively" trying to connect to the peer (and fail. in your case).
If the peer goes up, the state will be 'Established'.

**Comment by pavel-odintsov** [comment]
Thanks for detailed description! Will check this document!

On Tuesday, September 1, 2015, Wataru ISHIDA <notifications@github.com>
wrote:

> Hello @pavel-odintsov <https://github.com/pavel-odintsov> !
>
> The State shows BGP state machine's state. (See
> https://en.wikipedia.org/wiki/Border_Gateway_Protocol.)
> And 'Active' means its "Actively" trying to connect to the peer (and fail.
> in your case).
> If the peer goes up, the state will be 'Established'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/issues/300#issuecomment-136516831>.
>


-- 
Sincerely yours, Pavel Odintsov
