### ISSUE TITLE
Command gobgp neighbor xxx local hangs

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#305]
Hello!

I have two servers with standard iBGP configuration.

From second server I have announced some prefix:
```bash
gobgp global rib add 10.10.10.0/24
```

From second server I saw it:
```bash
gobgp neighbor
Peer              AS  Up/Down State       |#Advertised Received Accepted
178.62.227.110 65001 00:37:07 Establ      |          0        1        1
```

So when I tried to get "local" table gobgp get stuck:
```bash
gobgp neighbor 178.62.227.110 local
........ so long wait ...
```

But abj-in works with charm:
```bash
gobgp neighbor 178.62.227.110 adj-in
    Network              Next Hop             AS_PATH              Age        Attrs
N   10.10.10.0/24        178.62.227.110                            00:05:27   [{Origin: i} {LocalPref: 100}]
```

I have tried -d option but without any success:
```bash
gobgp -d neighbor 178.62.227.110 local
... still hangs ...
```

I could share strace of gobgp process too: https://www.dropbox.com/s/7vl7p69do3jxtcl/gobgp_local.trace?dl=0

**Comment by ishidawataru** [comment]
Thank you again for the report! 

should be fixed. https://github.com/osrg/gobgp/commit/21e90498549fedb59dfe288e866e020bb30e58a3

I think you are not configuring peers as route-server clients.
In that case, no routes will be appear by `gobgp neighbor <ip addr> local`.
Instead, you should check global rib by `gobgp global rib -a ipv4`.

local table is for route-server clients.

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for fix! Yes, I'm understand this idea. I found this error accidentally :)
