### ISSUE TITLE
EVPN BGP Encapsulation Extended Community

### ISSUE THREAD

**Issue by sevid** [osrg/gobgp#311]
Is there any way to set the BGP encapsulation extended community attribute on routes ( https://tools.ietf.org/html/rfc5512#section-4.5 ) generated by the "rib add <> -a evpn" commands?

**Comment by ishidawataru** [comment]
Hi @sevid !

Currently no.
I will write a patch to add such way shortly.
The format I'm planning is

```bash
$ gobgp global rib add -a evpn macadv <mac address> <ip address> <etag> <label> rd <rd> rt <rt> [encap <encap type>]
<encap type> : [ l2tpv3 | gre | ip-in-ip | vxlan | nvgre | mpls | mpls-in-gre | vxlan-gre ]
```

What do you think ?

**Comment by ishidawataru** [comment]
How about this? https://github.com/osrg/gobgp/commit/bb6df0687cc7d5c57c10e715c68cc68cfc34b330

**Comment by sevid** [comment]
Yes, it is working! Thank you, this is very cool.

**Comment by ishidawataru** [comment]
Thanks for the check. pushed to the master.
