### ISSUE TITLE
Ability to specify custom nexthop with gRPC or CLI

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#333]
Hello, folks!

I want to get working nexthop for unicast IPv4 as recommended here https://github.com/osrg/gobgp/issues/306#issuecomment-137085541 

I have implemented complete API for announce/withdraw prefixes with gRPC: https://github.com/pavel-odintsov/gobgp_api_cpp_client/blob/master/gobgp_api_client.cc#L82

So I could not specify nexthop with gRPC too :(

Because function for generating BGP structures serialize_path hasn't this capability and uses hardcoded nexthop: https://github.com/osrg/gobgp/blob/ba3a7ddb02855ffdf799a65c4cad7d75909a1371/gobgp/cmd/global.go#L398

Could you add any option for doing this job?

I'm using uRPF capability from Cisco and Juniper and really need nexthop... http://www.cisco.com/web/about/security/intelligence/urpf.pdf

Thanks so much!

**Comment by ishidawataru** [comment]
Hi

Which do you use iBGP or eBGP?
It's easy to have nexthop option in cli, but currently GoBGP changes original nexthop to the connected local address in eBGP(as RFC4271 says).
In iBGP the specified nexthop will be preserved.

**Comment by ishidawataru** [comment]
Done! https://github.com/osrg/gobgp/commit/2b0632fdc10b105be667750d52e14ecdf36cbde8

**Comment by pavel-odintsov** [comment]
Thanks for fast fix! :)

I have added announce with nexthop on server 1:
```bash
gobgp global rib add 10.33.0.0/24 nexthop 11.22.33.44 -a ipv4
```

And got broken nexthop on receiver side:
```bash
gobgp global rib
    Network              Next Hop             AS_PATH              Age        Attrs
N*> 10.33.0.0/24         10.10.10.250                              00:01:41   [{Origin: i} {LocalPref: 100}]
```

As you can see receiving side uses peer IP instead explicitly specified nexthop.

But I'm using iBGP.

Server 1:
```bash
[Global]
  [Global.GlobalConfig]
    As = 65001
    RouterId = "213.133.111.200"

[Neighbors]
  [[Neighbors.NeighborList]]
    [Neighbors.NeighborList.NeighborConfig]
      NeighborAddress = "10.10.10.250"
      PeerAs = 65001
```

Server 2:
```bash
[Global]
  [Global.GlobalConfig]
    As = 65001
    RouterId = "213.133.111.200"

[Neighbors]
  [[Neighbors.NeighborList]]
    [Neighbors.NeighborList.NeighborConfig]
      NeighborAddress = "10.10.10.250"
      PeerAs = 65001
```

**Comment by pavel-odintsov** [comment]
With explicit call of adj-in same issue:
```bash
 gobgp neighbor 10.10.10.250 adj-in
    Network              Next Hop             AS_PATH              Age        Attrs
N   10.33.0.0/24         10.10.10.250                              00:00:20   [{Origin: i} {LocalPref: 100}]
```

**Comment by pavel-odintsov** [comment]
On server 1 (announcer) side we have some strange issues with rib and adj-out.

In rib we have correct custom next-hop:
```bash
gobgp global rib
    Network              Next Hop             AS_PATH              Age        Attrs
*>  10.33.0.0/24         11.22.33.44                               00:07:16   [{Origin: i}]
```

But in adj-out we have peer address as nexthop:
```bash
gobgp neighbor 213.133.111.200 adj-out
    Network              Next Hop             AS_PATH              Attrs
    10.33.0.0/24         10.10.10.250                              [{Origin: i} {LocalPref: 100}]
```

Thanks for attention!

**Comment by ishidawataru** [comment]
Thanks for the detailed report. I've reproduced the problem.
Think I can fix it shortly.

**Comment by ishidawataru** [comment]
fixed. please try!

https://github.com/osrg/gobgp/commit/d026fabfea3f529fd6148cb487e24dab48a73081

**Comment by pavel-odintsov** [comment]
Perfect! Sorry for delay with answer! I visited awesome Belgium on vacations :)

Announcer side:
```bash
gobgp global rib add 10.33.0.0/24 nexthop 11.22.33.44 -a ipv4
```

```bash
gobgp global rib
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.33.0.0/24        11.22.33.44                               00:01:00   [{Origin: i}]
```

```bash
gobgp neighbor 213.133.111.200  adj-out
    Network             Next Hop             AS_PATH              Attrs
    10.33.0.0/24        11.22.33.44                               [{Origin: i} {LocalPref: 100}]
```

Receiver side:
```bash
gobgp neighbor 10.10.10.250 adj-in
    Network             Next Hop             AS_PATH              Age        Attrs
N   10.33.0.0/24        11.22.33.44                               00:00:09   [{Origin: i} {LocalPref: 100}]
```
