### ISSUE TITLE
Broken error message

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#339]
Hello!

I typo mistake and got broken error message (netxhop instead nexthop):
```bash
gobgp global rib add 10.33.0.0/24 netxhop 11.22.33.44 -a ipv4
usage: %!s(MISSING) rib %!s(MISSING) <PREFIX> [nexthop <ADDRESS>] -a ipv4
```

Please fix!

**Comment by ishidawataru** [comment]
oops. sorry for that. fixed! https://github.com/osrg/gobgp/commit/0672c729e34a8ab2460c9244350266992f9838a6

**Comment by pavel-odintsov** [comment]
Thanks!
