### ISSUE TITLE
 BGP announcements with timers

### ISSUE THREAD

**Issue by darconada** [osrg/gobgp#356]
Would be great to have the chance of  configure timers to BGP announcements in order to be able perform temporal filters with BGP flowspec.

Something like ban an ips address for 1 hour.

**Comment by fujita** [comment]
I think that it would be better to have such feature outside GoBGP. GoBGP is designed to easily work with other applications. We already see such example https://github.com/FastVPSEestiOu/fastnetmon/issues/389

**Comment by pavel-odintsov** [comment]
Yep, I'm completely agree with @fujita because with gRPC we could pull all active announces, check they for timeout (stored in separate app) and withdraw: https://github.com/pavel-odintsov/gobgp_api_cpp_client
