### ISSUE TITLE
External "key" for announces

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#372]
Hello!

As mentioned in issue https://github.com/osrg/gobgp/issues/356 so much users want to store additional information for each announce. 

So we have two ways:
1) Store everything in gobgp
2) Store everything outside

I prefer second option but we need some key for merging data from external storage and gobgp together. 

I would like to ask for some way to select announces by ID. With IPv4 unicast is really simple to select announce by key because CIDR mask work as key. But for flow spec announces we should mention whole rule for withdraw. 

It's really hard to withdraw announces in full form:
```bash
gobgp global rib -a ipv4-flowspec del match destination 10.0.0.0/24 protocol tcp source 20.0.0.0/24 then redirect 10:10
```

Will be fine to "assign" some uniq key (uuid will be fine) to each flow spec announce for simplified withdrawal process:
```bash
gobgp global rib -a ipv4-flowspec del 56beb318-641e-4dd0-8b69-83223f10199a
```

With uuid's we could store any required information outside without bothering about "key".

**Comment by fujita** [comment]
Looks reasonable. grpc API for adding a route could return an uuid and then grpc API for deleting a route with the uuid?

**Comment by pavel-odintsov** [comment]
Yes! It's what I'm looking for!

**Comment by fujita** [comment]
The API was added.

https://gist.github.com/fujita/c5d5983690039673b807

**Comment by pavel-odintsov** [comment]
Thanks so much! Very very very useful!  Will check soon!

**Comment by fujita** [comment]
Please reopen it if it doesn't work.
