### ISSUE TITLE
Ability to specify custom community with gRPC API

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#375]
Hello!

As mentioned before I'm looking for some way to specify custom community with gRPC: https://github.com/osrg/gobgp/issues/306#issuecomment-137085541 :)

But unfortunately I could generate BGP data structures only with serialize_path function from GoBGP .so library: serialize_path.

For example:
```C
gobgpapi::Path* current_path = new gobgpapi::Path;
path* path_c_struct = serialize_path(ipv4_unicast_route_family, (char*)"10.10.20.33/22");

for (int path_attribute_number = 0; path_attribute_number < path_c_struct->path_attributes_len; path_attribute_number++) {
    current_path->add_pattrs(path_c_struct->path_attributes[path_attribute_number]->value, 
    path_c_struct->path_attributes[path_attribute_number]->len);
} 

current_path->set_nlri(path_c_struct->nlri.value, path_c_struct->nlri.len);
```

As you can see we could generate PATH only with GoBGP's dynamic library and I could not specify community manually.

So will be fine to open some way to do this because custom community is "must" for me :) Each ISP uses different community numbers for blackhole and I need to use different community numbers each time.

Thanks!

**Comment by ishidawataru** [comment]
Hi @pavel-odintsov 

Try newly added global policy feature !

see https://gist.github.com/ishidawataru/26daf32b7badafbab7c9 to get an idea how to configure global policy via grpc api.

equivalent cli commands are

```shell
$ gobgp prefix neighbor add ns01 10.0.0.1
$ gobgp policy statement add st01
$ gobgp policy statement st01 add condition neighbor ns01
$ gobgp policy statement st01 add action community add 100:100
$ gobgp policy add policy0 st01
$ gobgp global policy export add policy0 default accept
```

with these commands, gobgpd will add community 100:100 to all routes which
are going to be advertised to ns01(10.0.01)

**Comment by pavel-odintsov** [comment]
Great! Thanks!
