### ISSUE TITLE
Graceful restart capability

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#378]
Hello! 

I have looked to source code and found support for BGP_CAP_GRACEFUL_RESTART. So I'm looking for some way to specify this option.

I want to keep my announces while gobgp is restarting or server with gobgp become unreachable. 

More information you could find here:
http://www.juniper.net/techpubs/en_US/junos15.1/topics/concept/bgp-long-lived-graceful-restart.html
https://datatracker.ietf.org/doc/draft-uttaro-idr-bgp-persistence/

So we need two directions:
- Option for gobgp client tool for graceful daemon restart
- Option for gobgpd.conf for tuning time for timeout for unreachable BGP session.

**Comment by pavel-odintsov** [comment]
Hello!

We have found this feature in source code:
```bash
//struct for container bgp:config
type GracefulRestartConfig struct {
	// original -> bgp:enabled
	//bgp:enabled's original type is boolean
	Enabled bool
	// original -> bgp:restart-time
	RestartTime uint16
	// original -> bgp:stale-routes-time
	//bgp:stale-routes-time's original type is decimal64
	StaleRoutesTime float64
	// original -> bgp:helper-only
	//bgp:helper-only's original type is boolean
	HelperOnly bool
```

But we haven't any idea how to specify it in configuration file :(

**Comment by fujita** [comment]
GoBGP configuration format is mechanically generated from a YANG model under IETF standardization of BGP configuration:
https://datatracker.ietf.org/doc/draft-shaikh-idr-bgp-model/?include_text=1

So you can find bgp configuration items that commonly used but some are not implemented yet. Graceful restart is still on our TODO list.

**Comment by pavel-odintsov** [comment]
Thanks for information!

**Comment by pavel-odintsov** [comment]
Hello!

I read this slides https://www.euro-ix.net/m/uploads/2015/10/23/MF_GoBGP-for-euroix_1QFWz3B.pdf

And found "Configuration reload is also fast. using kill –SIGHUP instead of vty".

Could you share some details about current implementation of this feature?

**Comment by fujita** [comment]
I guess that he meant that updating a config file and sending SIGHUP signal faster than changing the configuration via CLIs like Quagga especially when you need to change lots.

About the original topic of this issue, if the GR feature doesn't work, please create a new issue.

**Comment by pavel-odintsov** [comment]
It's already implemented and working perfect! This ticket has out of dated information :) Thanks!
