### ISSUE TITLE
Install issues on CentOS 6

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#387]
Hello, folks!

Please read this issue https://github.com/niemeyer/gopkg/issues/36#issuecomment-136807142 

So we have troubles if we want to install gobgpd in CentOS 6 or another old platform. This platform supported by golang but this folks drop support for this really popular platforms.

Do you have any ideas how to solve this issue?

**Comment by pavel-odintsov** [comment]
So I have grate news bit Gitter is not working :)  I would like to share my story about success integration of GoBGP into FastNetMon DDoS detection toolkit: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/GOBGP.md 

Huge thanks, folks :)

**Comment by fujita** [comment]
Thanks for sharing the great work! One thing that I'm thinking about is that gobgpd should work without a config file. All the configuration (e.g. peers) could be done via grpc.

**Comment by pavel-odintsov** [comment]
It will be really awesome if I could do all configuration tasks with gRPC :)

**Comment by pavel-odintsov** [comment]
What about compatibility with CentOS 6?

**Comment by fujita** [comment]
I've not tried but the following git rpm package might work:
http://opensource.wandisco.com/centos/6/git/x86_64/

I've not seen CentOS6 around here for years.

**Comment by pavel-odintsov** [comment]
Yep we could upgrade git but golang itself working perfectly. So this issue
related with service used for stable dependency list.

On Wednesday, 14 October 2015, FUJITA Tomonori <notifications@github.com>
wrote:

> I've not tried but the following git rpm package might work:
> http://opensource.wandisco.com/centos/6/git/x86_64/
>
> I've not seen CentOS6 around here for years.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/issues/387#issuecomment-147879707>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by fujita** [comment]
How about building statically linked binaries on a different machine?

**Comment by pavel-odintsov** [comment]
That's definitely work for me. Actually will be fine to offer binary version for 32 and 64 bit platforms of GoBGP. So also we could pack it into deb / rpm but it's real pain. With Go you could build binary and just share it in tar.gz without any pain (thanks to statical linking). This approach could increase number of customers. Because install of Go compiler is a bit complicated sometimes.
