### ISSUE TITLE
Memory leak in Gobgp

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#404]
Hello!

I'm running gobgp for one week with single unicast peer and got really big memory consumption:
```bash
ps aux|grep gobgp
root       226  0.0  0.1 1979544 3832 ?        Sl   Oct06   0:24 /opt/gobgp_1_0_0/gobgpd -f /etc/gobgpd.conf
root     25668  0.0  0.0  11064   888 pts/1    S+   18:57   0:00 grep gobgp
```

And I'm scary by number of gobgp processes:
```bash
        |-gobgpd-+-{gobgpd) S 1 223 
        |        `-36*[{gobgpd}]
```

Normal usage is about 150 mb:
```bash
ps aux|grep bgp
root     22091  0.0  0.0 145140 10800 pts/1    Sl+  18:48   0:00 /opt/gobgp_1_0_0/gobgpd -f /etc/gobgpd.conf
root     22100  0.0  0.0  14188  2144 pts/0    S+   18:49   0:00 grep bgp
```

**Comment by pavel-odintsov** [comment]
I have created memory snapshot with gdb --pid=226 and gcore and could share with you:
```bash
397M Oct  8 19:08 core.226
```

**Comment by fujita** [comment]
Thanks for the report (and sorry about the delay),

Surely, looks worrying. Let me try to reproduce here. You just configure a single peer and let it run for a week? No gRPC (and CLI commands)?

The number of processes also looks scary. How about the number of processes just after starting gobgp?

btw, I've just add the pprof support:
https://golang.org/pkg/net/http/pprof/

The following command gives an idea on who hogs memory:
$go tool pprof --text http://localhost:6060/debug/pprof/heap

**Comment by pavel-odintsov** [comment]
Hello!

Yes, we have only single peer but we have used gRPC from CLI tool. 

Recently started tool looks like this:
```bash
root      8984  0.0  0.3 290236  7328 pts/1    Sl   16:21   0:00 /opt/gobgp_1_0_0/gobgpd -f /etc/gobgpd.conf
gobgpd---7*[{gobgpd}]
```

Nice idea about pprof!

**Comment by fujita** [comment]
Sorry about the delay,

We added lots of routes and then remove them via gRPC. Seems no memory leak.
https://gist.github.com/fujita/cf526e8db0e082daf4f7#file-gistfile1-txt

RSS increased as the number of routes does, then RSS decreased as the number of routes does. As same as your observation, VIRT increased up to about 2G  and didn't decrease. But VIRT isn't the amount of memory actually in use. Seems that what we observed is what we expect with golang.

Here is some info about how golang uses memory: 
https://deferpanic.com/blog/understanding-golang-memory-usage/

**Comment by pavel-odintsov** [comment]
Hello!

I'm running GoBGP for ~1 weeks and it's looks like this:
```bash
root       260  0.0  0.3 1521048 8224 ?        Sl   Nov12   1:09 /usr/local/bin/gobgpd -f /etc/gobgpd.conf
```

So it's OK :) We actually haven't any mmeory leaks in awesome gobgp toolkit! Thanks for nice explanation of go's memory behavior.
