### ISSUE TITLE
What about GoBGP's logotype?

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#492]
Hello, folks!

I'm working hard on my slides for RIPE 71 and I want to mention your awesome toolkit here. But I really like logotypes and will be very happy if you create some logo for GoBGP! :)

Thanks!

**Comment by ishidawataru** [comment]
Hi,

We are working on it now but it will take few more weeks...
I'm also going to make a lighting talk at RIPE71. see you soon!

**Comment by pavel-odintsov** [comment]
Awesome! See you soon too!

On Friday, 13 November 2015, Wataru Ishida <notifications@github.com> wrote:

> Hi,
>
> We are working on it now but it will take few more weeks...
> I'm also going to make a lighting talk at RIPE71. see you soon!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/issues/492#issuecomment-156354437>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Any news about logotype? :)

**Comment by ishidawataru** [comment]
Hi @pavel-odintsov, here you are!

![gobgp_v](https://cloud.githubusercontent.com/assets/5915117/18071534/7c6ff4be-6e91-11e6-8680-c3d211f0f08a.png)

**Comment by pavel-odintsov** [comment]
Great! Thanks!
