### ISSUE TITLE
Learn routes from Linux routing table

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#510]
Hello, GoBGP team!

I have idea to use GoBGP for routing between Docker host servers over routing server. I want to deploy Bird as Routing Server and use GoBGP on physical server. So I need two options: add received announces to linux routing table and announce all routes from linux routing table to route server.   

I know about some netlink integration in GoBGP. Could you share ideas?

**Comment by ishidawataru** [comment]
what we have in GoBGP now is this
https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md

uses Quagga zebra to inject/extract routes from linux routing table.

**Comment by pavel-odintsov** [comment]
So if you got library for Go for injecting / reading routes from linux table you could use it, right?

**Comment by ishidawataru** [comment]
you mean you want do injecting/reading routes without Quagga?

If so, currently GoBGP doesn't support such feature natively.
But you can add such feature by using GoBGP's gRPC monitor/modpath api and some netlink library.
you can get some idea from this (https://github.com/osrg/goplane/tree/master/netlink)

**Comment by pavel-odintsov** [comment]
Great! Thanks!

**Comment by KassemEl-Murad** [comment]
Hello, GoBGP team!

asking after few years. is there any library to use for injecting / reading routes to linux routing table without Quagga?

thanks in advance!
regards,
kassem

**Comment by maxpain** [comment]
I'm also interested in using GoBGP without Quagga/FRR, just native netlink
