### ISSUE TITLE
GoBGP RFC Support

### ISSUE THREAD

**Issue by danielseide** [osrg/gobgp#512]
I intend to compare your OSS BGP Implementation with other ones in my master thesis. I also plan to analyze the implemented features by comparing the supported RFCs.

My issue is that I couldn't find a list of RFCs for GoBGP. I would appreciate if you created a list or posted me the link to the existing one. 

Regards
Daniel Seidenstücker
(P.S.: Excuse my non-native English skills.)

**Comment by ishidawataru** [comment]
Hi

You want something like this? (https://github.com/Exa-Networks/exabgp/wiki/RFC-Information)
Unfortunately we don't have such yet.
For the comparison, this might help you (https://github.com/tking/route-server/wiki/Gap-Analysis-(Requirements-vs-Implementations)

**Comment by danielseide** [comment]
Thanks for the quick answer. 
Yes I looked for such RFC-Information relative to GoBGP. Without it I intend to compare the features of the implementations rather than their RFCs. Most RFC Lists are outdated anyway.
And there your 2nd link helps a lot. Thanks again.

Regards
Daniel Seidenstücker
