### ISSUE TITLE
Broken origin for unicats announces with gRPC API and CLI

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#556]
Hello!

I'm using my C++ code with external call of serialize_path and announce single unicast route. But in CLI client I saw "?" in origin field instead of "i" or "e"
```bash
gobgp global rib -a ipv4
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.10.20.0/22       0.0.0.0                                   00:05:42   [{Origin: ?}]
```

When I announce unicast route with CLI I got same issue:
```bash
gobgp global rib add 11.22.33.44/32 nexthop 0.0.0.0 -a ipv4
*>  11.22.33.44/32      0.0.0.0                                   00:00:04   [{Origin: ?}]
```

Is it OK?

**Comment by ishidawataru** [comment]
Yes, it's OK.
'?' represents origin incomplete which means a route is learned via neither IGP nor EGP (mainly used when a route is statically learned).

**Comment by pavel-odintsov** [comment]
Oh, thanks! Me bad :)
