### ISSUE TITLE
Mistake with array length

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#569]
Hello!

Please look at line: https://github.com/osrg/gobgp/blob/d6148c75a30d87c3f8c1d0f68725127e4c5f3a65/packet/bgp.go#L5941

You are expecting two elements array (because you are reading data[1], second element from data) but you check array length to be more than single byte.

**Comment by ishidawataru** [comment]
Fixed. Thanks!

https://github.com/osrg/gobgp/commit/634c408903fffd5f4a13016cf29d23cb652cf3d0

**Comment by pavel-odintsov** [comment]
Thanks!
