### ISSUE TITLE
Detailed information about RPKI status for prefix

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#574]
Hello, folks!

I'm hardworking on RPKI deployment and have yet another suggestion about it.

I haven't found any ways to check details about RPKI invalid prefixes. Sign "I*>" is not enough for me.

I need something like RIPE RPKI validator REST API output (please look at description field):
curl http://127.0.0.1:8090/api/v1/validity/AS198068/159.253.16.0/24

``` bash
{
  "validated_route":{
    "route":{
      "origin_asn":"xx",
      "prefix":"xx/24"
    },
    "validity":{
      "state":"Invalid",
      "reason":"as",
      "description":"At least one VRP Covers the Route Prefix, but no VRP ASN matches the route origin ASN",
      "VRPs":{
        "matched":[],
        "unmatched_as":[{
          "asn":"xxx",
          "prefix":"xxx/20",
          "max_length":20
        },{
          "asn":"xx",
          "prefix":"xxx/20",
          "max_length":20
        },{
          "asn":"xx",
          "prefix":"xxx/20",
          "max_length":20
        },{
          "asn":"xxx",
          "prefix":"xxxx/20",
          "max_length":20
        }],
        "unmatched_length":[]
      }
    }
  }
}
```

Will be fine to get new command to get details about RPKI failed state.

**Comment by fujita** [comment]
Thanks for the proposal. I've been working on a stream API to provide the similar information:
https://github.com/osrg/gobgp/blob/master/api/gobgp.proto#L474

The API enables you to continuously monitor the suspicious state changes (e.g. you get notified when a peer advertises an invalid route). Once I finish the feature, I'll work on this.

**Comment by pavel-odintsov** [comment]
That's great! Thanks!

**Comment by fujita** [comment]
Please reopen this or create a new one if the master doesn't work.
