### ISSUE TITLE
Nil value in not yet initizalied peer name

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#581]
Hello!

I have some peer in configuration and when I start GoBGP and before peer init I'm getting NIL instead remote router ID:
```bash
gobgp nei xxxx
BGP neighbor is xxxx, remote AS xxxx
  BGP version 4, remote router ID <nil>
  BGP state = BGP_FSM_ACTIVE, up for 00:00:00
  BGP OutQ = 0, Flops = 0
  Hold time is 0, keepalive interval is 0 seconds
  Configured hold time is 90, keepalive interval is 0 seconds
  Neighbor capabilities:
    BGP_CAP_MULTIPROTOCOL:
        RF_IPv4_UC:	advertised
    BGP_CAP_ROUTE_REFRESH:	advertised
    BGP_CAP_FOUR_OCTET_AS_NUMBER:	advertised
  Message statistics:
                         Sent       Rcvd
    Opens:                  0          0
    Notifications:          0          0
    Updates:                0          0
    Keepalives:             0          0
    Route Refesh:           0          0
    Discarded:              0          0
    Total:                  0          0
  Route statistics:
    Advertised:             0
    Received:               0
    Accepted:               0
```

When peer initialized correctly I get correct IP address instead NIL ;) So issue exists only between GoBGP startup and peer initialization.

**Comment by ishidawataru** [comment]
Since remote router ID is in a received bgp open message,
we can't know remote router ID before peer establishment.

Quagga shows 0.0.0.0 before peer establishment for remote router ID.
But I think this is also misleading.

**Comment by xiaopeng163** [comment]
It's not Quaaga's fault. Cisco routers also use 0.0.0.0 as the remote BGP Identifier before peer establishment. I think maybe Quaaga does not know how to do it and just follow Cisco's rule.  :sweat_smile:

**Comment by pavel-odintsov** [comment]
I prefer unknown over "<Nil>". Nil for not a developer point of view looks as "ooops, something going wrong!"

**Comment by ishidawataru** [comment]
Fixed. Thanks guys!

https://github.com/osrg/gobgp/commit/ebe493913af9a57c8488119009c6006430001cce

**Comment by pavel-odintsov** [comment]
Thanks!
