### ISSUE TITLE
Question about image size

### ISSUE THREAD

**Issue by aledbf** [osrg/gobgp#582]
Hi, is possible to open a PR that reduces the docker image size to 84MB?
```
aledbf/gobgp       0.1                 b98b5cd57243        2 minutes ago       83.35 MB
osrg/gobgp         latest              76abf8cf461f        4 days ago          900.5 MB
```

[This is the change](https://github.com/osrg/gobgp/compare/master...aledbf:shrink-image-alpine?expand=1)
Thanks

**Comment by ishidawataru** [comment]
Hi,

Reducing the size of docker image is welcome!
But osrg/gobgp is using automated build.
Is is possible to make your image automated build enabled?

osrg/gobgp automated build status
https://hub.docker.com/r/osrg/gobgp/builds/
dockerfile hosted here
https://github.com/osrg/dockerfiles

**Comment by aledbf** [comment]
@ishidawataru thanks for the response.

> Is is possible to make your image automated build enabled?

Sadly no because is not possible to copy files from other images (gobgp and gobgp) from other image during a build.
