### ISSUE TITLE
Implement more human understandable key names

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#595]
Hello!

I'm trying to configure default policy for my peers with configuration file. Actually it's bit complicated because you are using 0 and 1 as params for reject and accept here: https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md

My suggestion to change non meaningful 0 and 1 to something like: reject / accept / pass. 

BGP filters is very-very-very dangerous part of BGP daemon and we need to prevent as much as possible errors here.

**Comment by ishidawataru** [comment]
Hi

I've changed configuration enums to `string` from `int`.

please use `reject-route` and `accept-route`.

https://github.com/osrg/gobgp/commit/b0fbcc6b1b18d2c9fe67437fe6432914b67c5508

**Comment by pavel-odintsov** [comment]
That's awesome! Works fine! Thanks!
