### ISSUE TITLE
Ability to commit all changes in CLI to persistent configuration file

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#597]
Hello!

I have some idea about "commit" option for CLI which could save all changes executed with CLI to configuration file. 

Will be interesting to get example configuration file with CLI (and manually replace it in the filesystem or backup somewhere).

**Comment by moolinet** [comment]
Hello,

Are you still working on this enhancement?
We are trying to integrate gobgp in our ci and would like to be able to automatically reload gobgp with it's updated config while preserving any config applied via cli/api.
Or is there another way to do this?

Thanks,

**Comment by fujita** [comment]
This will not be supported. IMHO, persistency should be handled by software designed for it (such as database). If you have the source information for configuration in database (or such), then you can easily integrate gobgp in various ways. I know gobgp production deployments that do such.

I close this.
