### ISSUE TITLE
Memory leak when querying the RIB

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#695]
Hey!

Here is a simple way to reproduce the memory leak:

 1. Start `gobgpd`. Configuration is not important.
 2. Inject 1000 routes:

  ```
gobgp mrt inject global <(zcat latest-bview.gz) 1000
  ```

 3. Check memory usage with `ps`:

  ```
root       190  5.7 11.6 284344 28668 ?        Sl   17:10   0:00 /mnt/lab/gobgpd -f /mnt/lab/gobgp.U1.conf -t yaml -p -s unix --disable-stdlog
  ```

 4. Run `gobgp global rib` several times:

  ```
for i in $(seq 1 10); do gobgp global rib > /dev/null ; done
  ```

 5. Check memory usage:

  ```
root       190  1.8 57.8 397516 142780 ?       Sl   17:10   0:01 /mnt/lab/gobgpd -f /mnt/lab/gobgp.U1.conf -t yaml -p -s unix --disable-stdlog
  ```

gobgp is compiled with Go 1.5.3.

**Comment by ishidawataru** [comment]
Could you share the result of  `go tool pprof -inuse_objects http://localhost:6060/debug/pprof/heap` ?

Also please refer to https://github.com/osrg/gobgp/issues/404

**Comment by vincentbernat** [comment]
Here is the result...
[pprof.localhost:6060.inuse_objects.inuse_space.002.pb.gz](https://github.com/osrg/gobgp/files/137586/pprof.localhost.6060.inuse_objects.inuse_space.002.pb.gz)
[pprof.localhost:6060.inuse_objects.inuse_space.001.pb.gz](https://github.com/osrg/gobgp/files/137585/pprof.localhost.6060.inuse_objects.inuse_space.001.pb.gz)

**Comment by fujita** [comment]
Same with https://github.com/osrg/gobgp/issues/698

Please update all the libraries and try the latest code. Note that Go might take several minutes to free memory. Sending USR1 signal to gobpd triggers GC immediately.
