### ISSUE TITLE
Suggestion to rename structures exported to C and C++

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#706]
Hello, folks! 

I would like to ask you about some small changes in C exported structure names. You've using "buf" and "path_t" type names and they could clash with other type names in program.

I would like to ask to change they to gobgp_buf and gobgp_path_t accordingly. 

What do you think about it?

**Comment by fujita** [comment]
Sounds reasonable to me. Can you send a pull request for it?

**Comment by fujita** [comment]
the library for C was removed so we can close this.
