### ISSUE TITLE
Suspected regression - standard config if not working anymore: Expected map but found '[]map[string]interface {}

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#710]
Hello, folks!

I installed GoBGP few minutes ago and used following configuration example from https://github.com/osrg/gobgp/blob/master/docs/sources/flowspec.md 

```bash
cat gobgpd.conf 
[global.config]
  as = 64512
  router-id = "192.168.255.1"

[[neighbors]]
[neighbors.config]
  neighbor-address = "10.0.255.1"
  peer-as = 64512
[[neighbors.afi-safis]]
  afi-safi-name = "ipv4-flowspec"
```

And I could not run GoBGP with this configuration file:
```bash
/Users/pavel-odintsov/gofolder/bin//gobgpd -f gobgpd.conf 
{"level":"fatal","msg":"can't read config file gobgpd.conf, Type mismatch for 'config.Bgp.Neighbors': Type mismatch for config.Neighbors. Expected map but found '[]map[string]interface {}'.","time":"2016-02-23T15:23:18+03:00"}
```

I've reproduced this bug on Ubuntu 14.04 and Mac OX X 10.11 with equal results. I've used go 1.6 everywhere.

Thanks!

**Comment by ishidawataru** [comment]
Can you do `$ go get -u -v github.com/osrg/gobgp/gobgpd` ?
[This](https://github.com/spf13/viper/commit/0c82789feb03da74b3390a5d64b8ce2ce9ba0f3e) may fix the issue

**Comment by pavel-odintsov** [comment]
Thanks, Ishida! Will check right now!

**Comment by pavel-odintsov** [comment]
It's working! Thanks :)
