### ISSUE TITLE
Suggestion to change "not-a-fragment" to "dont-fragment"

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#715]
Hello!

I would like to ask you to rename flow spec fragmentation option name "not-a-fragment" to "dont-fragment". Because in other case it's pretty hard to understand what it doing. 

From my point of view "not-a-fragment" - means "not fragmented packet" but actual mean of this flag is "packet for which fragmentation disallowed". And this is not fragmented :) 

Somebody could decide "not-a-fragment" has opposite meaning to "is-a-fragment" but it's defeinitely false :)

What do you think about it?

**Comment by fujita** [comment]
Totally makes sense. Fixed by https://github.com/osrg/gobgp/commit/e97594e0218584d766eaaa5822bb58bd26a7bb9d

**Comment by pavel-odintsov** [comment]
Thanks!
