### ISSUE TITLE
Broken example in "GoBGP as a Go Native BGP library"

### ISSUE THREAD

**Issue by shevchenkodenis** [osrg/gobgp#721]
I have an error while building source code of [provided example](https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md#basic)

> ./main.go:59: unknown gobgpapi.ModPathArguments field 'Paths' in struct literal

**Comment by fujita** [comment]
Thanks for the report, fixed by https://github.com/osrg/gobgp/commit/aaa6004f5d9bba03091bf95550781bcc27dac1a4
