### ISSUE TITLE
MY_AS=0 in Open Messages

### ISSUE THREAD

**Issue by shevchenkodenis** [osrg/gobgp#734]
[This commit](https://github.com/osrg/gobgp/commit/0b78f57ccdf63591fd211ade0b571189e070f598) resulted to MY_AS=0 in every OPEN Messages. So, it fails to establish connection with BGP Peer. 
Configured and checked via gRPC requests.
[This commit](https://github.com/osrg/gobgp/commit/53c5bc0258cede44d3544270309b6dd2e83cf058) works fine

**Comment by fujita** [comment]
Oops, sorry. The issue should be fixed by https://github.com/osrg/gobgp/commit/ac040204f8acdeb3dd2491b85e9ba1ddc1ee43de

The code to complement configurations via a file and gRPC should be unified. It has been on my TODO list...
