### ISSUE TITLE
Please add human readable flow spec type names into decode_path's output

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#737]
Hello!

I'm using GoBGP for cross-validation of my own bgp messages producer (for GoBGP's gRPC API). And I'm interested only in flow spec.

So could you add human readable names for flow spec types?

For example instead of:
```bash
{"nlri":{"value":[{"type":1,"value":{"prefix":"144.0.0.0/24"}},{"type":2,"value":{"prefix":"22.0.0.0/16"}},{"type":3,"value":[{"op":129,"value":17}]},{"type":6,"value":[{"op":1,"value":53}
```

I want something like:
```bash
{"nlri":{"value":[{"type":"flow_spec_rource_prefix_type","value":{"prefix":"144.0.0.0/24"}},{"type":"flow_spec_destination_prefix_type","value":{"prefix":"22.0.0.0/16"}},{"type":"flow_spec_protocol_type',"value":[{"op":129,"value":17}]},{"type":6,"value":[{"op":1,"value":53}
```

Numbers are pretty complicated I could miss some mistakes in this case... If you add human-aware types I will be pretty happy ;)

**Comment by ishidawataru** [comment]
Hi,

JSON representation is not for human. so I think it is better to keep them int for machines.
Also, we are using {"type": <int>} in other places (e.g. path-attribute type), it is better to keep a consistency with them.

**Comment by pavel-odintsov** [comment]
Hi!

Make sense. Agree with you :)
