### ISSUE TITLE
gobgp crash on duplicate statement removal

### ISSUE THREAD

**Issue by nuclearcat** [osrg/gobgp#754]
Hi! I observed gobgp crash on duplicate statement(which is mistake to be allowed, i guess) removal. I had to edit some names (confidential employer), i hope it doesnt matter.

/root/go/bin/gobgp policy statement s1-statement add condition prefix s1
/root/go/bin/gobgp policy statement s1-statement add action accept
/root/go/bin/gobgp policy add t-export s1-statement
/root/go/bin/gobgp policy statement s1-statement add condition prefix s1
/root/go/bin/gobgp policy statement s1-statement add action accept
/root/go/bin/gobgp policy add t-export starscool1-statement
/root/go/bin/gobgp policy
/root/go/bin/gobgp policy del s1-statement
/root/go/bin/gobgp policy del t-export s1-statement
/root/go/bin/gobgp policy del t-export s1-statement

After last command i will get daemon crashed and this traceback:

panic: runtime error: makeslice: cap out of range

goroutine 34 [running]:
github.com/osrg/gobgp/table.(*Policy).Remove(0xc8202c0840, 0xc820378d50, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/table/policy.go:2492 +0x6d
github.com/osrg/gobgp/server.(*BgpServer).handleGrpcModPolicy(0xc8200fe800, 0xc820133c20, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/server.go:2603 +0xd5d
github.com/osrg/gobgp/server.(*BgpServer).handleGrpc(0xc8200fe800, 0xc820133c20, 0x0, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/server.go:2190 +0x7612
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc8200fe800)
        /root/go/src/github.com/osrg/gobgp/server/server.go:477 +0x2c79
created by main.main
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:188 +0xe4f

goroutine 1 [select]:
main.main()
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:201 +0x1f11

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 35 [IO wait]:
net.runtime_pollWait(0x7fb3060904d0, 0x72, 0xc820012200)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820202060, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820202060, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820202000, 0x0, 0x7fb304232350, 0xc820358720)
        /usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820130148, 0xc8201f6de8, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820130148, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc820138380, 0x7fb304232298, 0xc820130148, 0x0, 0x0)
        /root/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/osrg/gobgp/server.(*Server).Serve(0xc820136a00, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/grpc_server.go:88 +0x29c
main.main.func2(0xc820136a00)
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:193 +0x25
created by main.main
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:196 +0xe9a

goroutine 7 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, locked to thread]:
runtime.gopark(0xe09488, 0xc82004cf28, 0xc89eb8, 0x6, 0x431618, 0x2)
        /usr/lib/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82004cf28, 0x0, 0x18)
        /usr/lib/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82004cf28)
        /usr/lib/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7fb306090590, 0x72, 0xc820012200)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201541b0, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201541b0, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820154150, 0x0, 0x7fb304232350, 0xc82013cd60)
        /usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201401f8, 0xc82006bd80, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8201401f8, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc82014e180, 0x7fb304232318, 0xc8201401f8, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc82014e180, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc9f9d0, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:1967 +0x8f
main.main.func1()
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:71 +0x3c
created by main.main
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:72 +0x2c9

goroutine 10 [chan receive]:
github.com/osrg/gobgp/config.ReadConfigfileServe(0x7ffe7f619012, 0xf, 0xdbfdfe, 0x4, 0xc8200246c0, 0xc820024720)
        /root/go/src/github.com/osrg/gobgp/config/serve.go:17 +0x75
created by main.main
        /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:185 +0x1fb9

goroutine 11 [select]:
github.com/osrg/gobgp/server.(*grpcIncomingWatcher).loop(0xc820234c00, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/monitor.go:65 +0x99f
github.com/osrg/gobgp/server.(*grpcIncomingWatcher).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/monitor.go:119 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820234c00, 0xc820236110)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 12 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc820234d20)
        /root/go/src/github.com/osrg/gobgp/server/server.go:251 +0x61
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
        /root/go/src/github.com/osrg/gobgp/server/server.go:270 +0x5bd

goroutine 13 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func2(0xc820234d80)
        /root/go/src/github.com/osrg/gobgp/server/server.go:275 +0x43
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
        /root/go/src/github.com/osrg/gobgp/server/server.go:278 +0x600

goroutine 14 [IO wait]:
net.runtime_pollWait(0x7fb306090410, 0x72, 0xc820012200)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820217640, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820217640, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8202175e0, 0x0, 0x7fb304232350, 0xc820136aa0)
        /usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82004e280, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.listenAndAccept.func1(0xc82004e280, 0xc820234de0)
        /root/go/src/github.com/osrg/gobgp/server/server.go:149 +0x31
created by github.com/osrg/gobgp/server.listenAndAccept
        /root/go/src/github.com/osrg/gobgp/server/server.go:156 +0x36f

goroutine 15 [IO wait]:
net.runtime_pollWait(0x7fb306090350, 0x72, 0xc820012200)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202176b0, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202176b0, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820217650, 0x0, 0x7fb304232350, 0xc820136ac0)
        /usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82004e288, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.listenAndAccept.func1(0xc82004e288, 0xc820234de0)
        /root/go/src/github.com/osrg/gobgp/server/server.go:149 +0x31
created by github.com/osrg/gobgp/server.listenAndAccept
        /root/go/src/github.com/osrg/gobgp/server/server.go:156 +0x36f

goroutine 50 [sleep]:
time.Sleep(0x2540be400)
        /usr/lib/go/src/runtime/time.go:59 +0xf9
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc82011d790, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:348 +0x595
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:209 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82011d790, 0xc820236d30)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 52 [sleep]:
time.Sleep(0x28fa6ae00)
        /usr/lib/go/src/runtime/time.go:59 +0xf9
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc82011da00, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:348 +0x595
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:209 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82011da00, 0xc820236f20)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 90 [chan receive]:
github.com/osrg/gobgp/server.(*Server).mod(0xc820136a00, 0x26, 0xbed7e0, 0xc820137ca0, 0x413400, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/grpc_server.go:353 +0x1fb
github.com/osrg/gobgp/server.(*Server).ModPolicy(0xc820136a00, 0x7fb3042723d8, 0xc820378c90, 0xc820137ca0, 0xc82005fa80, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/grpc_server.go:425 +0x59
github.com/osrg/gobgp/api._GobgpApi_ModPolicy_Handler(0xc73a60, 0xc820136a00, 0x7fb3042723d8, 0xc820378c90, 0xc82034cf40, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/api/gobgp.pb.go:2787 +0x135
google.golang.org/grpc.(*Server).processUnaryRPC(0xc820138380, 0x7fb306094e80, 0xc8200218c0, 0xc820164620, 0xc820136a60, 0x10761b0, 0xc820378c60, 0x0, 0x0)
        /root/go/src/google.golang.org/grpc/server.go:497 +0xe1f
google.golang.org/grpc.(*Server).handleStream(0xc820138380, 0x7fb306094e80, 0xc8200218c0, 0xc820164620, 0xc820378c60)
        /root/go/src/google.golang.org/grpc/server.go:646 +0x109d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8202379a0, 0xc820138380, 0x7fb306094e80, 0xc8200218c0, 0xc820164620)
        /root/go/src/google.golang.org/grpc/server.go:323 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/src/google.golang.org/grpc/server.go:324 +0x9a

goroutine 36 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc820138400, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1178 +0x14a
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:376 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82011da00, 0xc82012cc00)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 37 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc820138480, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1178 +0x14a
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:376 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82011d790, 0xc82012cd00)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 38 [sleep]:
time.Sleep(0x3f5476a00)
        /usr/lib/go/src/runtime/time.go:59 +0xf9
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc8201de680, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:348 +0x595
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:209 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8201de680, 0xc82012cee0)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 41 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).active(0xc820138400, 0xc820123080, 0xe09598)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:441 +0xbf6
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1163 +0xbc
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820138400, 0xc820136ce0)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 42 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).active(0xc820138480, 0xc820123080, 0xe09598)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:441 +0xbf6
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1163 +0xbc
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820138480, 0xc820136d00)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 43 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc820138600, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1178 +0x14a
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:376 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8201de680, 0xc82012d040)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 44 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).active(0xc820138600, 0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:441 +0xbf6
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
        /root/go/src/github.com/osrg/gobgp/server/fsm.go:1163 +0xbc
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820138600, 0xc820136dc0)
        /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 98 [IO wait]:
net.runtime_pollWait(0x7fb306090290, 0x72, 0xc820012200)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82032cca0, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82032cca0, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82032cc40, 0xc8201be638, 0x9, 0x9, 0x0, 0x7fb30608a050, 0xc820012200)
        /usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82004e3e0, 0xc8201be638, 0x9, 0x9, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7fb306094e08, 0xc82004e3e0, 0xc8201be638, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7fb306094e08, 0xc82004e3e0, 0xc8201be638, 0x9, 0x9, 0xa7a43ce0357f7e01, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:316 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8201be638, 0x9, 0x9, 0x7fb306094e08, 0xc82004e3e0, 0x6000000, 0xc800000000, 0x0, 0x0)
        /root/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201be600, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/golang.org/x/net/http2/frame.go:463 +0x115
google.golang.org/grpc/transport.(*framer).readFrame(0xc8203822a0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/google.golang.org/grpc/transport/http_util.go:405 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8200218c0, 0xc820382330)
        /root/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x63a
google.golang.org/grpc.(*Server).serveStreams(0xc820138380, 0x7fb306094e80, 0xc8200218c0)
        /root/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820138380, 0x7fb306094d80, 0xc82004e3e0, 0x0, 0x0)
        /root/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc820138380, 0x7fb306094d80, 0xc82004e3e0)
        /root/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
        /root/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 99 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8200218c0)
        /root/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5d8
created by google.golang.org/grpc/transport.newHTTP2Server
        /root/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x852

**Comment by fujita** [comment]
Thanks for the report! Can you try the latest?
