### ISSUE TITLE
Solution architecture - manage announce to multiple peers

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#755]
Hello!

I want to deploy solution where I have multiple peers and I want some way to announce certain unicast / flow spec announces to certain peer.

Idea of "local rib" is not working for me because each peer receives really different announces.

**Comment by nuclearcat** [comment]
I will provide example, and i failed to implement it with gobgp, maybe i missed something?

Let's say i have 3 BGP peers/neighbours
10.0.1.250 as121
10.0.2.250 as122
10.0.3.250 as123

And i have subnets that is added to rib, to be announced like that:
192.168.1.0/24 over 10.0.1.250
192.168.2.0/24 over 10.0.2.250
192.168.3.0/24 over 10.0.3.250

As i understood policy working only on route-server setup, but route-server doesn't take routes from rib.

**Comment by fujita** [comment]
Actually, policy works with global rib setup (that is, non route-server setup). Here's one example to do such scenario:

https://gist.github.com/fujita/c3f17d8351127a675867

```
fujita@ubuntu:~$ gobgp g r
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.3.2.0/24         10.3.2.1             65003                00:05:14   [{Origin: i} {Communities: 0:65001}]
*>  10.3.3.0/24         10.3.2.1             65003                00:05:14   [{Origin: i} {Communities: 0:65002}]
```
As you can see, there are two routes in the global rib.

A certain route is advertised to only certain peer:
```
fujita@ubuntu:~$ gobgp n 10.0.255.1 adj-out
    Network             Next Hop             AS_PATH              Attrs
    10.3.2.0/24         10.0.255.254         64512 65003          [{Origin: i}]
fujita@ubuntu:~$ gobgp n 10.0.255.2 adj-out
    Network             Next Hop             AS_PATH              Attrs
    10.3.3.0/24         10.0.255.254         64512 65003          [{Origin: i}]
```

The above config is just an example. Invent your tricks with the policy feature ;)

**Comment by pavel-odintsov** [comment]
Yes, I think community is a best option in this case. They can be used to filter out announces only for specific peer.
