### ISSUE TITLE
How to bind API to localhost?

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#796]
Hell, folks!

Bu default gobgp API listen on all interfaces (including external) and it's not expected behavior :)

Actually we have option to change default port but we haven't any way to specify custom host:
```bash
 /opt/dps/libraries/gobgp_1_4_0_git/gobgpd --help 2>&1|grep grpc
  -g, --grpc-port=        grpc port (default: 50051)
```

Finally, I have two suggestions:
1) Let's bind to 127.0.0.1 by default
2) Offer configurable option to specify custom host for listening 

Thanks!

**Comment by pavel-odintsov** [comment]
Hi, folks!

Do you have some updates? :) That's real security issue for production use and I would be very glad if you could fix it.

**Comment by fujita** [comment]
why not iptables? If it doesn't work for you, I guess that we could extend '-g' option or something.

**Comment by pavel-odintsov** [comment]
Hello!

Will be fine to have option to tune bind interface. On servers with bunch
of interfaces I want to have multiple GoBGP instances for different
tasks (for example, first gobgp on 192.168.155.1:179, second on
10.10.10.12:179 etc). So we could not handle this configuration with
iptables.

Also iptables configuration adds another level of complexity and very error
prone for new users of gobgp. And open api interface offer very dangerous
level of acces for external malicious user.

 So I will be very glad to avoid it.



On Saturday, 9 April 2016, FUJITA Tomonori <notifications@github.com> wrote:

> why not iptables? If it doesn't work for you, I guess that we could extend
> '-g' option or something.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/issues/796#issuecomment-207854321>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/pull/828

Works for you?

**Comment by pavel-odintsov** [comment]
Yep, looks awesome! Waiting in master! :)

On Sun, Apr 10, 2016 at 8:53 AM, FUJITA Tomonori <notifications@github.com>
wrote:

> #828 <https://github.com/osrg/gobgp/pull/828>
>
> Works for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/issues/796#issuecomment-207988870>
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by fujita** [comment]
Pushed. Please try the latest master.

**Comment by pavel-odintsov** [comment]
Perfect! Working as expected. Thanks!

Sorry for delay. I had short holidays.
