### ISSUE TITLE
Error while compile gRPC client for C++

### ISSUE THREAD

**Issue by Anito23** [osrg/gobgp#801]
While compile gRPC client for C++ by instruction https://github.com/osrg/gobgp/blob/master/docs/sources/grpc-client.md#cpp I have following errors:

g++ -std=c++11 -I/opt/protobuf_3.0.0_alpha4/include -I/opt/grpc/include -pthread  -c -o gobgp_api_client.o gobgp_api_client.cc
gobgp_api_client.cc: In member function ‘void GrpcClient::AnnounceFlowSpecPrefix(bool)’:
gobgp_api_client.cc:119:97: error: ‘class gobgpapi::ModPathArguments’ has no member named ‘mutable_paths’
             google::protobuf::RepeatedPtrField< ::gobgpapi::Path >* current_path_list = request.mutable_paths(); 
                                                                                                 ^
gobgp_api_client.cc:128:70: error: no matching function for call to ‘gobgpapi::GobgpApi::Stub::ModPath(grpc::ClientContext*, gobgpapi::Error*)’
             auto send_stream = stub_->ModPath(&context, &return_error);
                                                                      ^
gobgp_api_client.cc:128:70: note: candidate is:
In file included from gobgp_api_client.cc:12:0:
gobgp_api_client.grpc.pb.h:321:20: note: virtual grpc::Status gobgpapi::GobgpApi::Stub::ModPath(grpc::ClientContext*, const gobgpapi::ModPathArguments&, gobgpapi::ModPathResponse*)
     ::grpc::Status ModPath(::grpc::ClientContext* context, const ::gobgpapi::ModPathArguments& request, ::gobgpapi::ModPathResponse* response) GRPC_OVERRIDE;
                    ^
gobgp_api_client.grpc.pb.h:321:20: note:   candidate expects 3 arguments, 2 provided
gobgp_api_client.cc: In member function ‘void GrpcClient::AnnounceUnicastPrefix(bool)’:
gobgp_api_client.cc:185:97: error: ‘class gobgpapi::ModPathArguments’ has no member named ‘mutable_paths’
             google::protobuf::RepeatedPtrField< ::gobgpapi::Path >* current_path_list = request.mutable_paths(); 
                                                                                                 ^
gobgp_api_client.cc:194:70: error: no matching function for call to ‘gobgpapi::GobgpApi::Stub::ModPath(grpc::ClientContext*, gobgpapi::Error*)’
             auto send_stream = stub_->ModPath(&context, &return_error);
                                                                      ^
gobgp_api_client.cc:194:70: note: candidate is:
In file included from gobgp_api_client.cc:12:0:
gobgp_api_client.grpc.pb.h:321:20: note: virtual grpc::Status gobgpapi::GobgpApi::Stub::ModPath(grpc::ClientContext*, const gobgpapi::ModPathArguments&, gobgpapi::ModPathResponse*)
     ::grpc::Status ModPath(::grpc::ClientContext* context, const ::gobgpapi::ModPathArguments& request, ::gobgpapi::ModPathResponse* response) GRPC_OVERRIDE;
                    ^
gobgp_api_client.grpc.pb.h:321:20: note:   candidate expects 3 arguments, 2 provided
<builtin>: recipe for target 'gobgp_api_client.o' failed
make: *** [gobgp_api_client.o] Error 1

**Comment by Anito23** [comment]
We change some lines of code in file gobgp_api_client.cc from:
two lines 
`gobgpapi::ModPathArguments request;`
to 
`gobgpapi::ModPathsArguments request;`

and 
two lines 
`auto send_stream = stub_->ModPath(&context, &return_error);`
to 
`auto send_stream = stub_->ModPaths(&context, &return_error);`

and compilation complete without errors. 
Thank you.

**Comment by pavel-odintsov** [comment]
Hi!

You could just sent pull requests :)

**Comment by Anito23** [comment]
Pull request was sent.
