### ISSUE TITLE
Security problem when parse open message

### ISSUE THREAD

**Issue by gonotes** [osrg/gobgp#818]
The following code parse open message from peer, it use` rest` for buffer len which is a `uint8` variable,
```
func (msg *BGPOpen) DecodeFromBytes(data []byte) error {
    ......
for rest := msg.OptParamLen; rest > 0; {
    paramtype := data[0]
    paramlen := data[1]
    rest -= paramlen + 2

    if paramtype == BGP_OPT_CAPABILITY {
        p := &OptionParameterCapability{}
        p.ParamType = paramtype
        p.ParamLen = paramlen
        p.DecodeFromBytes(data[2 : 2+paramlen])
        msg.OptParams = append(msg.OptParams, p)
    } 
    ......
}

}
```
As a malformed open message, when `paramlen` is too big, then `rest` is always grater then 0, then the next loop we will access `data `may out of range, there will be a panic!

**Comment by fujita** [comment]
Thanks for the nice findings! How about the above PR?
