### ISSUE TITLE
Per-peer MRT dumps of tables, and updates

### ISSUE THREAD

**Issue by icb-** [osrg/gobgp#903]
I need to be able to periodically dump MRT files of per-peer routing tables, as well as the updates received between those dumps.

I get an error if I try to define both `[[mrt-dump]]` types in the config `{"level":"fatal","msg":"failed to set mrt config: already enabled","time":"2016-05-10T19:27:42Z"}`

```
[[mrt-dump]]
  dump-type = "updates"
  file-name = "/var/db/dumps/updates/{{.NeighborAddress }}/{{.Y}}/{{.M}}/{{.D}}/{{.Y}}-{{.M}}-{{.D}}T{{.H}}:{{.Min}}:{{.Sec}}.updates"
  interval = 60

[[mrt-dump]]
  dump-type = "table"
  file-name = "/var/db/dumps/dumps/{{.NeighborAddress }}/{{.Y}}/{{.M}}/{{.D}}/{{.Y}}-{{.M}}-{{.D}}T{{.H}}:{{.Min}}:{{.Sec}}.dump"
  interval = 300
```

If I define only one, it seems to try to dump them, but ignores the formatting, and doesn't rotate.

**Comment by fujita** [comment]
GoBGP supports only dumping updates currently. What 'per-peer routing tables' means? Route Server deployment?

**Comment by icb-** [comment]
Yes. The MRT documentation a week ago said I could [dump per-neighbor tables](https://github.com/osrg/gobgp/blob/da01fa48af05820d8b8731379cf647be049be503/docs/sources/mrt.md#-dump-neighbors-local-table) in route-server mode.

**Comment by fujita** [comment]
per-peer table dump feature was added:

https://github.com/osrg/gobgp/commit/2c12fa2b92c3372d8639e84be6ee89a9ab581158

per-peer update dump was not supported before and I don't think it's necessary because It's easy to get such from update dump.
