### ISSUE TITLE
Neighbor 'uptime' is really time time neighbor become ESTABLISHED

### ISSUE THREAD

**Issue by agallo** [osrg/gobgp#919]
The uptime reported by `gobgp neighbor x.x.x.x` is not time since establishment, but the time the neighbor entered the ESTABLISHED state.  Output for a new peer:
> BGP state = BGP_FSM_ESTABLISHED, up for 16933d 15:03:17

Output from the example Python get_neighbor script:
>   BGP state = BGP_FSM_ESTABLISHED, up for 1463065447

That looks more like an epoch time for when the neighbor established (Thursday, May 12, 2016 11:04:07 AM GMT-4:00 DST) , not a timer showing how long the neighbor has been up (which was only a few seconds.

**Comment by fujita** [comment]
Thanks for the report, the issue was fixed by:
https://github.com/osrg/gobgp/commit/54a19978eeae12ef01872485994c2b260fbdb297

Please try latest code.

Updating the example of other languages is on the TODO list (the GRPC API was changed too).

**Comment by agallo** [comment]
Code looks good, but I'm having trouble testing it.  This is the first time I've dealt with a Go program.  How do I 'get get' a specific commit?  (sorry for the basic question!)

**Comment by fujita** [comment]
I would recommend the latest code rather than applying only this fix. It's quite easy:
$ go get -u github.com/osrg/gobgp/gobgpd
$ go get -u github.com/osrg/gobgp/gobgp

If you really want to apply only this, then you have to move to the code directly, play with git commands, then build the binaries by hand.

**Comment by fujita** [comment]
Please reopen if you still hit the problem with the latest code.
