### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#936]
Hello,

Would you be opposed to have GoBGP packaged in Debian and Ubuntu? Notably, this means that in about a year, there will be a frozen version of GoBGP in Debian that will stay here for about 3 years. People may bother you with it (but they should bother me instead and I will bother you only if needed). This also means that it will get in LTS Ubuntu in about 2 years, frozen for 3 years too and people may bother you too about it too.

If you just think this is too soon, I can package it nevertheless but we can decide in one year if the current version is relatively OK to be frozen for 3 years. If not, a removal can be asked.

**Comment by fujita** [comment]
GoBGP package in Debian and Ubuntu sounds great! Maybe the next release?

**Comment by vincentbernat** [comment]
If I start today, I can package the current release. Once the new release happens, I will update it. The freeze only happens during distribution freeze. The next one for Debian is in November and the next one for Ubuntu is in one and a half year.

Unless you think that the current release has some problems and that casual users shouldn't use it.

**Comment by fujita** [comment]
Understood. Then you can start today.

**Comment by vincentbernat** [comment]
I have to wait to get protobuf compiler 3 in Debian. I suppose it will be uploaded as soon as it is out of beta. In the meantime, I close the issue here.

**Comment by vincentbernat** [comment]
For information, I have uploaded GoBGP 1.10 to Debian. It still needs to be reviewed and accepted (usually less than 2 weeks). Once it's done, I'll update to 1.11 (or whatever the current version will be). I have used the following service file for systemd integration:

```
[Unit]
Description=GoBGP server
Documentation=file:/usr/share/doc/gobgpd/getting-started.md
After=network.target syslog.service
ConditionPathExists=/etc/gobgpd.conf

[Service]
Type=simple
ExecStart=/usr/bin/gobgpd -f /etc/gobgpd.conf --disable-stdlog --syslog yes
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by fujita** [comment]
Great, thanks a lot!
