### ISSUE TITLE
Go1.3 no longer supported

### ISSUE THREAD

**Issue by nlewo** [osrg/gobgp#942]
I tryied to install gobgp with go1.3.3 but go1.3.3 is no longer supported by golang.org/x/sys/unix
  ```
$ golang-go version
go version go1.3.3 linux/amd64

$ go get github.com/osrg/gobgp/gobgpd
# golang.org/x/sys/unix
gocode/src/golang.org/x/sys/unix/asm.s:8 6a: No such file or directory: textflag.h
# golang.org/x/net/http2
gocode/src/golang.org/x/net/http2/transport.go:209: req.Cancel undefined (type *http.Request has no field or method Cancel)
gocode/src/golang.org/x/net/http2/transport.go:213: req.Cancel undefined (type *http.Request has no field or method Cancel)
```

For more information: https://github.com/golang/go/issues/9211

**Comment by fujita** [comment]
Yeah, we know but forgot to update the doc. Now the doc is updated:

https://github.com/osrg/gobgp/commit/c1b95aa96192a3c0e02b0847694715f130010df3

Thanks for the report!
