### ISSUE TITLE
use gobgp as a native lib issues

### ISSUE THREAD

**Issue by PeiwenChen** [osrg/gobgp#951]
hi, @aledbf @fujita @ishidawataru  
I copied the basic example https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md.
But I got these errors when running `go build`:
```
# command-line-arguments
./gobgp.go:22: undefined: server.REQ_MOD_GLOBAL_CONFIG
./gobgp.go:22: undefined: gobgpapi.ModGlobalConfigArguments
./gobgp.go:37: undefined: server.REQ_MOD_NEIGHBOR
./gobgp.go:37: undefined: gobgpapi.ModGlobalConfigArguments
./gobgp.go:57: undefined: server.REQ_ADD_PATHS
./gobgp.go:57: undefined: gobgpapi.ModPathsArguments
```

Looks like it's a lib dependency issue. Do I need to add some other libs to resolve this?

Thanks,

**Comment by ishidawataru** [comment]
sorry for the outdated document.
just updated now.

https://github.com/osrg/gobgp/commit/9f6b62a5e5abcebde0008b56edcb8f40bd762d52

please refer to the latest.

**Comment by PeiwenChen** [comment]
@ishidawataru  Thanks a lot for the very quick fix!

So if I am using GoBGP as native lib, how do I check if BGP session is up? And how to check the adjacent rib-in and rib-out?

**Comment by ishidawataru** [comment]
In the example in the doc, we starts grpc server, so `gobgp` cli command should work normally.
If you want to check to BGP session status, you can do `gobgp neighbor`.

If you want to check it inside the program, you need to read the source code since there's no document for native lib yet :(

**Comment by PeiwenChen** [comment]
I copied your latest lib file, but still have issue:
```
./gobgp 
panic: interface conversion: interface {} is *gobgpapi.AddNeighborRequest, not
 *config.Neighbor

goroutine 6 [running]:
github.com/osrg/gobgp/server.(*BgpServer).handleGrpc(0xc820180480, 0xc820098dc
0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/src/github.com/osrg/gobgp/server/server.go:
2165 +0x74ee
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc820180480)
        /usr/local/Cellar/go/1.5.1/src/github.com/osrg/gobgp/server/server.go:
348 +0xcb1
created by main.main
        /Users/Peiwen/github.com/exabgp/gobgp.go:14 +0x65

goroutine 1 [chan receive]:
main.main()
        /Users/Peiwen/github.com/exabgp/gobgp.go:48 +0x75a

```

**Comment by ishidawataru** [comment]
please change REQ_ADD_NEIGHBOR to REQ_GRPC_ADD_NEIGHBOR

https://github.com/osrg/gobgp/pull/954/commits/06304ba48b3d2c8fbcbf511b3d87abc593158a58

sorry for the incomplete fix

**Comment by PeiwenChen** [comment]
Yeah, now it works.
