### ISSUE TITLE
Vendoring dependencies

### ISSUE THREAD

**Issue by fcantournet** [osrg/gobgp#963]
There isn't any dependency vendoring. Now that go 1.6 is the latest stable release there isn't any good reason not to have this.
Packages will still be go get-able for convenience.

Are you guys open to this ?
If yes I'm proposing to do it with glide.
Does anyone have a good reason not to do this?
Or preferences for another vendoring tool ?

**Comment by fujita** [comment]
GoBGP is used in two ways, stand-alone binaries and a package. 
As far as I know, with the latter use-case, the vendoring doesn't work:
https://github.com/mattfarina/golang-broken-vendor

**Comment by fcantournet** [comment]
@fujita You are 100% correct.
I suppose the "correct" way of doing this would be to split the library into its own repository, which should be doable since it's already its own package, and then release this library with tags and vendor it in the binary repository.
In the binary repository you could then vendor all other dependencies.

However this is quite a large body of work and it would impact your release management.
It might not be worth it today, but I suspect it will be more expensive to do later on if you need it.

If this is of any interest I'm willing to lend a hand.
If not feel free to close the issue.

**Comment by fujita** [comment]
I plan to use:
https://github.com/golang/dep

seems works for both stand-alone binaries and a package (users for a package can just ignore).

looks like it's still in the pre-alpha state so let's wait for a while.

**Comment by magiconair** [comment]
No need to wait. `govendor` does the trick already and you can switch to a different tool later. See https://github.com/magiconair/gobgp

```
govendor init
govendor add +e
git add vendor/
git commit -m 'Vendoring in dependencies'
```

**Comment by fujita** [comment]
I added the [dep](https://github.com/golang/dep):
https://github.com/osrg/gobgp/commit/11f3fcc7ef7b05948b64412ffc8fca90ae097ce1
They claim that it's ready for production use

Hopefully, it will be the official means of package management soon:
https://blog.golang.org/contributors-summit
