### ISSUE TITLE
APIs to listen to BGP messages

### ISSUE THREAD

**Issue by PeiwenChen** [osrg/gobgp#968]
Hi, @ishidawataru @fujita 

Currently, in the `serve()` function, it listens to the channel for any coming message: https://github.com/osrg/gobgp/blob/c96b6d119849677aa8db8298a412f7ff501b879a/server/server.go#L244-L249

But is there an API that can be used by another application (who uses the gobgp embeded) to listen to incoming BGP messages?
I noticed the `MonitorRib`, `MonitorBestChanged` and `MonitorPeerState` can be used for monitoring routes and peer states, but how about monitoring the BGP messages(OPEN/NOTIFICATION/UPDATE mostly)?

I think I can add a watcher in my application code for my purpose, but since at the server init process, it already adds a watcher of `WATCHER_GRPC_MONITOR`, the other application code cannot add the same type of watcher. And the `addWatcher` is actually a private method, cannot be called in an external application.

Any comments?

**Comment by PeiwenChen** [comment]
@ishidawataru  Any comments will be appreciated, thanks

**Comment by ishidawataru** [comment]
@PeiwenChen sorry for the delay.

Exposing `addWatcher` seems reasonable, but we are thinking we need to refactor watcher infra before doing that.

Meanwhile, could you try BMP to get raw BGP messages?
You can use `REQ_ADD_BMP` to configure BMP server.
[This](https://github.com/osrg/gobgp/blob/master/gobmpd/main.go) is an example of plain BMP server.
