### ISSUE TITLE
Collector error when route is withdrawn

### ISSUE THREAD

**Issue by nlewo** [osrg/gobgp#985]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x696fe9]

goroutine 26 [running]:
panic(0xc717a0, 0xc82000e170)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/osrg/gobgp/packet/bgp.(*PathAttributeAsPath).String(0x0, 0x0, 0x0)
        /home/aeiche/gocode/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4231 +0x39
github.com/osrg/gobgp/server.path2data(0xc8202d86c0, 0x0, 0x1)
        /home/aeiche/gocode/src/github.com/osrg/gobgp/server/collector.go:95 +0x5c
github.com/osrg/gobgp/server.(*Collector).writeUpdate(0xc82019ed20, 0xc82029ae70, 0x0, 0x0)
        /home/aeiche/gocode/src/github.com/osrg/gobgp/server/collector.go:140 +0x170
github.com/osrg/gobgp/server.(*Collector).loop(0xc82019ed20)
        /home/aeiche/gocode/src/github.com/osrg/gobgp/server/collector.go:187 +0x312
created by github.com/osrg/gobgp/server.NewCollector
        /home/aeiche/gocode/src/github.com/osrg/gobgp/server/collector.go:231 +0x4fc

**Comment by fujita** [comment]
Should be fixed by:
https://github.com/osrg/gobgp/commit/0ef14bb14bfb600957325cde65d59a650ff9bff1
