### ISSUE TITLE
crash in gobgp/server.filterpath

### ISSUE THREAD

**Issue by tmmorin** [osrg/gobgp#990]
I have the following crash:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x507adb]

goroutine 25 [running]:
panic(0xc72c80, 0xc82000e0e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/osrg/gobgp/server.filterpath(0xc820185b30, 0xc8202df980, 0x7fc347a37000)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:270 +0x34b
github.com/osrg/gobgp/server.(*Peer).filterpath(0xc820185b30, 0xc8202df980, 0x1)
	/opt/go/src/github.com/osrg/gobgp/server/peer.go:152 +0x29e
github.com/osrg/gobgp/server.(*Peer).processOutgoingPaths(0xc820185b30, 0xc820028818, 0x1, 0x1, 0xc8200287b0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/osrg/gobgp/server/peer.go:221 +0x538
github.com/osrg/gobgp/server.(*BgpServer).propagateUpdate(0xc8201ce000, 0xc8201859f0, 0xc820028768, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:518 +0xae1
github.com/osrg/gobgp/server.(*BgpServer).handleFSMMessage(0xc8201ce000, 0xc8201859f0, 0xc820088f80)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:675 +0x1da7
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc820088f80)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:151 +0x30c
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc8201ce000)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:227 +0x4d3
created by main.main
	/opt/go/src/github.com/osrg/gobgp/gobgpd/main.go:174 +0xbac

See detailed logs and config in attached files:
[crash-log.txt](https://github.com/osrg/gobgp/files/331897/crash-log.txt)
[gobgp.conf.txt](https://github.com/osrg/gobgp/files/331898/gobgp.conf.txt)

**Comment by tmmorin** [comment]
(This is with git current master HEAD.)

**Comment by ishidawataru** [comment]
It seems like a RTC bug.
Could you give me pcap file?

**Comment by tmmorin** [comment]
Yes, I'll send one when I reproduce this crash.

**Comment by tmmorin** [comment]
Here is a capture:
[gobgp-crash-991.pcap.zip](https://github.com/osrg/gobgp/files/334350/gobgp-crash-991.pcap.zip)

**Comment by tmmorin** [comment]
For this particular capture, the logs were:

root@l-n4c-osbgpadm:~# gobgpd -f gobgp.conf -l debug
{"level":"info","msg":"gobgpd started","time":"2016-06-27T10:04:56+02:00"}
{"level":"info","msg":"finished reading the config file","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Peer 127.0.0.1 is added","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Add a peer configuration for 127.0.0.1","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Peer 192.168.80.38 is added","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Add a peer configuration for 192.168.80.38","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Peer 192.168.80.37 is added","time":"2016-06-27T10:04:57+02:00"}
{"Duration":0,"Key":"127.0.0.1","Topic":"Peer","level":"debug","msg":"IdleHoldTimer expired","time":"2016-06-27T10:04:57+02:00"}
{"Duration":0,"Key":"192.168.80.38","Topic":"Peer","level":"debug","msg":"IdleHoldTimer expired","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Add a peer configuration for 192.168.80.37","time":"2016-06-27T10:04:57+02:00"}
{"Key":"127.0.0.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":"idle-hold-timer-expired","time":"2016-06-27T10:04:57+02:00"}
{"Key":"192.168.80.38","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":"idle-hold-timer-expired","time":"2016-06-27T10:04:57+02:00"}
{"Duration":0,"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"IdleHoldTimer expired","time":"2016-06-27T10:04:57+02:00"}
{"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":"idle-hold-timer-expired","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Peer 192.168.80.1 is added","time":"2016-06-27T10:04:57+02:00"}
{"level":"info","msg":"Add a peer configuration for 192.168.80.1","time":"2016-06-27T10:04:57+02:00"}
{"Duration":0,"Key":"192.168.80.1","Topic":"Peer","level":"debug","msg":"IdleHoldTimer expired","time":"2016-06-27T10:04:57+02:00"}
{"Key":"192.168.80.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ACTIVE","old":"BGP_FSM_IDLE","reason":"idle-hold-timer-expired","time":"2016-06-27T10:04:57+02:00"}


{"level":"debug","msg":"accepted a new passive connection from 192.168.80.1","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENSENT","old":"BGP_FSM_ACTIVE","reason":"new-connection","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENCONFIRM","old":"BGP_FSM_OPENSENT","reason":"open-msg-received","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ESTABLISHED","old":"BGP_FSM_OPENCONFIRM","reason":"open-msg-negotiated","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":14,"nexthop":"192.168.80.1","afi":1,"safi":132,"value":[{"prefix":"0:default"}]}],"level":"debug","msg":"received update","nlri":[],"time":"2016-06-27T10:08:17+02:00","withdrawals":[]}
{"Key":"0:default","Topic":"Table","level":"debug","msg":"create Destination","time":"2016-06-27T10:08:17+02:00"}
{"Key":"0:default","Topic":"table","level":"debug","msg":"Processing destination","time":"2016-06-27T10:08:17+02:00"}
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-06-27T10:08:17+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-06-27T10:08:47+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-06-27T10:09:17+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-06-27T10:09:47+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-06-27T10:10:17+02:00"}


{"level":"debug","msg":"accepted a new passive connection from 192.168.80.37","time":"2016-06-27T10:10:44+02:00"}
{"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENSENT","old":"BGP_FSM_ACTIVE","reason":"new-connection","time":"2016-06-27T10:10:44+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-06-27T10:10:47+02:00"}
{"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_OPENCONFIRM","old":"BGP_FSM_OPENSENT","reason":"open-msg-received","time":"2016-06-27T10:10:48+02:00"}
{"Key":"192.168.80.37","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-06-27T10:10:48+02:00"}
{"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"state changed","new":"BGP_FSM_ESTABLISHED","old":"BGP_FSM_OPENCONFIRM","reason":"open-msg-negotiated","time":"2016-06-27T10:10:48+02:00"}
{"Data":{"Header":{"Marker":null,"Len":0,"Type":2},"Body":{"WithdrawnRoutesLen":0,"WithdrawnRoutes":null,"TotalPathAttributeLen":0,"PathAttributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":9,"value":"192.168.80.40"},{"type":10,"value":["1.2.3.4"]},{"type":14,"nexthop":"192.168.80.40","afi":1,"safi":132,"value":[{"prefix":"0:default"}]}],"NLRI":null}},"Key":"192.168.80.37","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"debug","msg":"update for 2byte AS peer","time":"2016-06-27T10:10:48+02:00"}
{"Key":"192.168.80.37","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":[]},{"type":5,"value":100},{"type":9,"value":"192.168.80.40"},{"type":10,"value":["1.2.3.4"]},{"type":14,"nexthop":"192.168.80.40","afi":1,"safi":132,"value":[{"prefix":"0:default"}]}],"level":"debug","msg":"sent update","nlri":null,"time":"2016-06-27T10:10:48+02:00","withdrawals":null}
{"Key":"192.168.80.37","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":14,"nexthop":"192.168.80.37","afi":1,"safi":132,"value":[{"prefix":"2:2:121"}]}],"level":"debug","msg":"received update","nlri":[],"time":"2016-06-27T10:10:49+02:00","withdrawals":[]}
{"Key":"2:2:121","Topic":"Table","level":"debug","msg":"create Destination","time":"2016-06-27T10:10:49+02:00"}
{"Key":"2:2:121","Topic":"table","level":"debug","msg":"Processing destination","time":"2016-06-27T10:10:49+02:00"}
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-06-27T10:10:49+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":9,"value":"192.168.80.40"},{"type":10,"value":["1.2.3.4"]},{"type":14,"nexthop":"192.168.80.40","afi":1,"safi":132,"value":[{"prefix":"2:2:121"}]}],"level":"debug","msg":"sent update","nlri":null,"time":"2016-06-27T10:10:49+02:00","withdrawals":null}
{"Key":"192.168.80.37","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":14,"nexthop":"192.168.80.37","afi":1,"safi":132,"value":[{"prefix":"2:2:193"}]}],"level":"debug","msg":"received update","nlri":[],"time":"2016-06-27T10:10:49+02:00","withdrawals":[]}
{"Key":"2:2:193","Topic":"Table","level":"debug","msg":"create Destination","time":"2016-06-27T10:10:49+02:00"}
{"Key":"2:2:193","Topic":"table","level":"debug","msg":"Processing destination","time":"2016-06-27T10:10:49+02:00"}
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-06-27T10:10:49+02:00"}
{"Key":"192.168.80.37","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":14,"nexthop":"192.168.80.37","afi":1,"safi":132,"value":[{"prefix":"2:2:132"}]}],"level":"debug","msg":"received update","nlri":[],"time":"2016-06-27T10:10:49+02:00","withdrawals":[]}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":9,"value":"192.168.80.40"},{"type":10,"value":["1.2.3.4"]},{"type":14,"nexthop":"192.168.80.40","afi":1,"safi":132,"value":[{"prefix":"2:2:193"}]}],"level":"debug","msg":"sent update","nlri":null,"time":"2016-06-27T10:10:49+02:00","withdrawals":null}
{"Key":"2:2:132","Topic":"Table","level":"debug","msg":"create Destination","time":"2016-06-27T10:10:49+02:00"}
{"Key":"2:2:132","Topic":"table","level":"debug","msg":"Processing destination","time":"2016-06-27T10:10:49+02:00"}
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-06-27T10:10:49+02:00"}
{"Key":"192.168.80.1","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":9,"value":"192.168.80.40"},{"type":10,"value":["1.2.3.4"]},{"type":14,"nexthop":"192.168.80.40","afi":1,"safi":132,"value":[{"prefix":"2:2:132"}]}],"level":"debug","msg":"sent update","nlri":null,"time":"2016-06-27T10:10:49+02:00","withdrawals":null}
{"Key":"192.168.80.37","Topic":"Peer","attributes":[{"type":1,"value":0},{"type":2,"as_paths":null},{"type":5,"value":100},{"type":16,"value":[{"type":3,"subtype":12,"value":{"TunnelType":8}},{"type":0,"subtype":2,"value":"2:193"}]},{"type":22,"is-leaf-info-required":false,"tunnel-type":6,"label":1744,"tunnel-id":"192.168.80.37"},{"type":14,"nexthop":"192.168.80.37","afi":25,"safi":70,"value":[{"type":3,"value":{"rd":{"type":1,"admin":"192.168.80.37","assigned":2},"etag":0,"ip":"192.168.80.37"}}]}],"level":"debug","msg":"received update","nlri":[],"time":"2016-06-27T10:10:49+02:00","withdrawals":[]}
{"Key":"[type:multicast][rd:192.168.80.37:2][etag:0][ip:192.168.80.37]","Topic":"Table","level":"debug","msg":"create Destination","time":"2016-06-27T10:10:49+02:00"}
{"Key":"[type:multicast][rd:192.168.80.37:2][etag:0][ip:192.168.80.37]","Topic":"table","level":"debug","msg":"Processing destination","time":"2016-06-27T10:10:49+02:00"}
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-06-27T10:10:49+02:00"}
{"Data":{"IsWithdraw":false},"Key":"192.168.80.37","Topic":"Peer","level":"debug","msg":"From me, ignore.","time":"2016-06-27T10:10:49+02:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x507adb]

goroutine 23 [running]:
panic(0xc72c80, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/osrg/gobgp/server.filterpath(0xc820165ea0, 0xc8202e6240, 0x7fecc1c684b0)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:270 +0x34b
github.com/osrg/gobgp/server.(*Peer).filterpath(0xc820165ea0, 0xc8202e6240, 0x1)
	/opt/go/src/github.com/osrg/gobgp/server/peer.go:152 +0x29e
github.com/osrg/gobgp/server.(*Peer).processOutgoingPaths(0xc820165ea0, 0xc820158e90, 0x1, 0x1, 0xc820158e28, 0x0, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/osrg/gobgp/server/peer.go:221 +0x538
github.com/osrg/gobgp/server.(*BgpServer).propagateUpdate(0xc8201c0000, 0xc820165db0, 0xc820158de0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:518 +0xae1
github.com/osrg/gobgp/server.(*BgpServer).handleFSMMessage(0xc8201c0000, 0xc820165db0, 0xc82016f900)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:675 +0x1da7
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc82016f900)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:151 +0x30c
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc8201c0000)
	/opt/go/src/github.com/osrg/gobgp/server/server.go:227 +0x4d3
created by main.main
	/opt/go/src/github.com/osrg/gobgp/gobgpd/main.go:174 +0xbac

**Comment by tmmorin** [comment]
Among the UPDATE messages received before the crash, there is a wildcard RTC announce by router 192.168.80.1 (JunOS).  It's possibly something to look at.

**Comment by tmmorin** [comment]
Ok, after digging a bit, it is clear that wildcard RTC routes are not supported yet at all.
There are many places that expect a non-nil RouteTargetMembershipNLRI.RouteTarget.

**Comment by tmmorin** [comment]
This fixes it for me:

diff --```
git a/server/server.go b/server/server.go
index a2662a4..0bee727 100644
--- a/server/server.go
+++ b/server/server.go
@@ -267,7 +267,9 @@ func filterpath(peer *Peer, path *table.Path) *table.Path {
                        for _, ext := range path.GetExtCommunities() {
                                for _, path := range peer.adjRibIn.PathList([]bgp.RouteFamily{bgp.RF_RTC_UC}, true) {
                                        rt := path.GetNlri().(*bgp.RouteTargetMembershipNLRI).RouteTarget
-                                       if ext.String() == rt.String() {
+                                       if rt == nil {
+                                               ignore = false
+                                       } else if ext.String() == rt.String() {
                                                ignore = false
                                                break
                                        }
@@ -485,7 +487,7 @@ func (server *BgpServer) propagateUpdate(peer *Peer, pathList []*table.Path) []*
                                paths := make([]*table.Path, 0, len(candidates))
                                for _, p := range candidates {
                                        for _, ext := range p.GetExtCommunities() {
-                                               if ext.String() == rt.String() {
+                                               if rt == nil || ext.String() == rt.String() {
                                                        if path.IsWithdraw {
                                                                p = p.Clone(true)
                                                        }

```
