### ISSUE TITLE
missing RD field in FlowSpec VPN code

### ISSUE THREAD

**Issue by tmmorin** [osrg/gobgp#997]
RFC5575 says:

> The NLRI format for this address family consists of a fixed-length Route Distinguisher field (8 bytes) followed by a flow specification, following the encoding defined in this document.  The NLRI length field shall include both the 8 bytes of the Route Distinguisher as well as the subsequent flow specification.

However, GoBGP currently parses a FlowSpecIPv4VPN NLRI like a FlowSpecIPv4 route, not parsing the 8 first bytes as a Route Distinguisher. Same for creating/encoding.  

(The same applies to IPv6)

**Comment by ishidawataru** [comment]
Could you explain how you are testing gobgp's flowspec VPN feature?
You mean packet library has a bug?

**Comment by tmmorin** [comment]
Yes, its about the FlowSpecIPv4VPN code packet/bgp/bgp.go:
- has no RouteDistinguisher in the FlowSpecIPv4VPN struct 
- the decoding tries to decode the first byte as a flowspec rule, but the first byte are a Route Distinguisher
- similar for encoding

**Comment by ishidawataru** [comment]
Thanks! should be fixed by [this PR](https://github.com/osrg/gobgp/pull/1004)
Not tested with other implementation though..
